{"expand":"renderedFields,names,schema,transitions,operations,editmeta,changelog","id":"12526723","self":"https://issues.apache.org/jira/rest/api/latest/issue/12526723","key":"DERBY-5456","fields":{"issuetype":{"self":"https://issues.apache.org/jira/rest/api/2/issuetype/1","id":"1","description":"A problem which impairs or prevents the functions of the product.","iconUrl":"https://issues.apache.org/jira/images/icons/issuetypes/bug.png","name":"Bug","subtask":false},"timespent":null,"project":{"self":"https://issues.apache.org/jira/rest/api/2/project/10594","id":"10594","key":"DERBY","name":"Derby","avatarUrls":{"48x48":"https://issues.apache.org/jira/secure/projectavatar?pid=10594&avatarId=10122","24x24":"https://issues.apache.org/jira/secure/projectavatar?size=small&pid=10594&avatarId=10122","16x16":"https://issues.apache.org/jira/secure/projectavatar?size=xsmall&pid=10594&avatarId=10122","32x32":"https://issues.apache.org/jira/secure/projectavatar?size=medium&pid=10594&avatarId=10122"},"projectCategory":{"self":"https://issues.apache.org/jira/rest/api/2/projectCategory/10090","id":"10090","description":"DB related projects","name":"DB"}},"fixVersions":[{"self":"https://issues.apache.org/jira/rest/api/2/version/12323456","id":"12323456","description":"Third release on the 10.8 branch","name":"10.8.3.0","archived":false,"released":true,"releaseDate":"2012-11-16"},{"self":"https://issues.apache.org/jira/rest/api/2/version/12316344","id":"12316344","description":"First release on the 10.9 branch","name":"10.9.1.0","archived":false,"released":true,"releaseDate":"2012-06-25"}],"aggregatetimespent":null,"resolution":{"self":"https://issues.apache.org/jira/rest/api/2/resolution/1","id":"1","description":"A fix for this issue is checked into the tree and tested.","name":"Fixed"},"customfield_12310220":"2011-10-11 20:10:41.074","customfield_12312322":null,"customfield_12312323":null,"customfield_12310420":"59372","customfield_12310222":"1_*:*_1_*:*_508275519_*|*_5_*:*_1_*:*_0","customfield_12312320":null,"customfield_12312321":null,"customfield_12312120":null,"customfield_12312121":null,"resolutiondate":"2011-10-17T16:25:19.255+0000","workratio":-1,"customfield_12312328":null,"customfield_12312329":null,"customfield_12312326":null,"customfield_12310300":null,"customfield_12312327":null,"customfield_12312324":null,"customfield_12312325":null,"lastViewed":null,"watches":{"self":"https://issues.apache.org/jira/rest/api/2/issue/DERBY-5456/watchers","watchCount":0,"isWatching":false},"created":"2011-10-11T19:14:03.816+0000","priority":{"self":"https://issues.apache.org/jira/rest/api/2/priority/3","iconUrl":"https://issues.apache.org/jira/images/icons/priorities/major.png","name":"Major","id":"3"},"labels":[],"customfield_12312333":null,"customfield_12312334":null,"customfield_12310310":"1.0","customfield_12312331":null,"customfield_12312332":null,"timeestimate":null,"aggregatetimeoriginalestimate":null,"versions":[{"self":"https://issues.apache.org/jira/rest/api/2/version/12317968","id":"12317968","description":"second release on the 10.8 branch","name":"10.8.2.2","archived":false,"released":true,"releaseDate":"2011-10-24"}],"customfield_12311120":null,"customfield_12312330":null,"issuelinks":[],"customfield_12312339":null,"assignee":null,"customfield_12312337":null,"customfield_12312338":null,"updated":"2012-11-01T21:10:39.997+0000","customfield_12312335":null,"customfield_12311720":null,"customfield_12312336":null,"status":{"self":"https://issues.apache.org/jira/rest/api/2/status/6","description":"The issue is considered finished, the resolution is correct. Issues which are closed can be reopened.","iconUrl":"https://issues.apache.org/jira/images/icons/statuses/closed.png","name":"Closed","id":"6","statusCategory":{"self":"https://issues.apache.org/jira/rest/api/2/statuscategory/3","id":3,"key":"done","colorName":"green","name":"Complete"}},"components":[{"self":"https://issues.apache.org/jira/rest/api/2/component/11413","id":"11413","name":"Test"}],"timeoriginalestimate":null,"description":"I see the following errors when I run the JUnit tests on Open JDK 7 for Mac OS X:\r\n\r\nsanity is sane\r\n.........................................\r\n.........................................\r\n.........START-SPAWNED:sysinfo STANDARD OUTPUT: exit code=1\r\nTue Oct 11 10:15:02 PDT 2011 : Error getting SysInfo information.\r\nEND-SPAWNED  :sysinfo STANDARD OUTPUT:\r\nFSTART-SPAWNED:SpawnedNetworkServer STANDARD OUTPUT: exit code=143\r\nTue Oct 11 10:14:54 PDT 2011 : Security manager installed using the Basic server security policy.\r\nTue Oct 11 10:15:01 PDT 2011 : Warning: UnknkownHostException: richard-hillegas-computer.local: richard-hillegas-computer.local: nodename nor servname provided, or not known.\r\nTue Oct 11 10:15:01 PDT 2011 : Apache Derby Network Server - 10.8.2.2 - (1181258) started and ready to accept connections on port 1527\r\nTue Oct 11 10:15:02 PDT 2011 : host: localhost is not local to the server running on 0.0.0.0, so cannot be used for NetworkServerControl commands  \r\nTue Oct 11 10:15:02 PDT 2011 : host: localhost is not local to the server running on 0.0.0.0, so cannot be used for NetworkServerControl commands  \r\nEND-SPAWNED  :SpawnedNetworkServer STANDARD OUTPUT:\r\nE.START-SPAWNED:sysinfo STANDARD OUTPUT: exit code=1\r\nTue Oct 11 10:15:50 PDT 2011 : Error getting SysInfo information.\r\nEND-SPAWNED  :sysinfo STANDARD OUTPUT:\r\nFSTART-SPAWNED:SpawnedNetworkServer STANDARD OUTPUT: exit code=143\r\nTue Oct 11 10:15:43 PDT 2011 : Security manager installed using the Basic server security policy.\r\nTue Oct 11 10:15:50 PDT 2011 : Warning: UnknkownHostException: richard-hillegas-computer.local: richard-hillegas-computer.local: nodename nor servname provided, or not known.\r\nTue Oct 11 10:15:50 PDT 2011 : Apache Derby Network Server - 10.8.2.2 - (1181258) started and ready to accept connections on port 1527\r\nTue Oct 11 10:15:50 PDT 2011 : host: localhost is not local to the server running on 0.0.0.0, so cannot be used for NetworkServerControl commands  \r\nTue Oct 11 10:15:50 PDT 2011 : host: localhost is not local to the server running on 0.0.0.0, so cannot be used for NetworkServerControl commands  \r\nEND-SPAWNED  :SpawnedNetworkServer STANDARD OUTPUT:\r\nE...............................\r\n.........................................\r\n.........................................\r\n.........................................\r\n.........................................\r\n.........................................\r\n.........................................\r\n.........................................\r\n.........................................\r\n.........................................\r\n.........................................\r\n.........................................\r\n.........................................\r\n.........................................\r\n.........................................\r\n.........................................\r\n.........................................\r\n.........................................\r\n.........................................\r\n.........................................\r\n.........................................\r\n.........................................\r\n.........................................\r\n.........................................\r\n.........................................\r\n.........................................\r\n.........................................\r\n.........................................\r\n.........................................\r\n.........................................\r\n.........................................\r\n.........................................\r\n.........................................\r\n.........................................\r\n.........................................\r\n.........................................\r\n.........................................\r\n.........................................\r\n.........................................\r\n.........................................\r\n.........................................\r\n.........................................\r\n.........................................\r\n.........................................\r\n.........................................\r\n.........................................\r\n.........................................\r\n.........................................\r\n.........................................\r\n.........................................\r\n.........................................\r\n.........................................\r\n.........................................\r\n.........................................\r\n.........................................\r\n.........................................\r\n.........................................\r\n.........................................\r\n.........................................\r\n.........................................\r\n.........................................\r\n.........................................\r\n.........................................\r\n.........................................\r\n.........................................\r\n.........................................\r\n.........................................\r\n.........................................\r\n.........................................\r\n.........................................\r\n.........................................\r\n.........................................\r\n.........................................\r\n.........................................\r\n.........................................\r\n.........................................\r\n.........................................\r\n.........................................\r\n.........................................\r\n.........................................\r\n.........................................\r\n.........................................\r\n.........................................\r\n.........................................\r\n.........................................\r\n.........................................\r\n.........................................\r\n.........................................\r\n.........................................\r\n.........................................\r\n.........................................\r\n.........................................\r\n.........................................\r\n.........................................\r\n.........................................\r\n.........................................\r\n.........................................\r\n.........................................\r\n.........................................\r\n.........................................\r\n.........................................\r\n.........................................\r\n.........................................\r\n.........................................\r\n.........................................\r\n.........................................\r\n.........................................\r\n.........................................\r\n.........................................\r\n.........................................\r\n.........................................\r\n.........................................\r\n.........................................\r\n.........................................\r\n.........................................\r\n.........................................\r\n.........................................\r\n.........................................\r\n.........................................\r\n.........................................\r\n.........................................\r\n.........................................\r\n.........................................\r\n.........................................\r\n.........................................\r\n.........................................\r\n.........................................\r\n.........................................\r\n.........................................\r\n.........................................\r\n.........................................\r\n.........................................\r\n.........................................\r\n.........................................\r\n.........................................\r\n.........................................\r\n.........................................\r\n.........................................\r\n.........................................\r\n.........................................\r\n.........................................\r\n.........................................\r\n.........................................\r\n.........................................\r\n.........................................\r\n.........................................\r\n.........................................\r\n.........................................\r\n.........................................\r\n.........................................\r\n.........................................\r\n.........................................\r\n.........................................\r\n.........................................\r\n.........................................\r\n.........................................\r\n.........................................\r\n.........................................\r\n.........................................\r\n.........................................\r\n.........................................\r\n.........................................\r\n.........................................\r\n.........................................\r\n.........................................\r\n.........................................\r\n.........................................\r\n.........................................\r\n.........................................\r\n.........................................\r\n.........................................\r\n.........................................\r\n.........................................\r\n.........................................\r\n.........................................\r\n.........................................\r\n.........................................\r\n.........................................\r\n.........................................\r\n.........................................\r\n.........................................\r\n.........................................\r\n.........................................\r\n.........................................\r\n.........................................\r\n.........................................\r\n.........................................\r\n.........................................\r\n.........................................\r\n.........................................\r\n.........................................\r\n.........................................\r\n.........................................\r\n.........................................\r\n.........................................\r\n.........................................\r\n.........................................\r\n.........................................\r\n.........................................\r\n.........................................\r\n.........................................\r\n.........................................\r\n.........................................\r\n.........................................\r\n.........................................\r\n.........................................\r\n.........................................\r\n.........................................\r\n.........................................\r\n.........................................\r\n.........................................\r\n.........................................\r\n.........................................\r\n.........................................\r\n.........................................\r\n.........................................\r\n.........................................\r\n.........................................\r\n.........................................\r\n.........................................\r\n.........................................\r\n.........................................\r\n.........................................\r\n.........................................\r\n.........................................\r\n.........................................\r\n.........................................\r\n.........................................\r\n.........................................\r\n.........................................\r\n.........................................\r\n.........................................\r\n.........................................\r\n.........................................\r\n.........................................\r\n.........................................\r\n.........................................\r\n.........................................\r\n.........................................\r\n.........................................\r\n.........................................\r\n.........................................\r\n.........................................\r\n.........................................\r\n.........................................\r\n.........................................\r\n.........................................\r\n.........................................\r\n.........................................\r\n.........................................\r\n.........................................\r\n...................START-SPAWNED:SpawnedNetworkServer ERROR OUTPUT:\r\nError: Exception thrown by the agent : java.net.MalformedURLException: Local host name unknown: java.net.UnknownHostException: richard-hillegas-computer.local: richard-hillegas-computer.local: nodename nor servname provided, or not known\r\nEND-SPAWNED  :SpawnedNetworkServer ERROR OUTPUT:\r\nF.START-SPAWNED:SpawnedNetworkServer ERROR OUTPUT:\r\nError: Exception thrown by the agent : java.net.MalformedURLException: Local host name unknown: java.net.UnknownHostException: richard-hillegas-computer.local: richard-hillegas-computer.local: nodename nor servname provided, or not known\r\nEND-SPAWNED  :SpawnedNetworkServer ERROR OUTPUT:\r\nF.START-SPAWNED:SpawnedNetworkServer ERROR OUTPUT:\r\nError: Exception thrown by the agent : java.net.MalformedURLException: Local host name unknown: java.net.UnknownHostException: richard-hillegas-computer.local: richard-hillegas-computer.local: nodename nor servname provided, or not known\r\nEND-SPAWNED  :SpawnedNetworkServer ERROR OUTPUT:\r\nF....................\r\nSTART-SPAWNED:SpawnedNetworkServer ERROR OUTPUT:\r\nError: Exception thrown by the agent : java.net.MalformedURLException: Local host name unknown: java.net.UnknownHostException: richard-hillegas-computer.local: richard-hillegas-computer.local: nodename nor servname provided, or not known\r\nEND-SPAWNED  :SpawnedNetworkServer ERROR OUTPUT:\r\nF.....START-SPAWNED:SpawnedNetworkServer ERROR OUTPUT:\r\nError: Exception thrown by the agent : java.net.MalformedURLException: Local host name unknown: java.net.UnknownHostException: richard-hillegas-computer.local: richard-hillegas-computer.local: nodename nor servname provided, or not known\r\nEND-SPAWNED  :SpawnedNetworkServer ERROR OUTPUT:\r\nF......................START-SPAWNED:SpawnedNetworkServer ERROR OUTPUT:\r\nError: Exception thrown by the agent : java.net.MalformedURLException: Local host name unknown: java.net.UnknownHostException: richard-hillegas-computer.local: richard-hillegas-computer.local: nodename nor servname provided, or not known\r\nEND-SPAWNED  :SpawnedNetworkServer ERROR OUTPUT:\r\nF..............\r\n.........................................\r\n.........................................\r\n.........................................\r\n.........................................\r\n.........................................\r\n.........................................\r\n.........................................\r\n.........................................\r\n.........................................\r\n.........................................\r\n.........................................\r\n.........................................\r\n.........................................\r\n.........................................\r\n.........................................\r\n.........................................\r\n.........................................\r\n.........................................\r\n.........................................\r\n.........................................\r\n.........................................\r\n.........................................\r\n.........................................\r\n.........................................\r\n.........................................\r\n.........................................\r\n....................E.E.E.F.E.E.E.E.E.E.E.E.E.E.E.E.E.E.E\r\nTime: 5,033.075\r\nThere were 20 errors:\r\n1) SecureServerTest( Opened = false, Authenticated= true, CustomDerbyProperties= null, WildCardHost= 0.0.0.0 )java.lang.Exception: DRDA_NeedLocalHost.S:host: localhost is not local to the server running on 0.0.0.0, so cannot be used for NetworkServerControl commands  \r\n\tat org.apache.derby.impl.drda.NetworkServerControlImpl.consolePropertyMessageWork(Unknown Source)\r\n\tat org.apache.derby.impl.drda.NetworkServerControlImpl.consolePropertyMessage(Unknown Source)\r\n\tat org.apache.derby.impl.drda.NetworkServerControlImpl.readResult(Unknown Source)\r\n\tat org.apache.derby.impl.drda.NetworkServerControlImpl.shutdown(Unknown Source)\r\n\tat org.apache.derby.drda.NetworkServerControl.shutdown(Unknown Source)\r\n\tat org.apache.derbyTesting.junit.NetworkServerTestSetup.tearDown(NetworkServerTestSetup.java:379)\r\n\tat junit.extensions.TestSetup$1.protect(TestSetup.java:22)\r\n\tat junit.extensions.TestSetup.run(TestSetup.java:25)\r\n\tat org.apache.derbyTesting.junit.BaseTestSetup.run(BaseTestSetup.java:57)\r\n\tat junit.extensions.TestDecorator.basicRun(TestDecorator.java:24)\r\n\tat junit.extensions.TestSetup$1.protect(TestSetup.java:21)\r\n\tat junit.extensions.TestSetup.run(TestSetup.java:25)\r\n\tat junit.extensions.TestDecorator.basicRun(TestDecorator.java:24)\r\n\tat junit.extensions.TestSetup$1.protect(TestSetup.java:21)\r\n\tat junit.extensions.TestSetup.run(TestSetup.java:25)\r\n\tat junit.extensions.TestDecorator.basicRun(TestDecorator.java:24)\r\n\tat junit.extensions.TestSetup$1.protect(TestSetup.java:21)\r\n\tat junit.extensions.TestSetup.run(TestSetup.java:25)\r\n2) SecureServerTest( Opened = false, Authenticated= true, CustomDerbyProperties= null, WildCardHost= 0.00.000.0 )java.lang.Exception: DRDA_NeedLocalHost.S:host: localhost is not local to the server running on 0.0.0.0, so cannot be used for NetworkServerControl commands  \r\n\tat org.apache.derby.impl.drda.NetworkServerControlImpl.consolePropertyMessageWork(Unknown Source)\r\n\tat org.apache.derby.impl.drda.NetworkServerControlImpl.consolePropertyMessage(Unknown Source)\r\n\tat org.apache.derby.impl.drda.NetworkServerControlImpl.readResult(Unknown Source)\r\n\tat org.apache.derby.impl.drda.NetworkServerControlImpl.shutdown(Unknown Source)\r\n\tat org.apache.derby.drda.NetworkServerControl.shutdown(Unknown Source)\r\n\tat org.apache.derbyTesting.junit.NetworkServerTestSetup.tearDown(NetworkServerTestSetup.java:379)\r\n\tat junit.extensions.TestSetup$1.protect(TestSetup.java:22)\r\n\tat junit.extensions.TestSetup.run(TestSetup.java:25)\r\n\tat org.apache.derbyTesting.junit.BaseTestSetup.run(BaseTestSetup.java:57)\r\n\tat junit.extensions.TestDecorator.basicRun(TestDecorator.java:24)\r\n\tat junit.extensions.TestSetup$1.protect(TestSetup.java:21)\r\n\tat junit.extensions.TestSetup.run(TestSetup.java:25)\r\n\tat junit.extensions.TestDecorator.basicRun(TestDecorator.java:24)\r\n\tat junit.extensions.TestSetup$1.protect(TestSetup.java:21)\r\n\tat junit.extensions.TestSetup.run(TestSetup.java:25)\r\n\tat junit.extensions.TestDecorator.basicRun(TestDecorator.java:24)\r\n\tat junit.extensions.TestSetup$1.protect(TestSetup.java:21)\r\n\tat junit.extensions.TestSetup.run(TestSetup.java:25)\r\n3) testReplication_Local_LogFilesSynched(org.apache.derbyTesting.functionTests.tests.replicationTests.ReplicationRun_Local)java.sql.SQLException: DERBY SQL error: SQLCODE: -1, SQLSTATE: XSAI2, SQLERRMC: 384XSAI2.S\r\n\tat org.apache.derby.client.am.SQLExceptionFactory40.getSQLException(Unknown Source)\r\n\tat org.apache.derby.client.am.SqlException.getSQLException(Unknown Source)\r\n\tat org.apache.derby.client.am.Statement.execute(Unknown Source)\r\n\tat org.apache.derbyTesting.functionTests.tests.replicationTests.ReplicationRun.bootMasterDatabase(ReplicationRun.java:868)\r\n\tat org.apache.derbyTesting.functionTests.tests.replicationTests.ReplicationRun_Local.testReplication_Local_LogFilesSynched(ReplicationRun_Local.java:195)\r\n\tat sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)\r\n\tat sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)\r\n\tat sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)\r\n\tat org.apache.derbyTesting.junit.BaseTestCase.runBare(BaseTestCase.java:113)\r\n\tat org.apache.derbyTesting.functionTests.tests.replicationTests.ReplicationRun.runBare(ReplicationRun.java:206)\r\n\tat junit.extensions.TestDecorator.basicRun(TestDecorator.java:24)\r\n\tat junit.extensions.TestSetup$1.protect(TestSetup.java:21)\r\n\tat junit.extensions.TestSetup.run(TestSetup.java:25)\r\nCaused by: org.apache.derby.client.am.SqlException: DERBY SQL error: SQLCODE: -1, SQLSTATE: XSAI2, SQLERRMC: 384XSAI2.S\r\n\tat org.apache.derby.client.am.Statement.completeSqlca(Unknown Source)\r\n\tat org.apache.derby.client.net.NetStatementReply.parsePrepareError(Unknown Source)\r\n\tat org.apache.derby.client.net.NetStatementReply.parsePRPSQLSTTreply(Unknown Source)\r\n\tat org.apache.derby.client.net.NetStatementReply.readPrepare(Unknown Source)\r\n\tat org.apache.derby.client.net.StatementReply.readPrepare(Unknown Source)\r\n\tat org.apache.derby.client.net.NetStatement.readPrepare_(Unknown Source)\r\n\tat org.apache.derby.client.am.Statement.readPrepare(Unknown Source)\r\n\tat org.apache.derby.client.am.Statement.flowExecute(Unknown Source)\r\n\tat org.apache.derby.client.am.Statement.executeX(Unknown Source)\r\n\t... 32 more\r\n4) testReplication_Local_1_InsertUpdateDeleteOnMaster(org.apache.derbyTesting.functionTests.tests.replicationTests.ReplicationRun_Local_1)java.sql.SQLException: DERBY SQL error: SQLCODE: -1, SQLSTATE: XSAI2, SQLERRMC: 384XSAI2.S\r\n\tat org.apache.derby.client.am.SQLExceptionFactory40.getSQLException(Unknown Source)\r\n\tat org.apache.derby.client.am.SqlException.getSQLException(Unknown Source)\r\n\tat org.apache.derby.client.am.Statement.execute(Unknown Source)\r\n\tat org.apache.derbyTesting.functionTests.tests.replicationTests.ReplicationRun.bootMasterDatabase(ReplicationRun.java:868)\r\n\tat org.apache.derbyTesting.functionTests.tests.replicationTests.ReplicationRun_Local_1.testReplication_Local_1_InsertUpdateDeleteOnMaster(ReplicationRun_Local_1.java:77)\r\n\tat sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)\r\n\tat sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)\r\n\tat sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)\r\n\tat org.apache.derbyTesting.junit.BaseTestCase.runBare(BaseTestCase.java:113)\r\n\tat org.apache.derbyTesting.functionTests.tests.replicationTests.ReplicationRun.runBare(ReplicationRun.java:206)\r\n\tat junit.extensions.TestDecorator.basicRun(TestDecorator.java:24)\r\n\tat junit.extensions.TestSetup$1.protect(TestSetup.java:21)\r\n\tat junit.extensions.TestSetup.run(TestSetup.java:25)\r\nCaused by: org.apache.derby.client.am.SqlException: DERBY SQL error: SQLCODE: -1, SQLSTATE: XSAI2, SQLERRMC: 384XSAI2.S\r\n\tat org.apache.derby.client.am.Statement.completeSqlca(Unknown Source)\r\n\tat org.apache.derby.client.net.NetStatementReply.parsePrepareError(Unknown Source)\r\n\tat org.apache.derby.client.net.NetStatementReply.parsePRPSQLSTTreply(Unknown Source)\r\n\tat org.apache.derby.client.net.NetStatementReply.readPrepare(Unknown Source)\r\n\tat org.apache.derby.client.net.StatementReply.readPrepare(Unknown Source)\r\n\tat org.apache.derby.client.net.NetStatement.readPrepare_(Unknown Source)\r\n\tat org.apache.derby.client.am.Statement.readPrepare(Unknown Source)\r\n\tat org.apache.derby.client.am.Statement.flowExecute(Unknown Source)\r\n\tat org.apache.derby.client.am.Statement.executeX(Unknown Source)\r\n\t... 32 more\r\n5) testReplication_Local_1_Indexing(org.apache.derbyTesting.functionTests.tests.replicationTests.ReplicationRun_Local_1Indexing)java.sql.SQLException: DERBY SQL error: SQLCODE: -1, SQLSTATE: XSAI2, SQLERRMC: 384XSAI2.S\r\n\tat org.apache.derby.client.am.SQLExceptionFactory40.getSQLException(Unknown Source)\r\n\tat org.apache.derby.client.am.SqlException.getSQLException(Unknown Source)\r\n\tat org.apache.derby.client.am.Statement.execute(Unknown Source)\r\n\tat org.apache.derbyTesting.functionTests.tests.replicationTests.ReplicationRun.bootMasterDatabase(ReplicationRun.java:868)\r\n\tat org.apache.derbyTesting.functionTests.tests.replicationTests.ReplicationRun.makeReadyForReplication(ReplicationRun.java:2518)\r\n\tat org.apache.derbyTesting.functionTests.tests.replicationTests.ReplicationRun_Local_1Indexing.testReplication_Local_1_Indexing(ReplicationRun_Local_1Indexing.java:70)\r\n\tat sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)\r\n\tat sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)\r\n\tat sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)\r\n\tat org.apache.derbyTesting.junit.BaseTestCase.runBare(BaseTestCase.java:113)\r\n\tat org.apache.derbyTesting.functionTests.tests.replicationTests.ReplicationRun.runBare(ReplicationRun.java:206)\r\n\tat junit.extensions.TestDecorator.basicRun(TestDecorator.java:24)\r\n\tat junit.extensions.TestSetup$1.protect(TestSetup.java:21)\r\n\tat junit.extensions.TestSetup.run(TestSetup.java:25)\r\nCaused by: org.apache.derby.client.am.SqlException: DERBY SQL error: SQLCODE: -1, SQLSTATE: XSAI2, SQLERRMC: 384XSAI2.S\r\n\tat org.apache.derby.client.am.Statement.completeSqlca(Unknown Source)\r\n\tat org.apache.derby.client.net.NetStatementReply.parsePrepareError(Unknown Source)\r\n\tat org.apache.derby.client.net.NetStatementReply.parsePRPSQLSTTreply(Unknown Source)\r\n\tat org.apache.derby.client.net.NetStatementReply.readPrepare(Unknown Source)\r\n\tat org.apache.derby.client.net.StatementReply.readPrepare(Unknown Source)\r\n\tat org.apache.derby.client.net.NetStatement.readPrepare_(Unknown Source)\r\n\tat org.apache.derby.client.am.Statement.readPrepare(Unknown Source)\r\n\tat org.apache.derby.client.am.Statement.flowExecute(Unknown Source)\r\n\tat org.apache.derby.client.am.Statement.executeX(Unknown Source)\r\n\t... 33 more\r\n6) testReplication_Local_StateTest_part1_1(org.apache.derbyTesting.functionTests.tests.replicationTests.ReplicationRun_Local_StateTest_part1_1)java.sql.SQLException: DERBY SQL error: SQLCODE: -1, SQLSTATE: XSAI2, SQLERRMC: 384XSAI2.S\r\n\tat org.apache.derby.client.am.SQLExceptionFactory40.getSQLException(Unknown Source)\r\n\tat org.apache.derby.client.am.SqlException.getSQLException(Unknown Source)\r\n\tat org.apache.derby.client.am.Statement.execute(Unknown Source)\r\n\tat org.apache.derbyTesting.functionTests.tests.replicationTests.ReplicationRun.bootMasterDatabase(ReplicationRun.java:868)\r\n\tat org.apache.derbyTesting.functionTests.tests.replicationTests.ReplicationRun_Local_StateTest_part1_1.testReplication_Local_StateTest_part1_1(ReplicationRun_Local_StateTest_part1_1.java:96)\r\n\tat sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)\r\n\tat sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)\r\n\tat sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)\r\n\tat org.apache.derbyTesting.junit.BaseTestCase.runBare(BaseTestCase.java:113)\r\n\tat org.apache.derbyTesting.functionTests.tests.replicationTests.ReplicationRun.runBare(ReplicationRun.java:206)\r\n\tat junit.extensions.TestDecorator.basicRun(TestDecorator.java:24)\r\n\tat junit.extensions.TestSetup$1.protect(TestSetup.java:21)\r\n\tat junit.extensions.TestSetup.run(TestSetup.java:25)\r\nCaused by: org.apache.derby.client.am.SqlException: DERBY SQL error: SQLCODE: -1, SQLSTATE: XSAI2, SQLERRMC: 384XSAI2.S\r\n\tat org.apache.derby.client.am.Statement.completeSqlca(Unknown Source)\r\n\tat org.apache.derby.client.net.NetStatementReply.parsePrepareError(Unknown Source)\r\n\tat org.apache.derby.client.net.NetStatementReply.parsePRPSQLSTTreply(Unknown Source)\r\n\tat org.apache.derby.client.net.NetStatementReply.readPrepare(Unknown Source)\r\n\tat org.apache.derby.client.net.StatementReply.readPrepare(Unknown Source)\r\n\tat org.apache.derby.client.net.NetStatement.readPrepare_(Unknown Source)\r\n\tat org.apache.derby.client.am.Statement.readPrepare(Unknown Source)\r\n\tat org.apache.derby.client.am.Statement.flowExecute(Unknown Source)\r\n\tat org.apache.derby.client.am.Statement.executeX(Unknown Source)\r\n\t... 32 more\r\n7) testReplication_Local_StateTest_part1_2(org.apache.derbyTesting.functionTests.tests.replicationTests.ReplicationRun_Local_StateTest_part1_2)java.sql.SQLException: DERBY SQL error: SQLCODE: -1, SQLSTATE: XSAI2, SQLERRMC: 384XSAI2.S\r\n\tat org.apache.derby.client.am.SQLExceptionFactory40.getSQLException(Unknown Source)\r\n\tat org.apache.derby.client.am.SqlException.getSQLException(Unknown Source)\r\n\tat org.apache.derby.client.am.Statement.execute(Unknown Source)\r\n\tat org.apache.derbyTesting.functionTests.tests.replicationTests.ReplicationRun.bootMasterDatabase(ReplicationRun.java:868)\r\n\tat org.apache.derbyTesting.functionTests.tests.replicationTests.ReplicationRun_Local_StateTest_part1_2.testReplication_Local_StateTest_part1_2(ReplicationRun_Local_StateTest_part1_2.java:104)\r\n\tat sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)\r\n\tat sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)\r\n\tat sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)\r\n\tat org.apache.derbyTesting.junit.BaseTestCase.runBare(BaseTestCase.java:113)\r\n\tat org.apache.derbyTesting.functionTests.tests.replicationTests.ReplicationRun.runBare(ReplicationRun.java:206)\r\n\tat junit.extensions.TestDecorator.basicRun(TestDecorator.java:24)\r\n\tat junit.extensions.TestSetup$1.protect(TestSetup.java:21)\r\n\tat junit.extensions.TestSetup.run(TestSetup.java:25)\r\nCaused by: org.apache.derby.client.am.SqlException: DERBY SQL error: SQLCODE: -1, SQLSTATE: XSAI2, SQLERRMC: 384XSAI2.S\r\n\tat org.apache.derby.client.am.Statement.completeSqlca(Unknown Source)\r\n\tat org.apache.derby.client.net.NetStatementReply.parsePrepareError(Unknown Source)\r\n\tat org.apache.derby.client.net.NetStatementReply.parsePRPSQLSTTreply(Unknown Source)\r\n\tat org.apache.derby.client.net.NetStatementReply.readPrepare(Unknown Source)\r\n\tat org.apache.derby.client.net.StatementReply.readPrepare(Unknown Source)\r\n\tat org.apache.derby.client.net.NetStatement.readPrepare_(Unknown Source)\r\n\tat org.apache.derby.client.am.Statement.readPrepare(Unknown Source)\r\n\tat org.apache.derby.client.am.Statement.flowExecute(Unknown Source)\r\n\tat org.apache.derby.client.am.Statement.executeX(Unknown Source)\r\n\t... 32 more\r\n8) testReplication_Local_StateTest_part1_3(org.apache.derbyTesting.functionTests.tests.replicationTests.ReplicationRun_Local_StateTest_part1_3)java.sql.SQLException: DERBY SQL error: SQLCODE: -1, SQLSTATE: XSAI2, SQLERRMC: 384XSAI2.S\r\n\tat org.apache.derby.client.am.SQLExceptionFactory40.getSQLException(Unknown Source)\r\n\tat org.apache.derby.client.am.SqlException.getSQLException(Unknown Source)\r\n\tat org.apache.derby.client.am.Statement.execute(Unknown Source)\r\n\tat org.apache.derbyTesting.functionTests.tests.replicationTests.ReplicationRun.bootMasterDatabase(ReplicationRun.java:868)\r\n\tat org.apache.derbyTesting.functionTests.tests.replicationTests.ReplicationRun_Local_StateTest_part1_3.testReplication_Local_StateTest_part1_3(ReplicationRun_Local_StateTest_part1_3.java:95)\r\n\tat sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)\r\n\tat sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)\r\n\tat sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)\r\n\tat org.apache.derbyTesting.junit.BaseTestCase.runBare(BaseTestCase.java:113)\r\n\tat org.apache.derbyTesting.functionTests.tests.replicationTests.ReplicationRun.runBare(ReplicationRun.java:206)\r\n\tat junit.extensions.TestDecorator.basicRun(TestDecorator.java:24)\r\n\tat junit.extensions.TestSetup$1.protect(TestSetup.java:21)\r\n\tat junit.extensions.TestSetup.run(TestSetup.java:25)\r\nCaused by: org.apache.derby.client.am.SqlException: DERBY SQL error: SQLCODE: -1, SQLSTATE: XSAI2, SQLERRMC: 384XSAI2.S\r\n\tat org.apache.derby.client.am.Statement.completeSqlca(Unknown Source)\r\n\tat org.apache.derby.client.net.NetStatementReply.parsePrepareError(Unknown Source)\r\n\tat org.apache.derby.client.net.NetStatementReply.parsePRPSQLSTTreply(Unknown Source)\r\n\tat org.apache.derby.client.net.NetStatementReply.readPrepare(Unknown Source)\r\n\tat org.apache.derby.client.net.StatementReply.readPrepare(Unknown Source)\r\n\tat org.apache.derby.client.net.NetStatement.readPrepare_(Unknown Source)\r\n\tat org.apache.derby.client.am.Statement.readPrepare(Unknown Source)\r\n\tat org.apache.derby.client.am.Statement.flowExecute(Unknown Source)\r\n\tat org.apache.derby.client.am.Statement.executeX(Unknown Source)\r\n\t... 32 more\r\n9) testReplication_Local_StateTest_part2(org.apache.derbyTesting.functionTests.tests.replicationTests.ReplicationRun_Local_StateTest_part2)java.sql.SQLException: DERBY SQL error: SQLCODE: -1, SQLSTATE: XSAI2, SQLERRMC: 384XSAI2.S\r\n\tat org.apache.derby.client.am.SQLExceptionFactory40.getSQLException(Unknown Source)\r\n\tat org.apache.derby.client.am.SqlException.getSQLException(Unknown Source)\r\n\tat org.apache.derby.client.am.Statement.execute(Unknown Source)\r\n\tat org.apache.derbyTesting.functionTests.tests.replicationTests.ReplicationRun.bootMasterDatabase(ReplicationRun.java:868)\r\n\tat org.apache.derbyTesting.functionTests.tests.replicationTests.ReplicationRun_Local_StateTest_part2.testReplication_Local_StateTest_part2(ReplicationRun_Local_StateTest_part2.java:97)\r\n\tat sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)\r\n\tat sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)\r\n\tat sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)\r\n\tat org.apache.derbyTesting.junit.BaseTestCase.runBare(BaseTestCase.java:113)\r\n\tat org.apache.derbyTesting.functionTests.tests.replicationTests.ReplicationRun.runBare(ReplicationRun.java:206)\r\n\tat junit.extensions.TestDecorator.basicRun(TestDecorator.java:24)\r\n\tat junit.extensions.TestSetup$1.protect(TestSetup.java:21)\r\n\tat junit.extensions.TestSetup.run(TestSetup.java:25)\r\nCaused by: org.apache.derby.client.am.SqlException: DERBY SQL error: SQLCODE: -1, SQLSTATE: XSAI2, SQLERRMC: 384XSAI2.S\r\n\tat org.apache.derby.client.am.Statement.completeSqlca(Unknown Source)\r\n\tat org.apache.derby.client.net.NetStatementReply.parsePrepareError(Unknown Source)\r\n\tat org.apache.derby.client.net.NetStatementReply.parsePRPSQLSTTreply(Unknown Source)\r\n\tat org.apache.derby.client.net.NetStatementReply.readPrepare(Unknown Source)\r\n\tat org.apache.derby.client.net.StatementReply.readPrepare(Unknown Source)\r\n\tat org.apache.derby.client.net.NetStatement.readPrepare_(Unknown Source)\r\n\tat org.apache.derby.client.am.Statement.readPrepare(Unknown Source)\r\n\tat org.apache.derby.client.am.Statement.flowExecute(Unknown Source)\r\n\tat org.apache.derby.client.am.Statement.executeX(Unknown Source)\r\n\t... 32 more\r\n10) testReplication_Local_3_p1_StateNegativeTests(org.apache.derbyTesting.functionTests.tests.replicationTests.ReplicationRun_Local_3_p1)java.sql.SQLException: DERBY SQL error: SQLCODE: -1, SQLSTATE: XSAI2, SQLERRMC: 384XSAI2.S\r\n\tat org.apache.derby.client.am.SQLExceptionFactory40.getSQLException(Unknown Source)\r\n\tat org.apache.derby.client.am.SqlException.getSQLException(Unknown Source)\r\n\tat org.apache.derby.client.am.Statement.execute(Unknown Source)\r\n\tat org.apache.derbyTesting.functionTests.tests.replicationTests.ReplicationRun.bootMasterDatabase(ReplicationRun.java:868)\r\n\tat org.apache.derbyTesting.functionTests.tests.replicationTests.ReplicationRun_Local_3_p1.testReplication_Local_3_p1_StateNegativeTests(ReplicationRun_Local_3_p1.java:98)\r\n\tat sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)\r\n\tat sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)\r\n\tat sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)\r\n\tat org.apache.derbyTesting.junit.BaseTestCase.runBare(BaseTestCase.java:113)\r\n\tat org.apache.derbyTesting.functionTests.tests.replicationTests.ReplicationRun.runBare(ReplicationRun.java:206)\r\n\tat junit.extensions.TestDecorator.basicRun(TestDecorator.java:24)\r\n\tat junit.extensions.TestSetup$1.protect(TestSetup.java:21)\r\n\tat junit.extensions.TestSetup.run(TestSetup.java:25)\r\nCaused by: org.apache.derby.client.am.SqlException: DERBY SQL error: SQLCODE: -1, SQLSTATE: XSAI2, SQLERRMC: 384XSAI2.S\r\n\tat org.apache.derby.client.am.Statement.completeSqlca(Unknown Source)\r\n\tat org.apache.derby.client.net.NetStatementReply.parsePrepareError(Unknown Source)\r\n\tat org.apache.derby.client.net.NetStatementReply.parsePRPSQLSTTreply(Unknown Source)\r\n\tat org.apache.derby.client.net.NetStatementReply.readPrepare(Unknown Source)\r\n\tat org.apache.derby.client.net.StatementReply.readPrepare(Unknown Source)\r\n\tat org.apache.derby.client.net.NetStatement.readPrepare_(Unknown Source)\r\n\tat org.apache.derby.client.am.Statement.readPrepare(Unknown Source)\r\n\tat org.apache.derby.client.am.Statement.flowExecute(Unknown Source)\r\n\tat org.apache.derby.client.am.Statement.executeX(Unknown Source)\r\n\t... 32 more\r\n11) testReplication_Local_3_p2_StateTests_bigInsert_sleepBeforeStopMaster(org.apache.derbyTesting.functionTests.tests.replicationTests.ReplicationRun_Local_3_p2)java.sql.SQLException: DERBY SQL error: SQLCODE: -1, SQLSTATE: XSAI2, SQLERRMC: 384XSAI2.S\r\n\tat org.apache.derby.client.am.SQLExceptionFactory40.getSQLException(Unknown Source)\r\n\tat org.apache.derby.client.am.SqlException.getSQLException(Unknown Source)\r\n\tat org.apache.derby.client.am.Statement.execute(Unknown Source)\r\n\tat org.apache.derbyTesting.functionTests.tests.replicationTests.ReplicationRun.bootMasterDatabase(ReplicationRun.java:868)\r\n\tat org.apache.derbyTesting.functionTests.tests.replicationTests.ReplicationRun_Local_3_p2.replication_Local_3_p2_StateTests(ReplicationRun_Local_3_p2.java:103)\r\n\tat org.apache.derbyTesting.functionTests.tests.replicationTests.ReplicationRun_Local_3_p2.testReplication_Local_3_p2_StateTests_bigInsert_sleepBeforeStopMaster(ReplicationRun_Local_3_p2.java:248)\r\n\tat sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)\r\n\tat sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)\r\n\tat sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)\r\n\tat org.apache.derbyTesting.junit.BaseTestCase.runBare(BaseTestCase.java:113)\r\n\tat org.apache.derbyTesting.functionTests.tests.replicationTests.ReplicationRun.runBare(ReplicationRun.java:206)\r\n\tat junit.extensions.TestDecorator.basicRun(TestDecorator.java:24)\r\n\tat junit.extensions.TestSetup$1.protect(TestSetup.java:21)\r\n\tat junit.extensions.TestSetup.run(TestSetup.java:25)\r\nCaused by: org.apache.derby.client.am.SqlException: DERBY SQL error: SQLCODE: -1, SQLSTATE: XSAI2, SQLERRMC: 384XSAI2.S\r\n\tat org.apache.derby.client.am.Statement.completeSqlca(Unknown Source)\r\n\tat org.apache.derby.client.net.NetStatementReply.parsePrepareError(Unknown Source)\r\n\tat org.apache.derby.client.net.NetStatementReply.parsePRPSQLSTTreply(Unknown Source)\r\n\tat org.apache.derby.client.net.NetStatementReply.readPrepare(Unknown Source)\r\n\tat org.apache.derby.client.net.StatementReply.readPrepare(Unknown Source)\r\n\tat org.apache.derby.client.net.NetStatement.readPrepare_(Unknown Source)\r\n\tat org.apache.derby.client.am.Statement.readPrepare(Unknown Source)\r\n\tat org.apache.derby.client.am.Statement.flowExecute(Unknown Source)\r\n\tat org.apache.derby.client.am.Statement.executeX(Unknown Source)\r\n\t... 33 more\r\n12) testReplication_Local_3_p2_StateTests_smallInsert_sleepBeforeStopMaster(org.apache.derbyTesting.functionTests.tests.replicationTests.ReplicationRun_Local_3_p2)java.sql.SQLException: DERBY SQL error: SQLCODE: -1, SQLSTATE: XSAI2, SQLERRMC: 384XSAI2.S\r\n\tat org.apache.derby.client.am.SQLExceptionFactory40.getSQLException(Unknown Source)\r\n\tat org.apache.derby.client.am.SqlException.getSQLException(Unknown Source)\r\n\tat org.apache.derby.client.am.Statement.execute(Unknown Source)\r\n\tat org.apache.derbyTesting.functionTests.tests.replicationTests.ReplicationRun.bootMasterDatabase(ReplicationRun.java:868)\r\n\tat org.apache.derbyTesting.functionTests.tests.replicationTests.ReplicationRun_Local_3_p2.replication_Local_3_p2_StateTests(ReplicationRun_Local_3_p2.java:103)\r\n\tat org.apache.derbyTesting.functionTests.tests.replicationTests.ReplicationRun_Local_3_p2.testReplication_Local_3_p2_StateTests_smallInsert_sleepBeforeStopMaster(ReplicationRun_Local_3_p2.java:253)\r\n\tat sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)\r\n\tat sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)\r\n\tat sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)\r\n\tat org.apache.derbyTesting.junit.BaseTestCase.runBare(BaseTestCase.java:113)\r\n\tat org.apache.derbyTesting.functionTests.tests.replicationTests.ReplicationRun.runBare(ReplicationRun.java:206)\r\n\tat junit.extensions.TestDecorator.basicRun(TestDecorator.java:24)\r\n\tat junit.extensions.TestSetup$1.protect(TestSetup.java:21)\r\n\tat junit.extensions.TestSetup.run(TestSetup.java:25)\r\nCaused by: org.apache.derby.client.am.SqlException: DERBY SQL error: SQLCODE: -1, SQLSTATE: XSAI2, SQLERRMC: 384XSAI2.S\r\n\tat org.apache.derby.client.am.Statement.completeSqlca(Unknown Source)\r\n\tat org.apache.derby.client.net.NetStatementReply.parsePrepareError(Unknown Source)\r\n\tat org.apache.derby.client.net.NetStatementReply.parsePRPSQLSTTreply(Unknown Source)\r\n\tat org.apache.derby.client.net.NetStatementReply.readPrepare(Unknown Source)\r\n\tat org.apache.derby.client.net.StatementReply.readPrepare(Unknown Source)\r\n\tat org.apache.derby.client.net.NetStatement.readPrepare_(Unknown Source)\r\n\tat org.apache.derby.client.am.Statement.readPrepare(Unknown Source)\r\n\tat org.apache.derby.client.am.Statement.flowExecute(Unknown Source)\r\n\tat org.apache.derby.client.am.Statement.executeX(Unknown Source)\r\n\t... 33 more\r\n13) testReplication_Local_3_p2_StateTests_bigInsert_immediateStopMaster(org.apache.derbyTesting.functionTests.tests.replicationTests.ReplicationRun_Local_3_p2)java.sql.SQLException: DERBY SQL error: SQLCODE: -1, SQLSTATE: XSAI2, SQLERRMC: 384XSAI2.S\r\n\tat org.apache.derby.client.am.SQLExceptionFactory40.getSQLException(Unknown Source)\r\n\tat org.apache.derby.client.am.SqlException.getSQLException(Unknown Source)\r\n\tat org.apache.derby.client.am.Statement.execute(Unknown Source)\r\n\tat org.apache.derbyTesting.functionTests.tests.replicationTests.ReplicationRun.bootMasterDatabase(ReplicationRun.java:868)\r\n\tat org.apache.derbyTesting.functionTests.tests.replicationTests.ReplicationRun_Local_3_p2.replication_Local_3_p2_StateTests(ReplicationRun_Local_3_p2.java:103)\r\n\tat org.apache.derbyTesting.functionTests.tests.replicationTests.ReplicationRun_Local_3_p2.testReplication_Local_3_p2_StateTests_bigInsert_immediateStopMaster(ReplicationRun_Local_3_p2.java:233)\r\n\tat sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)\r\n\tat sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)\r\n\tat sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)\r\n\tat org.apache.derbyTesting.junit.BaseTestCase.runBare(BaseTestCase.java:113)\r\n\tat org.apache.derbyTesting.functionTests.tests.replicationTests.ReplicationRun.runBare(ReplicationRun.java:206)\r\n\tat junit.extensions.TestDecorator.basicRun(TestDecorator.java:24)\r\n\tat junit.extensions.TestSetup$1.protect(TestSetup.java:21)\r\n\tat junit.extensions.TestSetup.run(TestSetup.java:25)\r\nCaused by: org.apache.derby.client.am.SqlException: DERBY SQL error: SQLCODE: -1, SQLSTATE: XSAI2, SQLERRMC: 384XSAI2.S\r\n\tat org.apache.derby.client.am.Statement.completeSqlca(Unknown Source)\r\n\tat org.apache.derby.client.net.NetStatementReply.parsePrepareError(Unknown Source)\r\n\tat org.apache.derby.client.net.NetStatementReply.parsePRPSQLSTTreply(Unknown Source)\r\n\tat org.apache.derby.client.net.NetStatementReply.readPrepare(Unknown Source)\r\n\tat org.apache.derby.client.net.StatementReply.readPrepare(Unknown Source)\r\n\tat org.apache.derby.client.net.NetStatement.readPrepare_(Unknown Source)\r\n\tat org.apache.derby.client.am.Statement.readPrepare(Unknown Source)\r\n\tat org.apache.derby.client.am.Statement.flowExecute(Unknown Source)\r\n\tat org.apache.derby.client.am.Statement.executeX(Unknown Source)\r\n\t... 33 more\r\n14) testReplication_Local_3_p3_StateNegativeTests(org.apache.derbyTesting.functionTests.tests.replicationTests.ReplicationRun_Local_3_p3)java.sql.SQLException: DERBY SQL error: SQLCODE: -1, SQLSTATE: XSAI2, SQLERRMC: 384XSAI2.S\r\n\tat org.apache.derby.client.am.SQLExceptionFactory40.getSQLException(Unknown Source)\r\n\tat org.apache.derby.client.am.SqlException.getSQLException(Unknown Source)\r\n\tat org.apache.derby.client.am.Statement.execute(Unknown Source)\r\n\tat org.apache.derbyTesting.functionTests.tests.replicationTests.ReplicationRun.bootMasterDatabase(ReplicationRun.java:868)\r\n\tat org.apache.derbyTesting.functionTests.tests.replicationTests.ReplicationRun_Local_3_p3.testReplication_Local_3_p3_StateNegativeTests(ReplicationRun_Local_3_p3.java:103)\r\n\tat sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)\r\n\tat sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)\r\n\tat sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)\r\n\tat org.apache.derbyTesting.junit.BaseTestCase.runBare(BaseTestCase.java:113)\r\n\tat org.apache.derbyTesting.functionTests.tests.replicationTests.ReplicationRun.runBare(ReplicationRun.java:206)\r\n\tat junit.extensions.TestDecorator.basicRun(TestDecorator.java:24)\r\n\tat junit.extensions.TestSetup$1.protect(TestSetup.java:21)\r\n\tat junit.extensions.TestSetup.run(TestSetup.java:25)\r\nCaused by: org.apache.derby.client.am.SqlException: DERBY SQL error: SQLCODE: -1, SQLSTATE: XSAI2, SQLERRMC: 384XSAI2.S\r\n\tat org.apache.derby.client.am.Statement.completeSqlca(Unknown Source)\r\n\tat org.apache.derby.client.net.NetStatementReply.parsePrepareError(Unknown Source)\r\n\tat org.apache.derby.client.net.NetStatementReply.parsePRPSQLSTTreply(Unknown Source)\r\n\tat org.apache.derby.client.net.NetStatementReply.readPrepare(Unknown Source)\r\n\tat org.apache.derby.client.net.StatementReply.readPrepare(Unknown Source)\r\n\tat org.apache.derby.client.net.NetStatement.readPrepare_(Unknown Source)\r\n\tat org.apache.derby.client.am.Statement.readPrepare(Unknown Source)\r\n\tat org.apache.derby.client.am.Statement.flowExecute(Unknown Source)\r\n\tat org.apache.derby.client.am.Statement.executeX(Unknown Source)\r\n\t... 32 more\r\n15) testReplication_Local_3_p4_StateNegativeTests(org.apache.derbyTesting.functionTests.tests.replicationTests.ReplicationRun_Local_3_p4)java.sql.SQLException: DERBY SQL error: SQLCODE: -1, SQLSTATE: XSAI2, SQLERRMC: 384XSAI2.S\r\n\tat org.apache.derby.client.am.SQLExceptionFactory40.getSQLException(Unknown Source)\r\n\tat org.apache.derby.client.am.SqlException.getSQLException(Unknown Source)\r\n\tat org.apache.derby.client.am.Statement.execute(Unknown Source)\r\n\tat org.apache.derbyTesting.functionTests.tests.replicationTests.ReplicationRun.bootMasterDatabase(ReplicationRun.java:868)\r\n\tat org.apache.derbyTesting.functionTests.tests.replicationTests.ReplicationRun_Local_3_p4.testReplication_Local_3_p4_StateNegativeTests(ReplicationRun_Local_3_p4.java:100)\r\n\tat sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)\r\n\tat sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)\r\n\tat sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)\r\n\tat org.apache.derbyTesting.junit.BaseTestCase.runBare(BaseTestCase.java:113)\r\n\tat org.apache.derbyTesting.functionTests.tests.replicationTests.ReplicationRun.runBare(ReplicationRun.java:206)\r\n\tat junit.extensions.TestDecorator.basicRun(TestDecorator.java:24)\r\n\tat junit.extensions.TestSetup$1.protect(TestSetup.java:21)\r\n\tat junit.extensions.TestSetup.run(TestSetup.java:25)\r\nCaused by: org.apache.derby.client.am.SqlException: DERBY SQL error: SQLCODE: -1, SQLSTATE: XSAI2, SQLERRMC: 384XSAI2.S\r\n\tat org.apache.derby.client.am.Statement.completeSqlca(Unknown Source)\r\n\tat org.apache.derby.client.net.NetStatementReply.parsePrepareError(Unknown Source)\r\n\tat org.apache.derby.client.net.NetStatementReply.parsePRPSQLSTTreply(Unknown Source)\r\n\tat org.apache.derby.client.net.NetStatementReply.readPrepare(Unknown Source)\r\n\tat org.apache.derby.client.net.StatementReply.readPrepare(Unknown Source)\r\n\tat org.apache.derby.client.net.NetStatement.readPrepare_(Unknown Source)\r\n\tat org.apache.derby.client.am.Statement.readPrepare(Unknown Source)\r\n\tat org.apache.derby.client.am.Statement.flowExecute(Unknown Source)\r\n\tat org.apache.derby.client.am.Statement.executeX(Unknown Source)\r\n\t... 32 more\r\n16) testReplication_Local_3_p5_DERBY_3878(org.apache.derbyTesting.functionTests.tests.replicationTests.ReplicationRun_Local_3_p5)java.sql.SQLException: DERBY SQL error: SQLCODE: -1, SQLSTATE: XSAI2, SQLERRMC: 384XSAI2.S\r\n\tat org.apache.derby.client.am.SQLExceptionFactory40.getSQLException(Unknown Source)\r\n\tat org.apache.derby.client.am.SqlException.getSQLException(Unknown Source)\r\n\tat org.apache.derby.client.am.Statement.execute(Unknown Source)\r\n\tat org.apache.derbyTesting.functionTests.tests.replicationTests.ReplicationRun.bootMasterDatabase(ReplicationRun.java:868)\r\n\tat org.apache.derbyTesting.functionTests.tests.replicationTests.ReplicationRun.makeReadyForReplication(ReplicationRun.java:2518)\r\n\tat org.apache.derbyTesting.functionTests.tests.replicationTests.ReplicationRun_Local_3_p5.testReplication_Local_3_p5_DERBY_3878(ReplicationRun_Local_3_p5.java:73)\r\n\tat sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)\r\n\tat sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)\r\n\tat sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)\r\n\tat org.apache.derbyTesting.junit.BaseTestCase.runBare(BaseTestCase.java:113)\r\n\tat org.apache.derbyTesting.functionTests.tests.replicationTests.ReplicationRun.runBare(ReplicationRun.java:206)\r\n\tat junit.extensions.TestDecorator.basicRun(TestDecorator.java:24)\r\n\tat junit.extensions.TestSetup$1.protect(TestSetup.java:21)\r\n\tat junit.extensions.TestSetup.run(TestSetup.java:25)\r\nCaused by: org.apache.derby.client.am.SqlException: DERBY SQL error: SQLCODE: -1, SQLSTATE: XSAI2, SQLERRMC: 384XSAI2.S\r\n\tat org.apache.derby.client.am.Statement.completeSqlca(Unknown Source)\r\n\tat org.apache.derby.client.net.NetStatementReply.parsePrepareError(Unknown Source)\r\n\tat org.apache.derby.client.net.NetStatementReply.parsePRPSQLSTTreply(Unknown Source)\r\n\tat org.apache.derby.client.net.NetStatementReply.readPrepare(Unknown Source)\r\n\tat org.apache.derby.client.net.StatementReply.readPrepare(Unknown Source)\r\n\tat org.apache.derby.client.net.NetStatement.readPrepare_(Unknown Source)\r\n\tat org.apache.derby.client.am.Statement.readPrepare(Unknown Source)\r\n\tat org.apache.derby.client.am.Statement.flowExecute(Unknown Source)\r\n\tat org.apache.derby.client.am.Statement.executeX(Unknown Source)\r\n\t... 33 more\r\n17) testReplication_Encrypted_1_miniLoad_negative(org.apache.derbyTesting.functionTests.tests.replicationTests.ReplicationRun_Local_Encrypted_1)java.sql.SQLException: DERBY SQL error: SQLCODE: -1, SQLSTATE: XSAI2, SQLERRMC: 384XSAI2.S\r\n\tat org.apache.derby.client.am.SQLExceptionFactory40.getSQLException(Unknown Source)\r\n\tat org.apache.derby.client.am.SqlException.getSQLException(Unknown Source)\r\n\tat org.apache.derby.client.am.Statement.execute(Unknown Source)\r\n\tat org.apache.derbyTesting.functionTests.tests.replicationTests.ReplicationRun.bootMasterDatabase(ReplicationRun.java:868)\r\n\tat org.apache.derbyTesting.functionTests.tests.replicationTests.ReplicationRun.makeReadyForReplication(ReplicationRun.java:2518)\r\n\tat org.apache.derbyTesting.functionTests.tests.replicationTests.ReplicationRun_Local_Encrypted_1.testReplication_Encrypted_1_miniLoad_negative(ReplicationRun_Local_Encrypted_1.java:132)\r\n\tat sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)\r\n\tat sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)\r\n\tat sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)\r\n\tat org.apache.derbyTesting.junit.BaseTestCase.runBare(BaseTestCase.java:113)\r\n\tat org.apache.derbyTesting.functionTests.tests.replicationTests.ReplicationRun.runBare(ReplicationRun.java:206)\r\n\tat junit.extensions.TestDecorator.basicRun(TestDecorator.java:24)\r\n\tat junit.extensions.TestSetup$1.protect(TestSetup.java:21)\r\n\tat junit.extensions.TestSetup.run(TestSetup.java:25)\r\nCaused by: org.apache.derby.client.am.SqlException: DERBY SQL error: SQLCODE: -1, SQLSTATE: XSAI2, SQLERRMC: 384XSAI2.S\r\n\tat org.apache.derby.client.am.Statement.completeSqlca(Unknown Source)\r\n\tat org.apache.derby.client.net.NetStatementReply.parsePrepareError(Unknown Source)\r\n\tat org.apache.derby.client.net.NetStatementReply.parsePRPSQLSTTreply(Unknown Source)\r\n\tat org.apache.derby.client.net.NetStatementReply.readPrepare(Unknown Source)\r\n\tat org.apache.derby.client.net.StatementReply.readPrepare(Unknown Source)\r\n\tat org.apache.derby.client.net.NetStatement.readPrepare_(Unknown Source)\r\n\tat org.apache.derby.client.am.Statement.readPrepare(Unknown Source)\r\n\tat org.apache.derby.client.am.Statement.flowExecute(Unknown Source)\r\n\tat org.apache.derby.client.am.Statement.executeX(Unknown Source)\r\n\t... 33 more\r\n18) testReplication_Encrypted_1_stdLoad(org.apache.derbyTesting.functionTests.tests.replicationTests.ReplicationRun_Local_Encrypted_1)java.sql.SQLException: DERBY SQL error: SQLCODE: -1, SQLSTATE: XSAI2, SQLERRMC: 384XSAI2.S\r\n\tat org.apache.derby.client.am.SQLExceptionFactory40.getSQLException(Unknown Source)\r\n\tat org.apache.derby.client.am.SqlException.getSQLException(Unknown Source)\r\n\tat org.apache.derby.client.am.Statement.execute(Unknown Source)\r\n\tat org.apache.derbyTesting.functionTests.tests.replicationTests.ReplicationRun.bootMasterDatabase(ReplicationRun.java:868)\r\n\tat org.apache.derbyTesting.functionTests.tests.replicationTests.ReplicationRun.makeReadyForReplication(ReplicationRun.java:2518)\r\n\tat org.apache.derbyTesting.functionTests.tests.replicationTests.ReplicationRun_Local_Encrypted_1.testReplication_Encrypted_1_stdLoad(ReplicationRun_Local_Encrypted_1.java:77)\r\n\tat sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)\r\n\tat sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)\r\n\tat sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)\r\n\tat org.apache.derbyTesting.junit.BaseTestCase.runBare(BaseTestCase.java:113)\r\n\tat org.apache.derbyTesting.functionTests.tests.replicationTests.ReplicationRun.runBare(ReplicationRun.java:206)\r\n\tat junit.extensions.TestDecorator.basicRun(TestDecorator.java:24)\r\n\tat junit.extensions.TestSetup$1.protect(TestSetup.java:21)\r\n\tat junit.extensions.TestSetup.run(TestSetup.java:25)\r\nCaused by: org.apache.derby.client.am.SqlException: DERBY SQL error: SQLCODE: -1, SQLSTATE: XSAI2, SQLERRMC: 384XSAI2.S\r\n\tat org.apache.derby.client.am.Statement.completeSqlca(Unknown Source)\r\n\tat org.apache.derby.client.net.NetStatementReply.parsePrepareError(Unknown Source)\r\n\tat org.apache.derby.client.net.NetStatementReply.parsePRPSQLSTTreply(Unknown Source)\r\n\tat org.apache.derby.client.net.NetStatementReply.readPrepare(Unknown Source)\r\n\tat org.apache.derby.client.net.StatementReply.readPrepare(Unknown Source)\r\n\tat org.apache.derby.client.net.NetStatement.readPrepare_(Unknown Source)\r\n\tat org.apache.derby.client.am.Statement.readPrepare(Unknown Source)\r\n\tat org.apache.derby.client.am.Statement.flowExecute(Unknown Source)\r\n\tat org.apache.derby.client.am.Statement.executeX(Unknown Source)\r\n\t... 33 more\r\n19) testReplication_Local_3_p6_autocommit_OK(org.apache.derbyTesting.functionTests.tests.replicationTests.ReplicationRun_Local_3_p6)java.sql.SQLException: DERBY SQL error: SQLCODE: -1, SQLSTATE: XBCA0, SQLERRMC: ContainerCacheContainer(0, 16)XBCA0.S\r\n\tat org.apache.derby.client.am.SQLExceptionFactory40.getSQLException(Unknown Source)\r\n\tat org.apache.derby.client.am.SqlException.getSQLException(Unknown Source)\r\n\tat org.apache.derby.client.am.PreparedStatement.execute(Unknown Source)\r\n\tat org.apache.derbyTesting.functionTests.tests.replicationTests.ReplicationRun_Local_3_p6.derby_3896(ReplicationRun_Local_3_p6.java:144)\r\n\tat org.apache.derbyTesting.functionTests.tests.replicationTests.ReplicationRun_Local_3_p6.testReplication_Local_3_p6_autocommit_OK(ReplicationRun_Local_3_p6.java:86)\r\n\tat sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)\r\n\tat sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)\r\n\tat sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)\r\n\tat org.apache.derbyTesting.junit.BaseTestCase.runBare(BaseTestCase.java:113)\r\n\tat org.apache.derbyTesting.functionTests.tests.replicationTests.ReplicationRun.runBare(ReplicationRun.java:206)\r\n\tat junit.extensions.TestDecorator.basicRun(TestDecorator.java:24)\r\n\tat junit.extensions.TestSetup$1.protect(TestSetup.java:21)\r\n\tat junit.extensions.TestSetup.run(TestSetup.java:25)\r\nCaused by: org.apache.derby.client.am.SqlException: DERBY SQL error: SQLCODE: -1, SQLSTATE: XBCA0, SQLERRMC: ContainerCacheContainer(0, 16)XBCA0.S\r\n\tat org.apache.derby.client.am.Statement.completeExecute(Unknown Source)\r\n\tat org.apache.derby.client.net.NetStatementReply.parseEXCSQLSTTreply(Unknown Source)\r\n\tat org.apache.derby.client.net.NetStatementReply.readExecute(Unknown Source)\r\n\tat org.apache.derby.client.net.StatementReply.readExecute(Unknown Source)\r\n\tat org.apache.derby.client.net.NetPreparedStatement.readExecute_(Unknown Source)\r\n\tat org.apache.derby.client.am.PreparedStatement.readExecute(Unknown Source)\r\n\tat org.apache.derby.client.am.PreparedStatement.flowExecute(Unknown Source)\r\n\tat org.apache.derby.client.am.PreparedStatement.executeX(Unknown Source)\r\n\t... 32 more\r\n20) testSlaveWaitsForMaster(org.apache.derbyTesting.functionTests.tests.replicationTests.ReplicationRun_Local_Derby4910)java.sql.SQLException: DERBY SQL error: SQLCODE: -1, SQLSTATE: XSAI2, SQLERRMC: 384XSAI2.S\r\n\tat org.apache.derby.client.am.SQLExceptionFactory40.getSQLException(Unknown Source)\r\n\tat org.apache.derby.client.am.SqlException.getSQLException(Unknown Source)\r\n\tat org.apache.derby.client.am.Statement.execute(Unknown Source)\r\n\tat org.apache.derbyTesting.functionTests.tests.replicationTests.ReplicationRun.bootMasterDatabase(ReplicationRun.java:868)\r\n\tat org.apache.derbyTesting.functionTests.tests.replicationTests.ReplicationRun_Local_Derby4910.testSlaveWaitsForMaster(ReplicationRun_Local_Derby4910.java:80)\r\n\tat sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)\r\n\tat sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)\r\n\tat sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)\r\n\tat org.apache.derbyTesting.junit.BaseTestCase.runBare(BaseTestCase.java:113)\r\n\tat org.apache.derbyTesting.functionTests.tests.replicationTests.ReplicationRun.runBare(ReplicationRun.java:206)\r\n\tat junit.extensions.TestDecorator.basicRun(TestDecorator.java:24)\r\n\tat junit.extensions.TestSetup$1.protect(TestSetup.java:21)\r\n\tat junit.extensions.TestSetup.run(TestSetup.java:25)\r\nCaused by: org.apache.derby.client.am.SqlException: DERBY SQL error: SQLCODE: -1, SQLSTATE: XSAI2, SQLERRMC: 384XSAI2.S\r\n\tat org.apache.derby.client.am.Statement.completeSqlca(Unknown Source)\r\n\tat org.apache.derby.client.net.NetStatementReply.parsePrepareError(Unknown Source)\r\n\tat org.apache.derby.client.net.NetStatementReply.parsePRPSQLSTTreply(Unknown Source)\r\n\tat org.apache.derby.client.net.NetStatementReply.readPrepare(Unknown Source)\r\n\tat org.apache.derby.client.net.StatementReply.readPrepare(Unknown Source)\r\n\tat org.apache.derby.client.net.NetStatement.readPrepare_(Unknown Source)\r\n\tat org.apache.derby.client.am.Statement.readPrepare(Unknown Source)\r\n\tat org.apache.derby.client.am.Statement.flowExecute(Unknown Source)\r\n\tat org.apache.derby.client.am.Statement.executeX(Unknown Source)\r\n\t... 32 more\r\nThere were 9 failures:\r\n1) SecureServerTest( Opened = false, Authenticated= true, CustomDerbyProperties= null, WildCardHost= 0.0.0.0 )junit.framework.AssertionFailedError: expected:<0> but was:<1>\r\n\tat org.apache.derbyTesting.functionTests.tests.derbynet.SecureServerTest.runServerCommand(SecureServerTest.java:501)\r\n\tat org.apache.derbyTesting.functionTests.tests.derbynet.SecureServerTest.runsysinfo(SecureServerTest.java:415)\r\n\tat org.apache.derbyTesting.functionTests.tests.derbynet.SecureServerTest.testServerStartup(SecureServerTest.java:356)\r\n\tat sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)\r\n\tat sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)\r\n\tat sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)\r\n\tat org.apache.derbyTesting.junit.BaseTestCase.runBare(BaseTestCase.java:113)\r\n\tat junit.extensions.TestDecorator.basicRun(TestDecorator.java:24)\r\n\tat junit.extensions.TestSetup$1.protect(TestSetup.java:21)\r\n\tat junit.extensions.TestSetup.run(TestSetup.java:25)\r\n\tat org.apache.derbyTesting.junit.BaseTestSetup.run(BaseTestSetup.java:57)\r\n\tat junit.extensions.TestDecorator.basicRun(TestDecorator.java:24)\r\n\tat junit.extensions.TestSetup$1.protect(TestSetup.java:21)\r\n\tat junit.extensions.TestSetup.run(TestSetup.java:25)\r\n\tat junit.extensions.TestDecorator.basicRun(TestDecorator.java:24)\r\n\tat junit.extensions.TestSetup$1.protect(TestSetup.java:21)\r\n\tat junit.extensions.TestSetup.run(TestSetup.java:25)\r\n\tat junit.extensions.TestDecorator.basicRun(TestDecorator.java:24)\r\n\tat junit.extensions.TestSetup$1.protect(TestSetup.java:21)\r\n\tat junit.extensions.TestSetup.run(TestSetup.java:25)\r\n2) SecureServerTest( Opened = false, Authenticated= true, CustomDerbyProperties= null, WildCardHost= 0.00.000.0 )junit.framework.AssertionFailedError: expected:<0> but was:<1>\r\n\tat org.apache.derbyTesting.functionTests.tests.derbynet.SecureServerTest.runServerCommand(SecureServerTest.java:501)\r\n\tat org.apache.derbyTesting.functionTests.tests.derbynet.SecureServerTest.runsysinfo(SecureServerTest.java:415)\r\n\tat org.apache.derbyTesting.functionTests.tests.derbynet.SecureServerTest.testServerStartup(SecureServerTest.java:356)\r\n\tat sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)\r\n\tat sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)\r\n\tat sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)\r\n\tat org.apache.derbyTesting.junit.BaseTestCase.runBare(BaseTestCase.java:113)\r\n\tat junit.extensions.TestDecorator.basicRun(TestDecorator.java:24)\r\n\tat junit.extensions.TestSetup$1.protect(TestSetup.java:21)\r\n\tat junit.extensions.TestSetup.run(TestSetup.java:25)\r\n\tat org.apache.derbyTesting.junit.BaseTestSetup.run(BaseTestSetup.java:57)\r\n\tat junit.extensions.TestDecorator.basicRun(TestDecorator.java:24)\r\n\tat junit.extensions.TestSetup$1.protect(TestSetup.java:21)\r\n\tat junit.extensions.TestSetup.run(TestSetup.java:25)\r\n\tat junit.extensions.TestDecorator.basicRun(TestDecorator.java:24)\r\n\tat junit.extensions.TestSetup$1.protect(TestSetup.java:21)\r\n\tat junit.extensions.TestSetup.run(TestSetup.java:25)\r\n\tat junit.extensions.TestDecorator.basicRun(TestDecorator.java:24)\r\n\tat junit.extensions.TestSetup$1.protect(TestSetup.java:21)\r\n\tat junit.extensions.TestSetup.run(TestSetup.java:25)\r\n3) JMXTest:clientjunit.framework.AssertionFailedError: Timed out waiting for network server to start:Spawned SpawnedNetworkServer exitCode=1\r\nSTDERR:\r\nError: Exception thrown by the agent : java.net.MalformedURLException: Local host name unknown: java.net.UnknownHostException: richard-hillegas-computer.local: richard-hillegas-computer.local: nodename nor servname provided, or not known\r\n\r\n\tat org.apache.derbyTesting.junit.NetworkServerTestSetup.setUp(NetworkServerTestSetup.java:205)\r\n\tat junit.extensions.TestSetup$1.protect(TestSetup.java:20)\r\n\tat junit.extensions.TestSetup.run(TestSetup.java:25)\r\n\tat org.apache.derbyTesting.junit.BaseTestSetup.run(BaseTestSetup.java:57)\r\n\tat junit.extensions.TestDecorator.basicRun(TestDecorator.java:24)\r\n\tat junit.extensions.TestSetup$1.protect(TestSetup.java:21)\r\n\tat junit.extensions.TestSetup.run(TestSetup.java:25)\r\n\tat junit.extensions.TestDecorator.basicRun(TestDecorator.java:24)\r\n\tat junit.extensions.TestSetup$1.protect(TestSetup.java:21)\r\n\tat junit.extensions.TestSetup.run(TestSetup.java:25)\r\n4) ManagementMBeanTest:clientjunit.framework.AssertionFailedError: Timed out waiting for network server to start:Spawned SpawnedNetworkServer exitCode=1\r\nSTDERR:\r\nError: Exception thrown by the agent : java.net.MalformedURLException: Local host name unknown: java.net.UnknownHostException: richard-hillegas-computer.local: richard-hillegas-computer.local: nodename nor servname provided, or not known\r\n\r\n\tat org.apache.derbyTesting.junit.NetworkServerTestSetup.setUp(NetworkServerTestSetup.java:205)\r\n\tat junit.extensions.TestSetup$1.protect(TestSetup.java:20)\r\n\tat junit.extensions.TestSetup.run(TestSetup.java:25)\r\n\tat org.apache.derbyTesting.junit.BaseTestSetup.run(BaseTestSetup.java:57)\r\n\tat junit.extensions.TestDecorator.basicRun(TestDecorator.java:24)\r\n\tat junit.extensions.TestSetup$1.protect(TestSetup.java:21)\r\n\tat junit.extensions.TestSetup.run(TestSetup.java:25)\r\n\tat junit.extensions.TestDecorator.basicRun(TestDecorator.java:24)\r\n\tat junit.extensions.TestSetup$1.protect(TestSetup.java:21)\r\n\tat junit.extensions.TestSetup.run(TestSetup.java:25)\r\n5) InactiveManagementMBeanTest:clientjunit.framework.AssertionFailedError: Timed out waiting for network server to start:Spawned SpawnedNetworkServer exitCode=1\r\nSTDERR:\r\nError: Exception thrown by the agent : java.net.MalformedURLException: Local host name unknown: java.net.UnknownHostException: richard-hillegas-computer.local: richard-hillegas-computer.local: nodename nor servname provided, or not known\r\n\r\n\tat org.apache.derbyTesting.junit.NetworkServerTestSetup.setUp(NetworkServerTestSetup.java:205)\r\n\tat junit.extensions.TestSetup$1.protect(TestSetup.java:20)\r\n\tat junit.extensions.TestSetup.run(TestSetup.java:25)\r\n\tat org.apache.derbyTesting.junit.BaseTestSetup.run(BaseTestSetup.java:57)\r\n\tat junit.extensions.TestDecorator.basicRun(TestDecorator.java:24)\r\n\tat junit.extensions.TestSetup$1.protect(TestSetup.java:21)\r\n\tat junit.extensions.TestSetup.run(TestSetup.java:25)\r\n\tat junit.extensions.TestDecorator.basicRun(TestDecorator.java:24)\r\n\tat junit.extensions.TestSetup$1.protect(TestSetup.java:21)\r\n\tat junit.extensions.TestSetup.run(TestSetup.java:25)\r\n6) VersionMBeanTest:clientjunit.framework.AssertionFailedError: Timed out waiting for network server to start:Spawned SpawnedNetworkServer exitCode=1\r\nSTDERR:\r\nError: Exception thrown by the agent : java.net.MalformedURLException: Local host name unknown: java.net.UnknownHostException: richard-hillegas-computer.local: richard-hillegas-computer.local: nodename nor servname provided, or not known\r\n\r\n\tat org.apache.derbyTesting.junit.NetworkServerTestSetup.setUp(NetworkServerTestSetup.java:205)\r\n\tat junit.extensions.TestSetup$1.protect(TestSetup.java:20)\r\n\tat junit.extensions.TestSetup.run(TestSetup.java:25)\r\n\tat org.apache.derbyTesting.junit.BaseTestSetup.run(BaseTestSetup.java:57)\r\n\tat junit.extensions.TestDecorator.basicRun(TestDecorator.java:24)\r\n\tat junit.extensions.TestSetup$1.protect(TestSetup.java:21)\r\n\tat junit.extensions.TestSetup.run(TestSetup.java:25)\r\n\tat junit.extensions.TestDecorator.basicRun(TestDecorator.java:24)\r\n\tat junit.extensions.TestSetup$1.protect(TestSetup.java:21)\r\n\tat junit.extensions.TestSetup.run(TestSetup.java:25)\r\n7) JDBCMBeanTest:clientjunit.framework.AssertionFailedError: Timed out waiting for network server to start:Spawned SpawnedNetworkServer exitCode=1\r\nSTDERR:\r\nError: Exception thrown by the agent : java.net.MalformedURLException: Local host name unknown: java.net.UnknownHostException: richard-hillegas-computer.local: richard-hillegas-computer.local: nodename nor servname provided, or not known\r\n\r\n\tat org.apache.derbyTesting.junit.NetworkServerTestSetup.setUp(NetworkServerTestSetup.java:205)\r\n\tat junit.extensions.TestSetup$1.protect(TestSetup.java:20)\r\n\tat junit.extensions.TestSetup.run(TestSetup.java:25)\r\n\tat org.apache.derbyTesting.junit.BaseTestSetup.run(BaseTestSetup.java:57)\r\n\tat junit.extensions.TestDecorator.basicRun(TestDecorator.java:24)\r\n\tat junit.extensions.TestSetup$1.protect(TestSetup.java:21)\r\n\tat junit.extensions.TestSetup.run(TestSetup.java:25)\r\n\tat junit.extensions.TestDecorator.basicRun(TestDecorator.java:24)\r\n\tat junit.extensions.TestSetup$1.protect(TestSetup.java:21)\r\n\tat junit.extensions.TestSetup.run(TestSetup.java:25)\r\n8) NetworkServerMBeanTest:clientjunit.framework.AssertionFailedError: Timed out waiting for network server to start:Spawned SpawnedNetworkServer exitCode=1\r\nSTDERR:\r\nError: Exception thrown by the agent : java.net.MalformedURLException: Local host name unknown: java.net.UnknownHostException: richard-hillegas-computer.local: richard-hillegas-computer.local: nodename nor servname provided, or not known\r\n\r\n\tat org.apache.derbyTesting.junit.NetworkServerTestSetup.setUp(NetworkServerTestSetup.java:205)\r\n\tat junit.extensions.TestSetup$1.protect(TestSetup.java:20)\r\n\tat junit.extensions.TestSetup.run(TestSetup.java:25)\r\n\tat org.apache.derbyTesting.junit.BaseTestSetup.run(BaseTestSetup.java:57)\r\n\tat junit.extensions.TestDecorator.basicRun(TestDecorator.java:24)\r\n\tat junit.extensions.TestSetup$1.protect(TestSetup.java:21)\r\n\tat junit.extensions.TestSetup.run(TestSetup.java:25)\r\n\tat junit.extensions.TestDecorator.basicRun(TestDecorator.java:24)\r\n\tat junit.extensions.TestSetup$1.protect(TestSetup.java:21)\r\n\tat junit.extensions.TestSetup.run(TestSetup.java:25)\r\n9) testReplication_Local_StateTest_part1(org.apache.derbyTesting.functionTests.tests.replicationTests.ReplicationRun_Local_StateTest_part1)junit.framework.AssertionFailedError: Unexpected SQLException: -1 08004 DERBY SQL error: SQLCODE: -1, SQLSTATE: 08004, SQLERRMC: Connection refused : java.sql.SQLException: Required property 'slaveHost' has not been set.\r\n\tat org.apache.derbyTesting.functionTests.tests.replicationTests.ReplicationRun_Local_StateTest_part1._testPreStartedMasterServer(ReplicationRun_Local_StateTest_part1.java:212)\r\n\tat org.apache.derbyTesting.functionTests.tests.replicationTests.ReplicationRun_Local_StateTest_part1.testReplication_Local_StateTest_part1(ReplicationRun_Local_StateTest_part1.java:88)\r\n\tat sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)\r\n\tat sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)\r\n\tat sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)\r\n\tat org.apache.derbyTesting.junit.BaseTestCase.runBare(BaseTestCase.java:113)\r\n\tat org.apache.derbyTesting.functionTests.tests.replicationTests.ReplicationRun.runBare(ReplicationRun.java:206)\r\n\tat junit.extensions.TestDecorator.basicRun(TestDecorator.java:24)\r\n\tat junit.extensions.TestSetup$1.protect(TestSetup.java:21)\r\n\tat junit.extensions.TestSetup.run(TestSetup.java:25)\r\n\r\nFAILURES!!!\r\nTests run: 11559,  Failures: 9,  Errors: 20\r\n","customfield_10010":null,"timetracking":{},"customfield_12312026":null,"customfield_12310200":null,"customfield_12312023":null,"customfield_12312024":null,"customfield_12312340":null,"aggregatetimeestimate":null,"customfield_12312022":null,"customfield_12312341":null,"customfield_12312220":null,"customfield_12310921":null,"customfield_12310920":"36158","summary":"Problems running SecureServerTest and replication tests on Open JDK 7 for Mac OS X","creator":{"self":"https://issues.apache.org/jira/rest/api/2/user?username=rhillegas","name":"rhillegas","emailAddress":"rhillegas at apache dot org","avatarUrls":{"48x48":"https://issues.apache.org/jira/secure/useravatar?avatarId=10452","24x24":"https://issues.apache.org/jira/secure/useravatar?size=small&avatarId=10452","16x16":"https://issues.apache.org/jira/secure/useravatar?size=xsmall&avatarId=10452","32x32":"https://issues.apache.org/jira/secure/useravatar?size=medium&avatarId=10452"},"displayName":"Rick Hillegas","active":true},"subtasks":[],"customfield_12310090":null,"reporter":{"self":"https://issues.apache.org/jira/rest/api/2/user?username=rhillegas","name":"rhillegas","emailAddress":"rhillegas at apache dot org","avatarUrls":{"48x48":"https://issues.apache.org/jira/secure/useravatar?avatarId=10452","24x24":"https://issues.apache.org/jira/secure/useravatar?size=small&avatarId=10452","16x16":"https://issues.apache.org/jira/secure/useravatar?size=xsmall&avatarId=10452","32x32":"https://issues.apache.org/jira/secure/useravatar?size=medium&avatarId=10452"},"displayName":"Rick Hillegas","active":true},"customfield_12310291":null,"customfield_12310290":null,"aggregateprogress":{"progress":0,"total":0},"environment":"mac os x 10.6.8, OpenJDK Runtime Environment (build 1.7.0-b210-20110929)","customfield_12311020":null,"customfield_12310050":null,"duedate":null,"customfield_12310250":null,"progress":{"progress":0,"total":0},"comment":{"startAt":0,"maxResults":9,"total":9,"comments":[{"self":"https://issues.apache.org/jira/rest/api/2/issue/12526723/comment/13125344","id":"13125344","author":{"self":"https://issues.apache.org/jira/rest/api/2/user?username=kristwaa","name":"kristwaa","emailAddress":"kristwaa at apache dot org","avatarUrls":{"48x48":"https://issues.apache.org/jira/secure/useravatar?ownerId=kristwaa&avatarId=14736","24x24":"https://issues.apache.org/jira/secure/useravatar?size=small&ownerId=kristwaa&avatarId=14736","16x16":"https://issues.apache.org/jira/secure/useravatar?size=xsmall&ownerId=kristwaa&avatarId=14736","32x32":"https://issues.apache.org/jira/secure/useravatar?size=medium&ownerId=kristwaa&avatarId=14736"},"displayName":"Kristian Waagan","active":true},"body":"This may be a machine configuration issue. Some questions:\r\nDo you have an entry for richard-hillegas-computer.local (or maybe without .local will suffice) in /etc/hosts, or can it otherwise be resolved?\r\nIs there more than one NIC on the computer?\r\nAre you running both IPv4 and IPv6?\r\n\r\nAnother issue would be to figure out how these tests differ from the other network tests spawning a network server when it comes to obtaining/resolving the host name.","updateAuthor":{"self":"https://issues.apache.org/jira/rest/api/2/user?username=kristwaa","name":"kristwaa","emailAddress":"kristwaa at apache dot org","avatarUrls":{"48x48":"https://issues.apache.org/jira/secure/useravatar?ownerId=kristwaa&avatarId=14736","24x24":"https://issues.apache.org/jira/secure/useravatar?size=small&ownerId=kristwaa&avatarId=14736","16x16":"https://issues.apache.org/jira/secure/useravatar?size=xsmall&ownerId=kristwaa&avatarId=14736","32x32":"https://issues.apache.org/jira/secure/useravatar?size=medium&ownerId=kristwaa&avatarId=14736"},"displayName":"Kristian Waagan","active":true},"created":"2011-10-11T20:10:41.074+0000","updated":"2011-10-11T20:10:41.074+0000"},{"self":"https://issues.apache.org/jira/rest/api/2/issue/12526723/comment/13125835","id":"13125835","author":{"self":"https://issues.apache.org/jira/rest/api/2/user?username=rhillegas","name":"rhillegas","emailAddress":"rhillegas at apache dot org","avatarUrls":{"48x48":"https://issues.apache.org/jira/secure/useravatar?avatarId=10452","24x24":"https://issues.apache.org/jira/secure/useravatar?size=small&avatarId=10452","16x16":"https://issues.apache.org/jira/secure/useravatar?size=xsmall&avatarId=10452","32x32":"https://issues.apache.org/jira/secure/useravatar?size=medium&avatarId=10452"},"displayName":"Rick Hillegas","active":true},"body":"Thanks for those questions, Kristian. Here are some answers:\r\n\r\n1) Do you have an entry for richard-hillegas-computer.local (or maybe without .local will suffice) in /etc/hosts, or can it otherwise be resolved?\r\n\r\nNope. /etc/hosts has entries for localhost and broadcasthost but not for richard-hillegas-computer.local. That latter, unknown name is what is printed out when I type the hostname command.\r\n\r\n2) Is there more than one NIC on the computer?\r\n\r\nNot that I can see.\r\n\r\n3) Are you running both IPv4 and IPv6? \r\n\r\nYes.\r\n\r\nThanks.","updateAuthor":{"self":"https://issues.apache.org/jira/rest/api/2/user?username=rhillegas","name":"rhillegas","emailAddress":"rhillegas at apache dot org","avatarUrls":{"48x48":"https://issues.apache.org/jira/secure/useravatar?avatarId=10452","24x24":"https://issues.apache.org/jira/secure/useravatar?size=small&avatarId=10452","16x16":"https://issues.apache.org/jira/secure/useravatar?size=xsmall&avatarId=10452","32x32":"https://issues.apache.org/jira/secure/useravatar?size=medium&avatarId=10452"},"displayName":"Rick Hillegas","active":true},"created":"2011-10-12T13:20:02.429+0000","updated":"2011-10-12T13:20:02.429+0000"},{"self":"https://issues.apache.org/jira/rest/api/2/issue/12526723/comment/13127676","id":"13127676","author":{"self":"https://issues.apache.org/jira/rest/api/2/user?username=rhillegas","name":"rhillegas","emailAddress":"rhillegas at apache dot org","avatarUrls":{"48x48":"https://issues.apache.org/jira/secure/useravatar?avatarId=10452","24x24":"https://issues.apache.org/jira/secure/useravatar?size=small&avatarId=10452","16x16":"https://issues.apache.org/jira/secure/useravatar?size=xsmall&avatarId=10452","32x32":"https://issues.apache.org/jira/secure/useravatar?size=medium&avatarId=10452"},"displayName":"Rick Hillegas","active":true},"body":"I have found a bug in the open jdk 7 preview for mac os x which causes server startup to cough up the following warning:\r\n\r\nWarning: UnknkownHostException: richard-hillegas-computer.local: richard-hillegas-computer.local: nodename nor servname provided, or not known. \r\n\r\nThis bug is tracked by http://java.net/jira/browse/MACOSX_PORT-564\r\n\r\nIn addition, it seems to me that server startup could be made more robust. Right now, it gives up collecting local addresses if it encounters a problem. If the server didn't give up, then it would eventually collect the local address it needs. I will attach a patch to make server startup more robust.","updateAuthor":{"self":"https://issues.apache.org/jira/rest/api/2/user?username=rhillegas","name":"rhillegas","emailAddress":"rhillegas at apache dot org","avatarUrls":{"48x48":"https://issues.apache.org/jira/secure/useravatar?avatarId=10452","24x24":"https://issues.apache.org/jira/secure/useravatar?size=small&avatarId=10452","16x16":"https://issues.apache.org/jira/secure/useravatar?size=xsmall&avatarId=10452","32x32":"https://issues.apache.org/jira/secure/useravatar?size=medium&avatarId=10452"},"displayName":"Rick Hillegas","active":true},"created":"2011-10-14T16:34:40.676+0000","updated":"2011-10-14T16:34:40.676+0000"},{"self":"https://issues.apache.org/jira/rest/api/2/issue/12526723/comment/13127683","id":"13127683","author":{"self":"https://issues.apache.org/jira/rest/api/2/user?username=rhillegas","name":"rhillegas","emailAddress":"rhillegas at apache dot org","avatarUrls":{"48x48":"https://issues.apache.org/jira/secure/useravatar?avatarId=10452","24x24":"https://issues.apache.org/jira/secure/useravatar?size=small&avatarId=10452","16x16":"https://issues.apache.org/jira/secure/useravatar?size=xsmall&avatarId=10452","32x32":"https://issues.apache.org/jira/secure/useravatar?size=medium&avatarId=10452"},"displayName":"Rick Hillegas","active":true},"body":"Attaching derby-5456-01-aa-moreRobustStartup.diff. This patch makes the server continue collecting local addresses if one of its attempts fails. The failures are not supposed to be fatal, they just result in the server printing a warning to derby.log. With this patch, SecureServerTest runs cleanly on the open jdk 7 preview for mac os x. I will run full regression tests now.\r\n\r\nTouches the following file:\r\n\r\nM       java/drda/org/apache/derby/impl/drda/NetworkServerControlImpl.java\r\n","updateAuthor":{"self":"https://issues.apache.org/jira/rest/api/2/user?username=rhillegas","name":"rhillegas","emailAddress":"rhillegas at apache dot org","avatarUrls":{"48x48":"https://issues.apache.org/jira/secure/useravatar?avatarId=10452","24x24":"https://issues.apache.org/jira/secure/useravatar?size=small&avatarId=10452","16x16":"https://issues.apache.org/jira/secure/useravatar?size=xsmall&avatarId=10452","32x32":"https://issues.apache.org/jira/secure/useravatar?size=medium&avatarId=10452"},"displayName":"Rick Hillegas","active":true},"created":"2011-10-14T16:40:30.441+0000","updated":"2011-10-14T16:40:30.441+0000"},{"self":"https://issues.apache.org/jira/rest/api/2/issue/12526723/comment/13127793","id":"13127793","author":{"self":"https://issues.apache.org/jira/rest/api/2/user?username=rhillegas","name":"rhillegas","emailAddress":"rhillegas at apache dot org","avatarUrls":{"48x48":"https://issues.apache.org/jira/secure/useravatar?avatarId=10452","24x24":"https://issues.apache.org/jira/secure/useravatar?size=small&avatarId=10452","16x16":"https://issues.apache.org/jira/secure/useravatar?size=xsmall&avatarId=10452","32x32":"https://issues.apache.org/jira/secure/useravatar?size=medium&avatarId=10452"},"displayName":"Rick Hillegas","active":true},"body":"Tests passed cleanly for me on Java 6 except for the error below. This error does not seem to me to be related to this change. Committed at subversion revision 1183463.\r\n\r\nTime: 5,975.721\r\nThere was 1 failure:\r\n1) testDerby3980_repeatable_read(org.apache.derbyTesting.functionTests.tests.lang.DeadlockDetectionTest)junit.framework.ComparisonFailure: Unexpected SQL state. expected:<40[00]1> but was:<40[XL]1>\r\n\tat org.apache.derbyTesting.junit.BaseJDBCTestCase.assertSQLState(BaseJDBCTestCase.java:791)\r\n\tat org.apache.derbyTesting.junit.BaseJDBCTestCase.assertSQLState(BaseJDBCTestCase.java:840)\r\n\tat org.apache.derbyTesting.functionTests.tests.lang.DeadlockDetectionTest.testDerby3980_repeatable_read(DeadlockDetectionTest.java:137)\r\n\tat sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)\r\n\tat sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)\r\n\tat sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)\r\n\tat org.apache.derbyTesting.junit.BaseTestCase.runBare(BaseTestCase.java:113)\r\n\tat junit.extensions.TestDecorator.basicRun(TestDecorator.java:24)\r\n\tat junit.extensions.TestSetup$1.protect(TestSetup.java:21)\r\n\tat junit.extensions.TestSetup.run(TestSetup.java:25)\r\n\tat org.apache.derbyTesting.junit.BaseTestSetup.run(BaseTestSetup.java:57)\r\n\tat junit.extensions.TestDecorator.basicRun(TestDecorator.java:24)\r\n\tat junit.extensions.TestSetup$1.protect(TestSetup.java:21)\r\n\tat junit.extensions.TestSetup.run(TestSetup.java:25)\r\n\tat org.apache.derbyTesting.junit.BaseTestSetup.run(BaseTestSetup.java:57)\r\nCaused by: java.sql.SQLTransactionRollbackException: A lock could not be obtained within the time requested\r\n\tat org.apache.derby.impl.jdbc.SQLExceptionFactory40.getSQLException(SQLExceptionFactory40.java:89)\r\n\tat org.apache.derby.impl.jdbc.Util.generateCsSQLException(Util.java:256)\r\n\tat org.apache.derby.impl.jdbc.TransactionResourceImpl.wrapInSQLException(TransactionResourceImpl.java:400)\r\n\tat org.apache.derby.impl.jdbc.TransactionResourceImpl.handleException(TransactionResourceImpl.java:348)\r\n\tat org.apache.derby.impl.jdbc.EmbedConnection.handleException(EmbedConnection.java:2290)\r\n\tat org.apache.derby.impl.jdbc.ConnectionChild.handleException(ConnectionChild.java:82)\r\n\tat org.apache.derby.impl.jdbc.EmbedStatement.executeStatement(EmbedStatement.java:1334)\r\n\tat org.apache.derby.impl.jdbc.EmbedPreparedStatement.executeStatement(EmbedPreparedStatement.java:1692)\r\n\tat org.apache.derby.impl.jdbc.EmbedPreparedStatement.executeUpdate(EmbedPreparedStatement.java:309)\r\n\tat org.apache.derbyTesting.junit.BaseJDBCTestCase.assertUpdateCount(BaseJDBCTestCase.java:1237)\r\n\tat org.apache.derbyTesting.functionTests.tests.lang.DeadlockDetectionTest$1.run(DeadlockDetectionTest.java:112)\r\nCaused by: java.sql.SQLException: A lock could not be obtained within the time requested\r\n\tat org.apache.derby.impl.jdbc.SQLExceptionFactory.getSQLException(SQLExceptionFactory.java:45)\r\n\tat org.apache.derby.impl.jdbc.SQLExceptionFactory40.wrapArgsForTransportAcrossDRDA(SQLExceptionFactory40.java:122)\r\n\tat org.apache.derby.impl.jdbc.SQLExceptionFactory40.getSQLException(SQLExceptionFactory40.java:71)\r\n\t... 10 more\r\nCaused by: ERROR 40XL1: A lock could not be obtained within the time requested\r\n\tat org.apache.derby.iapi.error.StandardException.newException(StandardException.java:268)\r\n\tat org.apache.derby.impl.services.locks.ConcurrentLockSet.lockObject(ConcurrentLockSet.java:618)\r\n\tat org.apache.derby.impl.services.locks.AbstractPool.lockObject(AbstractPool.java:119)\r\n\tat org.apache.derby.impl.services.locks.ConcurrentPool.lockObject(ConcurrentPool.java:28)\r\n\tat org.apache.derby.impl.store.raw.xact.RowLocking3.lockRecordForRead(RowLocking3.java:187)\r\n\tat org.apache.derby.impl.store.access.conglomerate.OpenConglomerate.lockPositionForRead(OpenConglomerate.java:466)\r\n\tat org.apache.derby.impl.store.access.conglomerate.GenericScanController.fetchRows(GenericScanController.java:683)\r\n\tat org.apache.derby.impl.store.access.heap.HeapScan.fetchNext(HeapScan.java:238)\r\n\tat org.apache.derby.impl.sql.execute.TableScanResultSet.getNextRowCore(TableScanResultSet.java:577)\r\n\tat org.apache.derby.impl.sql.execute.ProjectRestrictResultSet.getNextRowCore(ProjectRestrictResultSet.java:261)\r\n\tat org.apache.derby.impl.sql.execute.DMLWriteResultSet.getNextRowCore(DMLWriteResultSet.java:127)\r\n\tat org.apache.derby.impl.sql.execute.UpdateResultSet.collectAffectedRows(UpdateResultSet.java:440)\r\n\tat org.apache.derby.impl.sql.execute.UpdateResultSet.open(UpdateResultSet.java:264)\r\n\tat org.apache.derby.impl.sql.GenericPreparedStatement.executeStmt(GenericPreparedStatement.java:478)\r\n\tat org.apache.derby.impl.sql.GenericPreparedStatement.execute(GenericPreparedStatement.java:319)\r\n\tat org.apache.derby.impl.jdbc.EmbedStatement.executeStatement(EmbedStatement.java:1242)\r\n\t... 4 more\r\n\r\nFAILURES!!!\r\nTests run: 11647,  Failures: 1,  Errors: 0\r\n","updateAuthor":{"self":"https://issues.apache.org/jira/rest/api/2/user?username=rhillegas","name":"rhillegas","emailAddress":"rhillegas at apache dot org","avatarUrls":{"48x48":"https://issues.apache.org/jira/secure/useravatar?avatarId=10452","24x24":"https://issues.apache.org/jira/secure/useravatar?size=small&avatarId=10452","16x16":"https://issues.apache.org/jira/secure/useravatar?size=xsmall&avatarId=10452","32x32":"https://issues.apache.org/jira/secure/useravatar?size=medium&avatarId=10452"},"displayName":"Rick Hillegas","active":true},"created":"2011-10-14T19:18:17.744+0000","updated":"2011-10-14T19:18:17.744+0000"},{"self":"https://issues.apache.org/jira/rest/api/2/issue/12526723/comment/13127865","id":"13127865","author":{"self":"https://issues.apache.org/jira/rest/api/2/user?username=knutanders","name":"knutanders","emailAddress":"knut dot hatlen at oracle dot com","avatarUrls":{"48x48":"https://issues.apache.org/jira/secure/useravatar?avatarId=10452","24x24":"https://issues.apache.org/jira/secure/useravatar?size=small&avatarId=10452","16x16":"https://issues.apache.org/jira/secure/useravatar?size=xsmall&avatarId=10452","32x32":"https://issues.apache.org/jira/secure/useravatar?size=medium&avatarId=10452"},"displayName":"Knut Anders Hatlen","active":true},"body":"I suppose it would have been more robust to use InetAddress.getLoopbackAddress(), since it doesn't depend on name resolution. Unfortunately, that method is only available on Java 7.","updateAuthor":{"self":"https://issues.apache.org/jira/rest/api/2/user?username=knutanders","name":"knutanders","emailAddress":"knut dot hatlen at oracle dot com","avatarUrls":{"48x48":"https://issues.apache.org/jira/secure/useravatar?avatarId=10452","24x24":"https://issues.apache.org/jira/secure/useravatar?size=small&avatarId=10452","16x16":"https://issues.apache.org/jira/secure/useravatar?size=xsmall&avatarId=10452","32x32":"https://issues.apache.org/jira/secure/useravatar?size=medium&avatarId=10452"},"displayName":"Knut Anders Hatlen","active":true},"created":"2011-10-14T21:13:45.883+0000","updated":"2011-10-14T21:13:45.883+0000"},{"self":"https://issues.apache.org/jira/rest/api/2/issue/12526723/comment/13128970","id":"13128970","author":{"self":"https://issues.apache.org/jira/rest/api/2/user?username=rhillegas","name":"rhillegas","emailAddress":"rhillegas at apache dot org","avatarUrls":{"48x48":"https://issues.apache.org/jira/secure/useravatar?avatarId=10452","24x24":"https://issues.apache.org/jira/secure/useravatar?size=small&avatarId=10452","16x16":"https://issues.apache.org/jira/secure/useravatar?size=xsmall&avatarId=10452","32x32":"https://issues.apache.org/jira/secure/useravatar?size=medium&avatarId=10452"},"displayName":"Rick Hillegas","active":true},"body":"All tests passed cleanly for my on the open jdk 7 preview for mac os x. That includes SecureServerTest and the replication tests.","updateAuthor":{"self":"https://issues.apache.org/jira/rest/api/2/user?username=rhillegas","name":"rhillegas","emailAddress":"rhillegas at apache dot org","avatarUrls":{"48x48":"https://issues.apache.org/jira/secure/useravatar?avatarId=10452","24x24":"https://issues.apache.org/jira/secure/useravatar?size=small&avatarId=10452","16x16":"https://issues.apache.org/jira/secure/useravatar?size=xsmall&avatarId=10452","32x32":"https://issues.apache.org/jira/secure/useravatar?size=medium&avatarId=10452"},"displayName":"Rick Hillegas","active":true},"created":"2011-10-17T16:16:42.320+0000","updated":"2011-10-17T16:16:42.320+0000"},{"self":"https://issues.apache.org/jira/rest/api/2/issue/12526723/comment/13128976","id":"13128976","author":{"self":"https://issues.apache.org/jira/rest/api/2/user?username=rhillegas","name":"rhillegas","emailAddress":"rhillegas at apache dot org","avatarUrls":{"48x48":"https://issues.apache.org/jira/secure/useravatar?avatarId=10452","24x24":"https://issues.apache.org/jira/secure/useravatar?size=small&avatarId=10452","16x16":"https://issues.apache.org/jira/secure/useravatar?size=xsmall&avatarId=10452","32x32":"https://issues.apache.org/jira/secure/useravatar?size=medium&avatarId=10452"},"displayName":"Rick Hillegas","active":true},"body":"Ported 1183463 from trunk to 10.8 branch at subversion revision 1185277.","updateAuthor":{"self":"https://issues.apache.org/jira/rest/api/2/user?username=rhillegas","name":"rhillegas","emailAddress":"rhillegas at apache dot org","avatarUrls":{"48x48":"https://issues.apache.org/jira/secure/useravatar?avatarId=10452","24x24":"https://issues.apache.org/jira/secure/useravatar?size=small&avatarId=10452","16x16":"https://issues.apache.org/jira/secure/useravatar?size=xsmall&avatarId=10452","32x32":"https://issues.apache.org/jira/secure/useravatar?size=medium&avatarId=10452"},"displayName":"Rick Hillegas","active":true},"created":"2011-10-17T16:24:03.638+0000","updated":"2011-10-17T16:24:03.638+0000"},{"self":"https://issues.apache.org/jira/rest/api/2/issue/12526723/comment/13164535","id":"13164535","author":{"self":"https://issues.apache.org/jira/rest/api/2/user?username=rhillegas","name":"rhillegas","emailAddress":"rhillegas at apache dot org","avatarUrls":{"48x48":"https://issues.apache.org/jira/secure/useravatar?avatarId=10452","24x24":"https://issues.apache.org/jira/secure/useravatar?size=small&avatarId=10452","16x16":"https://issues.apache.org/jira/secure/useravatar?size=xsmall&avatarId=10452","32x32":"https://issues.apache.org/jira/secure/useravatar?size=medium&avatarId=10452"},"displayName":"Rick Hillegas","active":true},"body":"I have verified that these errors do not occur any more using the latest build (220) of the OpenJDK 7 preview for Mac OS X. I verified this by running the full regression suite on build 220 using Derby 10.8.2.2. I did see 7 unrelated errors (the trigger-related errors in the upgrade tests, which have been fixed on the trunk).","updateAuthor":{"self":"https://issues.apache.org/jira/rest/api/2/user?username=rhillegas","name":"rhillegas","emailAddress":"rhillegas at apache dot org","avatarUrls":{"48x48":"https://issues.apache.org/jira/secure/useravatar?avatarId=10452","24x24":"https://issues.apache.org/jira/secure/useravatar?size=small&avatarId=10452","16x16":"https://issues.apache.org/jira/secure/useravatar?size=xsmall&avatarId=10452","32x32":"https://issues.apache.org/jira/secure/useravatar?size=medium&avatarId=10452"},"displayName":"Rick Hillegas","active":true},"created":"2011-12-07T17:18:35.359+0000","updated":"2011-12-07T17:18:35.359+0000"}]},"votes":{"self":"https://issues.apache.org/jira/rest/api/2/issue/DERBY-5456/votes","votes":0,"hasVoted":false},"worklog":{"startAt":0,"maxResults":20,"total":0,"worklogs":[]},"customfield_12311820":"0|i06jwf:"}}