{"expand":"renderedFields,names,schema,transitions,operations,editmeta,changelog","id":"12416839","self":"https://issues.apache.org/jira/rest/api/latest/issue/12416839","key":"DERBY-4095","fields":{"issuetype":{"self":"https://issues.apache.org/jira/rest/api/2/issuetype/1","id":"1","description":"A problem which impairs or prevents the functions of the product.","iconUrl":"https://issues.apache.org/jira/images/icons/issuetypes/bug.png","name":"Bug","subtask":false},"timespent":null,"project":{"self":"https://issues.apache.org/jira/rest/api/2/project/10594","id":"10594","key":"DERBY","name":"Derby","avatarUrls":{"48x48":"https://issues.apache.org/jira/secure/projectavatar?pid=10594&avatarId=10122","24x24":"https://issues.apache.org/jira/secure/projectavatar?size=small&pid=10594&avatarId=10122","16x16":"https://issues.apache.org/jira/secure/projectavatar?size=xsmall&pid=10594&avatarId=10122","32x32":"https://issues.apache.org/jira/secure/projectavatar?size=medium&pid=10594&avatarId=10122"},"projectCategory":{"self":"https://issues.apache.org/jira/rest/api/2/projectCategory/10090","id":"10090","description":"DB related projects","name":"DB"}},"fixVersions":[{"self":"https://issues.apache.org/jira/rest/api/2/version/12312251","id":"12312251","description":"Head of 10.2 branch","name":"10.2.2.1","archived":false,"released":false},{"self":"https://issues.apache.org/jira/rest/api/2/version/12313143","id":"12313143","description":"Head of 10.3 branch","name":"10.3.3.1","archived":false,"released":false},{"self":"https://issues.apache.org/jira/rest/api/2/version/12313401","id":"12313401","description":"Head of 10.4 branch","name":"10.4.2.1","archived":false,"released":false},{"self":"https://issues.apache.org/jira/rest/api/2/version/12313771","id":"12313771","description":"build: 764942, 14/Apr/09. Voted release: 28/Apr/09. Announced: 1/May/09","name":"10.5.1.1","archived":false,"released":true,"releaseDate":"2009-04-28"}],"aggregatetimespent":null,"resolution":{"self":"https://issues.apache.org/jira/rest/api/2/resolution/1","id":"1","description":"A fix for this issue is checked into the tree and tested.","name":"Fixed"},"customfield_12310220":"2009-03-19 12:21:30.785","customfield_12312322":null,"customfield_12312323":null,"customfield_12310420":"24020","customfield_12310222":"1_*:*_1_*:*_2108305710_*|*_6_*:*_1_*:*_0","customfield_12312320":null,"customfield_12312321":null,"customfield_12312120":null,"customfield_12312121":null,"resolutiondate":"2009-04-06T23:51:45.502+0000","workratio":-1,"customfield_12312328":null,"customfield_12312329":null,"customfield_12312326":null,"customfield_12310300":null,"customfield_12312327":null,"customfield_12312324":null,"customfield_12312325":null,"lastViewed":null,"watches":{"self":"https://issues.apache.org/jira/rest/api/2/issue/DERBY-4095/watchers","watchCount":0,"isWatching":false},"created":"2009-03-13T14:13:19.792+0000","priority":{"self":"https://issues.apache.org/jira/rest/api/2/priority/3","iconUrl":"https://issues.apache.org/jira/images/icons/priorities/major.png","name":"Major","id":"3"},"labels":[],"customfield_12312333":null,"customfield_12312334":null,"customfield_12310310":"3.0","customfield_12312331":null,"customfield_12312332":null,"timeestimate":null,"aggregatetimeoriginalestimate":null,"versions":[{"self":"https://issues.apache.org/jira/rest/api/2/version/12312251","id":"12312251","description":"Head of 10.2 branch","name":"10.2.2.1","archived":false,"released":false},{"self":"https://issues.apache.org/jira/rest/api/2/version/12313143","id":"12313143","description":"Head of 10.3 branch","name":"10.3.3.1","archived":false,"released":false},{"self":"https://issues.apache.org/jira/rest/api/2/version/12313401","id":"12313401","description":"Head of 10.4 branch","name":"10.4.2.1","archived":false,"released":false},{"self":"https://issues.apache.org/jira/rest/api/2/version/12313771","id":"12313771","description":"build: 764942, 14/Apr/09. Voted release: 28/Apr/09. Announced: 1/May/09","name":"10.5.1.1","archived":false,"released":true,"releaseDate":"2009-04-28"}],"customfield_12311120":null,"customfield_12312330":null,"issuelinks":[],"customfield_12312339":null,"assignee":{"self":"https://issues.apache.org/jira/rest/api/2/user?username=kmarsden","name":"kmarsden","emailAddress":"kmarsdenderby at sbcglobal dot net","avatarUrls":{"48x48":"https://issues.apache.org/jira/secure/useravatar?avatarId=10452","24x24":"https://issues.apache.org/jira/secure/useravatar?size=small&avatarId=10452","16x16":"https://issues.apache.org/jira/secure/useravatar?size=xsmall&avatarId=10452","32x32":"https://issues.apache.org/jira/secure/useravatar?size=medium&avatarId=10452"},"displayName":"Kathey Marsden","active":true},"customfield_12312337":null,"customfield_12312338":null,"updated":"2010-07-05T16:58:48.931+0000","customfield_12312335":null,"customfield_12311720":null,"customfield_12312336":null,"status":{"self":"https://issues.apache.org/jira/rest/api/2/status/6","description":"The issue is considered finished, the resolution is correct. Issues which are closed can be reopened.","iconUrl":"https://issues.apache.org/jira/images/icons/statuses/closed.png","name":"Closed","id":"6","statusCategory":{"self":"https://issues.apache.org/jira/rest/api/2/statuscategory/3","id":3,"key":"done","colorName":"green","name":"Complete"}},"components":[{"self":"https://issues.apache.org/jira/rest/api/2/component/11408","id":"11408","name":"SQL"}],"timeoriginalestimate":null,"description":"I don't have a reproduction without the user database yet, but it seems that recompiling the trigger stored prepared statements on upgrade is causing a result set to get closed and is causing the following error when firing a trigger in a global transaction.  The holdability in an XA  transaction is CLOSE_CURSORS_AT_COMMIT so it may be that there is a commit occurring as part of the process that is causing the problem.  I haven't tried yet with a regular transaction and using default holdability CLOSE_CURSORS_AT_COMMIT.   The error comes on a delete which fires an after delete statement trigger to insert some values into another table.\r\n\r\nHere is the stack trace:\r\n\r\n2009-03-13 14:10:49.375 GMT Thread[main,5,main] (XID = 1853834), (SESSIONID = 1), (DATABASE = derby/wpsdb), (DRDAID = null), Cleanup action starting\r\n\r\n2009-03-13 14:10:49.375 GMT Thread[main,5,main] (XID = 1853834), (SESSIONID = 1), (DATABASE = derby/wpsdb), (DRDAID = null), Failed Statement is: DELETE FROM XXX WHERE WSID=9\r\n\r\nERROR 38000: The exception 'java.sql.SQLException: ResultSet not open. Operation 'next' not permitted. Verify that autocommit is OFF.' was thrown while evaluating an expression.\r\n\r\n\tat org.apache.derby.iapi.error.StandardException.newException(StandardException.java:294)\r\n\r\n\tat org.apache.derby.iapi.error.StandardException.unexpectedUserException(StandardException.java:554)\r\n\r\n\tat org.apache.derby.impl.sql.execute.VTIResultSet.getNextRowCore(VTIResultSet.java:326)\r\n\r\n\tat org.apache.derby.impl.sql.execute.ProjectRestrictResultSet.getNextRowCore(ProjectRestrictResultSet.java:255)\r\n\r\n\tat org.apache.derby.impl.sql.execute.NestedLoopJoinResultSet.getNextRowCore(NestedLoopJoinResultSet.java:116)\r\n\r\n\tat org.apache.derby.impl.sql.execute.ProjectRestrictResultSet.getNextRowCore(ProjectRestrictResultSet.java:255)\r\n\r\n\tat org.apache.derby.impl.sql.execute.NormalizeResultSet.getNextRowCore(NormalizeResultSet.java:186)\r\n\r\n\tat org.apache.derby.impl.sql.execute.DMLWriteResultSet.getNextRowCore(DMLWriteResultSet.java:127)\r\n\r\n\tat org.apache.derby.impl.sql.execute.InsertResultSet.open(InsertResultSet.java:496)\r\n\r\n\tat org.apache.derby.impl.sql.GenericPreparedStatement.execute(GenericPreparedStatement.java:370)\r\n\r\n\tat org.apache.derby.impl.sql.execute.GenericTriggerExecutor.executeSPS(GenericTriggerExecutor.java:173)\r\n\r\n\tat org.apache.derby.impl.sql.execute.StatementTriggerExecutor.fireTrigger(StatementTriggerExecutor.java:80)\r\n\r\n\tat org.apache.derby.impl.sql.execute.TriggerEventActivator.notifyEvent(TriggerEventActivator.java:278)\r\n\r\n\tat org.apache.derby.impl.sql.execute.DeleteResultSet.fireAfterTriggers(DeleteResultSet.java:479)\r\n\r\n\tat org.apache.derby.impl.sql.execute.DeleteResultSet.open(DeleteResultSet.java:167)\r\n\r\n\tat org.apache.derby.impl.sql.GenericPreparedStatement.execute(GenericPreparedStatement.java:370)\r\n\r\n\tat org.apache.derby.impl.jdbc.EmbedStatement.executeStatement(EmbedStatement.java:1203)\r\n\r\n\tat org.apache.derby.impl.jdbc.EmbedStatement.execute(EmbedStatement.java:596)\r\n\r\n\tat org.apache.derby.impl.jdbc.EmbedStatement.executeUpdate(EmbedStatement.java:176)\r\n\r\n\tat org.apache.derby.iapi.jdbc.BrokeredStatement.executeUpdate(BrokeredStatement.java:113)\r\n\r\n\tat ReproRSClosed.main(ReproRSClosed.java:20)\r\n\r\nCaused by: java.sql.SQLException: ResultSet not open. Operation 'next' not permitted. Verify that autocommit is OFF.\r\n\r\n\tat org.apache.derby.impl.jdbc.SQLExceptionFactory40.getSQLException(SQLExceptionFactory40.java:95)\r\n\r\n\tat org.apache.derby.impl.jdbc.Util.newEmbedSQLException(Util.java:88)\r\n\r\n\tat org.apache.derby.impl.jdbc.Util.newEmbedSQLException(Util.java:94)\r\n\r\n\tat org.apache.derby.impl.jdbc.Util.generateCsSQLException(Util.java:173)\r\n\r\n\tat org.apache.derby.impl.jdbc.EmbedConnection.newSQLException(EmbedConnection.java:2244)\r\n\r\n\tat org.apache.derby.impl.jdbc.ConnectionChild.newSQLException(ConnectionChild.java:151)\r\n\r\n\tat org.apache.derby.impl.jdbc.EmbedResultSet.checkIfClosed(EmbedResultSet.java:4280)\r\n\r\n\tat org.apache.derby.impl.jdbc.EmbedResultSet.checkExecIfClosed(EmbedResultSet.java:4292)\r\n\r\n\tat org.apache.derby.impl.jdbc.EmbedResultSet.movePosition(EmbedResultSet.java:404)\r\n\r\n\tat org.apache.derby.impl.jdbc.EmbedResultSet.next(EmbedResultSet.java:388)\r\n\r\n\tat org.apache.derby.impl.sql.execute.VTIResultSet.getNextRowCore(VTIResultSet.java:308)\r\n\r\n\t... 18 more\r\n\r\nCaused by: java.sql.SQLException: ResultSet not open. Operation 'next' not permitted. Verify that autocommit is OFF.\r\n\r\n\tat org.apache.derby.impl.jdbc.SQLExceptionFactory.getSQLException(SQLExceptionFactory.java:45)\r\n\r\n\tat org.apache.derby.impl.jdbc.SQLExceptionFactory40.wrapArgsForTransportAcrossDRDA(SQLExceptionFactory40.java:135)\r\n\r\n\tat org.apache.derby.impl.jdbc.SQLExceptionFactory40.getSQLException(SQLExceptionFactory40.java:70)\r\n\r\n\t... 28 more\r\n\r\n============= begin nested exception, level (1) ===========\r\n\r\njava.sql.SQLException: ResultSet not open. Operation 'next' not permitted. Verify that autocommit is OFF.\r\n\r\n\tat org.apache.derby.impl.jdbc.SQLExceptionFactory40.getSQLException(SQLExceptionFactory40.java:95)\r\n\r\n\tat org.apache.derby.impl.jdbc.Util.newEmbedSQLException(Util.java:88)\r\n\r\n\tat org.apache.derby.impl.jdbc.Util.newEmbedSQLException(Util.java:94)\r\n\r\n\tat org.apache.derby.impl.jdbc.Util.generateCsSQLException(Util.java:173)\r\n\r\n\tat org.apache.derby.impl.jdbc.EmbedConnection.newSQLException(EmbedConnection.java:2244)\r\n\r\n\tat org.apache.derby.impl.jdbc.ConnectionChild.newSQLException(ConnectionChild.java:151)\r\n\r\n\tat org.apache.derby.impl.jdbc.EmbedResultSet.checkIfClosed(EmbedResultSet.java:4280)\r\n\r\n\tat org.apache.derby.impl.jdbc.EmbedResultSet.checkExecIfClosed(EmbedResultSet.java:4292)\r\n\r\n\tat org.apache.derby.impl.jdbc.EmbedResultSet.movePosition(EmbedResultSet.java:404)\r\n\r\n\tat org.apache.derby.impl.jdbc.EmbedResultSet.next(EmbedResultSet.java:388)\r\n\r\n\tat org.apache.derby.impl.sql.execute.VTIResultSet.getNextRowCore(VTIResultSet.java:308)\r\n\r\n\tat org.apache.derby.impl.sql.execute.ProjectRestrictResultSet.getNextRowCore(ProjectRestrictResultSet.java:255)\r\n\r\n\tat org.apache.derby.impl.sql.execute.NestedLoopJoinResultSet.getNextRowCore(NestedLoopJoinResultSet.java:116)\r\n\r\n\tat org.apache.derby.impl.sql.execute.ProjectRestrictResultSet.getNextRowCore(ProjectRestrictResultSet.java:255)\r\n\r\n\tat org.apache.derby.impl.sql.execute.NormalizeResultSet.getNextRowCore(NormalizeResultSet.java:186)\r\n\r\n\tat org.apache.derby.impl.sql.execute.DMLWriteResultSet.getNextRowCore(DMLWriteResultSet.java:127)\r\n\r\n\tat org.apache.derby.impl.sql.execute.InsertResultSet.open(InsertResultSet.java:496)\r\n\r\n\tat org.apache.derby.impl.sql.GenericPreparedStatement.execute(GenericPreparedStatement.java:370)\r\n\r\n\tat org.apache.derby.impl.sql.execute.GenericTriggerExecutor.executeSPS(GenericTriggerExecutor.java:173)\r\n\r\n\tat org.apache.derby.impl.sql.execute.StatementTriggerExecutor.fireTrigger(StatementTriggerExecutor.java:80)\r\n\r\n\tat org.apache.derby.impl.sql.execute.TriggerEventActivator.notifyEvent(TriggerEventActivator.java:278)\r\n\r\n\tat org.apache.derby.impl.sql.execute.DeleteResultSet.fireAfterTriggers(DeleteResultSet.java:479)\r\n\r\n\tat org.apache.derby.impl.sql.execute.DeleteResultSet.open(DeleteResultSet.java:167)\r\n\r\n\tat org.apache.derby.impl.sql.GenericPreparedStatement.execute(GenericPreparedStatement.java:370)\r\n\r\n\tat org.apache.derby.impl.jdbc.EmbedStatement.executeStatement(EmbedStatement.java:1203)\r\n\r\n\tat org.apache.derby.impl.jdbc.EmbedStatement.execute(EmbedStatement.java:596)\r\n\r\n\tat org.apache.derby.impl.jdbc.EmbedStatement.executeUpdate(EmbedStatement.java:176)\r\n\r\n\tat org.apache.derby.iapi.jdbc.BrokeredStatement.executeUpdate(BrokeredStatement.java:113)\r\n\r\n\tat ReproRSClosed.main(ReproRSClosed.java:20)\r\n\r\nCaused by: java.sql.SQLException: ResultSet not open. Operation 'next' not permitted. Verify that autocommit is OFF.\r\n\r\n\tat org.apache.derby.impl.jdbc.SQLExceptionFactory.getSQLException(SQLExceptionFactory.java:45)\r\n\r\n\tat org.apache.derby.impl.jdbc.SQLExceptionFactory40.wrapArgsForTransportAcrossDRDA(SQLExceptionFactory40.java:135)\r\n\r\n\tat org.apache.derby.impl.jdbc.SQLExceptionFactory40.getSQLException(SQLExceptionFactory40.java:70)\r\n\r\n\t... 28 more\r\n\r\n============= end nested exception, level (1) ===========\r\n\r\n============= begin nested exception, level (2) ===========\r\n\r\njava.sql.SQLException: ResultSet not open. Operation 'next' not permitted. Verify that autocommit is OFF.\r\n\r\n\tat org.apache.derby.impl.jdbc.SQLExceptionFactory.getSQLException(SQLExceptionFactory.java:45)\r\n\r\n\tat org.apache.derby.impl.jdbc.SQLExceptionFactory40.wrapArgsForTransportAcrossDRDA(SQLExceptionFactory40.java:135)\r\n\r\n\tat org.apache.derby.impl.jdbc.SQLExceptionFactory40.getSQLException(SQLExceptionFactory40.java:70)\r\n\r\n\tat org.apache.derby.impl.jdbc.Util.newEmbedSQLException(Util.java:88)\r\n\r\n\tat org.apache.derby.impl.jdbc.Util.newEmbedSQLException(Util.java:94)\r\n\r\n\tat org.apache.derby.impl.jdbc.Util.generateCsSQLException(Util.java:173)\r\n\r\n\tat org.apache.derby.impl.jdbc.EmbedConnection.newSQLException(EmbedConnection.java:2244)\r\n\r\n\tat org.apache.derby.impl.jdbc.ConnectionChild.newSQLException(ConnectionChild.java:151)\r\n\r\n\tat org.apache.derby.impl.jdbc.EmbedResultSet.checkIfClosed(EmbedResultSet.java:4280)\r\n\r\n\tat org.apache.derby.impl.jdbc.EmbedResultSet.checkExecIfClosed(EmbedResultSet.java:4292)\r\n\r\n\tat org.apache.derby.impl.jdbc.EmbedResultSet.movePosition(EmbedResultSet.java:404)\r\n\r\n\tat org.apache.derby.impl.jdbc.EmbedResultSet.next(EmbedResultSet.java:388)\r\n\r\n\tat org.apache.derby.impl.sql.execute.VTIResultSet.getNextRowCore(VTIResultSet.java:308)\r\n\r\n\tat org.apache.derby.impl.sql.execute.ProjectRestrictResultSet.getNextRowCore(ProjectRestrictResultSet.java:255)\r\n\r\n\tat org.apache.derby.impl.sql.execute.NestedLoopJoinResultSet.getNextRowCore(NestedLoopJoinResultSet.java:116)\r\n\r\n\tat org.apache.derby.impl.sql.execute.ProjectRestrictResultSet.getNextRowCore(ProjectRestrictResultSet.java:255)\r\n\r\n\tat org.apache.derby.impl.sql.execute.NormalizeResultSet.getNextRowCore(NormalizeResultSet.java:186)\r\n\r\n\tat org.apache.derby.impl.sql.execute.DMLWriteResultSet.getNextRowCore(DMLWriteResultSet.java:127)\r\n\r\n\tat org.apache.derby.impl.sql.execute.InsertResultSet.open(InsertResultSet.java:496)\r\n\r\n\tat org.apache.derby.impl.sql.GenericPreparedStatement.execute(GenericPreparedStatement.java:370)\r\n\r\n\tat org.apache.derby.impl.sql.execute.GenericTriggerExecutor.executeSPS(GenericTriggerExecutor.java:173)\r\n\r\n\tat org.apache.derby.impl.sql.execute.StatementTriggerExecutor.fireTrigger(StatementTriggerExecutor.java:80)\r\n\r\n\tat org.apache.derby.impl.sql.execute.TriggerEventActivator.notifyEvent(TriggerEventActivator.java:278)\r\n\r\n\tat org.apache.derby.impl.sql.execute.DeleteResultSet.fireAfterTriggers(DeleteResultSet.java:479)\r\n\r\n\tat org.apache.derby.impl.sql.execute.DeleteResultSet.open(DeleteResultSet.java:167)\r\n\r\n\tat org.apache.derby.impl.sql.GenericPreparedStatement.execute(GenericPreparedStatement.java:370)\r\n\r\n\tat org.apache.derby.impl.jdbc.EmbedStatement.executeStatement(EmbedStatement.java:1203)\r\n\r\n\tat org.apache.derby.impl.jdbc.EmbedStatement.execute(EmbedStatement.java:596)\r\n\r\n\tat org.apache.derby.impl.jdbc.EmbedStatement.executeUpdate(EmbedStatement.java:176)\r\n\r\n\tat org.apache.derby.iapi.jdbc.BrokeredStatement.executeUpdate(BrokeredStatement.java:113)\r\n\r\n\tat ReproRSClosed.main(ReproRSClosed.java:20)\r\n\r\n============= end nested exception, level (2) ===========\r\n\r\nCleanup action completed\r\n\r\n","customfield_10010":null,"timetracking":{},"customfield_12312026":null,"customfield_12310200":[{"self":"https://issues.apache.org/jira/rest/api/2/customFieldOption/10420","value":"Regression","id":"10420"}],"customfield_12312023":null,"customfield_12312024":null,"customfield_12312340":null,"aggregatetimeestimate":null,"customfield_12312022":null,"customfield_12312341":null,"customfield_12312220":null,"customfield_12310921":null,"customfield_12310920":"38024","summary":"Trigger  fails with ERROR 38000: The exception 'java.sql.SQLException: ResultSet not open  during VTIResultSet.getNextRowCore()","creator":{"self":"https://issues.apache.org/jira/rest/api/2/user?username=kmarsden","name":"kmarsden","emailAddress":"kmarsdenderby at sbcglobal dot net","avatarUrls":{"48x48":"https://issues.apache.org/jira/secure/useravatar?avatarId=10452","24x24":"https://issues.apache.org/jira/secure/useravatar?size=small&avatarId=10452","16x16":"https://issues.apache.org/jira/secure/useravatar?size=xsmall&avatarId=10452","32x32":"https://issues.apache.org/jira/secure/useravatar?size=medium&avatarId=10452"},"displayName":"Kathey Marsden","active":true},"subtasks":[],"customfield_12310090":[{"self":"https://issues.apache.org/jira/rest/api/2/customFieldOption/10102","value":"Patch Available","id":"10102"}],"reporter":{"self":"https://issues.apache.org/jira/rest/api/2/user?username=kmarsden","name":"kmarsden","emailAddress":"kmarsdenderby at sbcglobal dot net","avatarUrls":{"48x48":"https://issues.apache.org/jira/secure/useravatar?avatarId=10452","24x24":"https://issues.apache.org/jira/secure/useravatar?size=small&avatarId=10452","16x16":"https://issues.apache.org/jira/secure/useravatar?size=xsmall&avatarId=10452","32x32":"https://issues.apache.org/jira/secure/useravatar?size=medium&avatarId=10452"},"displayName":"Kathey Marsden","active":true},"customfield_12310291":null,"customfield_12310290":null,"aggregateprogress":{"progress":0,"total":0},"environment":null,"customfield_12311020":null,"customfield_12310050":null,"duedate":null,"customfield_12310250":null,"progress":{"progress":0,"total":0},"comment":{"startAt":0,"maxResults":17,"total":17,"comments":[{"self":"https://issues.apache.org/jira/rest/api/2/issue/12416839/comment/12681734","id":"12681734","author":{"self":"https://issues.apache.org/jira/rest/api/2/user?username=kmarsden","name":"kmarsden","emailAddress":"kmarsdenderby at sbcglobal dot net","avatarUrls":{"48x48":"https://issues.apache.org/jira/secure/useravatar?avatarId=10452","24x24":"https://issues.apache.org/jira/secure/useravatar?size=small&avatarId=10452","16x16":"https://issues.apache.org/jira/secure/useravatar?size=xsmall&avatarId=10452","32x32":"https://issues.apache.org/jira/secure/useravatar?size=medium&avatarId=10452"},"displayName":"Kathey Marsden","active":true},"body":"It does reproduce with a local transaction, autocommit off,  and connection holdability set to ResultSet.CLOSE_CURSORS_AT_COMMIT as well, so apparently there is an unexpected commit occurring.\r\n\r\n","updateAuthor":{"self":"https://issues.apache.org/jira/rest/api/2/user?username=kmarsden","name":"kmarsden","emailAddress":"kmarsdenderby at sbcglobal dot net","avatarUrls":{"48x48":"https://issues.apache.org/jira/secure/useravatar?avatarId=10452","24x24":"https://issues.apache.org/jira/secure/useravatar?size=small&avatarId=10452","16x16":"https://issues.apache.org/jira/secure/useravatar?size=xsmall&avatarId=10452","32x32":"https://issues.apache.org/jira/secure/useravatar?size=medium&avatarId=10452"},"displayName":"Kathey Marsden","active":true},"created":"2009-03-13T14:45:24.584+0000","updated":"2009-03-13T14:45:24.584+0000"},{"self":"https://issues.apache.org/jira/rest/api/2/issue/12416839/comment/12681958","id":"12681958","author":{"self":"https://issues.apache.org/jira/rest/api/2/user?username=kmarsden","name":"kmarsden","emailAddress":"kmarsdenderby at sbcglobal dot net","avatarUrls":{"48x48":"https://issues.apache.org/jira/secure/useravatar?avatarId=10452","24x24":"https://issues.apache.org/jira/secure/useravatar?size=small&avatarId=10452","16x16":"https://issues.apache.org/jira/secure/useravatar?size=xsmall&avatarId=10452","32x32":"https://issues.apache.org/jira/secure/useravatar?size=medium&avatarId=10452"},"displayName":"Kathey Marsden","active":true},"body":"Most of what I have found on this issue today is quite mysterious to me, but I figure I will summarize it here for weekend contemplation and attack it again on Monday.\r\n\r\nHere is the little program I use to reproduce the issue. Unfortunately table and trigger information I can't post here, except to say there is a after delete statement trigger that inserts some rows into a table.\r\n\r\nimport org.apache.derby.jdbc.EmbeddedDataSource;\r\nimport java.sql.*;\r\n\r\n\r\npublic class ReproRSClosedLocal {\r\n\r\n    public static void main(String[] args) throws Exception {\r\n        EmbeddedDataSource ds = new EmbeddedDataSource();\r\n        ds.setDatabaseName(\"mydb\");\r\n        Connection conn = ds.getConnection();\r\n        conn.setAutoCommit(false);\r\n        conn.setHoldability(ResultSet.CLOSE_CURSORS_AT_COMMIT);\r\n        Statement s = conn.createStatement();\r\n        s.executeUpdate(\"DELETE FROM XXX WHERE WSID=9\");\r\n        conn.rollback();\r\n        conn.close();\r\n\r\n\r\n\r\n    }\r\n\r\n}\r\n\r\nNotice the program rolls back so there should be no change from one run to the next in terms of what gets deleted and what trigger fires.\r\n\r\nI am not sure yet, what version the user database was upgraded from, just that with the database as I got it from the user, the trigger works fine up until 660483 where the version was bumped and we start getting the error.  What I have noticed is.\r\n\r\n- With the failing and passing runs we get the same number of commits, so there doesn't seem to be an extra commit.\r\n- If I run the program at 660482 (before the version change) and *then* move up to 660483 the trigger works fine.  I have to unzip the db to get the error again.\r\n- If I drop and recreate the trigger, and then run the program it runs fine.\r\n- If I connect with 10.4  with soft upgrade  the program works fine.\r\n\r\n\r\n\r\n\r\n\r\n","updateAuthor":{"self":"https://issues.apache.org/jira/rest/api/2/user?username=kmarsden","name":"kmarsden","emailAddress":"kmarsdenderby at sbcglobal dot net","avatarUrls":{"48x48":"https://issues.apache.org/jira/secure/useravatar?avatarId=10452","24x24":"https://issues.apache.org/jira/secure/useravatar?size=small&avatarId=10452","16x16":"https://issues.apache.org/jira/secure/useravatar?size=xsmall&avatarId=10452","32x32":"https://issues.apache.org/jira/secure/useravatar?size=medium&avatarId=10452"},"displayName":"Kathey Marsden","active":true},"created":"2009-03-14T00:36:36.533+0000","updated":"2009-03-14T00:36:36.533+0000"},{"self":"https://issues.apache.org/jira/rest/api/2/issue/12416839/comment/12682793","id":"12682793","author":{"self":"https://issues.apache.org/jira/rest/api/2/user?username=kmarsden","name":"kmarsden","emailAddress":"kmarsdenderby at sbcglobal dot net","avatarUrls":{"48x48":"https://issues.apache.org/jira/secure/useravatar?avatarId=10452","24x24":"https://issues.apache.org/jira/secure/useravatar?size=small&avatarId=10452","16x16":"https://issues.apache.org/jira/secure/useravatar?size=xsmall&avatarId=10452","32x32":"https://issues.apache.org/jira/secure/useravatar?size=medium&avatarId=10452"},"displayName":"Kathey Marsden","active":true},"body":"In the failing case we go through VTIResultSet.reopenCore during execution of the trigger and close the ResultSet associated with the TriggerOldTransitionRows VTI.  Here is the trace when we go through this code.\r\n\r\njava.lang.Exception: TemporaryRowHolderResultSet.close()\r\n\tat org.apache.derby.impl.sql.execute.TemporaryRowHolderResultSet.close(TemporaryRowHolderResultSet.java:574)\r\n\tat org.apache.derby.impl.jdbc.EmbedResultSet.close(EmbedResultSet.java:596)\r\n\tat org.apache.derby.impl.sql.execute.VTIResultSet.reopenCore(VTIResultSet.java:258)\r\n\tat org.apache.derby.impl.sql.execute.ProjectRestrictResultSet.reopenCore(ProjectRestrictResultSet.java:212)\r\n\tat org.apache.derby.impl.sql.execute.JoinResultSet.openRight(JoinResultSet.java:266)\r\n\tat org.apache.derby.impl.sql.execute.NestedLoopJoinResultSet.getNextRowCore(NestedLoopJoinResultSet.java:147)\r\n\tat org.apache.derby.impl.sql.execute.ProjectRestrictResultSet.getNextRowCore(ProjectRestrictResultSet.java:255)\r\n\tat org.apache.derby.impl.sql.execute.NormalizeResultSet.getNextRowCore(NormalizeResultSet.java:186)\r\n\tat org.apache.derby.impl.sql.execute.DMLWriteResultSet.getNextRowCore(DMLWriteResultSet.java:127)\r\n\tat org.apache.derby.impl.sql.execute.InsertResultSet.open(InsertResultSet.java:496)\r\n\tat org.apache.derby.impl.sql.GenericPreparedStatement.execute(GenericPreparedStatement.java:370)\r\n\tat org.apache.derby.impl.sql.execute.GenericTriggerExecutor.executeSPS(GenericTriggerExecutor.java:173)\r\n\tat org.apache.derby.impl.sql.execute.StatementTriggerExecutor.fireTrigger(StatementTriggerExecutor.java:81)\r\n\tat org.apache.derby.impl.sql.execute.TriggerEventActivator.notifyEvent(TriggerEventActivator.java:278)\r\n\tat org.apache.derby.impl.sql.execute.DeleteResultSet.fireAfterTriggers(DeleteResultSet.java:479)\r\n\tat org.apache.derby.impl.sql.execute.DeleteResultSet.open(DeleteResultSet.java:167)\r\n\tat org.apache.derby.impl.sql.GenericPreparedStatement.execute(GenericPreparedStatement.java:370)\r\n\tat org.apache.derby.impl.jdbc.EmbedStatement.executeStatement(EmbedStatement.java:1203)\r\n\tat org.apache.derby.impl.jdbc.EmbedStatement.execute(EmbedStatement.java:596)\r\n\tat org.apache.derby.impl.jdbc.EmbedStatement.executeUpdate(EmbedStatement.java:176)\r\n\tat ReproRSClosedLocal.main(ReproRSClosedLocal.java:16)\r\n\t\t\t\r\n\r\nIn VTIResultSet reopenCore we have:\r\n\r\n\t/**\r\n\t * If the VTI is a version2 vti that does not\r\n\t * need to be instantiated multiple times then\r\n\t * we simply close the current ResultSet and \r\n\t * create a new one via a call to \r\n\t * PreparedStatement.executeQuery().\r\n\t *\r\n\t * @see NoPutResultSet#openCore\r\n\t * @exception StandardException thrown if cursor finished.\r\n\t */\r\n\tpublic void reopenCore() throws StandardException\r\n\t{\r\n\t\tif (reuseablePs)\r\n\t\t{\r\n\t\t\t/* close the user ResultSet.\r\n\t\t\t */\r\n\t\t\tif (userVTI != null)\r\n\t\t\t{\r\n\t\t\t\ttry\r\n\t\t\t\t{\r\n--> We close the RS here\t\tuserVTI.close();\r\n\t\t\t\t\tuserVTI = userPS.executeQuery();\r\n\r\n\t\t\t\t\t/* Save off the target VTI */\r\n\t\t\t\t\tif (isTarget)\r\n\t\t\t\t\t{\r\n\t\t\t\t\t\tactivation.setTargetVTI(userVTI);\r\n\t\t\t\t\t}\r\n\t\t\t\t} catch (SQLException se)\r\n\t\t\t\t{\r\n\t\t\t\t\tthrow StandardException.unexpectedUserException(se);\r\n\t\t\t\t}\r\n\t\t\t}\r\n\t\t}\r\n\t\telse\r\n\t\t{\r\n\t\t\tclose();\r\n\t\t\topenCore();\t\r\n\t\t}\r\n\t}\r\n\r\n\r\nThe TriggerOldTransitionRows VTI seems to have reusablePs set to true, so we close the ResultSet and call executeQuery() on the VTI prepared statement, but our TriggerOldTransitionRows.executeQuery()  method only returns the existing resultSet, even if it has been closed and this the issue.  It is not really a reusable prepared statement.  If I change executeQuery to rebuild the resultSet  like:\r\n\r\n    public ResultSet executeQuery() throws SQLException {              \r\n           TriggerExecutionContext tec = Factory.getTriggerExecutionContext();\r\n           resultSet = tec.getOldRowSet();               \r\n           return resultSet;\r\n            \r\n       }\r\n\r\n\r\ninstead of just returning the existing ResultSet, it works ok, but I am not sure that this is the right fix.\r\n\r\nIn the working case we don't seem to go through this reopenCore code.  I'm not entirely sure why, perhaps a different plan?\r\n\r\nAlso not clear to me is what CLOSE_CURSORS_AT_COMMIT has to do with this, because it doesn't seem to be a commit that is closing the result set.\r\n\r\nI will debug more and try to find answers to those questions but thought I would post my findings so far.\r\n","updateAuthor":{"self":"https://issues.apache.org/jira/rest/api/2/user?username=kmarsden","name":"kmarsden","emailAddress":"kmarsdenderby at sbcglobal dot net","avatarUrls":{"48x48":"https://issues.apache.org/jira/secure/useravatar?avatarId=10452","24x24":"https://issues.apache.org/jira/secure/useravatar?size=small&avatarId=10452","16x16":"https://issues.apache.org/jira/secure/useravatar?size=xsmall&avatarId=10452","32x32":"https://issues.apache.org/jira/secure/useravatar?size=medium&avatarId=10452"},"displayName":"Kathey Marsden","active":true},"created":"2009-03-17T20:50:53.405+0000","updated":"2009-03-17T20:50:53.405+0000"},{"self":"https://issues.apache.org/jira/rest/api/2/issue/12416839/comment/12682863","id":"12682863","author":{"self":"https://issues.apache.org/jira/rest/api/2/user?username=kmarsden","name":"kmarsden","emailAddress":"kmarsdenderby at sbcglobal dot net","avatarUrls":{"48x48":"https://issues.apache.org/jira/secure/useravatar?avatarId=10452","24x24":"https://issues.apache.org/jira/secure/useravatar?size=small&avatarId=10452","16x16":"https://issues.apache.org/jira/secure/useravatar?size=xsmall&avatarId=10452","32x32":"https://issues.apache.org/jira/secure/useravatar?size=medium&avatarId=10452"},"displayName":"Kathey Marsden","active":true},"body":"So yes, the failing case was using a different plan which reopened the VTI multiple times, which just happened to change on upgrade.  I was able to construct a reproduction (Derby4095Local.java) by using optimizer directives in the trigger definition.\r\n\r\nI think the CLOSE_CURSORS_AT_COMMIT was a red herring.  I was able to reproduce with the original user case without setting CLOSE_CURSORS_AT_COMMIT, so that was not really part of it.\r\n\r\n\r\nAnyway, here is the trunk stack trace.\r\n>java Derby4095Local\r\nException in thread \"main\" java.sql.SQLException: The exception 'java.sql.SQLException: ResultSet not open. Operation 'n\r\next' not permitted. Verify that autocommit is OFF.' was thrown while evaluating an expression.\r\n        at org.apache.derby.impl.jdbc.SQLExceptionFactory40.getSQLException(SQLExceptionFactory40.java:95)\r\n        at org.apache.derby.impl.jdbc.Util.newEmbedSQLException(Util.java:87)\r\n        at org.apache.derby.impl.jdbc.Util.seeNextException(Util.java:223)\r\n        at org.apache.derby.impl.jdbc.TransactionResourceImpl.wrapInSQLException(TransactionResourceImpl.java:398)\r\n        at org.apache.derby.impl.jdbc.TransactionResourceImpl.handleException(TransactionResourceImpl.java:346)\r\n        at org.apache.derby.impl.jdbc.EmbedConnection.handleException(EmbedConnection.java:2201)\r\n        at org.apache.derby.impl.jdbc.ConnectionChild.handleException(ConnectionChild.java:81)\r\n        at org.apache.derby.impl.jdbc.EmbedStatement.executeStatement(EmbedStatement.java:1323)\r\n        at org.apache.derby.impl.jdbc.EmbedStatement.execute(EmbedStatement.java:625)\r\n        at org.apache.derby.impl.jdbc.EmbedStatement.executeUpdate(EmbedStatement.java:175)\r\n        at ReproDerby4095Local.main(ReproDerby4095Local.java:14)\r\nCaused by: java.sql.SQLException: The exception 'java.sql.SQLException: ResultSet not open. Operation 'next' not permitt\r\ned. Verify that autocommit is OFF.' was thrown while evaluating an expression.\r\n        at org.apache.derby.impl.jdbc.SQLExceptionFactory.getSQLException(SQLExceptionFactory.java:45)\r\n        at org.apache.derby.impl.jdbc.SQLExceptionFactory40.wrapArgsForTransportAcrossDRDA(SQLExceptionFactory40.java:11\r\n9)\r\n        at org.apache.derby.impl.jdbc.SQLExceptionFactory40.getSQLException(SQLExceptionFactory40.java:70)\r\n        ... 10 more\r\nCaused by: java.sql.SQLException: ResultSet not open. Operation 'next' not permitted. Verify that autocommit is OFF.\r\n        at org.apache.derby.impl.jdbc.SQLExceptionFactory.getSQLException(SQLExceptionFactory.java:45)\r\n        at org.apache.derby.impl.jdbc.SQLExceptionFactory40.wrapArgsForTransportAcrossDRDA(SQLExceptionFactory40.java:11\r\n9)\r\n        at org.apache.derby.impl.jdbc.SQLExceptionFactory40.getSQLException(SQLExceptionFactory40.java:70)\r\n        at org.apache.derby.impl.jdbc.Util.newEmbedSQLException(Util.java:87)\r\n        at org.apache.derby.impl.jdbc.Util.newEmbedSQLException(Util.java:93)\r\n        at org.apache.derby.impl.jdbc.Util.generateCsSQLException(Util.java:172)\r\n        at org.apache.derby.impl.jdbc.EmbedConnection.newSQLException(EmbedConnection.java:2951)\r\n        at org.apache.derby.impl.jdbc.ConnectionChild.newSQLException(ConnectionChild.java:151)\r\n        at org.apache.derby.impl.jdbc.EmbedResultSet.checkIfClosed(EmbedResultSet.java:4275)\r\n        at org.apache.derby.impl.jdbc.EmbedResultSet.checkExecIfClosed(EmbedResultSet.java:4287)\r\n        at org.apache.derby.impl.jdbc.EmbedResultSet.movePosition(EmbedResultSet.java:387)\r\n        at org.apache.derby.impl.jdbc.EmbedResultSet.next(EmbedResultSet.java:371)\r\n        at org.apache.derby.impl.sql.execute.VTIResultSet.getNextRowCore(VTIResultSet.java:338)\r\n        at org.apache.derby.impl.sql.execute.ProjectRestrictResultSet.getNextRowCore(ProjectRestrictResultSet.java:255)\r\n        at org.apache.derby.impl.sql.execute.NestedLoopJoinResultSet.getNextRowCore(NestedLoopJoinResultSet.java:116)\r\n        at org.apache.derby.impl.sql.execute.ProjectRestrictResultSet.getNextRowCore(ProjectRestrictResultSet.java:255)\r\n        at org.apache.derby.impl.sql.execute.DMLWriteResultSet.getNextRowCore(DMLWriteResultSet.java:127)\r\n        at org.apache.derby.impl.sql.execute.InsertResultSet.normalInsertCore(InsertResultSet.java:1058)\r\n        at org.apache.derby.impl.sql.execute.InsertResultSet.open(InsertResultSet.java:495)\r\n        at org.apache.derby.impl.sql.GenericPreparedStatement.executeStmt(GenericPreparedStatement.java:416)\r\n        at org.apache.derby.impl.sql.GenericPreparedStatement.executeSubStatement(GenericPreparedStatement.java:286)\r\n        at org.apache.derby.impl.sql.execute.GenericTriggerExecutor.executeSPS(GenericTriggerExecutor.java:159)\r\n        at org.apache.derby.impl.sql.execute.StatementTriggerExecutor.fireTrigger(StatementTriggerExecutor.java:80)\r\n        at org.apache.derby.impl.sql.execute.TriggerEventActivator.notifyEvent(TriggerEventActivator.java:269)\r\n        at org.apache.derby.impl.sql.execute.DeleteResultSet.fireAfterTriggers(DeleteResultSet.java:465)\r\n        at org.apache.derby.impl.sql.execute.DeleteResultSet.open(DeleteResultSet.java:158)\r\n        at org.apache.derby.impl.sql.GenericPreparedStatement.executeStmt(GenericPreparedStatement.java:416)\r\n        at org.apache.derby.impl.sql.GenericPreparedStatement.execute(GenericPreparedStatement.java:297)\r\n        at org.apache.derby.impl.jdbc.EmbedStatement.executeStatement(EmbedStatement.java:1235)\r\n\r\n\r\nI think I will pursue the fix of having TriggerOldTransitionRows reconstruct the ResultSet on executeQuery.  Please let me know if that does not sound acceptable.\r\n\r\n\r\n","updateAuthor":{"self":"https://issues.apache.org/jira/rest/api/2/user?username=kmarsden","name":"kmarsden","emailAddress":"kmarsdenderby at sbcglobal dot net","avatarUrls":{"48x48":"https://issues.apache.org/jira/secure/useravatar?avatarId=10452","24x24":"https://issues.apache.org/jira/secure/useravatar?size=small&avatarId=10452","16x16":"https://issues.apache.org/jira/secure/useravatar?size=xsmall&avatarId=10452","32x32":"https://issues.apache.org/jira/secure/useravatar?size=medium&avatarId=10452"},"displayName":"Kathey Marsden","active":true},"created":"2009-03-18T00:13:04.574+0000","updated":"2009-03-18T00:13:04.574+0000"},{"self":"https://issues.apache.org/jira/rest/api/2/issue/12416839/comment/12683108","id":"12683108","author":{"self":"https://issues.apache.org/jira/rest/api/2/user?username=kmarsden","name":"kmarsden","emailAddress":"kmarsdenderby at sbcglobal dot net","avatarUrls":{"48x48":"https://issues.apache.org/jira/secure/useravatar?avatarId=10452","24x24":"https://issues.apache.org/jira/secure/useravatar?size=small&avatarId=10452","16x16":"https://issues.apache.org/jira/secure/useravatar?size=xsmall&avatarId=10452","32x32":"https://issues.apache.org/jira/secure/useravatar?size=medium&avatarId=10452"},"displayName":"Kathey Marsden","active":true},"body":"Attached is a patch for this issue.\r\nIt changes TriggerOldTransitionRows.java and TriggerNewTransitionRows.java to intialize the ResultSet on executeQuery to fix the ResultSet not open problem when a nested loop join is performed.\r\nIt adds two tests to TriggerTest testDerby4095OldTriggerRows()  and testDerby4095NewTriggerRows() \r\n\r\nI am running tests now.\r\n","updateAuthor":{"self":"https://issues.apache.org/jira/rest/api/2/user?username=kmarsden","name":"kmarsden","emailAddress":"kmarsdenderby at sbcglobal dot net","avatarUrls":{"48x48":"https://issues.apache.org/jira/secure/useravatar?avatarId=10452","24x24":"https://issues.apache.org/jira/secure/useravatar?size=small&avatarId=10452","16x16":"https://issues.apache.org/jira/secure/useravatar?size=xsmall&avatarId=10452","32x32":"https://issues.apache.org/jira/secure/useravatar?size=medium&avatarId=10452"},"displayName":"Kathey Marsden","active":true},"created":"2009-03-18T17:49:56.173+0000","updated":"2009-03-18T17:49:56.173+0000"},{"self":"https://issues.apache.org/jira/rest/api/2/issue/12416839/comment/12683198","id":"12683198","author":{"self":"https://issues.apache.org/jira/rest/api/2/user?username=kmarsden","name":"kmarsden","emailAddress":"kmarsdenderby at sbcglobal dot net","avatarUrls":{"48x48":"https://issues.apache.org/jira/secure/useravatar?avatarId=10452","24x24":"https://issues.apache.org/jira/secure/useravatar?size=small&avatarId=10452","16x16":"https://issues.apache.org/jira/secure/useravatar?size=xsmall&avatarId=10452","32x32":"https://issues.apache.org/jira/secure/useravatar?size=medium&avatarId=10452"},"displayName":"Kathey Marsden","active":true},"body":"Tests passed. Please review patch derby-4095_diff.txt.\r\n","updateAuthor":{"self":"https://issues.apache.org/jira/rest/api/2/user?username=kmarsden","name":"kmarsden","emailAddress":"kmarsdenderby at sbcglobal dot net","avatarUrls":{"48x48":"https://issues.apache.org/jira/secure/useravatar?avatarId=10452","24x24":"https://issues.apache.org/jira/secure/useravatar?size=small&avatarId=10452","16x16":"https://issues.apache.org/jira/secure/useravatar?size=xsmall&avatarId=10452","32x32":"https://issues.apache.org/jira/secure/useravatar?size=medium&avatarId=10452"},"displayName":"Kathey Marsden","active":true},"created":"2009-03-18T22:04:13.628+0000","updated":"2009-03-18T22:04:13.628+0000"},{"self":"https://issues.apache.org/jira/rest/api/2/issue/12416839/comment/12683449","id":"12683449","author":{"self":"https://issues.apache.org/jira/rest/api/2/user?username=knutanders","name":"knutanders","emailAddress":"knut dot hatlen at oracle dot com","avatarUrls":{"48x48":"https://issues.apache.org/jira/secure/useravatar?avatarId=10452","24x24":"https://issues.apache.org/jira/secure/useravatar?size=small&avatarId=10452","16x16":"https://issues.apache.org/jira/secure/useravatar?size=xsmall&avatarId=10452","32x32":"https://issues.apache.org/jira/secure/useravatar?size=medium&avatarId=10452"},"displayName":"Knut Anders Hatlen","active":true},"body":"With the patch, we always reinitialize the result set on executeQuery(), even if the existing one has not been closed. Is there a way to avoid it? And is it worth avoiding? (I don't know what the initialization does and if it's a heavy operation.)","updateAuthor":{"self":"https://issues.apache.org/jira/rest/api/2/user?username=knutanders","name":"knutanders","emailAddress":"knut dot hatlen at oracle dot com","avatarUrls":{"48x48":"https://issues.apache.org/jira/secure/useravatar?avatarId=10452","24x24":"https://issues.apache.org/jira/secure/useravatar?size=small&avatarId=10452","16x16":"https://issues.apache.org/jira/secure/useravatar?size=xsmall&avatarId=10452","32x32":"https://issues.apache.org/jira/secure/useravatar?size=medium&avatarId=10452"},"displayName":"Knut Anders Hatlen","active":true},"created":"2009-03-19T12:21:30.785+0000","updated":"2009-03-19T12:21:30.785+0000"},{"self":"https://issues.apache.org/jira/rest/api/2/issue/12416839/comment/12683498","id":"12683498","author":{"self":"https://issues.apache.org/jira/rest/api/2/user?username=kmarsden","name":"kmarsden","emailAddress":"kmarsdenderby at sbcglobal dot net","avatarUrls":{"48x48":"https://issues.apache.org/jira/secure/useravatar?avatarId=10452","24x24":"https://issues.apache.org/jira/secure/useravatar?size=small&avatarId=10452","16x16":"https://issues.apache.org/jira/secure/useravatar?size=xsmall&avatarId=10452","32x32":"https://issues.apache.org/jira/secure/useravatar?size=medium&avatarId=10452"},"displayName":"Kathey Marsden","active":true},"body":"Well ResultSet.isClosed() is not available in the 1.5 context which this seems to be, so we can''t tell if the ResultSet is closed or not, but I think even if the ResultSet wasn't closed but was positioned on a different row than the first it would need to be reinitialized, so probably safest to do it always.\r\n","updateAuthor":{"self":"https://issues.apache.org/jira/rest/api/2/user?username=kmarsden","name":"kmarsden","emailAddress":"kmarsdenderby at sbcglobal dot net","avatarUrls":{"48x48":"https://issues.apache.org/jira/secure/useravatar?avatarId=10452","24x24":"https://issues.apache.org/jira/secure/useravatar?size=small&avatarId=10452","16x16":"https://issues.apache.org/jira/secure/useravatar?size=xsmall&avatarId=10452","32x32":"https://issues.apache.org/jira/secure/useravatar?size=medium&avatarId=10452"},"displayName":"Kathey Marsden","active":true},"created":"2009-03-19T16:02:38.897+0000","updated":"2009-03-19T16:02:38.897+0000"},{"self":"https://issues.apache.org/jira/rest/api/2/issue/12416839/comment/12683543","id":"12683543","author":{"self":"https://issues.apache.org/jira/rest/api/2/user?username=mamtas","name":"mamtas","emailAddress":"msatoor at gmail dot com","avatarUrls":{"48x48":"https://issues.apache.org/jira/secure/useravatar?avatarId=10452","24x24":"https://issues.apache.org/jira/secure/useravatar?size=small&avatarId=10452","16x16":"https://issues.apache.org/jira/secure/useravatar?size=xsmall&avatarId=10452","32x32":"https://issues.apache.org/jira/secure/useravatar?size=medium&avatarId=10452"},"displayName":"Mamta A. Satoor","active":true},"body":"Hi Kathey, the patch looks good. I just had one question. \r\n\r\nSeems like, during the initialization of the new resultset, the following piece of code gets executed for TriggerNewTransitionRows(very similar code gets executed for TriggerOldTransitionRows). I was just wondering if we should close the old resultset that we are not going to use. \r\n\tpublic java.sql.ResultSet getNewRowSet() throws SQLException\r\n\t{\r\n\t\tensureProperContext();\r\n\r\n\t\tif (afterResultSet == null)\r\n\t\t{\r\n\t\t\treturn null;\r\n\t\t}\r\n\t\ttry\r\n\t\t{\r\n\t\t\t/* We should really shallow clone the result set, because it could be used\r\n\t\t\t * at multiple places independently in trigger action.  This is a bug found\r\n\t\t\t * during the fix of beetle 4373.\r\n\t\t\t */\r\n\t\t\tCursorResultSet ars = afterResultSet;\r\n\t\t\tif (ars instanceof TemporaryRowHolderResultSet)\r\n\t\t\t\tars = (CursorResultSet) ((TemporaryRowHolderResultSet) ars).clone();\r\n\t\t\telse if (ars instanceof TableScanResultSet)\r\n\t\t\t\tars = (CursorResultSet) ((TableScanResultSet) ars).clone();\r\n\t\t\tars.open();\r\n\t\t\tjava.sql.ResultSet rs = cc.getResultSet(ars);\r\n\t\t\tresultSetVector.addElement(rs);\r\n\t\t\treturn rs;\r\n\t\t} catch (StandardException se)\r\n\t\t{\r\n\t\t\tthrow PublicAPI.wrapStandardException(se);\r\n\t\t}\r\n\t}\r\n","updateAuthor":{"self":"https://issues.apache.org/jira/rest/api/2/user?username=mamtas","name":"mamtas","emailAddress":"msatoor at gmail dot com","avatarUrls":{"48x48":"https://issues.apache.org/jira/secure/useravatar?avatarId=10452","24x24":"https://issues.apache.org/jira/secure/useravatar?size=small&avatarId=10452","16x16":"https://issues.apache.org/jira/secure/useravatar?size=xsmall&avatarId=10452","32x32":"https://issues.apache.org/jira/secure/useravatar?size=medium&avatarId=10452"},"displayName":"Mamta A. Satoor","active":true},"created":"2009-03-19T17:57:53.112+0000","updated":"2009-03-19T17:57:53.112+0000"},{"self":"https://issues.apache.org/jira/rest/api/2/issue/12416839/comment/12683600","id":"12683600","author":{"self":"https://issues.apache.org/jira/rest/api/2/user?username=kmarsden","name":"kmarsden","emailAddress":"kmarsdenderby at sbcglobal dot net","avatarUrls":{"48x48":"https://issues.apache.org/jira/secure/useravatar?avatarId=10452","24x24":"https://issues.apache.org/jira/secure/useravatar?size=small&avatarId=10452","16x16":"https://issues.apache.org/jira/secure/useravatar?size=xsmall&avatarId=10452","32x32":"https://issues.apache.org/jira/secure/useravatar?size=medium&avatarId=10452"},"displayName":"Kathey Marsden","active":true},"body":"Thanks Mamta for looking at the patch.  I changed it to close the previous ResultSet and am rerunning tests now and will wait to see what Knut says about the performance concern.  I hope I can get this checked in tomorrow as there is a user on 10.3 that needs it.  Perhaps if more performance work is needed I could check that in as a separate patch? Since we are moving from not working to working the performance is a lot better than it was before #:)\r\n\r\n\r\n","updateAuthor":{"self":"https://issues.apache.org/jira/rest/api/2/user?username=kmarsden","name":"kmarsden","emailAddress":"kmarsdenderby at sbcglobal dot net","avatarUrls":{"48x48":"https://issues.apache.org/jira/secure/useravatar?avatarId=10452","24x24":"https://issues.apache.org/jira/secure/useravatar?size=small&avatarId=10452","16x16":"https://issues.apache.org/jira/secure/useravatar?size=xsmall&avatarId=10452","32x32":"https://issues.apache.org/jira/secure/useravatar?size=medium&avatarId=10452"},"displayName":"Kathey Marsden","active":true},"created":"2009-03-19T20:33:06.663+0000","updated":"2009-03-19T20:33:06.663+0000"},{"self":"https://issues.apache.org/jira/rest/api/2/issue/12416839/comment/12683612","id":"12683612","author":{"self":"https://issues.apache.org/jira/rest/api/2/user?username=kmarsden","name":"kmarsden","emailAddress":"kmarsdenderby at sbcglobal dot net","avatarUrls":{"48x48":"https://issues.apache.org/jira/secure/useravatar?avatarId=10452","24x24":"https://issues.apache.org/jira/secure/useravatar?size=small&avatarId=10452","16x16":"https://issues.apache.org/jira/secure/useravatar?size=xsmall&avatarId=10452","32x32":"https://issues.apache.org/jira/secure/useravatar?size=medium&avatarId=10452"},"displayName":"Kathey Marsden","active":true},"body":"Changing the title of the bug since this really could occur on any version if the plan with the problem is chosen. Leaving as regression, since from the user perspective, this was a regression triggered by upgrade.\r\n","updateAuthor":{"self":"https://issues.apache.org/jira/rest/api/2/user?username=kmarsden","name":"kmarsden","emailAddress":"kmarsdenderby at sbcglobal dot net","avatarUrls":{"48x48":"https://issues.apache.org/jira/secure/useravatar?avatarId=10452","24x24":"https://issues.apache.org/jira/secure/useravatar?size=small&avatarId=10452","16x16":"https://issues.apache.org/jira/secure/useravatar?size=xsmall&avatarId=10452","32x32":"https://issues.apache.org/jira/secure/useravatar?size=medium&avatarId=10452"},"displayName":"Kathey Marsden","active":true},"created":"2009-03-19T21:00:40.713+0000","updated":"2009-03-19T21:00:40.713+0000"},{"self":"https://issues.apache.org/jira/rest/api/2/issue/12416839/comment/12683632","id":"12683632","author":{"self":"https://issues.apache.org/jira/rest/api/2/user?username=mamtas","name":"mamtas","emailAddress":"msatoor at gmail dot com","avatarUrls":{"48x48":"https://issues.apache.org/jira/secure/useravatar?avatarId=10452","24x24":"https://issues.apache.org/jira/secure/useravatar?size=small&avatarId=10452","16x16":"https://issues.apache.org/jira/secure/useravatar?size=xsmall&avatarId=10452","32x32":"https://issues.apache.org/jira/secure/useravatar?size=medium&avatarId=10452"},"displayName":"Mamta A. Satoor","active":true},"body":"Kathey, I agree that performance can be addressed later on so feel free to checkin tomorrow the patch that you are testing.","updateAuthor":{"self":"https://issues.apache.org/jira/rest/api/2/user?username=mamtas","name":"mamtas","emailAddress":"msatoor at gmail dot com","avatarUrls":{"48x48":"https://issues.apache.org/jira/secure/useravatar?avatarId=10452","24x24":"https://issues.apache.org/jira/secure/useravatar?size=small&avatarId=10452","16x16":"https://issues.apache.org/jira/secure/useravatar?size=xsmall&avatarId=10452","32x32":"https://issues.apache.org/jira/secure/useravatar?size=medium&avatarId=10452"},"displayName":"Mamta A. Satoor","active":true},"created":"2009-03-19T21:39:42.886+0000","updated":"2009-03-19T21:39:42.886+0000"},{"self":"https://issues.apache.org/jira/rest/api/2/issue/12416839/comment/12683709","id":"12683709","author":{"self":"https://issues.apache.org/jira/rest/api/2/user?username=kmarsden","name":"kmarsden","emailAddress":"kmarsdenderby at sbcglobal dot net","avatarUrls":{"48x48":"https://issues.apache.org/jira/secure/useravatar?avatarId=10452","24x24":"https://issues.apache.org/jira/secure/useravatar?size=small&avatarId=10452","16x16":"https://issues.apache.org/jira/secure/useravatar?size=xsmall&avatarId=10452","32x32":"https://issues.apache.org/jira/secure/useravatar?size=medium&avatarId=10452"},"displayName":"Kathey Marsden","active":true},"body":"Tests ran fine. Attached is the new patch closing the previous ResultSet (derby-4095_diff2.txt).  I'll commit tomorrow morning if I hear no objection.\r\n","updateAuthor":{"self":"https://issues.apache.org/jira/rest/api/2/user?username=kmarsden","name":"kmarsden","emailAddress":"kmarsdenderby at sbcglobal dot net","avatarUrls":{"48x48":"https://issues.apache.org/jira/secure/useravatar?avatarId=10452","24x24":"https://issues.apache.org/jira/secure/useravatar?size=small&avatarId=10452","16x16":"https://issues.apache.org/jira/secure/useravatar?size=xsmall&avatarId=10452","32x32":"https://issues.apache.org/jira/secure/useravatar?size=medium&avatarId=10452"},"displayName":"Kathey Marsden","active":true},"created":"2009-03-20T01:49:27.611+0000","updated":"2009-03-20T01:49:27.611+0000"},{"self":"https://issues.apache.org/jira/rest/api/2/issue/12416839/comment/12685378","id":"12685378","author":{"self":"https://issues.apache.org/jira/rest/api/2/user?username=kmarsden","name":"kmarsden","emailAddress":"kmarsdenderby at sbcglobal dot net","avatarUrls":{"48x48":"https://issues.apache.org/jira/secure/useravatar?avatarId=10452","24x24":"https://issues.apache.org/jira/secure/useravatar?size=small&avatarId=10452","16x16":"https://issues.apache.org/jira/secure/useravatar?size=xsmall&avatarId=10452","32x32":"https://issues.apache.org/jira/secure/useravatar?size=medium&avatarId=10452"},"displayName":"Kathey Marsden","active":true},"body":"committed to trunk and 10.3. Will commit to 10.5,10.4.10.2, and 10.1 next week.  Leaving this issue open until then.\r\n\r\n","updateAuthor":{"self":"https://issues.apache.org/jira/rest/api/2/user?username=kmarsden","name":"kmarsden","emailAddress":"kmarsdenderby at sbcglobal dot net","avatarUrls":{"48x48":"https://issues.apache.org/jira/secure/useravatar?avatarId=10452","24x24":"https://issues.apache.org/jira/secure/useravatar?size=small&avatarId=10452","16x16":"https://issues.apache.org/jira/secure/useravatar?size=xsmall&avatarId=10452","32x32":"https://issues.apache.org/jira/secure/useravatar?size=medium&avatarId=10452"},"displayName":"Kathey Marsden","active":true},"created":"2009-03-20T22:22:27.230+0000","updated":"2009-03-20T22:22:27.230+0000"},{"self":"https://issues.apache.org/jira/rest/api/2/issue/12416839/comment/12688109","id":"12688109","author":{"self":"https://issues.apache.org/jira/rest/api/2/user?username=knutanders","name":"knutanders","emailAddress":"knut dot hatlen at oracle dot com","avatarUrls":{"48x48":"https://issues.apache.org/jira/secure/useravatar?avatarId=10452","24x24":"https://issues.apache.org/jira/secure/useravatar?size=small&avatarId=10452","16x16":"https://issues.apache.org/jira/secure/useravatar?size=xsmall&avatarId=10452","32x32":"https://issues.apache.org/jira/secure/useravatar?size=medium&avatarId=10452"},"displayName":"Knut Anders Hatlen","active":true},"body":"Sorry for not responding earlier, I've been on the road for a couple of days.\r\n\r\nI'm fine with the patch as it is. The reinitialization of the result set apparently creates a shallow clone of the underlying result set (see InternalTriggerExecutionContext.getNewRowSet()) so it shouldn't be that expensive to perform it twice, even if the before or after image is big.","updateAuthor":{"self":"https://issues.apache.org/jira/rest/api/2/user?username=knutanders","name":"knutanders","emailAddress":"knut dot hatlen at oracle dot com","avatarUrls":{"48x48":"https://issues.apache.org/jira/secure/useravatar?avatarId=10452","24x24":"https://issues.apache.org/jira/secure/useravatar?size=small&avatarId=10452","16x16":"https://issues.apache.org/jira/secure/useravatar?size=xsmall&avatarId=10452","32x32":"https://issues.apache.org/jira/secure/useravatar?size=medium&avatarId=10452"},"displayName":"Knut Anders Hatlen","active":true},"created":"2009-03-22T09:29:03.462+0000","updated":"2009-03-22T09:29:03.462+0000"},{"self":"https://issues.apache.org/jira/rest/api/2/issue/12416839/comment/12688149","id":"12688149","author":{"self":"https://issues.apache.org/jira/rest/api/2/user?username=kmarsden","name":"kmarsden","emailAddress":"kmarsdenderby at sbcglobal dot net","avatarUrls":{"48x48":"https://issues.apache.org/jira/secure/useravatar?avatarId=10452","24x24":"https://issues.apache.org/jira/secure/useravatar?size=small&avatarId=10452","16x16":"https://issues.apache.org/jira/secure/useravatar?size=xsmall&avatarId=10452","32x32":"https://issues.apache.org/jira/secure/useravatar?size=medium&avatarId=10452"},"displayName":"Kathey Marsden","active":true},"body":"Thanks Knut for looking at the performance issue. I will go ahead and backport and close this out then as is.\r\n","updateAuthor":{"self":"https://issues.apache.org/jira/rest/api/2/user?username=kmarsden","name":"kmarsden","emailAddress":"kmarsdenderby at sbcglobal dot net","avatarUrls":{"48x48":"https://issues.apache.org/jira/secure/useravatar?avatarId=10452","24x24":"https://issues.apache.org/jira/secure/useravatar?size=small&avatarId=10452","16x16":"https://issues.apache.org/jira/secure/useravatar?size=xsmall&avatarId=10452","32x32":"https://issues.apache.org/jira/secure/useravatar?size=medium&avatarId=10452"},"displayName":"Kathey Marsden","active":true},"created":"2009-03-22T16:51:15.611+0000","updated":"2009-03-22T16:51:15.611+0000"},{"self":"https://issues.apache.org/jira/rest/api/2/issue/12416839/comment/12688185","id":"12688185","author":{"self":"https://issues.apache.org/jira/rest/api/2/user?username=kmarsden","name":"kmarsden","emailAddress":"kmarsdenderby at sbcglobal dot net","avatarUrls":{"48x48":"https://issues.apache.org/jira/secure/useravatar?avatarId=10452","24x24":"https://issues.apache.org/jira/secure/useravatar?size=small&avatarId=10452","16x16":"https://issues.apache.org/jira/secure/useravatar?size=xsmall&avatarId=10452","32x32":"https://issues.apache.org/jira/secure/useravatar?size=medium&avatarId=10452"},"displayName":"Kathey Marsden","active":true},"body":"For 10.1 I don't think this bug exists because TriggerNewTransitionRows and TriggerOldTransitionRows extend VTITemplate insted of UpdatableVTITemplate  (This was changed in DERBY-438) so I don't think it will be considered a \"version2\" style VTI and go through the reOpenCore code and there is no executeQuery for it to execute anyway.\r\n\r\nI am not *totally*  sure the problematic plan does not have a problem in  10.1 because we don't have optimizer directives in 10.1 so  can't try it out, but for now we will leave this just as affecting 10.2\r\n\r\n","updateAuthor":{"self":"https://issues.apache.org/jira/rest/api/2/user?username=kmarsden","name":"kmarsden","emailAddress":"kmarsdenderby at sbcglobal dot net","avatarUrls":{"48x48":"https://issues.apache.org/jira/secure/useravatar?avatarId=10452","24x24":"https://issues.apache.org/jira/secure/useravatar?size=small&avatarId=10452","16x16":"https://issues.apache.org/jira/secure/useravatar?size=xsmall&avatarId=10452","32x32":"https://issues.apache.org/jira/secure/useravatar?size=medium&avatarId=10452"},"displayName":"Kathey Marsden","active":true},"created":"2009-03-22T23:56:02.259+0000","updated":"2009-03-22T23:56:02.259+0000"}]},"votes":{"self":"https://issues.apache.org/jira/rest/api/2/issue/DERBY-4095/votes","votes":0,"hasVoted":false},"worklog":{"startAt":0,"maxResults":20,"total":0,"worklogs":[]},"customfield_12311820":"0|i06vf3:"}}