{"expand":"renderedFields,names,schema,transitions,operations,editmeta,changelog","id":"12538901","self":"https://issues.apache.org/jira/rest/api/latest/issue/12538901","key":"DERBY-5574","fields":{"issuetype":{"self":"https://issues.apache.org/jira/rest/api/2/issuetype/1","id":"1","description":"A problem which impairs or prevents the functions of the product.","iconUrl":"https://issues.apache.org/jira/images/icons/issuetypes/bug.png","name":"Bug","subtask":false},"timespent":null,"project":{"self":"https://issues.apache.org/jira/rest/api/2/project/10594","id":"10594","key":"DERBY","name":"Derby","avatarUrls":{"48x48":"https://issues.apache.org/jira/secure/projectavatar?pid=10594&avatarId=10122","24x24":"https://issues.apache.org/jira/secure/projectavatar?size=small&pid=10594&avatarId=10122","16x16":"https://issues.apache.org/jira/secure/projectavatar?size=xsmall&pid=10594&avatarId=10122","32x32":"https://issues.apache.org/jira/secure/projectavatar?size=medium&pid=10594&avatarId=10122"},"projectCategory":{"self":"https://issues.apache.org/jira/rest/api/2/projectCategory/10090","id":"10090","description":"DB related projects","name":"DB"}},"fixVersions":[{"self":"https://issues.apache.org/jira/rest/api/2/version/12315902","id":"12315902","description":"Head of 10.7 branch as of 2010-11-29","name":"10.7.1.4","archived":false,"released":false},{"self":"https://issues.apache.org/jira/rest/api/2/version/12323456","id":"12323456","description":"Third release on the 10.8 branch","name":"10.8.3.0","archived":false,"released":true,"releaseDate":"2012-11-16"},{"self":"https://issues.apache.org/jira/rest/api/2/version/12316344","id":"12316344","description":"First release on the 10.9 branch","name":"10.9.1.0","archived":false,"released":true,"releaseDate":"2012-06-25"}],"aggregatetimespent":null,"resolution":{"self":"https://issues.apache.org/jira/rest/api/2/resolution/1","id":"1","description":"A fix for this issue is checked into the tree and tested.","name":"Fixed"},"customfield_12310220":null,"customfield_12312322":null,"customfield_12312323":null,"customfield_12310420":"224404","customfield_12310222":"1_*:*_1_*:*_2328174729_*|*_5_*:*_1_*:*_0","customfield_12312320":null,"customfield_12312321":null,"customfield_12312120":null,"customfield_12312121":null,"resolutiondate":"2012-02-14T22:43:26.191+0000","workratio":-1,"customfield_12312328":null,"customfield_12312329":null,"customfield_12312326":null,"customfield_12310300":null,"customfield_12312327":null,"customfield_12312324":null,"customfield_12312325":null,"lastViewed":null,"watches":{"self":"https://issues.apache.org/jira/rest/api/2/issue/DERBY-5574/watchers","watchCount":0,"isWatching":false},"created":"2012-01-19T00:00:31.629+0000","priority":{"self":"https://issues.apache.org/jira/rest/api/2/priority/3","iconUrl":"https://issues.apache.org/jira/images/icons/priorities/major.png","name":"Major","id":"3"},"labels":[],"customfield_12312333":null,"customfield_12312334":null,"customfield_12310310":"2.0","customfield_12312331":null,"customfield_12312332":null,"timeestimate":null,"aggregatetimeoriginalestimate":null,"versions":[{"self":"https://issues.apache.org/jira/rest/api/2/version/12315902","id":"12315902","description":"Head of 10.7 branch as of 2010-11-29","name":"10.7.1.4","archived":false,"released":false}],"customfield_12311120":null,"customfield_12312330":null,"issuelinks":[{"id":"12348848","self":"https://issues.apache.org/jira/rest/api/2/issueLink/12348848","type":{"id":"12310000","name":"Duplicate","inward":"is duplicated by","outward":"duplicates","self":"https://issues.apache.org/jira/rest/api/2/issueLinkType/12310000"},"inwardIssue":{"id":"12504109","key":"DERBY-5188","self":"https://issues.apache.org/jira/rest/api/2/issue/12504109","fields":{"summary":"error XBM0S in nstest on attempting re-encryption","status":{"self":"https://issues.apache.org/jira/rest/api/2/status/6","description":"The issue is considered finished, the resolution is correct. Issues which are closed can be reopened.","iconUrl":"https://issues.apache.org/jira/images/icons/statuses/closed.png","name":"Closed","id":"6","statusCategory":{"self":"https://issues.apache.org/jira/rest/api/2/statuscategory/3","id":3,"key":"done","colorName":"green","name":"Complete"}},"priority":{"self":"https://issues.apache.org/jira/rest/api/2/priority/3","iconUrl":"https://issues.apache.org/jira/images/icons/priorities/major.png","name":"Major","id":"3"},"issuetype":{"self":"https://issues.apache.org/jira/rest/api/2/issuetype/1","id":"1","description":"A problem which impairs or prevents the functions of the product.","iconUrl":"https://issues.apache.org/jira/images/icons/issuetypes/bug.png","name":"Bug","subtask":false}}}}],"customfield_12312339":null,"assignee":{"self":"https://issues.apache.org/jira/rest/api/2/user?username=mikem","name":"mikem","emailAddress":"mikem_app at sbcglobal dot net","avatarUrls":{"48x48":"https://issues.apache.org/jira/secure/useravatar?avatarId=10452","24x24":"https://issues.apache.org/jira/secure/useravatar?size=small&avatarId=10452","16x16":"https://issues.apache.org/jira/secure/useravatar?size=xsmall&avatarId=10452","32x32":"https://issues.apache.org/jira/secure/useravatar?size=medium&avatarId=10452"},"displayName":"Mike Matrigali","active":true},"customfield_12312337":null,"customfield_12312338":null,"updated":"2013-06-19T17:19:26.023+0000","customfield_12312335":null,"customfield_12311720":null,"customfield_12312336":null,"status":{"self":"https://issues.apache.org/jira/rest/api/2/status/6","description":"The issue is considered finished, the resolution is correct. Issues which are closed can be reopened.","iconUrl":"https://issues.apache.org/jira/images/icons/statuses/closed.png","name":"Closed","id":"6","statusCategory":{"self":"https://issues.apache.org/jira/rest/api/2/statuscategory/3","id":3,"key":"done","colorName":"green","name":"Complete"}},"components":[{"self":"https://issues.apache.org/jira/rest/api/2/component/11413","id":"11413","name":"Test"}],"timeoriginalestimate":null,"description":"encryption tests in nightly are intermittently failing.  The suite runs same set of tests with a number of different\r\nencryption algorithms.  Different ones of these runs sometimes fail.  \r\n\r\nWhat has changed on this nightly platform is that we are now running each jvm set of tests concurrently to\r\nget better throughput.  This has changed load on machine and timing of operations.  Each JVM puts results\r\ninto a different part of file system.  \r\n\r\nAt least after the fact the file being renamed still exists and the destination file does not exist.\r\n\r\nnightly test failure, jdk16, current 10.7 branch, windows.\r\n\r\nhttp://people.apache.org/~myrnavl/derby_test_results/v10_7/windows/testlog/ibm16/1231439-derbyall_diff.txt\r\n\r\nFailure Details:\r\n********* Diff file derbyall/derbynetclientmats/DerbyNetClient/encodingTests/TestEnc.diff\r\n*** Start: TestEnc jdk1.6.0 DerbyNetClient derbynetclientmats:encodingTests 2012-01-14 01:42:10 ***\r\nderbyTesting.encoding can only be used with jdk15, skipping test\r\n*** End:   TestEnc jdk1.6.0 DerbyNetClient derbynetclientmats:encodingTests 2012-01-14 01:42:10 ***\r\n********* Diff file derbyall/encryptionAll/encryptionAES/encryptDatabase.diff\r\n*** Start: encryptDatabase jdk1.6.0 encryptionAll:encryptionAES 2012-01-14 01:51:40 ***\r\n74 del\r\n< 0 rows inserted/updated/deleted\r\n74a74,76\r\n> ERROR 38000: The exception 'org.apache.derby.iapi.error.PassThroughException: encryptionAll:encryptionAES 'F:\\jartest\\JarResults.2012-01-13\\ibm16_derbyall\\derbyall\\encryptionAll\\encryptionAES\\encryptDatabase\\wombat\\service.properties' to 'F:\\jartest\\JarResults.2012-01-13\\ibm16_derbyall\\derbyall\\encryptionAll\\encryptionAES\\encryptDatabase\\wombat\\service.propertiesold'' was thrown while evaluating an expression.\r\n> ERROR XJ001: Java exception: 'ERROR XBM0S: Unable to rename file 'F:\\jartest\\JarResults.2012-01-13\\ibm16_derbyall\\derbyall\\encryptionAll\\encryptionAES\\encryptDatabase\\wombat\\service.properties' to 'F:\\jartest\\JarResults.2012-01-13\\ibm16_derbyall\\derbyall\\encryptionAll\\encryptionAES\\encryptDatabase\\wombat\\service.propertiesold': org.apache.derby.iapi.error.PassThroughException'.\r\n> ERROR XBM0S: Unable to rename file 'F:\\jartest\\JarResults.2012-01-13\\ibm16_derbyall\\derbyall\\encryptionAll\\encryptionAES\\encryptDatabase\\wombat\\service.properties' to 'F:\\jartest\\JarResults.2012-01-13\\ibm16_derbyall\\derbyall\\encryptionAll\\encryptionAES\\encryptDatabase\\wombat\\service.propertiesold'\r\n94,95d95\r\n< ERROR XJ040: Failed to start database 'wombat' with class loader XXXX,  see the next exception for details.\r\n< ERROR XBM06: Startup failed. An encrypted database cannot be accessed without the correct boot password.  \r\n97 del\r\n< ij> values SYSCS_UTIL.SYSCS_GET_DATABASE_PROPERTY('bootPassword');\r\n97a97\r\n> ij(CONNECTION1)> values SYSCS_UTIL.SYSCS_GET_DATABASE_PROPERTY('bootPassword');\r\n101 del\r\n< ij> values SYSCS_UTIL.SYSCS_GET_DATABASE_PROPERTY('encryptedBootPassword');\r\n101a101\r\n> ij(CONNECTION1)> values SYSCS_UTIL.SYSCS_GET_DATABASE_PROPERTY('encryptedBootPassword');\r\n105 del\r\n< ij> -- change it again, make sure it trims white spaces\r\n105a105\r\n> ij(CONNECTION1)> -- change it again, make sure it trims white spaces\r\n107 del\r\n< 0 rows inserted/updated/deleted\r\n108 del\r\n< ij> call SYSCS_UTIL.SYSCS_SET_DATABASE_PROPERTY('bootPassword', 'bbderbypwdx, derbypwdxx ');\r\n109 del\r\n< 0 rows inserted/updated/deleted\r\n110 del\r\n< ij> values SYSCS_UTIL.SYSCS_GET_DATABASE_PROPERTY('bootPassword');\r\n110a107,110\r\n> ERROR XBCXA: Wrong boot password.\r\n> ij(CONNECTION1)> call SYSCS_UTIL.SYSCS_SET_DATABASE_PROPERTY('bootPassword', 'bbderbypwdx, derbypwdxx ');\r\n> ERROR XBCXA: Wrong boot password.\r\n> ij(CONNECTION1)> values SYSCS_UTIL.SYSCS_GET_DATABASE_PROPERTY('bootPassword');\r\n114 del\r\n< ij> values SYSCS_UTIL.SYSCS_GET_DATABASE_PROPERTY('encryptedBootPassword');\r\n114a114\r\n> ij(CONNECTION1)> values SYSCS_UTIL.SYSCS_GET_DATABASE_PROPERTY('encryptedBootPassword');\r\n118 del\r\n< ij> disconnect;\r\n118a118\r\n> ij(CONNECTION1)> disconnect;\r\n124a125,126\r\n> ERROR XJ040: Failed to start database 'wombat' with class loader XXXX,  see the next exception for details.\r\n> ERROR XBM06: Startup failed. An encrypted database cannot be accessed without the correct boot password.  \r\n126 del\r\n< A                   \r\n127 del\r\n< --------------------\r\n128 del\r\n< hello world         \r\n128a128\r\n> IJ ERROR: Unable to establish connection\r\n132 del\r\n< ERROR XBCXD: The encryption algorithm cannot be changed after the database is created.\r\n132a132\r\n> IJ ERROR: Unable to establish connection\r\n134 del\r\n< ERROR XBCXE: The encryption provider cannot be changed after the database is created.\r\n134a134\r\n> IJ ERROR: Unable to establish connection\r\nTest Failed.\r\n*** End:   encryptDatabase jdk1.6.0 encryptionAll:encryptionAES 2012-01-14 01:51:49 ***\r\n------------------------------------------------------\r\n","customfield_10010":null,"timetracking":{},"customfield_12312026":null,"customfield_12310200":[{"self":"https://issues.apache.org/jira/rest/api/2/customFieldOption/10369","value":"Regression Test Failure","id":"10369"}],"customfield_12312023":null,"customfield_12312024":null,"customfield_12312340":null,"aggregatetimeestimate":null,"customfield_12312022":null,"customfield_12312341":null,"customfield_12312220":null,"customfield_12310921":null,"customfield_12310920":"35894","summary":"encryption test in encryption nightly suite test fails with ERROR XBM0S: Unable to rename file error","creator":{"self":"https://issues.apache.org/jira/rest/api/2/user?username=mikem","name":"mikem","emailAddress":"mikem_app at sbcglobal dot net","avatarUrls":{"48x48":"https://issues.apache.org/jira/secure/useravatar?avatarId=10452","24x24":"https://issues.apache.org/jira/secure/useravatar?size=small&avatarId=10452","16x16":"https://issues.apache.org/jira/secure/useravatar?size=xsmall&avatarId=10452","32x32":"https://issues.apache.org/jira/secure/useravatar?size=medium&avatarId=10452"},"displayName":"Mike Matrigali","active":true},"subtasks":[],"customfield_12310090":null,"reporter":{"self":"https://issues.apache.org/jira/rest/api/2/user?username=mikem","name":"mikem","emailAddress":"mikem_app at sbcglobal dot net","avatarUrls":{"48x48":"https://issues.apache.org/jira/secure/useravatar?avatarId=10452","24x24":"https://issues.apache.org/jira/secure/useravatar?size=small&avatarId=10452","16x16":"https://issues.apache.org/jira/secure/useravatar?size=xsmall&avatarId=10452","32x32":"https://issues.apache.org/jira/secure/useravatar?size=medium&avatarId=10452"},"displayName":"Mike Matrigali","active":true},"customfield_12310291":null,"customfield_12310290":null,"aggregateprogress":{"progress":0,"total":0},"environment":"------------------ Java Information ------------------\r\nJava Version:    1.6.0\r\nJava Vendor:     IBM Corporation\r\nJava home:       F:\\jartest\\ibm16\\jre\r\nJava classpath:  F:\\jartest/tools/java/jakarta-oro-2.0.8.jar;F:\\jartest/junit/junit.jar;;F:\\jartest/classes/derbyrun.jar;F:\\jartest/classes/derbyTesting.jar;F:\\jartest/junit/junit.jar;F:\\jartest/tools/java/jakarta-oro-2.0.8.jar;F:\\jartest/tools/java/geronimo-spec-servlet-2.4-rc4.jar;F:\\jartest/tools/java/xalan.jar;F:\\jartest/tools/java/xercesImpl.jar;\r\nOS name:         Windows XP\r\nOS architecture: x86\r\nOS version:      5.1 build 2600 Service Pack 3\r\nJava user name:  cloudtest\r\nJava user home:  C:\\Documents and Settings\\cloudtest\r\nJava user dir:   F:\\jartest\\JarResults.2012-01-13\\ibm16_derbyall\r\njava.specification.name: Java Platform API Specification\r\njava.specification.version: 1.6\r\njava.runtime.version: jvmwi3260sr9-20110203_74623\r\njava.fullversion: JRE 1.6.0 IBM J9 2.4 Windows XP x86-32 jvmwi3260sr9-20110203_74623 (JIT enabled, AOT enabled)\r\nJ9VM - 20110203_074623\r\nJIT  - r9_20101028_17488ifx3\r\nGC   - 20101027_AA\r\n--------- Derby Information --------\r\nJRE - JDBC: Java SE 6 - JDBC 4.0\r\n[F:\\jartest\\classes\\derby.jar] 10.7.1.4 - (1231439)\r\n[F:\\jartest\\classes\\derbytools.jar] 10.7.1.4 - (1231439)\r\n[F:\\jartest\\classes\\derbynet.jar] 10.7.1.4 - (1231439)\r\n[F:\\jartest\\classes\\derbyclient.jar] 10.7.1.4 - (1231439)\r\n------------------------------------------------------\r\n----------------- Locale Information -----------------\r\nCurrent Locale :  [English/United States [en_US]]\r\nFound support for locale: [cs]\r\n\t version: 10.7.1.4 - (1231439)\r\nFound support for locale: [de_DE]\r\n\t version: 10.7.1.4 - (1231439)\r\nFound support for locale: [es]\r\n\t version: 10.7.1.4 - (1231439)\r\nFound support for locale: [fr]\r\n\t version: 10.7.1.4 - (1231439)\r\nFound support for locale: [hu]\r\n\t version: 10.7.1.4 - (1231439)\r\nFound support for locale: [it]\r\n\t version: 10.7.1.4 - (1231439)\r\nFound support for locale: [ja_JP]\r\n\t version: 10.7.1.4 - (1231439)\r\nFound support for locale: [ko_KR]\r\n\t version: 10.7.1.4 - (1231439)\r\nFound support for locale: [pl]\r\n\t version: 10.7.1.4 - (1231439)\r\nFound support for locale: [pt_BR]\r\n\t version: 10.7.1.4 - (1231439)\r\nFound support for locale: [ru]\r\n\t version: 10.7.1.4 - (1231439)\r\nFound support for locale: [zh_CN]\r\n\t version: 10.7.1.4 - (1231439)\r\nFound support for locale: [zh_TW]\r\n\t version: 10.7.1.4 - (1231439)\r\n------------------------------------------------------\r\n","customfield_12311020":null,"customfield_12310050":null,"duedate":null,"customfield_12310250":null,"progress":{"progress":0,"total":0},"comment":{"startAt":0,"maxResults":8,"total":8,"comments":[{"self":"https://issues.apache.org/jira/rest/api/2/issue/12538901/comment/13188820","id":"13188820","author":{"self":"https://issues.apache.org/jira/rest/api/2/user?username=mikem","name":"mikem","emailAddress":"mikem_app at sbcglobal dot net","avatarUrls":{"48x48":"https://issues.apache.org/jira/secure/useravatar?avatarId=10452","24x24":"https://issues.apache.org/jira/secure/useravatar?size=small&avatarId=10452","16x16":"https://issues.apache.org/jira/secure/useravatar?size=xsmall&avatarId=10452","32x32":"https://issues.apache.org/jira/secure/useravatar?size=medium&avatarId=10452"},"displayName":"Mike Matrigali","active":true},"body":"failed also in same way against ibm16 in a run a week later against 10.7 head of brach\r\n\r\nhttp://people.apache.org/~myrnavl/derby_test_results/v10_7/windows/testlog/ibm16/1231617-derbyall_diff.txt\r\n\r\nFailure Details:\r\n********* Diff file derbyall/derbynetclientmats/DerbyNetClient/encodingTests/TestEnc.diff\r\n*** Start: TestEnc jdk1.6.0 DerbyNetClient derbynetclientmats:encodingTests 2012-01-15 00:58:34 ***\r\nderbyTesting.encoding can only be used with jdk15, skipping test\r\n*** End:   TestEnc jdk1.6.0 DerbyNetClient derbynetclientmats:encodingTests 2012-01-15 00:58:34 ***\r\n********* Diff file derbyall/encryptionAll/encryptionECB/encryptDatabase.diff\r\n*** Start: encryptDatabase jdk1.6.0 encryptionAll:encryptionECB 2012-01-15 01:04:22 ***\r\n68 del\r\n< 0 rows inserted/updated/deleted\r\n68a68,70\r\n> ERROR 38000: The exception 'org.apache.derby.iapi.error.PassThroughException: ERROR XBM0S: Unable to rename file 'F:\\jartest\\JarResults.2012-01-14\\ibm16_derbyall\\derbyall\\encryptionAll\\encryptionECB\\encryptDatabase\\wombat\\service.properties' to 'F:\\jartest\\JarResults.2012-01-14\\ibm16_derbyall\\derbyall\\encryptionAll\\encryptionECB\\encryptDatabase\\wombat\\service.propertiesold'' was thrown while evaluating an expression.\r\n> ERROR XJ001: Java exception: 'ERROR XBM0S: Unable to rename file 'F:\\jartest\\JarResults.2012-01-14\\ibm16_derbyall\\derbyall\\encryptionAll\\encryptionECB\\encryptDatabase\\wombat\\service.properties' to 'F:\\jartest\\JarResults.2012-01-14\\ibm16_derbyall\\derbyall\\encryptionAll\\encryptionECB\\encryptDatabase\\wombat\\service.propertiesold': org.apache.derby.iapi.error.PassThroughException'.\r\n> ERROR XBM0S: Unable to rename file 'F:\\jartest\\JarResults.2012-01-14\\ibm16_derbyall\\derbyall\\encryptionAll\\encryptionECB\\encryptDatabase\\wombat\\service.properties' to 'F:\\jartest\\JarResults.2012-01-14\\ibm16_derbyall\\derbyall\\encryptionAll\\encryptionECB\\encryptDatabase\\wombat\\service.propertiesold'\r\n74 del\r\n< 0 rows inserted/updated/deleted\r\n74a76,78\r\n> ERROR 38000: The exception 'org.apache.derby.iapi.error.PassThroughException: ERROR XBM0S: Unable to rename file 'F:\\jartest\\JarResults.2012-01-14\\ibm16_derbyall\\derbyall\\encryptionAll\\encryptionECB\\encryptDatabase\\wombat\\service.properties' to 'F:\\jartest\\JarResults.2012-01-14\\ibm16_derbyall\\derbyall\\encryptionAll\\encryptionECB\\encryptDatabase\\wombat\\service.propertiesold'' was thrown while evaluating an expression.\r\n> ERROR XJ001: Java exception: 'ERROR XBM0S: Unable to rename file 'F:\\jartest\\JarResults.2012-01-14\\ibm16_derbyall\\derbyall\\encryptionAll\\encryptionECB\\encryptDatabase\\wombat\\service.properties' to 'F:\\jartest\\JarResults.2012-01-14\\ibm16_derbyall\\derbyall\\encryptionAll\\encryptionECB\\encryptDatabase\\wombat\\service.propertiesold': org.apache.derby.iapi.error.PassThroughException'.\r\n> ERROR XBM0S: Unable to rename file 'F:\\jartest\\JarResults.2012-01-14\\ibm16_derbyall\\derbyall\\encryptionAll\\encryptionECB\\encryptDatabase\\wombat\\service.properties' to 'F:\\jartest\\JarResults.2012-01-14\\ibm16_derbyall\\derbyall\\encryptionAll\\encryptionECB\\encryptDatabase\\wombat\\service.propertiesold'\r\n91,92d94\r\n< ERROR XJ040: Failed to start database 'wombat' with class loader XXXX,  see the next exception for details.\r\n< ERROR XBM06: Startup failed. An encrypted database cannot be accessed without the correct boot password.  \r\n94 del\r\n< ERROR XJ040: Failed to start database 'wombat' with class loader XXXX,  see the next exception for details.\r\n95 del\r\n< ERROR XBM06: Startup failed. An encrypted database cannot be accessed without the correct boot password.  \r\n96 del\r\n< ij> connect 'jdbc:derby:wombat;bootPassword=derbypwd';\r\n97 del\r\n< ij> values SYSCS_UTIL.SYSCS_GET_DATABASE_PROPERTY('bootPassword');\r\n97a96,97\r\n> ij(CONNECTION1)> connect 'jdbc:derby:wombat;bootPassword=derbypwd';\r\n> ij(CONNECTION2)> values SYSCS_UTIL.SYSCS_GET_DATABASE_PROPERTY('bootPassword');\r\n101 del\r\n< ij> values SYSCS_UTIL.SYSCS_GET_DATABASE_PROPERTY('encryptedBootPassword');\r\n101a101\r\n> ij(CONNECTION2)> values SYSCS_UTIL.SYSCS_GET_DATABASE_PROPERTY('encryptedBootPassword');\r\n105 del\r\n< ij> -- change it again, make sure it trims white spaces\r\n105a105\r\n> ij(CONNECTION2)> -- change it again, make sure it trims white spaces\r\n107 del\r\n< 0 rows inserted/updated/deleted\r\n108 del\r\n< ij> call SYSCS_UTIL.SYSCS_SET_DATABASE_PROPERTY('bootPassword', 'bbderbypwdx, derbypwdxx ');\r\n109 del\r\n< 0 rows inserted/updated/deleted\r\n110 del\r\n< ij> values SYSCS_UTIL.SYSCS_GET_DATABASE_PROPERTY('bootPassword');\r\n110a107,110\r\n> ERROR XBCXA: Wrong boot password.\r\n> ij(CONNECTION2)> call SYSCS_UTIL.SYSCS_SET_DATABASE_PROPERTY('bootPassword', 'bbderbypwdx, derbypwdxx ');\r\n> ERROR XBCXA: Wrong boot password.\r\n> ij(CONNECTION2)> values SYSCS_UTIL.SYSCS_GET_DATABASE_PROPERTY('bootPassword');\r\n114 del\r\n< ij> values SYSCS_UTIL.SYSCS_GET_DATABASE_PROPERTY('encryptedBootPassword');\r\n114a114\r\n> ij(CONNECTION2)> values SYSCS_UTIL.SYSCS_GET_DATABASE_PROPERTY('encryptedBootPassword');\r\n118 del\r\n< ij> disconnect;\r\n118a118\r\n> ij(CONNECTION2)> disconnect;\r\n124a125,126\r\n> ERROR XJ040: Failed to start database 'wombat' with class loader XXXX,  see the next exception for details.\r\n> ERROR XBM06: Startup failed. An encrypted database cannot be accessed without the correct boot password.  \r\n126 del\r\n< A                   \r\n127 del\r\n< --------------------\r\n128 del\r\n< hello world         \r\n128a128\r\n> IJ ERROR: Unable to establish connection\r\n132 del\r\n< ERROR XBCXD: The encryption algorithm cannot be changed after the database is created.\r\n132a132\r\n> IJ ERROR: Unable to establish connection\r\n134 del\r\n< ERROR XBCXE: The encryption provider cannot be changed after the database is created.\r\n134a134\r\n> IJ ERROR: Unable to establish connection\r\nTest Failed.\r\n*** End:   encryptDatabase jdk1.6.0 encryptionAll:encryptionECB 2012-01-15 01:04:32 ***\r\n","updateAuthor":{"self":"https://issues.apache.org/jira/rest/api/2/user?username=mikem","name":"mikem","emailAddress":"mikem_app at sbcglobal dot net","avatarUrls":{"48x48":"https://issues.apache.org/jira/secure/useravatar?avatarId=10452","24x24":"https://issues.apache.org/jira/secure/useravatar?size=small&avatarId=10452","16x16":"https://issues.apache.org/jira/secure/useravatar?size=xsmall&avatarId=10452","32x32":"https://issues.apache.org/jira/secure/useravatar?size=medium&avatarId=10452"},"displayName":"Mike Matrigali","active":true},"created":"2012-01-19T00:02:16.978+0000","updated":"2012-01-19T00:03:49.518+0000"},{"self":"https://issues.apache.org/jira/rest/api/2/issue/12538901/comment/13189207","id":"13189207","author":{"self":"https://issues.apache.org/jira/rest/api/2/user?username=mikem","name":"mikem","emailAddress":"mikem_app at sbcglobal dot net","avatarUrls":{"48x48":"https://issues.apache.org/jira/secure/useravatar?avatarId=10452","24x24":"https://issues.apache.org/jira/secure/useravatar?size=small&avatarId=10452","16x16":"https://issues.apache.org/jira/secure/useravatar?size=xsmall&avatarId=10452","32x32":"https://issues.apache.org/jira/secure/useravatar?size=medium&avatarId=10452"},"displayName":"Mike Matrigali","active":true},"body":"changing title as different tests in the encryption suite seem to be failing intermittently.","updateAuthor":{"self":"https://issues.apache.org/jira/rest/api/2/user?username=mikem","name":"mikem","emailAddress":"mikem_app at sbcglobal dot net","avatarUrls":{"48x48":"https://issues.apache.org/jira/secure/useravatar?avatarId=10452","24x24":"https://issues.apache.org/jira/secure/useravatar?size=small&avatarId=10452","16x16":"https://issues.apache.org/jira/secure/useravatar?size=xsmall&avatarId=10452","32x32":"https://issues.apache.org/jira/secure/useravatar?size=medium&avatarId=10452"},"displayName":"Mike Matrigali","active":true},"created":"2012-01-19T17:13:35.676+0000","updated":"2012-01-19T17:13:35.676+0000"},{"self":"https://issues.apache.org/jira/rest/api/2/issue/12538901/comment/13189228","id":"13189228","author":{"self":"https://issues.apache.org/jira/rest/api/2/user?username=mikem","name":"mikem","emailAddress":"mikem_app at sbcglobal dot net","avatarUrls":{"48x48":"https://issues.apache.org/jira/secure/useravatar?avatarId=10452","24x24":"https://issues.apache.org/jira/secure/useravatar?size=small&avatarId=10452","16x16":"https://issues.apache.org/jira/secure/useravatar?size=xsmall&avatarId=10452","32x32":"https://issues.apache.org/jira/secure/useravatar?size=medium&avatarId=10452"},"displayName":"Mike Matrigali","active":true},"body":"here is derby.log left around after one of the errors.","updateAuthor":{"self":"https://issues.apache.org/jira/rest/api/2/user?username=mikem","name":"mikem","emailAddress":"mikem_app at sbcglobal dot net","avatarUrls":{"48x48":"https://issues.apache.org/jira/secure/useravatar?avatarId=10452","24x24":"https://issues.apache.org/jira/secure/useravatar?size=small&avatarId=10452","16x16":"https://issues.apache.org/jira/secure/useravatar?size=xsmall&avatarId=10452","32x32":"https://issues.apache.org/jira/secure/useravatar?size=medium&avatarId=10452"},"displayName":"Mike Matrigali","active":true},"created":"2012-01-19T17:43:30.692+0000","updated":"2012-01-19T17:43:30.692+0000"},{"self":"https://issues.apache.org/jira/rest/api/2/issue/12538901/comment/13189230","id":"13189230","author":{"self":"https://issues.apache.org/jira/rest/api/2/user?username=mikem","name":"mikem","emailAddress":"mikem_app at sbcglobal dot net","avatarUrls":{"48x48":"https://issues.apache.org/jira/secure/useravatar?avatarId=10452","24x24":"https://issues.apache.org/jira/secure/useravatar?size=small&avatarId=10452","16x16":"https://issues.apache.org/jira/secure/useravatar?size=xsmall&avatarId=10452","32x32":"https://issues.apache.org/jira/secure/useravatar?size=medium&avatarId=10452"},"displayName":"Mike Matrigali","active":true},"body":"here are the stacks from first error in one of the failures:\r\nThu Jan 19 00:35:33 PST 2012 Thread[main,5,main] (XID = 211), (SESSIONID = 1), (DATABASE = wombat), (DRDAID = null), Failed Statement is: -- change it again\r\ncall SYSCS_UTIL.SYSCS_SET_DATABASE_PROPERTY('bootPassword', 'Saturday,derbypwd')\r\nERROR 38000: The exception 'org.apache.derby.iapi.error.PassThroughException: ERROR XBM0S: Unable to rename file 'D:\\jartest\\JarResults.2012-01-18\\ibm16_derbyall\\derbyall\\encryptionAll\\encryption\\encryption\\encryptDatabase\\wombat\\service.properties' to 'D:\\jartest\\JarResults.2012-01-18\\ibm16_derbyall\\derbyall\\encryptionAll\\encryption\\encryption\\encryptDatabase\\wombat\\service.propertiesold'' was thrown while evaluating an expression.\r\n\tat org.apache.derby.iapi.error.StandardException.newException(Unknown Source)\r\n\tat org.apache.derby.iapi.error.StandardException.unexpectedUserException(Unknown Source)\r\n\tat org.apache.derby.impl.services.reflect.ReflectMethod.invoke(Unknown Source)\r\n\tat org.apache.derby.impl.sql.execute.CallStatementResultSet.open(Unknown Source)\r\n\tat org.apache.derby.impl.sql.GenericPreparedStatement.executeStmt(Unknown Source)\r\n\tat org.apache.derby.impl.sql.GenericPreparedStatement.execute(Unknown Source)\r\n\tat org.apache.derby.impl.jdbc.EmbedStatement.executeStatement(Unknown Source)\r\n\tat org.apache.derby.impl.jdbc.EmbedStatement.execute(Unknown Source)\r\n\tat org.apache.derby.impl.jdbc.EmbedStatement.execute(Unknown Source)\r\n\tat org.apache.derby.impl.tools.ij.ij.executeImmediate(Unknown Source)\r\n\tat org.apache.derby.impl.tools.ij.utilMain.doCatch(Unknown Source)\r\n\tat org.apache.derby.impl.tools.ij.utilMain.runScriptGuts(Unknown Source)\r\n\tat org.apache.derby.impl.tools.ij.utilMain.go(Unknown Source)\r\n\tat org.apache.derby.impl.tools.ij.Main.go(Unknown Source)\r\n\tat org.apache.derby.impl.tools.ij.Main.mainCore(Unknown Source)\r\n\tat org.apache.derby.impl.tools.ij.Main.main(Unknown Source)\r\n\tat org.apache.derby.tools.ij.main(Unknown Source)\r\nCaused by: org.apache.derby.iapi.error.PassThroughException: ERROR XBM0S: Unable to rename file 'D:\\jartest\\JarResults.2012-01-18\\ibm16_derbyall\\derbyall\\encryptionAll\\encryption\\encryption\\encryptDatabase\\wombat\\service.properties' to 'D:\\jartest\\JarResults.2012-01-18\\ibm16_derbyall\\derbyall\\encryptionAll\\encryption\\encryption\\encryptDatabase\\wombat\\service.propertiesold'\r\n\tat org.apache.derby.impl.services.monitor.UpdateServiceProperties.update(Unknown Source)\r\n\tat org.apache.derby.impl.services.monitor.UpdateServiceProperties.put(Unknown Source)\r\n\tat org.apache.derby.impl.services.jce.JCECipherFactory.changeBootPassword(Unknown Source)\r\n\tat org.apache.derby.impl.store.raw.RawStore.changeBootPassword(Unknown Source)\r\n\tat org.apache.derby.impl.store.access.PropertyConglomerate.bootPasswordChange(Unknown Source)\r\n\tat org.apache.derby.impl.store.access.PropertyConglomerate.setProperty(Unknown Source)\r\n\tat org.apache.derby.impl.store.access.RAMTransaction.setProperty(Unknown Source)\r\n\tat org.apache.derby.iapi.db.PropertyInfo.setDatabaseProperty(Unknown Source)\r\n\tat org.apache.derby.catalog.SystemProcedures.SYSCS_SET_DATABASE_PROPERTY(Unknown Source)\r\n\tat org.apache.derby.exe.ac80220011x0134xf51bx34daxffffbee07f83f.g0(Unknown Source)\r\n\tat sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)\r\n\tat sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:60)\r\n\tat sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:37)\r\n\tat java.lang.reflect.Method.invoke(Method.java:611)\r\n\t... 15 more\r\nCaused by: ERROR XBM0S: Unable to rename file 'D:\\jartest\\JarResults.2012-01-18\\ibm16_derbyall\\derbyall\\encryptionAll\\encryption\\encryption\\encryptDatabase\\wombat\\service.properties' to 'D:\\jartest\\JarResults.2012-01-18\\ibm16_derbyall\\derbyall\\encryptionAll\\encryption\\encryption\\encryptDatabase\\wombat\\service.propertiesold'\r\n\tat org.apache.derby.iapi.error.StandardException.newException(Unknown Source)\r\n\tat org.apache.derby.impl.services.monitor.StorageFactoryService$FileOperationHelper.renameTo(Unknown Source)\r\n\tat org.apache.derby.impl.services.monitor.StorageFactoryService$5.run(Unknown Source)\r\n\tat java.security.AccessController.doPrivileged(AccessController.java:251)\r\n\tat org.apache.derby.impl.services.monitor.StorageFactoryService.saveServiceProperties(Unknown Source)\r\n\t... 29 more\r\n============= begin nested exception, level (1) ===========\r\norg.apache.derby.iapi.error.PassThroughException: ERROR XBM0S: Unable to rename file 'D:\\jartest\\JarResults.2012-01-18\\ibm16_derbyall\\derbyall\\encryptionAll\\encryption\\encryption\\encryptDatabase\\wombat\\service.properties' to 'D:\\jartest\\JarResults.2012-01-18\\ibm16_derbyall\\derbyall\\encryptionAll\\encryption\\encryption\\encryptDatabase\\wombat\\service.propertiesold'\r\n\tat org.apache.derby.impl.services.monitor.UpdateServiceProperties.update(Unknown Source)\r\n\tat org.apache.derby.impl.services.monitor.UpdateServiceProperties.put(Unknown Source)\r\n\tat org.apache.derby.impl.services.jce.JCECipherFactory.changeBootPassword(Unknown Source)\r\n\tat org.apache.derby.impl.store.raw.RawStore.changeBootPassword(Unknown Source)\r\n\tat org.apache.derby.impl.store.access.PropertyConglomerate.bootPasswordChange(Unknown Source)\r\n\tat org.apache.derby.impl.store.access.PropertyConglomerate.setProperty(Unknown Source)\r\n\tat org.apache.derby.impl.store.access.RAMTransaction.setProperty(Unknown Source)\r\n\tat org.apache.derby.iapi.db.PropertyInfo.setDatabaseProperty(Unknown Source)\r\n\tat org.apache.derby.catalog.SystemProcedures.SYSCS_SET_DATABASE_PROPERTY(Unknown Source)\r\n\tat org.apache.derby.exe.ac80220011x0134xf51bx34daxffffbee07f83f.g0(Unknown Source)\r\n\tat sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)\r\n\tat sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:60)\r\n\tat sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:37)\r\n\tat java.lang.reflect.Method.invoke(Method.java:611)\r\n\tat org.apache.derby.impl.services.reflect.ReflectMethod.invoke(Unknown Source)\r\n\tat org.apache.derby.impl.sql.execute.CallStatementResultSet.open(Unknown Source)\r\n\tat org.apache.derby.impl.sql.GenericPreparedStatement.executeStmt(Unknown Source)\r\n\tat org.apache.derby.impl.sql.GenericPreparedStatement.execute(Unknown Source)\r\n\tat org.apache.derby.impl.jdbc.EmbedStatement.executeStatement(Unknown Source)\r\n\tat org.apache.derby.impl.jdbc.EmbedStatement.execute(Unknown Source)\r\n\tat org.apache.derby.impl.jdbc.EmbedStatement.execute(Unknown Source)\r\n\tat org.apache.derby.impl.tools.ij.ij.executeImmediate(Unknown Source)\r\n\tat org.apache.derby.impl.tools.ij.utilMain.doCatch(Unknown Source)\r\n\tat org.apache.derby.impl.tools.ij.utilMain.runScriptGuts(Unknown Source)\r\n\tat org.apache.derby.impl.tools.ij.utilMain.go(Unknown Source)\r\n\tat org.apache.derby.impl.tools.ij.Main.go(Unknown Source)\r\n\tat org.apache.derby.impl.tools.ij.Main.mainCore(Unknown Source)\r\n\tat org.apache.derby.impl.tools.ij.Main.main(Unknown Source)\r\n\tat org.apache.derby.tools.ij.main(Unknown Source)\r\nCaused by: ERROR XBM0S: Unable to rename file 'D:\\jartest\\JarResults.2012-01-18\\ibm16_derbyall\\derbyall\\encryptionAll\\encryption\\encryption\\encryptDatabase\\wombat\\service.properties' to 'D:\\jartest\\JarResults.2012-01-18\\ibm16_derbyall\\derbyall\\encryptionAll\\encryption\\encryption\\encryptDatabase\\wombat\\service.propertiesold'\r\n\tat org.apache.derby.iapi.error.StandardException.newException(Unknown Source)\r\n\tat org.apache.derby.impl.services.monitor.StorageFactoryService$FileOperationHelper.renameTo(Unknown Source)\r\n\tat org.apache.derby.impl.services.monitor.StorageFactoryService$5.run(Unknown Source)\r\n\tat java.security.AccessController.doPrivileged(AccessController.java:251)\r\n\tat org.apache.derby.impl.services.monitor.StorageFactoryService.saveServiceProperties(Unknown Source)\r\n\t... 29 more\r\n============= end nested exception, level (1) ===========\r\n============= begin nested exception, level (2) ===========\r\nERROR XBM0S: Unable to rename file 'D:\\jartest\\JarResults.2012-01-18\\ibm16_derbyall\\derbyall\\encryptionAll\\encryption\\encryption\\encryptDatabase\\wombat\\service.properties' to 'D:\\jartest\\JarResults.2012-01-18\\ibm16_derbyall\\derbyall\\encryptionAll\\encryption\\encryption\\encryptDatabase\\wombat\\service.propertiesold'\r\n\tat org.apache.derby.iapi.error.StandardException.newException(Unknown Source)\r\n\tat org.apache.derby.impl.services.monitor.StorageFactoryService$FileOperationHelper.renameTo(Unknown Source)\r\n\tat org.apache.derby.impl.services.monitor.StorageFactoryService$5.run(Unknown Source)\r\n\tat java.security.AccessController.doPrivileged(AccessController.java:251)\r\n\tat org.apache.derby.impl.services.monitor.StorageFactoryService.saveServiceProperties(Unknown Source)\r\n\tat org.apache.derby.impl.services.monitor.UpdateServiceProperties.update(Unknown Source)\r\n\tat org.apache.derby.impl.services.monitor.UpdateServiceProperties.put(Unknown Source)\r\n\tat org.apache.derby.impl.services.jce.JCECipherFactory.changeBootPassword(Unknown Source)\r\n\tat org.apache.derby.impl.store.raw.RawStore.changeBootPassword(Unknown Source)\r\n\tat org.apache.derby.impl.store.access.PropertyConglomerate.bootPasswordChange(Unknown Source)\r\n\tat org.apache.derby.impl.store.access.PropertyConglomerate.setProperty(Unknown Source)\r\n\tat org.apache.derby.impl.store.access.RAMTransaction.setProperty(Unknown Source)\r\n\tat org.apache.derby.iapi.db.PropertyInfo.setDatabaseProperty(Unknown Source)\r\n\tat org.apache.derby.catalog.SystemProcedures.SYSCS_SET_DATABASE_PROPERTY(Unknown Source)\r\n\tat org.apache.derby.exe.ac80220011x0134xf51bx34daxffffbee07f83f.g0(Unknown Source)\r\n\tat sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)\r\n\tat sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:60)\r\n\tat sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:37)\r\n\tat java.lang.reflect.Method.invoke(Method.java:611)\r\n\tat org.apache.derby.impl.services.reflect.ReflectMethod.invoke(Unknown Source)\r\n\tat org.apache.derby.impl.sql.execute.CallStatementResultSet.open(Unknown Source)\r\n\tat org.apache.derby.impl.sql.GenericPreparedStatement.executeStmt(Unknown Source)\r\n\tat org.apache.derby.impl.sql.GenericPreparedStatement.execute(Unknown Source)\r\n\tat org.apache.derby.impl.jdbc.EmbedStatement.executeStatement(Unknown Source)\r\n\tat org.apache.derby.impl.jdbc.EmbedStatement.execute(Unknown Source)\r\n\tat org.apache.derby.impl.jdbc.EmbedStatement.execute(Unknown Source)\r\n\tat org.apache.derby.impl.tools.ij.ij.executeImmediate(Unknown Source)\r\n\tat org.apache.derby.impl.tools.ij.utilMain.doCatch(Unknown Source)\r\n\tat org.apache.derby.impl.tools.ij.utilMain.runScriptGuts(Unknown Source)\r\n\tat org.apache.derby.impl.tools.ij.utilMain.go(Unknown Source)\r\n\tat org.apache.derby.impl.tools.ij.Main.go(Unknown Source)\r\n\tat org.apache.derby.impl.tools.ij.Main.mainCore(Unknown Source)\r\n\tat org.apache.derby.impl.tools.ij.Main.main(Unknown Source)\r\n\tat org.apache.derby.tools.ij.main(Unknown Source)\r\n============= end nested exception, level (2) ===========\r\nCleanup action completed\r\n----------------------------------------------------------------\r\nThu Jan 19 00:35:33 PST 2012: Shutting down Derby engine","updateAuthor":{"self":"https://issues.apache.org/jira/rest/api/2/user?username=mikem","name":"mikem","emailAddress":"mikem_app at sbcglobal dot net","avatarUrls":{"48x48":"https://issues.apache.org/jira/secure/useravatar?avatarId=10452","24x24":"https://issues.apache.org/jira/secure/useravatar?size=small&avatarId=10452","16x16":"https://issues.apache.org/jira/secure/useravatar?size=xsmall&avatarId=10452","32x32":"https://issues.apache.org/jira/secure/useravatar?size=medium&avatarId=10452"},"displayName":"Mike Matrigali","active":true},"created":"2012-01-19T17:46:32.764+0000","updated":"2012-01-19T17:46:32.764+0000"},{"self":"https://issues.apache.org/jira/rest/api/2/issue/12538901/comment/13189262","id":"13189262","author":{"self":"https://issues.apache.org/jira/rest/api/2/user?username=mikem","name":"mikem","emailAddress":"mikem_app at sbcglobal dot net","avatarUrls":{"48x48":"https://issues.apache.org/jira/secure/useravatar?avatarId=10452","24x24":"https://issues.apache.org/jira/secure/useravatar?size=small&avatarId=10452","16x16":"https://issues.apache.org/jira/secure/useravatar?size=xsmall&avatarId=10452","32x32":"https://issues.apache.org/jira/secure/useravatar?size=medium&avatarId=10452"},"displayName":"Mike Matrigali","active":true},"body":"unfortunately it looks like the code will eventually call File.renameTo() which looks like it will swallow any OS generated errors, and hide\r\nthem, returning just false if it didn't work. \r\n\r\nMy take on the test is that a lot of renaming of service.properties to service.propertiesold is happening in this test.   And since the test passes\r\nalmost everywhere it is unlikely we are not closing the file correctly.  So some sort of timing or resource issue is happening in this environment.\r\nSome of the other new errors that seem to be cropping up new in this environment also have the feel of a temporary resource issue of some sort.\r\n\r\nDoes anyone see a problem with adding some retry logic to the rename, similar to what we do for other failed I/O operations?","updateAuthor":{"self":"https://issues.apache.org/jira/rest/api/2/user?username=mikem","name":"mikem","emailAddress":"mikem_app at sbcglobal dot net","avatarUrls":{"48x48":"https://issues.apache.org/jira/secure/useravatar?avatarId=10452","24x24":"https://issues.apache.org/jira/secure/useravatar?size=small&avatarId=10452","16x16":"https://issues.apache.org/jira/secure/useravatar?size=xsmall&avatarId=10452","32x32":"https://issues.apache.org/jira/secure/useravatar?size=medium&avatarId=10452"},"displayName":"Mike Matrigali","active":true},"created":"2012-01-19T18:25:34.762+0000","updated":"2012-01-19T18:25:34.762+0000"},{"self":"https://issues.apache.org/jira/rest/api/2/issue/12538901/comment/13191420","id":"13191420","author":{"self":"https://issues.apache.org/jira/rest/api/2/user?username=mikem","name":"mikem","emailAddress":"mikem_app at sbcglobal dot net","avatarUrls":{"48x48":"https://issues.apache.org/jira/secure/useravatar?avatarId=10452","24x24":"https://issues.apache.org/jira/secure/useravatar?size=small&avatarId=10452","16x16":"https://issues.apache.org/jira/secure/useravatar?size=xsmall&avatarId=10452","32x32":"https://issues.apache.org/jira/secure/useravatar?size=medium&avatarId=10452"},"displayName":"Mike Matrigali","active":true},"body":"proposed patch to retry on rename failures.  passed full test suite run on my machine.","updateAuthor":{"self":"https://issues.apache.org/jira/rest/api/2/user?username=mikem","name":"mikem","emailAddress":"mikem_app at sbcglobal dot net","avatarUrls":{"48x48":"https://issues.apache.org/jira/secure/useravatar?avatarId=10452","24x24":"https://issues.apache.org/jira/secure/useravatar?size=small&avatarId=10452","16x16":"https://issues.apache.org/jira/secure/useravatar?size=xsmall&avatarId=10452","32x32":"https://issues.apache.org/jira/secure/useravatar?size=medium&avatarId=10452"},"displayName":"Mike Matrigali","active":true},"created":"2012-01-23T20:25:04.452+0000","updated":"2012-01-23T20:25:04.452+0000"},{"self":"https://issues.apache.org/jira/rest/api/2/issue/12538901/comment/13194259","id":"13194259","author":{"self":"https://issues.apache.org/jira/rest/api/2/user?username=mikem","name":"mikem","emailAddress":"mikem_app at sbcglobal dot net","avatarUrls":{"48x48":"https://issues.apache.org/jira/secure/useravatar?avatarId=10452","24x24":"https://issues.apache.org/jira/secure/useravatar?size=small&avatarId=10452","16x16":"https://issues.apache.org/jira/secure/useravatar?size=xsmall&avatarId=10452","32x32":"https://issues.apache.org/jira/secure/useravatar?size=medium&avatarId=10452"},"displayName":"Mike Matrigali","active":true},"body":"backported retry on rename to 10.8 and 10.7.  Going to let changes sit for awhile to see if problem still shows up.  I have only seen error intermittently in nightly runs, have not been able to reproduce in my environment.  Definitely log new instances of problem in this JIRA.  Change can be backported further but will need to be mondified slightly to not\r\nuse the InterruptStatus class.","updateAuthor":{"self":"https://issues.apache.org/jira/rest/api/2/user?username=mikem","name":"mikem","emailAddress":"mikem_app at sbcglobal dot net","avatarUrls":{"48x48":"https://issues.apache.org/jira/secure/useravatar?avatarId=10452","24x24":"https://issues.apache.org/jira/secure/useravatar?size=small&avatarId=10452","16x16":"https://issues.apache.org/jira/secure/useravatar?size=xsmall&avatarId=10452","32x32":"https://issues.apache.org/jira/secure/useravatar?size=medium&avatarId=10452"},"displayName":"Mike Matrigali","active":true},"created":"2012-01-26T23:14:16.258+0000","updated":"2012-01-26T23:14:16.258+0000"},{"self":"https://issues.apache.org/jira/rest/api/2/issue/12538901/comment/13208091","id":"13208091","author":{"self":"https://issues.apache.org/jira/rest/api/2/user?username=mikem","name":"mikem","emailAddress":"mikem_app at sbcglobal dot net","avatarUrls":{"48x48":"https://issues.apache.org/jira/secure/useravatar?avatarId=10452","24x24":"https://issues.apache.org/jira/secure/useravatar?size=small&avatarId=10452","16x16":"https://issues.apache.org/jira/secure/useravatar?size=xsmall&avatarId=10452","32x32":"https://issues.apache.org/jira/secure/useravatar?size=medium&avatarId=10452"},"displayName":"Mike Matrigali","active":true},"body":"have not seen error since retry was added.  closing issue for now, reopen if seen again in 10.7, 10.8 or trunk  branches after date of the comment.  Change was \r\nsubmitted to trunk, 10.7 and 10.8 prior to this comment.\r\n","updateAuthor":{"self":"https://issues.apache.org/jira/rest/api/2/user?username=mikem","name":"mikem","emailAddress":"mikem_app at sbcglobal dot net","avatarUrls":{"48x48":"https://issues.apache.org/jira/secure/useravatar?avatarId=10452","24x24":"https://issues.apache.org/jira/secure/useravatar?size=small&avatarId=10452","16x16":"https://issues.apache.org/jira/secure/useravatar?size=xsmall&avatarId=10452","32x32":"https://issues.apache.org/jira/secure/useravatar?size=medium&avatarId=10452"},"displayName":"Mike Matrigali","active":true},"created":"2012-02-14T22:43:26.233+0000","updated":"2012-02-14T22:43:26.233+0000"}]},"votes":{"self":"https://issues.apache.org/jira/rest/api/2/issue/DERBY-5574/votes","votes":0,"hasVoted":false},"worklog":{"startAt":0,"maxResults":20,"total":0,"worklogs":[]},"customfield_12311820":"0|i06i9r:"}}