{"expand":"renderedFields,names,schema,transitions,operations,editmeta,changelog","id":"12372415","self":"https://issues.apache.org/jira/rest/api/latest/issue/12372415","key":"DERBY-2871","fields":{"issuetype":{"self":"https://issues.apache.org/jira/rest/api/2/issuetype/1","id":"1","description":"A problem which impairs or prevents the functions of the product.","iconUrl":"https://issues.apache.org/jira/images/icons/issuetypes/bug.png","name":"Bug","subtask":false},"timespent":null,"project":{"self":"https://issues.apache.org/jira/rest/api/2/project/10594","id":"10594","key":"DERBY","name":"Derby","avatarUrls":{"48x48":"https://issues.apache.org/jira/secure/projectavatar?pid=10594&avatarId=10122","24x24":"https://issues.apache.org/jira/secure/projectavatar?size=small&pid=10594&avatarId=10122","16x16":"https://issues.apache.org/jira/secure/projectavatar?size=xsmall&pid=10594&avatarId=10122","32x32":"https://issues.apache.org/jira/secure/projectavatar?size=medium&pid=10594&avatarId=10122"},"projectCategory":{"self":"https://issues.apache.org/jira/rest/api/2/projectCategory/10090","id":"10090","description":"DB related projects","name":"DB"}},"fixVersions":[{"self":"https://issues.apache.org/jira/rest/api/2/version/12313111","id":"12313111","description":"","name":"10.4.1.3","archived":false,"released":true,"releaseDate":"2008-04-24"}],"aggregatetimespent":null,"resolution":{"self":"https://issues.apache.org/jira/rest/api/2/resolution/1","id":"1","description":"A fix for this issue is checked into the tree and tested.","name":"Fixed"},"customfield_12310220":"2007-06-28 08:22:35.467","customfield_12312322":null,"customfield_12312323":null,"customfield_12310420":"23294","customfield_12310222":"3_*:*_1_*:*_24881750528_*|*_1_*:*_1_*:*_172655264_*|*_5_*:*_1_*:*_0","customfield_12312320":null,"customfield_12312321":null,"customfield_12312120":null,"customfield_12312121":null,"resolutiondate":"2008-04-11T08:40:40.335+0000","workratio":-1,"customfield_12312328":null,"customfield_12312329":null,"customfield_12312326":null,"customfield_12310300":null,"customfield_12312327":null,"customfield_12312324":null,"customfield_12312325":null,"lastViewed":null,"watches":{"self":"https://issues.apache.org/jira/rest/api/2/issue/DERBY-2871/watchers","watchCount":1,"isWatching":false},"created":"2007-06-26T09:07:14.543+0000","priority":{"self":"https://issues.apache.org/jira/rest/api/2/priority/4","iconUrl":"https://issues.apache.org/jira/images/icons/priorities/minor.png","name":"Minor","id":"4"},"labels":[],"customfield_12312333":null,"customfield_12312334":null,"customfield_12310310":"13.0","customfield_12312331":null,"customfield_12312332":null,"timeestimate":null,"aggregatetimeoriginalestimate":null,"versions":[{"self":"https://issues.apache.org/jira/rest/api/2/version/12312590","id":"12312590","description":"","name":"10.3.1.4","archived":false,"released":true,"releaseDate":"2007-08-10"}],"customfield_12311120":null,"customfield_12312330":null,"issuelinks":[{"id":"12316852","self":"https://issues.apache.org/jira/rest/api/2/issueLink/12316852","type":{"id":"12310010","name":"Incorporates","inward":"is part of","outward":"incorporates","self":"https://issues.apache.org/jira/rest/api/2/issueLinkType/12310010"},"outwardIssue":{"id":"12374134","key":"DERBY-2953","self":"https://issues.apache.org/jira/rest/api/2/issue/12374134","fields":{"summary":"Dump the information about rollbacks of the global transaction (introduced in DERBY-2220 and DERBY-2432) to derby.log","status":{"self":"https://issues.apache.org/jira/rest/api/2/status/3","description":"This issue is being actively worked on at the moment by the assignee.","iconUrl":"https://issues.apache.org/jira/images/icons/statuses/inprogress.png","name":"In Progress","id":"3","statusCategory":{"self":"https://issues.apache.org/jira/rest/api/2/statuscategory/4","id":4,"key":"indeterminate","colorName":"yellow","name":"In Progress"}},"priority":{"self":"https://issues.apache.org/jira/rest/api/2/priority/3","iconUrl":"https://issues.apache.org/jira/images/icons/priorities/major.png","name":"Major","id":"3"},"issuetype":{"self":"https://issues.apache.org/jira/rest/api/2/issuetype/4","id":"4","description":"An improvement or enhancement to an existing feature or task.","iconUrl":"https://issues.apache.org/jira/images/icons/issuetypes/improvement.png","name":"Improvement","subtask":false}}}}],"customfield_12312339":null,"assignee":{"self":"https://issues.apache.org/jira/rest/api/2/user?username=julo","name":"julo","emailAddress":"julo at stroffek dot cz","avatarUrls":{"48x48":"https://issues.apache.org/jira/secure/useravatar?avatarId=10452","24x24":"https://issues.apache.org/jira/secure/useravatar?size=small&avatarId=10452","16x16":"https://issues.apache.org/jira/secure/useravatar?size=xsmall&avatarId=10452","32x32":"https://issues.apache.org/jira/secure/useravatar?size=medium&avatarId=10452"},"displayName":"Julius Stroffek","active":true},"customfield_12312337":null,"customfield_12312338":null,"updated":"2011-01-21T18:17:04.820+0000","customfield_12312335":null,"customfield_12311720":null,"customfield_12312336":null,"status":{"self":"https://issues.apache.org/jira/rest/api/2/status/6","description":"The issue is considered finished, the resolution is correct. Issues which are closed can be reopened.","iconUrl":"https://issues.apache.org/jira/images/icons/statuses/closed.png","name":"Closed","id":"6","statusCategory":{"self":"https://issues.apache.org/jira/rest/api/2/statuscategory/3","id":3,"key":"done","colorName":"green","name":"Complete"}},"components":[{"self":"https://issues.apache.org/jira/rest/api/2/component/11407","id":"11407","name":"JDBC"}],"timeoriginalestimate":null,"description":"Method: org.apache.derbyTesting.functionTests.tests.jdbcapi.XATransactionTest\nSignature:\n%XAER_PROTO : Error executing a XAResource.commit(), server returned XAER_PROTO%\n\nAlso see: http://dbtg.thresher.com/derby/test/10.3.1.0_RC/jvm1.5/testing/testlog/hpux/548006-suitesAll_diff.txt","customfield_10010":null,"timetracking":{},"customfield_12312026":null,"customfield_12310200":null,"customfield_12312023":null,"customfield_12312024":null,"customfield_12312340":null,"aggregatetimeestimate":null,"customfield_12312022":null,"customfield_12312341":null,"customfield_12312220":null,"customfield_12310921":null,"customfield_12310920":"37056","summary":"XATransactionTest gets XaException: Error executing a XAResource.commit(), server returned XAER_PROTO.","creator":{"self":"https://issues.apache.org/jira/rest/api/2/user?username=scheur","name":"scheur","emailAddress":"Henri dot Vandescheur at Sun dot COM-disable","avatarUrls":{"48x48":"https://issues.apache.org/jira/secure/useravatar?avatarId=10452","24x24":"https://issues.apache.org/jira/secure/useravatar?size=small&avatarId=10452","16x16":"https://issues.apache.org/jira/secure/useravatar?size=xsmall&avatarId=10452","32x32":"https://issues.apache.org/jira/secure/useravatar?size=medium&avatarId=10452"},"displayName":"Henri van de Scheur","active":true},"subtasks":[],"customfield_12310090":null,"reporter":{"self":"https://issues.apache.org/jira/rest/api/2/user?username=scheur","name":"scheur","emailAddress":"Henri dot Vandescheur at Sun dot COM-disable","avatarUrls":{"48x48":"https://issues.apache.org/jira/secure/useravatar?avatarId=10452","24x24":"https://issues.apache.org/jira/secure/useravatar?size=small&avatarId=10452","16x16":"https://issues.apache.org/jira/secure/useravatar?size=xsmall&avatarId=10452","32x32":"https://issues.apache.org/jira/secure/useravatar?size=medium&avatarId=10452"},"displayName":"Henri van de Scheur","active":true},"customfield_12310291":null,"customfield_12310290":null,"aggregateprogress":{"progress":0,"total":0},"environment":"OS: HP-UX v1.11 i \nJDK: HP 1.5.0.03 ","customfield_12311020":null,"customfield_12310050":null,"duedate":null,"customfield_12310250":null,"progress":{"progress":0,"total":0},"comment":{"startAt":0,"maxResults":32,"total":32,"comments":[{"self":"https://issues.apache.org/jira/rest/api/2/issue/12372415/comment/12508767","id":"12508767","author":{"self":"https://issues.apache.org/jira/rest/api/2/user?username=julo","name":"julo","emailAddress":"julo at stroffek dot cz","avatarUrls":{"48x48":"https://issues.apache.org/jira/secure/useravatar?avatarId=10452","24x24":"https://issues.apache.org/jira/secure/useravatar?size=small&avatarId=10452","16x16":"https://issues.apache.org/jira/secure/useravatar?size=xsmall&avatarId=10452","32x32":"https://issues.apache.org/jira/secure/useravatar?size=medium&avatarId=10452"},"displayName":"Julius Stroffek","active":true},"body":"The exception is thrown probably on XATransaction:203 due to a to low transaction timeout value. I setted up the value just for 5 seconds which might not be enough to commit the transaction when garbage collection is invoked. I'll increase the value to 30s.","updateAuthor":{"self":"https://issues.apache.org/jira/rest/api/2/user?username=julo","name":"julo","emailAddress":"julo at stroffek dot cz","avatarUrls":{"48x48":"https://issues.apache.org/jira/secure/useravatar?avatarId=10452","24x24":"https://issues.apache.org/jira/secure/useravatar?size=small&avatarId=10452","16x16":"https://issues.apache.org/jira/secure/useravatar?size=xsmall&avatarId=10452","32x32":"https://issues.apache.org/jira/secure/useravatar?size=medium&avatarId=10452"},"displayName":"Julius Stroffek","active":true},"created":"2007-06-28T08:22:35.467+0000","updated":"2007-06-28T08:22:35.467+0000"},{"self":"https://issues.apache.org/jira/rest/api/2/issue/12372415/comment/12508794","id":"12508794","author":{"self":"https://issues.apache.org/jira/rest/api/2/user?username=julo","name":"julo","emailAddress":"julo at stroffek dot cz","avatarUrls":{"48x48":"https://issues.apache.org/jira/secure/useravatar?avatarId=10452","24x24":"https://issues.apache.org/jira/secure/useravatar?size=small&avatarId=10452","16x16":"https://issues.apache.org/jira/secure/useravatar?size=xsmall&avatarId=10452","32x32":"https://issues.apache.org/jira/secure/useravatar?size=medium&avatarId=10452"},"displayName":"Julius Stroffek","active":true},"body":"I changed the way of setting up the transaction timeout in the test.","updateAuthor":{"self":"https://issues.apache.org/jira/rest/api/2/user?username=julo","name":"julo","emailAddress":"julo at stroffek dot cz","avatarUrls":{"48x48":"https://issues.apache.org/jira/secure/useravatar?avatarId=10452","24x24":"https://issues.apache.org/jira/secure/useravatar?size=small&avatarId=10452","16x16":"https://issues.apache.org/jira/secure/useravatar?size=xsmall&avatarId=10452","32x32":"https://issues.apache.org/jira/secure/useravatar?size=medium&avatarId=10452"},"displayName":"Julius Stroffek","active":true},"created":"2007-06-28T11:23:38.825+0000","updated":"2007-06-28T11:23:38.825+0000"},{"self":"https://issues.apache.org/jira/rest/api/2/issue/12372415/comment/12508795","id":"12508795","author":{"self":"https://issues.apache.org/jira/rest/api/2/user?username=julo","name":"julo","emailAddress":"julo at stroffek dot cz","avatarUrls":{"48x48":"https://issues.apache.org/jira/secure/useravatar?avatarId=10452","24x24":"https://issues.apache.org/jira/secure/useravatar?size=small&avatarId=10452","16x16":"https://issues.apache.org/jira/secure/useravatar?size=xsmall&avatarId=10452","32x32":"https://issues.apache.org/jira/secure/useravatar?size=medium&avatarId=10452"},"displayName":"Julius Stroffek","active":true},"body":"When the transaction in the test is supposed to be committed the timeout is set to 60 seconds. If a transaction is supposed to be rolled back the timeout is set to 8 seconds only.\r\n\r\nI ran suites.All without failures on my box. No need to run derbyall since the change is just in a junit test.","updateAuthor":{"self":"https://issues.apache.org/jira/rest/api/2/user?username=julo","name":"julo","emailAddress":"julo at stroffek dot cz","avatarUrls":{"48x48":"https://issues.apache.org/jira/secure/useravatar?avatarId=10452","24x24":"https://issues.apache.org/jira/secure/useravatar?size=small&avatarId=10452","16x16":"https://issues.apache.org/jira/secure/useravatar?size=xsmall&avatarId=10452","32x32":"https://issues.apache.org/jira/secure/useravatar?size=medium&avatarId=10452"},"displayName":"Julius Stroffek","active":true},"created":"2007-06-28T11:28:25.381+0000","updated":"2007-06-28T11:28:25.381+0000"},{"self":"https://issues.apache.org/jira/rest/api/2/issue/12372415/comment/12509707","id":"12509707","author":{"self":"https://issues.apache.org/jira/rest/api/2/user?username=myrna","name":"myrna","emailAddress":"m dot v dot lunteren at gmail dot com","avatarUrls":{"48x48":"https://issues.apache.org/jira/secure/useravatar?avatarId=10452","24x24":"https://issues.apache.org/jira/secure/useravatar?size=small&avatarId=10452","16x16":"https://issues.apache.org/jira/secure/useravatar?size=xsmall&avatarId=10452","32x32":"https://issues.apache.org/jira/secure/useravatar?size=medium&avatarId=10452"},"displayName":"Myrna van Lunteren","active":true},"body":"I committed the patch on trunk with revision 552621.\r\nBut can someone verify this works on the platform it was reported on?\r\n","updateAuthor":{"self":"https://issues.apache.org/jira/rest/api/2/user?username=myrna","name":"myrna","emailAddress":"m dot v dot lunteren at gmail dot com","avatarUrls":{"48x48":"https://issues.apache.org/jira/secure/useravatar?avatarId=10452","24x24":"https://issues.apache.org/jira/secure/useravatar?size=small&avatarId=10452","16x16":"https://issues.apache.org/jira/secure/useravatar?size=xsmall&avatarId=10452","32x32":"https://issues.apache.org/jira/secure/useravatar?size=medium&avatarId=10452"},"displayName":"Myrna van Lunteren","active":true},"created":"2007-07-02T23:04:11.484+0000","updated":"2007-07-02T23:04:29.394+0000"},{"self":"https://issues.apache.org/jira/rest/api/2/issue/12372415/comment/12509881","id":"12509881","author":{"self":"https://issues.apache.org/jira/rest/api/2/user?username=vemund","name":"vemund","emailAddress":"vemund at sun dot com","avatarUrls":{"48x48":"https://issues.apache.org/jira/secure/useravatar?avatarId=10452","24x24":"https://issues.apache.org/jira/secure/useravatar?size=small&avatarId=10452","16x16":"https://issues.apache.org/jira/secure/useravatar?size=xsmall&avatarId=10452","32x32":"https://issues.apache.org/jira/secure/useravatar?size=medium&avatarId=10452"},"displayName":"Vemund Østgaard","active":true},"body":"I ran Suites.All on HP with my checked out version of trunk (revision 552770) to verify the fix.\r\n\r\nThe same test failed, but this time with a lock timeout instead: \r\n\r\n1) testXATransactionTimeout(org.apache.derbyTesting.functionTests.tests.jdbcapi.XATransactionTest)java.sql.SQLException: A lock could not be obtained within\r\nthe time requested\r\n        at org.apache.derby.client.am.SQLExceptionFactory.getSQLException(Unknown Source)\r\n        at org.apache.derby.client.am.SqlException.getSQLException(Unknown Source)\r\n        at org.apache.derby.client.am.Statement.executeQuery(Unknown Source)\r\n        at org.apache.derbyTesting.functionTests.tests.jdbcapi.XATransactionTest.testXATransactionTimeout(XATransactionTest.java:247)\r\n        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)\r\n        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)\r\n        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)\r\n        at org.apache.derbyTesting.junit.BaseTestCase.runBare(BaseTestCase.java:95)\r\n        at junit.extensions.TestDecorator.basicRun(TestDecorator.java:24)\r\n        at junit.extensions.TestSetup$1.protect(TestSetup.java:21)\r\n        at junit.extensions.TestSetup.run(TestSetup.java:25)\r\n        at org.apache.derbyTesting.junit.BaseTestSetup.run(BaseTestSetup.java:57)\r\n        at junit.extensions.TestDecorator.basicRun(TestDecorator.java:24)\r\n        at junit.extensions.TestSetup$1.protect(TestSetup.java:21)\r\n        at junit.extensions.TestSetup.run(TestSetup.java:25)\r\n        at junit.extensions.TestDecorator.basicRun(TestDecorator.java:24)\r\n        at junit.extensions.TestSetup$1.protect(TestSetup.java:21)\r\n        at junit.extensions.TestSetup.run(TestSetup.java:25)\r\n        at org.apache.derbyTesting.junit.BaseTestSetup.run(BaseTestSetup.java:57)\r\nCaused by: org.apache.derby.client.am.SqlException: A lock could not be obtained within the time requested\r\n        at org.apache.derby.client.am.Statement.completeSqlca(Unknown Source)\r\n        at org.apache.derby.client.net.NetStatementReply.parseOpenQueryError(Unknown Source)\r\n        at org.apache.derby.client.net.NetStatementReply.parseOPNQRYreply(Unknown Source)\r\n        at org.apache.derby.client.net.NetStatementReply.readOpenQuery(Unknown Source)\r\n        at org.apache.derby.client.net.StatementReply.readOpenQuery(Unknown Source)\r\n        at org.apache.derby.client.net.NetStatement.readOpenQuery_(Unknown Source)\r\n        at org.apache.derby.client.am.Statement.readOpenQuery(Unknown Source)\r\n        at org.apache.derby.client.am.Statement.flowExecute(Unknown Source)\r\n        at org.apache.derby.client.am.Statement.executeQueryX(Unknown Source)\r\n        ... 40 more\r\n","updateAuthor":{"self":"https://issues.apache.org/jira/rest/api/2/user?username=vemund","name":"vemund","emailAddress":"vemund at sun dot com","avatarUrls":{"48x48":"https://issues.apache.org/jira/secure/useravatar?avatarId=10452","24x24":"https://issues.apache.org/jira/secure/useravatar?size=small&avatarId=10452","16x16":"https://issues.apache.org/jira/secure/useravatar?size=xsmall&avatarId=10452","32x32":"https://issues.apache.org/jira/secure/useravatar?size=medium&avatarId=10452"},"displayName":"Vemund Østgaard","active":true},"created":"2007-07-03T14:08:59.589+0000","updated":"2007-07-03T14:08:59.589+0000"},{"self":"https://issues.apache.org/jira/rest/api/2/issue/12372415/comment/12510529","id":"12510529","author":{"self":"https://issues.apache.org/jira/rest/api/2/user?username=myrna","name":"myrna","emailAddress":"m dot v dot lunteren at gmail dot com","avatarUrls":{"48x48":"https://issues.apache.org/jira/secure/useravatar?avatarId=10452","24x24":"https://issues.apache.org/jira/secure/useravatar?size=small&avatarId=10452","16x16":"https://issues.apache.org/jira/secure/useravatar?size=xsmall&avatarId=10452","32x32":"https://issues.apache.org/jira/secure/useravatar?size=medium&avatarId=10452"},"displayName":"Myrna van Lunteren","active":true},"body":"unchecking patch available, I had checked in the change but it caused an intermittent failure in the test. \r\nAlso unmarking fix  for 10.3.","updateAuthor":{"self":"https://issues.apache.org/jira/rest/api/2/user?username=myrna","name":"myrna","emailAddress":"m dot v dot lunteren at gmail dot com","avatarUrls":{"48x48":"https://issues.apache.org/jira/secure/useravatar?avatarId=10452","24x24":"https://issues.apache.org/jira/secure/useravatar?size=small&avatarId=10452","16x16":"https://issues.apache.org/jira/secure/useravatar?size=xsmall&avatarId=10452","32x32":"https://issues.apache.org/jira/secure/useravatar?size=medium&avatarId=10452"},"displayName":"Myrna van Lunteren","active":true},"created":"2007-07-05T23:57:05.784+0000","updated":"2007-07-05T23:57:05.784+0000"},{"self":"https://issues.apache.org/jira/rest/api/2/issue/12372415/comment/12513901","id":"12513901","author":{"self":"https://issues.apache.org/jira/rest/api/2/user?username=julo","name":"julo","emailAddress":"julo at stroffek dot cz","avatarUrls":{"48x48":"https://issues.apache.org/jira/secure/useravatar?avatarId=10452","24x24":"https://issues.apache.org/jira/secure/useravatar?size=small&avatarId=10452","16x16":"https://issues.apache.org/jira/secure/useravatar?size=xsmall&avatarId=10452","32x32":"https://issues.apache.org/jira/secure/useravatar?size=medium&avatarId=10452"},"displayName":"Julius Stroffek","active":true},"body":"I have an access to the machine on which the test failed. However, I am not able to reproduce the failure. I will continue trying to find out what is going on.","updateAuthor":{"self":"https://issues.apache.org/jira/rest/api/2/user?username=julo","name":"julo","emailAddress":"julo at stroffek dot cz","avatarUrls":{"48x48":"https://issues.apache.org/jira/secure/useravatar?avatarId=10452","24x24":"https://issues.apache.org/jira/secure/useravatar?size=small&avatarId=10452","16x16":"https://issues.apache.org/jira/secure/useravatar?size=xsmall&avatarId=10452","32x32":"https://issues.apache.org/jira/secure/useravatar?size=medium&avatarId=10452"},"displayName":"Julius Stroffek","active":true},"created":"2007-07-19T14:06:13.091+0000","updated":"2007-07-19T14:06:13.091+0000"},{"self":"https://issues.apache.org/jira/rest/api/2/issue/12372415/comment/12518492","id":"12518492","author":{"self":"https://issues.apache.org/jira/rest/api/2/user?username=julo","name":"julo","emailAddress":"julo at stroffek dot cz","avatarUrls":{"48x48":"https://issues.apache.org/jira/secure/useravatar?avatarId=10452","24x24":"https://issues.apache.org/jira/secure/useravatar?size=small&avatarId=10452","16x16":"https://issues.apache.org/jira/secure/useravatar?size=xsmall&avatarId=10452","32x32":"https://issues.apache.org/jira/secure/useravatar?size=medium&avatarId=10452"},"displayName":"Julius Stroffek","active":true},"body":"I rewrote the test that it will not close the connections and they will not be garbage collected neither since I call the XAConnection.close method on every connection at the end of the test.\r\n\r\nI ran all the tests (suites.All and derbyall) without failures on my box for 'd2871-test' patch also with a patch for DERBY-2953 without any failures. I tried to run those test also on a HP-UX box where the test was originally failing. The rewritten test always fails with the message \r\n\r\n---\r\n1) testXATransactionTimeout(org.apache.derbyTesting.functionTests.tests.jdbcapi.XATransactionTest)java.sql.SQLException: A communications e\r\nrror has been detected: Broken pipe (errno:32).\r\n        at org.apache.derby.client.am.SQLExceptionFactory.getSQLException(SQLExceptionFactory.java:46)\r\n        at org.apache.derby.client.am.SqlException.getSQLException(SqlException.java:362)\r\n        at org.apache.derby.client.ClientPooledConnection.<init>(ClientPooledConnection.java:115)\r\n        at org.apache.derby.client.ClientXAConnection.<init>(ClientXAConnection.java:48)\r\n        at org.apache.derby.client.net.ClientJDBCObjectFactoryImpl.newClientXAConnection(ClientJDBCObjectFactoryImpl.java:76)\r\n        at org.apache.derby.jdbc.ClientXADataSource.getXAConnectionX(ClientXADataSource.java:88)\r\n        at org.apache.derby.jdbc.ClientXADataSource.getXAConnection(ClientXADataSource.java:72)\r\n        at org.apache.derby.jdbc.ClientXADataSource.getXAConnection(ClientXADataSource.java:65)\r\n        at org.apache.derbyTesting.functionTests.tests.jdbcapi.XATransactionTest.testXATransactionTimeout(XATransactionTest.java:188)\r\n        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)\r\n        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)\r\n        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)\r\n        at org.apache.derbyTesting.junit.BaseTestCase.runBare(BaseTestCase.java:95)\r\n        at junit.extensions.TestDecorator.basicRun(TestDecorator.java:24)\r\n        at junit.extensions.TestSetup$1.protect(TestSetup.java:21)\r\n        at junit.extensions.TestSetup.run(TestSetup.java:25)\r\n        at org.apache.derbyTesting.junit.BaseTestSetup.run(BaseTestSetup.java:57)\r\n        at junit.extensions.TestDecorator.basicRun(TestDecorator.java:24)\r\n        at junit.extensions.TestSetup$1.protect(TestSetup.java:21)\r\n        at junit.extensions.TestSetup.run(TestSetup.java:25)\r\n        at junit.extensions.TestDecorator.basicRun(TestDecorator.java:24)\r\n        at junit.extensions.TestSetup$1.protect(TestSetup.java:21)\r\n        at junit.extensions.TestSetup.run(TestSetup.java:25)\r\n        at org.apache.derbyTesting.junit.BaseTestSetup.run(BaseTestSetup.java:57)\r\nCaused by: org.apache.derby.client.am.DisconnectException: A communications error has been detected: Broken pipe (errno:32).\r\n        at org.apache.derby.client.net.NetAgent.throwCommunicationsFailure(NetAgent.java:413)\r\n        at org.apache.derby.client.net.NetAgent.sendRequest(NetAgent.java:387)\r\n        at org.apache.derby.client.net.NetAgent.flush_(NetAgent.java:265)\r\n        at org.apache.derby.client.am.Agent.flowOutsideUOW(Agent.java:196)\r\n        at org.apache.derby.client.net.NetConnection.flowServerAttributesAndKeyExchange(NetConnection.java:773)\r\n        at org.apache.derby.client.net.NetConnection.flowUSRIDPWDconnect(NetConnection.java:617)\r\n        at org.apache.derby.client.net.NetConnection.flowConnect(NetConnection.java:435)\r\n        at org.apache.derby.client.net.NetConnection.initialize(NetConnection.java:296)\r\n        at org.apache.derby.client.net.NetConnection.<init>(NetConnection.java:280)\r\n        at org.apache.derby.client.net.ClientJDBCObjectFactoryImpl.newNetConnection(ClientJDBCObjectFactoryImpl.java:264)\r\n        at org.apache.derby.client.net.NetXAConnection.createNetConnection(NetXAConnection.java:269)\r\n        at org.apache.derby.client.net.NetXAConnection.<init>(NetXAConnection.java:73)\r\n        at org.apache.derby.client.ClientPooledConnection.getNetXAConnection(ClientPooledConnection.java:331)\r\n        at org.apache.derby.client.ClientPooledConnection.<init>(ClientPooledConnection.java:108)\r\n        ... 44 more\r\nCaused by: java.net.SocketException: Broken pipe (errno:32)\r\n        at java.net.SocketOutputStream.socketWrite0(Native Method)\r\n        at java.net.SocketOutputStream.socketWrite(SocketOutputStream.java:97)\r\n        at java.net.SocketOutputStream.write(SocketOutputStream.java:141)\r\n        at org.apache.derby.client.net.Request.sendBytes(Request.java:1388)\r\n        at org.apache.derby.client.net.Request.flush(Request.java:1382)\r\n        at org.apache.derby.client.net.NetAgent.sendRequest(NetAgent.java:385)\r\n        ... 56 more\r\n---\r\n\r\n\r\nI explored a problem a bit and discovered that the problem occurs due to the limit of the number of open files and I have created a simple code to verify this...\r\n\r\n        int count = 1000;\r\n        XAConnection xaConn[] = new XAConnection[count];\r\n\r\n        try {\r\n            // start-up the server\r\n            NetworkServerControl server = new NetworkServerControl();\r\n            server.start (null);\r\n\r\n            for (int i=0; i < count; i++) {\r\n                System.out.print(\"Creating connection number \" + i + \"...\");\r\n                xaConn[i] = createXAConnection(connString, \"\", \"\");\r\n                System.out.println(\"Ok.\");\r\n            }\r\n\r\n            for (int i=0; i < count; i++) {\r\n                xaConn[i].close();\r\n            }\r\n        } catch (Exception ex) {\r\n            ex.printStackTrace();\r\n        }\r\n\r\nwhich will throw an exception after creating a connection number 391\r\n\r\norg.apache.derby.client.am.DisconnectException: java.net.SocketException : Error connecting to server localhost on port 1527 with message File table overflow (errno:23).\r\n        at org.apache.derby.client.net.NetAgent.<init>(NetAgent.java:129)\r\n        at org.apache.derby.client.net.NetConnection.newAgent_(NetConnection.java:1086)\r\n        at org.apache.derby.client.am.Connection.initConnection(Connection.java:218)\r\n        at org.apache.derby.client.am.Connection.<init>(Connection.java:169)\r\n        at org.apache.derby.client.net.NetConnection.<init>(NetConnection.java:278)\r\n        at org.apache.derby.client.net.ClientJDBCObjectFactoryImpl.newNetConnection(ClientJDBCObjectFactoryImpl.java:264)\r\n        at org.apache.derby.client.net.NetXAConnection.createNetConnection(NetXAConnection.java:269)\r\n        at org.apache.derby.client.net.NetXAConnection.<init>(NetXAConnection.java:73)\r\n        at org.apache.derby.client.ClientPooledConnection.getNetXAConnection(ClientPooledConnection.java:331)\r\n        at org.apache.derby.client.ClientPooledConnection.<init>(ClientPooledConnection.java:108)\r\n        ... 8 more\r\nCaused by: java.net.SocketException: File table overflow (errno:23)\r\n        at java.net.Socket.createImpl(Socket.java:397)\r\n        at java.net.Socket.<init>(Socket.java:359)\r\n        at java.net.Socket.<init>(Socket.java:178)\r\n        at javax.net.DefaultSocketFactory.createSocket(SocketFactory.java:196)\r\n        at org.apache.derby.client.net.OpenSocketAction.run(OpenSocketAction.java:62)\r\n        at java.security.AccessController.doPrivileged(Native Method)\r\n        at org.apache.derby.client.net.NetAgent.<init>(NetAgent.java:127)\r\n        ... 17 more\r\n------","updateAuthor":{"self":"https://issues.apache.org/jira/rest/api/2/user?username=julo","name":"julo","emailAddress":"julo at stroffek dot cz","avatarUrls":{"48x48":"https://issues.apache.org/jira/secure/useravatar?avatarId=10452","24x24":"https://issues.apache.org/jira/secure/useravatar?size=small&avatarId=10452","16x16":"https://issues.apache.org/jira/secure/useravatar?size=xsmall&avatarId=10452","32x32":"https://issues.apache.org/jira/secure/useravatar?size=medium&avatarId=10452"},"displayName":"Julius Stroffek","active":true},"created":"2007-08-08T16:24:52.095+0000","updated":"2007-08-08T16:24:52.095+0000"},{"self":"https://issues.apache.org/jira/rest/api/2/issue/12372415/comment/12518495","id":"12518495","author":{"self":"https://issues.apache.org/jira/rest/api/2/user?username=julo","name":"julo","emailAddress":"julo at stroffek dot cz","avatarUrls":{"48x48":"https://issues.apache.org/jira/secure/useravatar?avatarId=10452","24x24":"https://issues.apache.org/jira/secure/useravatar?size=small&avatarId=10452","16x16":"https://issues.apache.org/jira/secure/useravatar?size=xsmall&avatarId=10452","32x32":"https://issues.apache.org/jira/secure/useravatar?size=medium&avatarId=10452"},"displayName":"Julius Stroffek","active":true},"body":"I will rewrite a test in a way that will use much less connections created in parallel.\r\n\r\nLesson learned: It was not a good idea to use 1000 connections in a test for a small embedded database as derby is. There might be some restrictions on older or embedded systems.\r\n\r\nHowever, I am not quite sure if this will fix the issue for sure. I'll try to test the result as much as possible.","updateAuthor":{"self":"https://issues.apache.org/jira/rest/api/2/user?username=julo","name":"julo","emailAddress":"julo at stroffek dot cz","avatarUrls":{"48x48":"https://issues.apache.org/jira/secure/useravatar?avatarId=10452","24x24":"https://issues.apache.org/jira/secure/useravatar?size=small&avatarId=10452","16x16":"https://issues.apache.org/jira/secure/useravatar?size=xsmall&avatarId=10452","32x32":"https://issues.apache.org/jira/secure/useravatar?size=medium&avatarId=10452"},"displayName":"Julius Stroffek","active":true},"created":"2007-08-08T16:30:59.621+0000","updated":"2007-08-08T16:30:59.621+0000"},{"self":"https://issues.apache.org/jira/rest/api/2/issue/12372415/comment/12556551","id":"12556551","author":{"self":"https://issues.apache.org/jira/rest/api/2/user?username=julo","name":"julo","emailAddress":"julo at stroffek dot cz","avatarUrls":{"48x48":"https://issues.apache.org/jira/secure/useravatar?avatarId=10452","24x24":"https://issues.apache.org/jira/secure/useravatar?size=small&avatarId=10452","16x16":"https://issues.apache.org/jira/secure/useravatar?size=xsmall&avatarId=10452","32x32":"https://issues.apache.org/jira/secure/useravatar?size=medium&avatarId=10452"},"displayName":"Julius Stroffek","active":true},"body":"This is the patch fixing all the possible issues with the test I found. It merges also a change made for DERBY-2953.\r\n\r\nI ran the tests without failures. I am planning to run the tests also on the box where the test was originally failing. More detailed description of changes will follow afterwards.","updateAuthor":{"self":"https://issues.apache.org/jira/rest/api/2/user?username=julo","name":"julo","emailAddress":"julo at stroffek dot cz","avatarUrls":{"48x48":"https://issues.apache.org/jira/secure/useravatar?avatarId=10452","24x24":"https://issues.apache.org/jira/secure/useravatar?size=small&avatarId=10452","16x16":"https://issues.apache.org/jira/secure/useravatar?size=xsmall&avatarId=10452","32x32":"https://issues.apache.org/jira/secure/useravatar?size=medium&avatarId=10452"},"displayName":"Julius Stroffek","active":true},"created":"2008-01-07T12:00:46.916+0000","updated":"2008-01-07T12:00:46.916+0000"},{"self":"https://issues.apache.org/jira/rest/api/2/issue/12372415/comment/12557311","id":"12557311","author":{"self":"https://issues.apache.org/jira/rest/api/2/user?username=julo","name":"julo","emailAddress":"julo at stroffek dot cz","avatarUrls":{"48x48":"https://issues.apache.org/jira/secure/useravatar?avatarId=10452","24x24":"https://issues.apache.org/jira/secure/useravatar?size=small&avatarId=10452","16x16":"https://issues.apache.org/jira/secure/useravatar?size=xsmall&avatarId=10452","32x32":"https://issues.apache.org/jira/secure/useravatar?size=medium&avatarId=10452"},"displayName":"Julius Stroffek","active":true},"body":"I have tested the patch on the machine where the tests were originally failing and it went well without failures.","updateAuthor":{"self":"https://issues.apache.org/jira/rest/api/2/user?username=julo","name":"julo","emailAddress":"julo at stroffek dot cz","avatarUrls":{"48x48":"https://issues.apache.org/jira/secure/useravatar?avatarId=10452","24x24":"https://issues.apache.org/jira/secure/useravatar?size=small&avatarId=10452","16x16":"https://issues.apache.org/jira/secure/useravatar?size=xsmall&avatarId=10452","32x32":"https://issues.apache.org/jira/secure/useravatar?size=medium&avatarId=10452"},"displayName":"Julius Stroffek","active":true},"created":"2008-01-09T16:38:38.435+0000","updated":"2008-01-09T16:38:38.435+0000"},{"self":"https://issues.apache.org/jira/rest/api/2/issue/12372415/comment/12557350","id":"12557350","author":{"self":"https://issues.apache.org/jira/rest/api/2/user?username=julo","name":"julo","emailAddress":"julo at stroffek dot cz","avatarUrls":{"48x48":"https://issues.apache.org/jira/secure/useravatar?avatarId=10452","24x24":"https://issues.apache.org/jira/secure/useravatar?size=small&avatarId=10452","16x16":"https://issues.apache.org/jira/secure/useravatar?size=xsmall&avatarId=10452","32x32":"https://issues.apache.org/jira/secure/useravatar?size=medium&avatarId=10452"},"displayName":"Julius Stroffek","active":true},"body":"Changes in xa transaction timeout:\r\n* added a code to print a text message to a log file when the global transaction will get rolled back.\r\n* joined a code performing a rollback of the global transaction on both embedded and network drivers. The transaction is now atomically (XATransactionState lock is obtained only once) disassociated from the resource and rolled back. The common code is placed in XATransactionState object.\r\n* a reference to the ResourceAdapter instance was necessary to be present in DRDAXAProtocol/XADatabase and it is captured from EmbedXADataSource during a creation of a connection in XADatabase instance.\r\n\r\nChanges in XATransactionTest:\r\n* The number of connections created was reduced from 1000 to 66.\r\n* All the references to connections are kept in an array so that no optimization will garbage collect them before the transaction will get rolled back by the proper code tested. All the connections are closed manually at the end of the test.\r\n* The long running statement was rewritten to use system tables thus the test will no longer need an appropriate number of records in a test table (thus less connections might be created).\r\n* derby.locks.waitTimeout and derby.locks.deadlockTimeout are being stored in test setup and changed to high enough values and changed back at tearDown. jdbcapi/SetTransactionIsolationTest changes both of these to 3 without restoring them back and this was causing issues with a test.\r\n* a list of global transactions in progress is dumped when the test fails in case there are pending transactions that were supposed to be rolled back\r\n\r\nDyre (response to the comment at DERBY-2953):\r\nI am also not quite clear about the policy when to write a javadoc comment and when not. I think I have written javadoc comments for all new methods/classes except when the comment is present in the superclass or method of the superclass and there is nothing new to be written in the implementation. I can copy the comment from the superclass but I do not see a benefit of doing this.\r\n\r\nThanks for reviewing the patch.","updateAuthor":{"self":"https://issues.apache.org/jira/rest/api/2/user?username=julo","name":"julo","emailAddress":"julo at stroffek dot cz","avatarUrls":{"48x48":"https://issues.apache.org/jira/secure/useravatar?avatarId=10452","24x24":"https://issues.apache.org/jira/secure/useravatar?size=small&avatarId=10452","16x16":"https://issues.apache.org/jira/secure/useravatar?size=xsmall&avatarId=10452","32x32":"https://issues.apache.org/jira/secure/useravatar?size=medium&avatarId=10452"},"displayName":"Julius Stroffek","active":true},"created":"2008-01-09T17:39:02.942+0000","updated":"2008-01-09T17:39:02.942+0000"},{"self":"https://issues.apache.org/jira/rest/api/2/issue/12372415/comment/12557352","id":"12557352","author":{"self":"https://issues.apache.org/jira/rest/api/2/user?username=julo","name":"julo","emailAddress":"julo at stroffek dot cz","avatarUrls":{"48x48":"https://issues.apache.org/jira/secure/useravatar?avatarId=10452","24x24":"https://issues.apache.org/jira/secure/useravatar?size=small&avatarId=10452","16x16":"https://issues.apache.org/jira/secure/useravatar?size=xsmall&avatarId=10452","32x32":"https://issues.apache.org/jira/secure/useravatar?size=medium&avatarId=10452"},"displayName":"Julius Stroffek","active":true},"body":"suites.All and derbyall ran without failures.","updateAuthor":{"self":"https://issues.apache.org/jira/rest/api/2/user?username=julo","name":"julo","emailAddress":"julo at stroffek dot cz","avatarUrls":{"48x48":"https://issues.apache.org/jira/secure/useravatar?avatarId=10452","24x24":"https://issues.apache.org/jira/secure/useravatar?size=small&avatarId=10452","16x16":"https://issues.apache.org/jira/secure/useravatar?size=xsmall&avatarId=10452","32x32":"https://issues.apache.org/jira/secure/useravatar?size=medium&avatarId=10452"},"displayName":"Julius Stroffek","active":true},"created":"2008-01-09T17:40:21.934+0000","updated":"2008-01-09T17:40:21.934+0000"},{"self":"https://issues.apache.org/jira/rest/api/2/issue/12372415/comment/12564902","id":"12564902","author":{"self":"https://issues.apache.org/jira/rest/api/2/user?username=kmarsden","name":"kmarsden","emailAddress":"kmarsdenderby at sbcglobal dot net","avatarUrls":{"48x48":"https://issues.apache.org/jira/secure/useravatar?avatarId=10452","24x24":"https://issues.apache.org/jira/secure/useravatar?size=small&avatarId=10452","16x16":"https://issues.apache.org/jira/secure/useravatar?size=xsmall&avatarId=10452","32x32":"https://issues.apache.org/jira/secure/useravatar?size=medium&avatarId=10452"},"displayName":"Kathey Marsden","active":true},"body":"The patch didn't apply for me. I saw conflicts in messages.xml and MessageId.java.  Could you post an updated patch and I'll try to look quickly before it gets out of date?\r\n\r\n\r\n","updateAuthor":{"self":"https://issues.apache.org/jira/rest/api/2/user?username=kmarsden","name":"kmarsden","emailAddress":"kmarsdenderby at sbcglobal dot net","avatarUrls":{"48x48":"https://issues.apache.org/jira/secure/useravatar?avatarId=10452","24x24":"https://issues.apache.org/jira/secure/useravatar?size=small&avatarId=10452","16x16":"https://issues.apache.org/jira/secure/useravatar?size=xsmall&avatarId=10452","32x32":"https://issues.apache.org/jira/secure/useravatar?size=medium&avatarId=10452"},"displayName":"Kathey Marsden","active":true},"created":"2008-02-01T19:39:04.051+0000","updated":"2008-02-01T19:39:04.051+0000"},{"self":"https://issues.apache.org/jira/rest/api/2/issue/12372415/comment/12564916","id":"12564916","author":{"self":"https://issues.apache.org/jira/rest/api/2/user?username=myrna","name":"myrna","emailAddress":"m dot v dot lunteren at gmail dot com","avatarUrls":{"48x48":"https://issues.apache.org/jira/secure/useravatar?avatarId=10452","24x24":"https://issues.apache.org/jira/secure/useravatar?size=small&avatarId=10452","16x16":"https://issues.apache.org/jira/secure/useravatar?size=xsmall&avatarId=10452","32x32":"https://issues.apache.org/jira/secure/useravatar?size=medium&avatarId=10452"},"displayName":"Myrna van Lunteren","active":true},"body":"I svn updated to the earlier revision, then could apply the patch fine, and svn update seems to have merged correctly too. \r\nBut I'm out of my depth on this...\r\nAttaching an updated version so someone else can have a look too.\r\n\r\nquestions/comments I do have:\r\n- as was previously observed, I think javadoc would be good for every new method. For ones that overwrite methods from a higher level you can use the @see javadoc tag\r\n- the new test fixtures uses System.err.println. I think that's a 'not done', you need to change that into a fail(...)\r\n- in the test' Setup and tearDown methods, you may be able to take advantage of the new BaseJDBCTestCase.prepareCall. Or, better, can't you use the DatabasePropertyTestSetup?\r\n","updateAuthor":{"self":"https://issues.apache.org/jira/rest/api/2/user?username=myrna","name":"myrna","emailAddress":"m dot v dot lunteren at gmail dot com","avatarUrls":{"48x48":"https://issues.apache.org/jira/secure/useravatar?avatarId=10452","24x24":"https://issues.apache.org/jira/secure/useravatar?size=small&avatarId=10452","16x16":"https://issues.apache.org/jira/secure/useravatar?size=xsmall&avatarId=10452","32x32":"https://issues.apache.org/jira/secure/useravatar?size=medium&avatarId=10452"},"displayName":"Myrna van Lunteren","active":true},"created":"2008-02-01T20:09:47.645+0000","updated":"2008-02-01T20:09:47.645+0000"},{"self":"https://issues.apache.org/jira/rest/api/2/issue/12372415/comment/12564917","id":"12564917","author":{"self":"https://issues.apache.org/jira/rest/api/2/user?username=myrna","name":"myrna","emailAddress":"m dot v dot lunteren at gmail dot com","avatarUrls":{"48x48":"https://issues.apache.org/jira/secure/useravatar?avatarId=10452","24x24":"https://issues.apache.org/jira/secure/useravatar?size=small&avatarId=10452","16x16":"https://issues.apache.org/jira/secure/useravatar?size=xsmall&avatarId=10452","32x32":"https://issues.apache.org/jira/secure/useravatar?size=medium&avatarId=10452"},"displayName":"Myrna van Lunteren","active":true},"body":"too bad that we didn't get this in sooner, looks like we missed a translation effort. \r\n","updateAuthor":{"self":"https://issues.apache.org/jira/rest/api/2/user?username=myrna","name":"myrna","emailAddress":"m dot v dot lunteren at gmail dot com","avatarUrls":{"48x48":"https://issues.apache.org/jira/secure/useravatar?avatarId=10452","24x24":"https://issues.apache.org/jira/secure/useravatar?size=small&avatarId=10452","16x16":"https://issues.apache.org/jira/secure/useravatar?size=xsmall&avatarId=10452","32x32":"https://issues.apache.org/jira/secure/useravatar?size=medium&avatarId=10452"},"displayName":"Myrna van Lunteren","active":true},"created":"2008-02-01T20:13:27.039+0000","updated":"2008-02-01T20:13:27.039+0000"},{"self":"https://issues.apache.org/jira/rest/api/2/issue/12372415/comment/12564967","id":"12564967","author":{"self":"https://issues.apache.org/jira/rest/api/2/user?username=kmarsden","name":"kmarsden","emailAddress":"kmarsdenderby at sbcglobal dot net","avatarUrls":{"48x48":"https://issues.apache.org/jira/secure/useravatar?avatarId=10452","24x24":"https://issues.apache.org/jira/secure/useravatar?size=small&avatarId=10452","16x16":"https://issues.apache.org/jira/secure/useravatar?size=xsmall&avatarId=10452","32x32":"https://issues.apache.org/jira/secure/useravatar?size=medium&avatarId=10452"},"displayName":"Kathey Marsden","active":true},"body":"Thank you for looking at this issue.  I got a bit confused about which changes were part of this issue and which were part of DERBY-2953.  Are the code changes necessary for the test to pass with its changes or were the two issues' patches just combined for convenience? \r\n\r\nOn the code changes I got a bit confused with the XATransationState.isFinished instance variable changes.  isFinished is documented as:\r\n/** Has this transaction been finished (committed\r\n      * or rolled back)? */\r\nBut the makes isFinshed = true with the XATransactionState constructor, which I didn't quite understand. The transaction hasn't been committed or rolled back at that point. It looks like isFinished is only set to  false in setTransactionTimeout which doesn't seem quite right.\r\n\r\n\r\nOn the test in addition to Myrna's comments,  do we lose anything by dropping from 1000 connections to 66?  \r\nThe javadoc still says 1000 connections. \r\n\r\n\r\n\r\n","updateAuthor":{"self":"https://issues.apache.org/jira/rest/api/2/user?username=kmarsden","name":"kmarsden","emailAddress":"kmarsdenderby at sbcglobal dot net","avatarUrls":{"48x48":"https://issues.apache.org/jira/secure/useravatar?avatarId=10452","24x24":"https://issues.apache.org/jira/secure/useravatar?size=small&avatarId=10452","16x16":"https://issues.apache.org/jira/secure/useravatar?size=xsmall&avatarId=10452","32x32":"https://issues.apache.org/jira/secure/useravatar?size=medium&avatarId=10452"},"displayName":"Kathey Marsden","active":true},"created":"2008-02-01T22:56:53.441+0000","updated":"2008-02-01T22:56:53.441+0000"},{"self":"https://issues.apache.org/jira/rest/api/2/issue/12372415/comment/12565298","id":"12565298","author":{"self":"https://issues.apache.org/jira/rest/api/2/user?username=julo","name":"julo","emailAddress":"julo at stroffek dot cz","avatarUrls":{"48x48":"https://issues.apache.org/jira/secure/useravatar?avatarId=10452","24x24":"https://issues.apache.org/jira/secure/useravatar?size=small&avatarId=10452","16x16":"https://issues.apache.org/jira/secure/useravatar?size=xsmall&avatarId=10452","32x32":"https://issues.apache.org/jira/secure/useravatar?size=medium&avatarId=10452"},"displayName":"Julius Stroffek","active":true},"body":"Myrna, Kathey, thanks for looking at this issue.\r\n\r\n- I'll add the missing javadoc with @see tags.\r\n- I'll change System.err.println to fail(...) and and think about BaseJDBCTestCase.prepareCall or DatabasePropertyTestSetup.\r\n\r\n- I agree that isFinished is a bit confusing. The idea why it is there is that there is a just a small window in which the cancelation task might be executing and still not obtained a lock on XATransactionState object. In a meanwhile the transaction might get committed or rolled back by the application and afterwards the cancellation task will obtain a lock and run till the completition (see http://java.sun.com/javase/6/docs/api/java/util/TimerTask.html#cancel() ). This property is used just for preventing attempts to do rollbacks of transactions already committed or rolled back.\r\n\r\nValue of isFinished is assigned to false in schedule timeout task beacuse if the global transaction is started with EmbedXAResource.start(TMNOFLAGS) the method XATransactionState.start(TMNOFLAGS) is not called but scheduleTimeoutTask is called if the timeout is required.\r\n\r\nSo there are two possible options how to deal whith this:\r\na) rename isFinished to something less confusing like 'performTimeoutRollback', etc.\r\nb) or change the logic so XATransactionState.start would be called also for TMNOFLAGS and isFinished would behave as expected from its name.\r\n\r\nThanks for your opinions.","updateAuthor":{"self":"https://issues.apache.org/jira/rest/api/2/user?username=julo","name":"julo","emailAddress":"julo at stroffek dot cz","avatarUrls":{"48x48":"https://issues.apache.org/jira/secure/useravatar?avatarId=10452","24x24":"https://issues.apache.org/jira/secure/useravatar?size=small&avatarId=10452","16x16":"https://issues.apache.org/jira/secure/useravatar?size=xsmall&avatarId=10452","32x32":"https://issues.apache.org/jira/secure/useravatar?size=medium&avatarId=10452"},"displayName":"Julius Stroffek","active":true},"created":"2008-02-04T09:59:18.058+0000","updated":"2008-02-04T09:59:18.058+0000"},{"self":"https://issues.apache.org/jira/rest/api/2/issue/12372415/comment/12565465","id":"12565465","author":{"self":"https://issues.apache.org/jira/rest/api/2/user?username=kmarsden","name":"kmarsden","emailAddress":"kmarsdenderby at sbcglobal dot net","avatarUrls":{"48x48":"https://issues.apache.org/jira/secure/useravatar?avatarId=10452","24x24":"https://issues.apache.org/jira/secure/useravatar?size=small&avatarId=10452","16x16":"https://issues.apache.org/jira/secure/useravatar?size=xsmall&avatarId=10452","32x32":"https://issues.apache.org/jira/secure/useravatar?size=medium&avatarId=10452"},"displayName":"Kathey Marsden","active":true},"body":"Julius said:\r\n\r\n>So there are two possible options how to deal whith this:\r\n>a) rename isFinished to something less confusing like 'performTimeoutRollback', etc.\r\n>b) or change the logic so XATransactionState.start would be called also for TMNOFLAGS and isFinished would behave as expected from its name.\r\n\r\nI think either is fine, with a slight preference for a, since this is used only for timeout.\r\n","updateAuthor":{"self":"https://issues.apache.org/jira/rest/api/2/user?username=kmarsden","name":"kmarsden","emailAddress":"kmarsdenderby at sbcglobal dot net","avatarUrls":{"48x48":"https://issues.apache.org/jira/secure/useravatar?avatarId=10452","24x24":"https://issues.apache.org/jira/secure/useravatar?size=small&avatarId=10452","16x16":"https://issues.apache.org/jira/secure/useravatar?size=xsmall&avatarId=10452","32x32":"https://issues.apache.org/jira/secure/useravatar?size=medium&avatarId=10452"},"displayName":"Kathey Marsden","active":true},"created":"2008-02-04T18:50:04.565+0000","updated":"2008-02-04T18:50:04.565+0000"},{"self":"https://issues.apache.org/jira/rest/api/2/issue/12372415/comment/12565797","id":"12565797","author":{"self":"https://issues.apache.org/jira/rest/api/2/user?username=julo","name":"julo","emailAddress":"julo at stroffek dot cz","avatarUrls":{"48x48":"https://issues.apache.org/jira/secure/useravatar?avatarId=10452","24x24":"https://issues.apache.org/jira/secure/useravatar?size=small&avatarId=10452","16x16":"https://issues.apache.org/jira/secure/useravatar?size=xsmall&avatarId=10452","32x32":"https://issues.apache.org/jira/secure/useravatar?size=medium&avatarId=10452"},"displayName":"Julius Stroffek","active":true},"body":"I added/changed\r\n\r\n* missing javadoc with @see tag\r\n* renamed isFinished to performTimeoutRollback\r\n* changed XATransactionTest to use DatabasePropertyTestSetup.setLockTimeouts\r\n* changed System.err.println to Assert.fail with the message\r\n\r\nI think that I still have not answered couple of questions:\r\n\r\nKathey:\r\n> On the test in addition to Myrna's comments, do we lose anything by dropping from 1000 connections to 66?\r\n\r\nExactly the same functionality will be tested. Using 1000 connections worked also as something like a stress test and utilized the database much more.\r\n\r\n> I got a bit confused about which changes were part of this issue and which were part of DERBY-2953.\r\n> Are the code changes necessary for the test to pass with its changes or were the two issues' patches\r\n> just combined for convenience?\r\n\r\nI created DERBY-2953 as that it will log information about rollbacks to derby log in a situation when I did not know what is/might be causing failures. I also reorganized the code a bit - one common function is called to rollback/cancel the transaction from different places. I thought that this change could be committed sooner and it could help to diagnose the problem after test failures. Now, I have fixies for every possible issue I found and It is also a bit difficult to divide the patch now to DERBY-2871 and DERBY-2953.\r\n\r\nI am running the tests now. derbyall already completed without failures. suites.All are still running.","updateAuthor":{"self":"https://issues.apache.org/jira/rest/api/2/user?username=julo","name":"julo","emailAddress":"julo at stroffek dot cz","avatarUrls":{"48x48":"https://issues.apache.org/jira/secure/useravatar?avatarId=10452","24x24":"https://issues.apache.org/jira/secure/useravatar?size=small&avatarId=10452","16x16":"https://issues.apache.org/jira/secure/useravatar?size=xsmall&avatarId=10452","32x32":"https://issues.apache.org/jira/secure/useravatar?size=medium&avatarId=10452"},"displayName":"Julius Stroffek","active":true},"created":"2008-02-05T16:35:17.894+0000","updated":"2008-02-05T16:35:17.894+0000"},{"self":"https://issues.apache.org/jira/rest/api/2/issue/12372415/comment/12565863","id":"12565863","author":{"self":"https://issues.apache.org/jira/rest/api/2/user?username=myrna","name":"myrna","emailAddress":"m dot v dot lunteren at gmail dot com","avatarUrls":{"48x48":"https://issues.apache.org/jira/secure/useravatar?avatarId=10452","24x24":"https://issues.apache.org/jira/secure/useravatar?size=small&avatarId=10452","16x16":"https://issues.apache.org/jira/secure/useravatar?size=xsmall&avatarId=10452","32x32":"https://issues.apache.org/jira/secure/useravatar?size=medium&avatarId=10452"},"displayName":"Myrna van Lunteren","active":true},"body":"I have no further comments, but again, I'm not familiar with the xa code, maybe someone else can review also.","updateAuthor":{"self":"https://issues.apache.org/jira/rest/api/2/user?username=myrna","name":"myrna","emailAddress":"m dot v dot lunteren at gmail dot com","avatarUrls":{"48x48":"https://issues.apache.org/jira/secure/useravatar?avatarId=10452","24x24":"https://issues.apache.org/jira/secure/useravatar?size=small&avatarId=10452","16x16":"https://issues.apache.org/jira/secure/useravatar?size=xsmall&avatarId=10452","32x32":"https://issues.apache.org/jira/secure/useravatar?size=medium&avatarId=10452"},"displayName":"Myrna van Lunteren","active":true},"created":"2008-02-05T19:56:51.668+0000","updated":"2008-02-05T19:56:51.668+0000"},{"self":"https://issues.apache.org/jira/rest/api/2/issue/12372415/comment/12565866","id":"12565866","author":{"self":"https://issues.apache.org/jira/rest/api/2/user?username=djd","name":"djd","emailAddress":"djd at apache dot org","avatarUrls":{"48x48":"https://issues.apache.org/jira/secure/useravatar?avatarId=10452","24x24":"https://issues.apache.org/jira/secure/useravatar?size=small&avatarId=10452","16x16":"https://issues.apache.org/jira/secure/useravatar?size=xsmall&avatarId=10452","32x32":"https://issues.apache.org/jira/secure/useravatar?size=medium&avatarId=10452"},"displayName":"Daniel John Debrunner","active":true},"body":"Can some comments be added to this in the test, it's a little unclear what's going on in the catch block.\r\nThe exception that caused the failure is being thrown away, this is a problem if the test fails in the future, the exception normally points to where the problem is, losing that information makes debugging much harder, especially with an intermittent problem.\r\n\r\n+        try {\r\n+            stm = getConnection().createStatement();\r\n+            rs = stm.executeQuery(\"select count(*) from XATT\");\r\n+            rs.next();\r\n+        } catch (SQLException e) {\r\n+            rs = stm.executeQuery(\"select global_xid from syscs_diag.transaction_table \"\r\n+                                + \"where global_xid is not null order by global_xid\");\r\n+            StringBuffer sb = new StringBuffer(\"Global transactions in progress:\\n\"); \r\n+            while (rs.next()) {\r\n+                sb.append(rs.getString(1));\r\n+                sb.append(\"\\n\");\r\n+            }\r\n+            Assert.fail(sb.toString());\r\n+        }\r\n\r\n","updateAuthor":{"self":"https://issues.apache.org/jira/rest/api/2/user?username=djd","name":"djd","emailAddress":"djd at apache dot org","avatarUrls":{"48x48":"https://issues.apache.org/jira/secure/useravatar?avatarId=10452","24x24":"https://issues.apache.org/jira/secure/useravatar?size=small&avatarId=10452","16x16":"https://issues.apache.org/jira/secure/useravatar?size=xsmall&avatarId=10452","32x32":"https://issues.apache.org/jira/secure/useravatar?size=medium&avatarId=10452"},"displayName":"Daniel John Debrunner","active":true},"created":"2008-02-05T20:19:50.049+0000","updated":"2008-02-05T20:19:50.049+0000"},{"self":"https://issues.apache.org/jira/rest/api/2/issue/12372415/comment/12565869","id":"12565869","author":{"self":"https://issues.apache.org/jira/rest/api/2/user?username=djd","name":"djd","emailAddress":"djd at apache dot org","avatarUrls":{"48x48":"https://issues.apache.org/jira/secure/useravatar?avatarId=10452","24x24":"https://issues.apache.org/jira/secure/useravatar?size=small&avatarId=10452","16x16":"https://issues.apache.org/jira/secure/useravatar?size=xsmall&avatarId=10452","32x32":"https://issues.apache.org/jira/secure/useravatar?size=medium&avatarId=10452"},"displayName":"Daniel John Debrunner","active":true},"body":"Why does ResourceAdapter.cancelXATransaction() need to hold its synchronization for the lifetime of the call? It's explicitly called out in the javadoc and comments in this issue, but I don't see any reason for it. The rollback could take some time, and during that time any other global transaction work that needs the ResourceAdapter will be blocked.","updateAuthor":{"self":"https://issues.apache.org/jira/rest/api/2/user?username=djd","name":"djd","emailAddress":"djd at apache dot org","avatarUrls":{"48x48":"https://issues.apache.org/jira/secure/useravatar?avatarId=10452","24x24":"https://issues.apache.org/jira/secure/useravatar?size=small&avatarId=10452","16x16":"https://issues.apache.org/jira/secure/useravatar?size=xsmall&avatarId=10452","32x32":"https://issues.apache.org/jira/secure/useravatar?size=medium&avatarId=10452"},"displayName":"Daniel John Debrunner","active":true},"created":"2008-02-05T20:26:47.068+0000","updated":"2008-02-05T20:26:47.068+0000"},{"self":"https://issues.apache.org/jira/rest/api/2/issue/12372415/comment/12565938","id":"12565938","author":{"self":"https://issues.apache.org/jira/rest/api/2/user?username=knutanders","name":"knutanders","emailAddress":"knut dot hatlen at oracle dot com","avatarUrls":{"48x48":"https://issues.apache.org/jira/secure/useravatar?avatarId=10452","24x24":"https://issues.apache.org/jira/secure/useravatar?size=small&avatarId=10452","16x16":"https://issues.apache.org/jira/secure/useravatar?size=xsmall&avatarId=10452","32x32":"https://issues.apache.org/jira/secure/useravatar?size=medium&avatarId=10452"},"displayName":"Knut Anders Hatlen","active":true},"body":"Some nits:\r\n\r\n- typo in new error message (J135): beeing -> being\r\n\r\n- inconsistent use of tabs/spaces in the new methods in ResourceAdapter, ResourceAdapterImpl and XADatabase\r\n\r\n- unnecessary whitespace diff (adding trailing spaces) in XATransactionState.java, chunk @@ -200,8 +199,7 @@.","updateAuthor":{"self":"https://issues.apache.org/jira/rest/api/2/user?username=knutanders","name":"knutanders","emailAddress":"knut dot hatlen at oracle dot com","avatarUrls":{"48x48":"https://issues.apache.org/jira/secure/useravatar?avatarId=10452","24x24":"https://issues.apache.org/jira/secure/useravatar?size=small&avatarId=10452","16x16":"https://issues.apache.org/jira/secure/useravatar?size=xsmall&avatarId=10452","32x32":"https://issues.apache.org/jira/secure/useravatar?size=medium&avatarId=10452"},"displayName":"Knut Anders Hatlen","active":true},"created":"2008-02-05T23:02:20.496+0000","updated":"2008-02-05T23:02:20.496+0000"},{"self":"https://issues.apache.org/jira/rest/api/2/issue/12372415/comment/12567044","id":"12567044","author":{"self":"https://issues.apache.org/jira/rest/api/2/user?username=julo","name":"julo","emailAddress":"julo at stroffek dot cz","avatarUrls":{"48x48":"https://issues.apache.org/jira/secure/useravatar?avatarId=10452","24x24":"https://issues.apache.org/jira/secure/useravatar?size=small&avatarId=10452","16x16":"https://issues.apache.org/jira/secure/useravatar?size=xsmall&avatarId=10452","32x32":"https://issues.apache.org/jira/secure/useravatar?size=medium&avatarId=10452"},"displayName":"Julius Stroffek","active":true},"body":"Dan, Knut: Thanks for catching this. I fixed all of those. I ran all the testing again without failures.\r\n\r\nYes, it might be possible to run just the XATransactionTest since no other test is using the changed code but just for sure I ran all of them again.\r\n\r\nAttaching the latest patch...","updateAuthor":{"self":"https://issues.apache.org/jira/rest/api/2/user?username=julo","name":"julo","emailAddress":"julo at stroffek dot cz","avatarUrls":{"48x48":"https://issues.apache.org/jira/secure/useravatar?avatarId=10452","24x24":"https://issues.apache.org/jira/secure/useravatar?size=small&avatarId=10452","16x16":"https://issues.apache.org/jira/secure/useravatar?size=xsmall&avatarId=10452","32x32":"https://issues.apache.org/jira/secure/useravatar?size=medium&avatarId=10452"},"displayName":"Julius Stroffek","active":true},"created":"2008-02-08T14:08:37.604+0000","updated":"2008-02-08T14:08:37.604+0000"},{"self":"https://issues.apache.org/jira/rest/api/2/issue/12372415/comment/12569895","id":"12569895","author":{"self":"https://issues.apache.org/jira/rest/api/2/user?username=julo","name":"julo","emailAddress":"julo at stroffek dot cz","avatarUrls":{"48x48":"https://issues.apache.org/jira/secure/useravatar?avatarId=10452","24x24":"https://issues.apache.org/jira/secure/useravatar?size=small&avatarId=10452","16x16":"https://issues.apache.org/jira/secure/useravatar?size=xsmall&avatarId=10452","32x32":"https://issues.apache.org/jira/secure/useravatar?size=medium&avatarId=10452"},"displayName":"Julius Stroffek","active":true},"body":"Can somebody commit this patch if there are no objections?","updateAuthor":{"self":"https://issues.apache.org/jira/rest/api/2/user?username=julo","name":"julo","emailAddress":"julo at stroffek dot cz","avatarUrls":{"48x48":"https://issues.apache.org/jira/secure/useravatar?avatarId=10452","24x24":"https://issues.apache.org/jira/secure/useravatar?size=small&avatarId=10452","16x16":"https://issues.apache.org/jira/secure/useravatar?size=xsmall&avatarId=10452","32x32":"https://issues.apache.org/jira/secure/useravatar?size=medium&avatarId=10452"},"displayName":"Julius Stroffek","active":true},"created":"2008-02-18T13:32:43.541+0000","updated":"2008-02-18T13:32:43.541+0000"},{"self":"https://issues.apache.org/jira/rest/api/2/issue/12372415/comment/12570673","id":"12570673","author":{"self":"https://issues.apache.org/jira/rest/api/2/user?username=knutanders","name":"knutanders","emailAddress":"knut dot hatlen at oracle dot com","avatarUrls":{"48x48":"https://issues.apache.org/jira/secure/useravatar?avatarId=10452","24x24":"https://issues.apache.org/jira/secure/useravatar?size=small&avatarId=10452","16x16":"https://issues.apache.org/jira/secure/useravatar?size=xsmall&avatarId=10452","32x32":"https://issues.apache.org/jira/secure/useravatar?size=medium&avatarId=10452"},"displayName":"Knut Anders Hatlen","active":true},"body":"It seems like Dan's comment from 05/Feb/08 12:19 PM hasn't been addressed.\r\n\r\nResourceAdapterImpl.cancelXATransaction() calls findConnection() twice. Is that intentional?\r\n\r\nIs the comment about synchronization in ResourceAdapter.cancelXATransaction() still valid in the latest patch?\r\n\r\nCould you comment on why you call DatabasePropertyTestSetup.setLockTimeouts() in XATransactionTest.suite()? As far as I can see, the timeout values specified (20 sec deadlock, 60 sec wait) are the same as the default values, so it doesn't change anything.\r\n\r\nTiny nit: assertTrue(xaConn[i] != null) could be replaced with assertNotNull(xaConn[i]).","updateAuthor":{"self":"https://issues.apache.org/jira/rest/api/2/user?username=knutanders","name":"knutanders","emailAddress":"knut dot hatlen at oracle dot com","avatarUrls":{"48x48":"https://issues.apache.org/jira/secure/useravatar?avatarId=10452","24x24":"https://issues.apache.org/jira/secure/useravatar?size=small&avatarId=10452","16x16":"https://issues.apache.org/jira/secure/useravatar?size=xsmall&avatarId=10452","32x32":"https://issues.apache.org/jira/secure/useravatar?size=medium&avatarId=10452"},"displayName":"Knut Anders Hatlen","active":true},"created":"2008-02-20T12:49:47.126+0000","updated":"2008-02-20T12:49:47.126+0000"},{"self":"https://issues.apache.org/jira/rest/api/2/issue/12372415/comment/12587089","id":"12587089","author":{"self":"https://issues.apache.org/jira/rest/api/2/user?username=dyret","name":"dyret","emailAddress":"Dyre dot Tjeldvoll at oracle dot com","avatarUrls":{"48x48":"https://issues.apache.org/jira/secure/useravatar?avatarId=10452","24x24":"https://issues.apache.org/jira/secure/useravatar?size=small&avatarId=10452","16x16":"https://issues.apache.org/jira/secure/useravatar?size=xsmall&avatarId=10452","32x32":"https://issues.apache.org/jira/secure/useravatar?size=medium&avatarId=10452"},"displayName":"Dyre Tjeldvoll","active":true},"body":"Attaching derby-2871-NOT_FOR_COMMIT.diff where I have tried to address the latest review comments, (and which applies cleanly to the current trunk). With the new patch I can run XATransactionTest by itself, but when running as part of suites.All it fails with a lock timeout on line 233 or 234. I'm not sure how best to modify the test to achieve the intended effect, so I have uploaded a preliminary patch for people to comment on.","updateAuthor":{"self":"https://issues.apache.org/jira/rest/api/2/user?username=dyret","name":"dyret","emailAddress":"Dyre dot Tjeldvoll at oracle dot com","avatarUrls":{"48x48":"https://issues.apache.org/jira/secure/useravatar?avatarId=10452","24x24":"https://issues.apache.org/jira/secure/useravatar?size=small&avatarId=10452","16x16":"https://issues.apache.org/jira/secure/useravatar?size=xsmall&avatarId=10452","32x32":"https://issues.apache.org/jira/secure/useravatar?size=medium&avatarId=10452"},"displayName":"Dyre Tjeldvoll","active":true},"created":"2008-04-09T08:12:27.034+0000","updated":"2008-04-09T08:12:27.034+0000"},{"self":"https://issues.apache.org/jira/rest/api/2/issue/12372415/comment/12587161","id":"12587161","author":{"self":"https://issues.apache.org/jira/rest/api/2/user?username=julo","name":"julo","emailAddress":"julo at stroffek dot cz","avatarUrls":{"48x48":"https://issues.apache.org/jira/secure/useravatar?avatarId=10452","24x24":"https://issues.apache.org/jira/secure/useravatar?size=small&avatarId=10452","16x16":"https://issues.apache.org/jira/secure/useravatar?size=xsmall&avatarId=10452","32x32":"https://issues.apache.org/jira/secure/useravatar?size=medium&avatarId=10452"},"displayName":"Julius Stroffek","active":true},"body":"Dyre, thanks for working on this.\r\n\r\nThis is due the SetTransactionIsolationTest in jdbcapi test package sets the derby.locks.waitTimeout and derby.locks.deadLockTimeout to 3 which is not restored back to default. Afterwards, the xaTransactionTimeout test runs with a lock timeout to be smaller than an xa transaction timeout so the select on line 233 which checks that the locks are released has a smaller timeout than transactions them self. That's why I changed those properties to default values in the previous patches.\r\n\r\nI think that if you use DatabasePropertyTestSetup.setLockTimeouts to setup timeouts in \"suite\" method the test will stop failing.\r\n\r\nThe mistakes I made in my last patch are stupid and are done mostly because I have not spend required time on those changes. I have a patch prepared for this for some time now but wanted to spend more time to review that I addressed all the comments. Your patch looks good to me - you performed some more cleanups in the test (removed unnecessary Assert class when calling assert functions).","updateAuthor":{"self":"https://issues.apache.org/jira/rest/api/2/user?username=julo","name":"julo","emailAddress":"julo at stroffek dot cz","avatarUrls":{"48x48":"https://issues.apache.org/jira/secure/useravatar?avatarId=10452","24x24":"https://issues.apache.org/jira/secure/useravatar?size=small&avatarId=10452","16x16":"https://issues.apache.org/jira/secure/useravatar?size=xsmall&avatarId=10452","32x32":"https://issues.apache.org/jira/secure/useravatar?size=medium&avatarId=10452"},"displayName":"Julius Stroffek","active":true},"created":"2008-04-09T12:17:36.623+0000","updated":"2008-04-09T12:17:36.623+0000"},{"self":"https://issues.apache.org/jira/rest/api/2/issue/12372415/comment/12587191","id":"12587191","author":{"self":"https://issues.apache.org/jira/rest/api/2/user?username=dyret","name":"dyret","emailAddress":"Dyre dot Tjeldvoll at oracle dot com","avatarUrls":{"48x48":"https://issues.apache.org/jira/secure/useravatar?avatarId=10452","24x24":"https://issues.apache.org/jira/secure/useravatar?size=small&avatarId=10452","16x16":"https://issues.apache.org/jira/secure/useravatar?size=xsmall&avatarId=10452","32x32":"https://issues.apache.org/jira/secure/useravatar?size=medium&avatarId=10452"},"displayName":"Dyre Tjeldvoll","active":true},"body":"Thanks for the feedback, Julius. I know that you have other stuff on your plate these days. \r\n\r\nI see now why the lock timeouts had to be set back to the defaults in the suite method. I'll put that back and add a comment explaining why it is done that way.","updateAuthor":{"self":"https://issues.apache.org/jira/rest/api/2/user?username=dyret","name":"dyret","emailAddress":"Dyre dot Tjeldvoll at oracle dot com","avatarUrls":{"48x48":"https://issues.apache.org/jira/secure/useravatar?avatarId=10452","24x24":"https://issues.apache.org/jira/secure/useravatar?size=small&avatarId=10452","16x16":"https://issues.apache.org/jira/secure/useravatar?size=xsmall&avatarId=10452","32x32":"https://issues.apache.org/jira/secure/useravatar?size=medium&avatarId=10452"},"displayName":"Dyre Tjeldvoll","active":true},"created":"2008-04-09T13:42:06.399+0000","updated":"2008-04-09T13:42:06.399+0000"},{"self":"https://issues.apache.org/jira/rest/api/2/issue/12372415/comment/12587303","id":"12587303","author":{"self":"https://issues.apache.org/jira/rest/api/2/user?username=dyret","name":"dyret","emailAddress":"Dyre dot Tjeldvoll at oracle dot com","avatarUrls":{"48x48":"https://issues.apache.org/jira/secure/useravatar?avatarId=10452","24x24":"https://issues.apache.org/jira/secure/useravatar?size=small&avatarId=10452","16x16":"https://issues.apache.org/jira/secure/useravatar?size=xsmall&avatarId=10452","32x32":"https://issues.apache.org/jira/secure/useravatar?size=medium&avatarId=10452"},"displayName":"Dyre Tjeldvoll","active":true},"body":"Attaching a new patch (derby-2971.v2.diff) which re-enables the lock timeout setting. With this patch I could run the entire jdbcapi suite without failures.","updateAuthor":{"self":"https://issues.apache.org/jira/rest/api/2/user?username=dyret","name":"dyret","emailAddress":"Dyre dot Tjeldvoll at oracle dot com","avatarUrls":{"48x48":"https://issues.apache.org/jira/secure/useravatar?avatarId=10452","24x24":"https://issues.apache.org/jira/secure/useravatar?size=small&avatarId=10452","16x16":"https://issues.apache.org/jira/secure/useravatar?size=xsmall&avatarId=10452","32x32":"https://issues.apache.org/jira/secure/useravatar?size=medium&avatarId=10452"},"displayName":"Dyre Tjeldvoll","active":true},"created":"2008-04-09T18:54:42.094+0000","updated":"2008-04-09T18:54:42.094+0000"},{"self":"https://issues.apache.org/jira/rest/api/2/issue/12372415/comment/12587884","id":"12587884","author":{"self":"https://issues.apache.org/jira/rest/api/2/user?username=dyret","name":"dyret","emailAddress":"Dyre dot Tjeldvoll at oracle dot com","avatarUrls":{"48x48":"https://issues.apache.org/jira/secure/useravatar?avatarId=10452","24x24":"https://issues.apache.org/jira/secure/useravatar?size=small&avatarId=10452","16x16":"https://issues.apache.org/jira/secure/useravatar?size=xsmall&avatarId=10452","32x32":"https://issues.apache.org/jira/secure/useravatar?size=medium&avatarId=10452"},"displayName":"Dyre Tjeldvoll","active":true},"body":"Committed revision 647078.\r\n\r\n(derbyall and suites.All both ran without failures)","updateAuthor":{"self":"https://issues.apache.org/jira/rest/api/2/user?username=dyret","name":"dyret","emailAddress":"Dyre dot Tjeldvoll at oracle dot com","avatarUrls":{"48x48":"https://issues.apache.org/jira/secure/useravatar?avatarId=10452","24x24":"https://issues.apache.org/jira/secure/useravatar?size=small&avatarId=10452","16x16":"https://issues.apache.org/jira/secure/useravatar?size=xsmall&avatarId=10452","32x32":"https://issues.apache.org/jira/secure/useravatar?size=medium&avatarId=10452"},"displayName":"Dyre Tjeldvoll","active":true},"created":"2008-04-11T08:40:26.968+0000","updated":"2008-04-11T08:40:26.968+0000"}]},"votes":{"self":"https://issues.apache.org/jira/rest/api/2/issue/DERBY-2871/votes","votes":0,"hasVoted":false},"worklog":{"startAt":0,"maxResults":20,"total":0,"worklogs":[]},"customfield_12311820":"0|i06pfz:"}}