{"expand":"renderedFields,names,schema,transitions,operations,editmeta,changelog","id":"12618188","self":"https://issues.apache.org/jira/rest/api/latest/issue/12618188","key":"ARIES-976","fields":{"issuetype":{"self":"https://issues.apache.org/jira/rest/api/2/issuetype/1","id":"1","description":"A problem which impairs or prevents the functions of the product.","iconUrl":"https://issues.apache.org/jira/images/icons/issuetypes/bug.png","name":"Bug","subtask":false},"timespent":null,"project":{"self":"https://issues.apache.org/jira/rest/api/2/project/12310981","id":"12310981","key":"ARIES","name":"Aries","avatarUrls":{"48x48":"https://issues.apache.org/jira/secure/projectavatar?pid=12310981&avatarId=10065","24x24":"https://issues.apache.org/jira/secure/projectavatar?size=small&pid=12310981&avatarId=10065","16x16":"https://issues.apache.org/jira/secure/projectavatar?size=xsmall&pid=12310981&avatarId=10065","32x32":"https://issues.apache.org/jira/secure/projectavatar?size=medium&pid=12310981&avatarId=10065"},"projectCategory":{"self":"https://issues.apache.org/jira/rest/api/2/projectCategory/10520","id":"10520","description":"Apache Aries","name":"Aries"}},"fixVersions":[],"aggregatetimespent":null,"resolution":null,"customfield_12312322":null,"customfield_12310220":null,"customfield_12312323":null,"customfield_12310420":"292811","customfield_12312320":null,"customfield_12310222":null,"customfield_12312321":null,"customfield_12312120":null,"customfield_12312121":null,"resolutiondate":null,"workratio":-1,"customfield_12312328":null,"customfield_12312329":null,"customfield_12312326":null,"customfield_12310300":null,"customfield_12312327":null,"customfield_12312324":null,"customfield_12312325":null,"lastViewed":null,"watches":{"self":"https://issues.apache.org/jira/rest/api/2/issue/ARIES-976/watchers","watchCount":1,"isWatching":false},"created":"2012-11-29T17:54:49.041+0000","priority":{"self":"https://issues.apache.org/jira/rest/api/2/priority/3","iconUrl":"https://issues.apache.org/jira/images/icons/priorities/major.png","name":"Major","id":"3"},"labels":[],"customfield_12312333":null,"customfield_12312334":null,"customfield_12310310":"0.0","customfield_12312331":null,"customfield_12312332":null,"timeestimate":null,"aggregatetimeoriginalestimate":null,"customfield_12312330":null,"customfield_12311120":null,"versions":[],"issuelinks":[],"customfield_12312339":null,"assignee":{"self":"https://issues.apache.org/jira/rest/api/2/user?username=hughesj","name":"hughesj","emailAddress":"hughesj at apache dot org","avatarUrls":{"48x48":"https://issues.apache.org/jira/secure/useravatar?ownerId=hughesj&avatarId=24607","24x24":"https://issues.apache.org/jira/secure/useravatar?size=small&ownerId=hughesj&avatarId=24607","16x16":"https://issues.apache.org/jira/secure/useravatar?size=xsmall&ownerId=hughesj&avatarId=24607","32x32":"https://issues.apache.org/jira/secure/useravatar?size=medium&ownerId=hughesj&avatarId=24607"},"displayName":"Jeremy Hughes","active":true},"customfield_12312337":null,"customfield_12312338":null,"updated":"2012-12-03T10:58:26.036+0000","customfield_12312335":null,"customfield_12312336":null,"customfield_12311720":null,"status":{"self":"https://issues.apache.org/jira/rest/api/2/status/4","description":"This issue was once resolved, but the resolution was deemed incorrect. From here issues are either marked assigned or resolved.","iconUrl":"https://issues.apache.org/jira/images/icons/statuses/reopened.png","name":"Reopened","id":"4","statusCategory":{"self":"https://issues.apache.org/jira/rest/api/2/statuscategory/2","id":2,"key":"new","colorName":"blue-gray","name":"New"}},"components":[{"self":"https://issues.apache.org/jira/rest/api/2/component/12313048","id":"12313048","name":"Blueprint","description":"OSGi Blueprint Services implementation"}],"timeoriginalestimate":null,"description":"I'm seeing a timing issue in the case where a blueprint bundle (the client) has a service reference to a service in a second bundle (the service). But the service bean is for a class that can't be found. When the service bundle is processed first I get a helpful stacktrace of ClassNotFoundException. In the case where the client bundle is processed first, the GRACE_PERIOD event is sent then the service bundle is processed. After the ClassNotFoundException is thrown, the service bundle blueprint container is cleaned up - in the catch (Throwable t) at the end of BlueprintContainerImpl.doRun(). Eventually the BlueprintRepository.destroy() is called which gets a null back from BlueprintRepository.getInstance(). BlueprintRepository.destroy() passes that to BundleRecipe.destroy() which casts it and NPEs. The NPE gets swallowed by the BlueprintContainerImpl.doRun() and I never see the error message holding the original ClassNotFoundException.\r\n\r\nI'll commit a fix later.","customfield_10010":null,"timetracking":{},"customfield_12312026":null,"customfield_12312023":null,"customfield_12312024":null,"customfield_12312340":null,"aggregatetimeestimate":null,"customfield_12312022":null,"customfield_12312341":null,"customfield_12312220":null,"customfield_12310921":null,"customfield_12310920":"163820","summary":"BlueprintContainerImpl swallowing NPE prevents error being logged","creator":{"self":"https://issues.apache.org/jira/rest/api/2/user?username=hughesj","name":"hughesj","emailAddress":"hughesj at apache dot org","avatarUrls":{"48x48":"https://issues.apache.org/jira/secure/useravatar?ownerId=hughesj&avatarId=24607","24x24":"https://issues.apache.org/jira/secure/useravatar?size=small&ownerId=hughesj&avatarId=24607","16x16":"https://issues.apache.org/jira/secure/useravatar?size=xsmall&ownerId=hughesj&avatarId=24607","32x32":"https://issues.apache.org/jira/secure/useravatar?size=medium&ownerId=hughesj&avatarId=24607"},"displayName":"Jeremy Hughes","active":true},"subtasks":[],"customfield_12310291":null,"reporter":{"self":"https://issues.apache.org/jira/rest/api/2/user?username=hughesj","name":"hughesj","emailAddress":"hughesj at apache dot org","avatarUrls":{"48x48":"https://issues.apache.org/jira/secure/useravatar?ownerId=hughesj&avatarId=24607","24x24":"https://issues.apache.org/jira/secure/useravatar?size=small&ownerId=hughesj&avatarId=24607","16x16":"https://issues.apache.org/jira/secure/useravatar?size=xsmall&ownerId=hughesj&avatarId=24607","32x32":"https://issues.apache.org/jira/secure/useravatar?size=medium&ownerId=hughesj&avatarId=24607"},"displayName":"Jeremy Hughes","active":true},"customfield_12310290":null,"aggregateprogress":{"progress":0,"total":0},"customfield_12311024":null,"environment":null,"customfield_12311020":null,"duedate":null,"customfield_12310250":null,"progress":{"progress":0,"total":0},"comment":{"startAt":0,"maxResults":2,"total":2,"comments":[{"self":"https://issues.apache.org/jira/rest/api/2/issue/12618188/comment/13507257","id":"13507257","author":{"self":"https://issues.apache.org/jira/rest/api/2/user?username=hughesj","name":"hughesj","emailAddress":"hughesj at apache dot org","avatarUrls":{"48x48":"https://issues.apache.org/jira/secure/useravatar?ownerId=hughesj&avatarId=24607","24x24":"https://issues.apache.org/jira/secure/useravatar?size=small&ownerId=hughesj&avatarId=24607","16x16":"https://issues.apache.org/jira/secure/useravatar?size=xsmall&ownerId=hughesj&avatarId=24607","32x32":"https://issues.apache.org/jira/secure/useravatar?size=medium&ownerId=hughesj&avatarId=24607"},"displayName":"Jeremy Hughes","active":true},"body":"My mistake, already fixed by ARIES-847","updateAuthor":{"self":"https://issues.apache.org/jira/rest/api/2/user?username=hughesj","name":"hughesj","emailAddress":"hughesj at apache dot org","avatarUrls":{"48x48":"https://issues.apache.org/jira/secure/useravatar?ownerId=hughesj&avatarId=24607","24x24":"https://issues.apache.org/jira/secure/useravatar?size=small&ownerId=hughesj&avatarId=24607","16x16":"https://issues.apache.org/jira/secure/useravatar?size=xsmall&ownerId=hughesj&avatarId=24607","32x32":"https://issues.apache.org/jira/secure/useravatar?size=medium&ownerId=hughesj&avatarId=24607"},"displayName":"Jeremy Hughes","active":true},"created":"2012-11-30T10:48:22.270+0000","updated":"2012-11-30T10:48:22.270+0000"},{"self":"https://issues.apache.org/jira/rest/api/2/issue/12618188/comment/13508644","id":"13508644","author":{"self":"https://issues.apache.org/jira/rest/api/2/user?username=hughesj","name":"hughesj","emailAddress":"hughesj at apache dot org","avatarUrls":{"48x48":"https://issues.apache.org/jira/secure/useravatar?ownerId=hughesj&avatarId=24607","24x24":"https://issues.apache.org/jira/secure/useravatar?size=small&ownerId=hughesj&avatarId=24607","16x16":"https://issues.apache.org/jira/secure/useravatar?size=xsmall&ownerId=hughesj&avatarId=24607","32x32":"https://issues.apache.org/jira/secure/useravatar?size=medium&ownerId=hughesj&avatarId=24607"},"displayName":"Jeremy Hughes","active":true},"body":"The fix in ARIES-847 is ok, but if another unchecked exception comes out of the cleanup we swallow it. I'll add debug so at least we can see what's happening.","updateAuthor":{"self":"https://issues.apache.org/jira/rest/api/2/user?username=hughesj","name":"hughesj","emailAddress":"hughesj at apache dot org","avatarUrls":{"48x48":"https://issues.apache.org/jira/secure/useravatar?ownerId=hughesj&avatarId=24607","24x24":"https://issues.apache.org/jira/secure/useravatar?size=small&ownerId=hughesj&avatarId=24607","16x16":"https://issues.apache.org/jira/secure/useravatar?size=xsmall&ownerId=hughesj&avatarId=24607","32x32":"https://issues.apache.org/jira/secure/useravatar?size=medium&ownerId=hughesj&avatarId=24607"},"displayName":"Jeremy Hughes","active":true},"created":"2012-12-03T10:58:26.034+0000","updated":"2012-12-03T10:58:26.034+0000"}]},"votes":{"self":"https://issues.apache.org/jira/rest/api/2/issue/ARIES-976/votes","votes":0,"hasVoted":false},"worklog":{"startAt":0,"maxResults":20,"total":0,"worklogs":[]},"customfield_12311820":"0|i0segv:"}}