{"expand":"renderedFields,names,schema,transitions,operations,editmeta,changelog","id":"12517943","self":"https://issues.apache.org/jira/rest/api/latest/issue/12517943","key":"DERBY-5374","fields":{"issuetype":{"self":"https://issues.apache.org/jira/rest/api/2/issuetype/1","id":"1","description":"A problem which impairs or prevents the functions of the product.","iconUrl":"https://issues.apache.org/jira/images/icons/issuetypes/bug.png","name":"Bug","subtask":false},"timespent":null,"project":{"self":"https://issues.apache.org/jira/rest/api/2/project/10594","id":"10594","key":"DERBY","name":"Derby","avatarUrls":{"48x48":"https://issues.apache.org/jira/secure/projectavatar?pid=10594&avatarId=10122","24x24":"https://issues.apache.org/jira/secure/projectavatar?size=small&pid=10594&avatarId=10122","16x16":"https://issues.apache.org/jira/secure/projectavatar?size=xsmall&pid=10594&avatarId=10122","32x32":"https://issues.apache.org/jira/secure/projectavatar?size=medium&pid=10594&avatarId=10122"},"projectCategory":{"self":"https://issues.apache.org/jira/rest/api/2/projectCategory/10090","id":"10090","description":"DB related projects","name":"DB"}},"fixVersions":[{"self":"https://issues.apache.org/jira/rest/api/2/version/12316344","id":"12316344","description":"First release on the 10.9 branch","name":"10.9.1.0","archived":false,"released":true,"releaseDate":"2012-06-25"}],"aggregatetimespent":null,"resolution":{"self":"https://issues.apache.org/jira/rest/api/2/resolution/1","id":"1","description":"A fix for this issue is checked into the tree and tested.","name":"Fixed"},"customfield_12310220":"2011-08-05 00:53:31.679","customfield_12312322":null,"customfield_12312323":null,"customfield_12310420":"24804","customfield_12310222":"1_*:*_1_*:*_369020243_*|*_5_*:*_1_*:*_0","customfield_12312320":null,"customfield_12312321":null,"customfield_12312120":null,"customfield_12312121":null,"resolutiondate":"2011-08-09T00:08:00.216+0000","workratio":-1,"customfield_12312328":null,"customfield_12312329":null,"customfield_12312326":null,"customfield_12310300":null,"customfield_12312327":null,"customfield_12312324":null,"customfield_12312325":null,"lastViewed":null,"watches":{"self":"https://issues.apache.org/jira/rest/api/2/issue/DERBY-5374/watchers","watchCount":1,"isWatching":false},"created":"2011-08-04T17:37:40.019+0000","priority":{"self":"https://issues.apache.org/jira/rest/api/2/priority/3","iconUrl":"https://issues.apache.org/jira/images/icons/priorities/major.png","name":"Major","id":"3"},"labels":[],"customfield_12312333":null,"customfield_12312334":null,"customfield_12310310":"2.0","customfield_12312331":null,"customfield_12312332":null,"timeestimate":null,"aggregatetimeoriginalestimate":null,"versions":[{"self":"https://issues.apache.org/jira/rest/api/2/version/12316344","id":"12316344","description":"First release on the 10.9 branch","name":"10.9.1.0","archived":false,"released":true,"releaseDate":"2012-06-25"}],"customfield_12311120":null,"customfield_12312330":null,"issuelinks":[{"id":"12342006","self":"https://issues.apache.org/jira/rest/api/2/issueLink/12342006","type":{"id":"10030","name":"Reference","inward":"is related to","outward":"relates to","self":"https://issues.apache.org/jira/rest/api/2/issueLinkType/10030"},"inwardIssue":{"id":"12517717","key":"DERBY-5373","self":"https://issues.apache.org/jira/rest/api/2/issue/12517717","fields":{"summary":"test ImportExportIJ fails with weme 6.2; junit.framework.ComparisonFailure: Output at line 1 expected:<ij> --> but was:<ERROR XJ004: Database '' not found.>","status":{"self":"https://issues.apache.org/jira/rest/api/2/status/6","description":"The issue is considered finished, the resolution is correct. Issues which are closed can be reopened.","iconUrl":"https://issues.apache.org/jira/images/icons/statuses/closed.png","name":"Closed","id":"6","statusCategory":{"self":"https://issues.apache.org/jira/rest/api/2/statuscategory/3","id":3,"key":"done","colorName":"green","name":"Complete"}},"priority":{"self":"https://issues.apache.org/jira/rest/api/2/priority/3","iconUrl":"https://issues.apache.org/jira/images/icons/priorities/major.png","name":"Major","id":"3"},"issuetype":{"self":"https://issues.apache.org/jira/rest/api/2/issuetype/1","id":"1","description":"A problem which impairs or prevents the functions of the product.","iconUrl":"https://issues.apache.org/jira/images/icons/issuetypes/bug.png","name":"Bug","subtask":false}}}}],"customfield_12312339":null,"assignee":null,"customfield_12312337":null,"customfield_12312338":null,"updated":"2013-06-17T09:19:45.390+0000","customfield_12312335":null,"customfield_12311720":null,"customfield_12312336":null,"status":{"self":"https://issues.apache.org/jira/rest/api/2/status/6","description":"The issue is considered finished, the resolution is correct. Issues which are closed can be reopened.","iconUrl":"https://issues.apache.org/jira/images/icons/statuses/closed.png","name":"Closed","id":"6","statusCategory":{"self":"https://issues.apache.org/jira/rest/api/2/statuscategory/3","id":3,"key":"done","colorName":"green","name":"Complete"}},"components":[{"self":"https://issues.apache.org/jira/rest/api/2/component/11413","id":"11413","name":"Test"}],"timeoriginalestimate":null,"description":"The newly converted (to junit) test ij5Test fails with weme 6.2:\r\n\r\nij5(org.apache.derbyTesting.functionTests.tests.tools.ij5Test)junit.framework.ComparisonFailure: Output at line 1 expected:<CONNECTION0* - \tjdbc:derby:wombat> but was:<ERROR XJ004: Database '' not found.>\r\n\tat junit.framework.AssertionFailedError.<init>(AssertionFailedError.java:11)\r\n\tat junit.framework.ComparisonFailure.<init>(ComparisonFailure.java:19)\r\n\tat org.apache.derbyTesting.functionTests.util.CanonTestCase.compareCanon(CanonTestCase.java:109)\r\n\tat org.apache.derbyTesting.functionTests.util.ScriptTestCase.runTest(ScriptTestCase.java:204)\r\n\tat org.apache.derbyTesting.junit.BaseTestCase.runBare(BaseTestCase.java:112)\r\n\tat junit.extensions.TestDecorator.basicRun(TestDecorator.java:22)\r\n\tat junit.extensions.TestSetup$1.protect(TestSetup.java:19)\r\n\tat junit.extensions.TestSetup.run(TestSetup.java:23)\r\n\tat junit.extensions.TestDecorator.basicRun(TestDecorator.java:22)\r\n\tat junit.extensions.TestSetup$1.protect(TestSetup.java:19)\r\n\tat junit.extensions.TestSetup.run(TestSetup.java:23)\r\n\tat org.apache.derbyTesting.junit.BaseTestSetup.run(BaseTestSetup.java:57)\r\n\r\nThis is likely a similar problem as described in DERBY-5373 (re importExportIJ). \r\n\r\nsee also (until cleaned up at some point in the future): http://people.apache.org/~myrnavl/derby_test_results/main/windows/testlog/weme6.2/1152992-suites.All_diff.txt\r\n","customfield_10010":null,"timetracking":{},"customfield_12312026":null,"customfield_12310200":[{"self":"https://issues.apache.org/jira/rest/api/2/customFieldOption/10369","value":"Regression Test Failure","id":"10369"}],"customfield_12312023":null,"customfield_12312024":null,"customfield_12312340":null,"aggregatetimeestimate":null,"customfield_12312022":null,"customfield_12312341":null,"customfield_12312220":null,"customfield_12310921":null,"customfield_12310920":"36337","summary":"converted ij5Test fails with weme6.2 (CDC/Foundation): junit.framework.ComparisonFailure: Output at line 1 expected:<CONNECTION0* - \tjdbc:derby:wombat> but was:<ERROR XJ004: Database '' not found.>","creator":{"self":"https://issues.apache.org/jira/rest/api/2/user?username=myrna","name":"myrna","emailAddress":"m dot v dot lunteren at gmail dot com","avatarUrls":{"48x48":"https://issues.apache.org/jira/secure/useravatar?avatarId=10452","24x24":"https://issues.apache.org/jira/secure/useravatar?size=small&avatarId=10452","16x16":"https://issues.apache.org/jira/secure/useravatar?size=xsmall&avatarId=10452","32x32":"https://issues.apache.org/jira/secure/useravatar?size=medium&avatarId=10452"},"displayName":"Myrna van Lunteren","active":true},"subtasks":[],"customfield_12310090":null,"reporter":{"self":"https://issues.apache.org/jira/rest/api/2/user?username=myrna","name":"myrna","emailAddress":"m dot v dot lunteren at gmail dot com","avatarUrls":{"48x48":"https://issues.apache.org/jira/secure/useravatar?avatarId=10452","24x24":"https://issues.apache.org/jira/secure/useravatar?size=small&avatarId=10452","16x16":"https://issues.apache.org/jira/secure/useravatar?size=xsmall&avatarId=10452","32x32":"https://issues.apache.org/jira/secure/useravatar?size=medium&avatarId=10452"},"displayName":"Myrna van Lunteren","active":true},"customfield_12310291":null,"customfield_12310290":null,"aggregateprogress":{"progress":0,"total":0},"environment":"windows XP, with weme6.2 (IBM's CDC/Foundation implementation)","customfield_12311020":null,"customfield_12310050":null,"duedate":null,"customfield_12310250":null,"progress":{"progress":0,"total":0},"comment":{"startAt":0,"maxResults":11,"total":11,"comments":[{"self":"https://issues.apache.org/jira/rest/api/2/issue/12517943/comment/13079710","id":"13079710","author":{"self":"https://issues.apache.org/jira/rest/api/2/user?username=bryanpendleton","name":"bryanpendleton","emailAddress":"bpendleton dot derby at gmail dot com","avatarUrls":{"48x48":"https://issues.apache.org/jira/secure/useravatar?avatarId=10452","24x24":"https://issues.apache.org/jira/secure/useravatar?size=small&avatarId=10452","16x16":"https://issues.apache.org/jira/secure/useravatar?size=xsmall&avatarId=10452","32x32":"https://issues.apache.org/jira/secure/useravatar?size=medium&avatarId=10452"},"displayName":"Bryan Pendleton","active":true},"body":"Could it be that both DERBY-5373 and DERBY-5374 can be fixed the same way as DERBY-5346?\r\n\r\nI don't have phoneme or weme, but hopefully the solution is to make the same change to ij5Test.java\r\nand importExportIJTest.java as was made to ij3Test.java in DERBY-5346.\r\n","updateAuthor":{"self":"https://issues.apache.org/jira/rest/api/2/user?username=bryanpendleton","name":"bryanpendleton","emailAddress":"bpendleton dot derby at gmail dot com","avatarUrls":{"48x48":"https://issues.apache.org/jira/secure/useravatar?avatarId=10452","24x24":"https://issues.apache.org/jira/secure/useravatar?size=small&avatarId=10452","16x16":"https://issues.apache.org/jira/secure/useravatar?size=xsmall&avatarId=10452","32x32":"https://issues.apache.org/jira/secure/useravatar?size=medium&avatarId=10452"},"displayName":"Bryan Pendleton","active":true},"created":"2011-08-05T00:53:31.679+0000","updated":"2011-08-05T00:53:31.679+0000"},{"self":"https://issues.apache.org/jira/rest/api/2/issue/12517943/comment/13079729","id":"13079729","author":{"self":"https://issues.apache.org/jira/rest/api/2/user?username=myrna","name":"myrna","emailAddress":"m dot v dot lunteren at gmail dot com","avatarUrls":{"48x48":"https://issues.apache.org/jira/secure/useravatar?avatarId=10452","24x24":"https://issues.apache.org/jira/secure/useravatar?size=small&avatarId=10452","16x16":"https://issues.apache.org/jira/secure/useravatar?size=xsmall&avatarId=10452","32x32":"https://issues.apache.org/jira/secure/useravatar?size=medium&avatarId=10452"},"displayName":"Myrna van Lunteren","active":true},"body":"I was hoping the same thing, but I cannot reproduce the test failure on my machine.\r\n\r\nI did see another test failure in the ij5 test on my machine though:\r\n\r\n1) ij5(org.apache.derbyTesting.functionTests.tests.tools.ij5Test)java.lang.NoSuchMethodError: java/sql/DatabaseMetaData.getURL()Ljava/lang/String;\r\n\tat org.apache.derby.impl.tools.ij.ij.showConnectionsMethod(Unknown Source)\r\n\tat org.apache.derby.impl.tools.ij.utilMain.supportIJProperties(Unknown Source)\r\n\tat org.apache.derby.impl.tools.ij.utilMain.goScript(Unknown Source)\r\n\tat org.apache.derby.tools.ij.runScript(Unknown Source)\r\n\tat org.apache.derbyTesting.functionTests.util.ScriptTestCase.runTest(ScriptTestCase.java:191)\r\n\tat org.apache.derbyTesting.junit.BaseTestCase.runBare(BaseTestCase.java:112)\r\n\tat junit.extensions.TestDecorator.basicRun(TestDecorator.java:22)\r\n\tat junit.extensions.TestSetup$1.protect(TestSetup.java:19)\r\n\tat junit.extensions.TestSetup.run(TestSetup.java:23)\r\n\tat junit.extensions.TestDecorator.basicRun(TestDecorator.java:22)\r\n\tat junit.extensions.TestSetup$1.protect(TestSetup.java:19)\r\n\tat junit.extensions.TestSetup.run(TestSetup.java:23)\r\n\tat org.apache.derbyTesting.junit.BaseTestSetup.run(BaseTestSetup.java:57)\r\n\r\nI will look at that more closely too, but I did notice that the old ij5.sql test did not run with foundation profile, for it had this in ij5_app.properties:\r\n#Exclude for J2ME/Foundation - test requires java.sql.Driver\r\nrunwithfoundation=false\r\n","updateAuthor":{"self":"https://issues.apache.org/jira/rest/api/2/user?username=myrna","name":"myrna","emailAddress":"m dot v dot lunteren at gmail dot com","avatarUrls":{"48x48":"https://issues.apache.org/jira/secure/useravatar?avatarId=10452","24x24":"https://issues.apache.org/jira/secure/useravatar?size=small&avatarId=10452","16x16":"https://issues.apache.org/jira/secure/useravatar?size=xsmall&avatarId=10452","32x32":"https://issues.apache.org/jira/secure/useravatar?size=medium&avatarId=10452"},"displayName":"Myrna van Lunteren","active":true},"created":"2011-08-05T01:24:58.013+0000","updated":"2011-08-05T01:24:58.013+0000"},{"self":"https://issues.apache.org/jira/rest/api/2/issue/12517943/comment/13080578","id":"13080578","author":{"self":"https://issues.apache.org/jira/rest/api/2/user?username=houxzhang","name":"houxzhang","emailAddress":"houxzhang at gmail dot com","avatarUrls":{"48x48":"https://issues.apache.org/jira/secure/useravatar?avatarId=10452","24x24":"https://issues.apache.org/jira/secure/useravatar?size=small&avatarId=10452","16x16":"https://issues.apache.org/jira/secure/useravatar?size=xsmall&avatarId=10452","32x32":"https://issues.apache.org/jira/secure/useravatar?size=medium&avatarId=10452"},"displayName":"Houx Zhang","active":true},"body":"Then, for ij5Test, a JDBC.vmSupportsJSR169() should be added to avoid it run on j2me.\r\n\r\nHi, Myrna, you've said \"I did see another test failure in the ij5 test on my machine though: \", What machine did you run on, please? Is it j2me or a common pc platform?\r\n\r\n","updateAuthor":{"self":"https://issues.apache.org/jira/rest/api/2/user?username=houxzhang","name":"houxzhang","emailAddress":"houxzhang at gmail dot com","avatarUrls":{"48x48":"https://issues.apache.org/jira/secure/useravatar?avatarId=10452","24x24":"https://issues.apache.org/jira/secure/useravatar?size=small&avatarId=10452","16x16":"https://issues.apache.org/jira/secure/useravatar?size=xsmall&avatarId=10452","32x32":"https://issues.apache.org/jira/secure/useravatar?size=medium&avatarId=10452"},"displayName":"Houx Zhang","active":true},"created":"2011-08-07T14:02:57.957+0000","updated":"2011-08-07T14:02:57.957+0000"},{"self":"https://issues.apache.org/jira/rest/api/2/issue/12517943/comment/13081057","id":"13081057","author":{"self":"https://issues.apache.org/jira/rest/api/2/user?username=myrna","name":"myrna","emailAddress":"m dot v dot lunteren at gmail dot com","avatarUrls":{"48x48":"https://issues.apache.org/jira/secure/useravatar?avatarId=10452","24x24":"https://issues.apache.org/jira/secure/useravatar?size=small&avatarId=10452","16x16":"https://issues.apache.org/jira/secure/useravatar?size=xsmall&avatarId=10452","32x32":"https://issues.apache.org/jira/secure/useravatar?size=medium&avatarId=10452"},"displayName":"Myrna van Lunteren","active":true},"body":"Hi,\r\n\r\nApologies if I've been unclear. The failure from the description is seen on the machine where tests are run nightly - this is a Windows XP desktop (I think it's an IBM ThinkCentre). This machine runs suites.All with ibm 1.5, 1.6 and weme 6.2 (which is IBM's implementation of the J2ME/CDC/Foundation profile). The test failure is because at the top of the .out file, there is an extra message 'ERROR XJ004: Database ' ' not found, which isn't in the master (and doesn't show up on the other jvms). I think it's possible that this message would go away if we specify the properties as in DERBY-5346...\r\n\r\nBut I tried to reproduce this failure with weme 6.2 on my laptop, which is a Thinkpad T60 with Windows XP - by running the test by itself, by running a modified tools suite, running the full tools suite, and finally running the full suites.All, and I did not see the failure. I used the same weme version on both machines.\r\n\r\nSo I'm still struggling to figure out when this happens on the nightly machine.\r\n\r\nThe getURL(String) not found message I got on my laptop, in all of the experiments indicated above. I'm confused about that too, because the failure on the nightly machine really indicates that the entire test was executed correctly, which seems impossible based on the behavior on my laptop.\r\n\r\nIt would be interesting to know if either of those problems shows with PhoneME, but I don't have access to that.\r\n","updateAuthor":{"self":"https://issues.apache.org/jira/rest/api/2/user?username=myrna","name":"myrna","emailAddress":"m dot v dot lunteren at gmail dot com","avatarUrls":{"48x48":"https://issues.apache.org/jira/secure/useravatar?avatarId=10452","24x24":"https://issues.apache.org/jira/secure/useravatar?size=small&avatarId=10452","16x16":"https://issues.apache.org/jira/secure/useravatar?size=xsmall&avatarId=10452","32x32":"https://issues.apache.org/jira/secure/useravatar?size=medium&avatarId=10452"},"displayName":"Myrna van Lunteren","active":true},"created":"2011-08-08T16:59:15.131+0000","updated":"2011-08-08T16:59:15.131+0000"},{"self":"https://issues.apache.org/jira/rest/api/2/issue/12517943/comment/13081135","id":"13081135","author":{"self":"https://issues.apache.org/jira/rest/api/2/user?username=myrna","name":"myrna","emailAddress":"m dot v dot lunteren at gmail dot com","avatarUrls":{"48x48":"https://issues.apache.org/jira/secure/useravatar?avatarId=10452","24x24":"https://issues.apache.org/jira/secure/useravatar?size=small&avatarId=10452","16x16":"https://issues.apache.org/jira/secure/useravatar?size=xsmall&avatarId=10452","32x32":"https://issues.apache.org/jira/secure/useravatar?size=medium&avatarId=10452"},"displayName":"Myrna van Lunteren","active":true},"body":"I've found out the difference between the nightly run and what I was doing on my laptop; in the nightly run it was already having -Dij.dataSource=org.apache.derby.jdbc.EmbeddedSimpleDataSource set.\r\nWithout that, like on my laptop, ij will try to connect using java.sql.Driver subclasses, including using a getURL method that's not available on this jvm.\r\n\r\nIf memory serves me right, with ij.showNoConnectionsAtStart=false (so, show connections at start, if I understand this double negation) we get a different output between dataSources and Driver connections.\r\nI'm experimenting to see if there's a way to get the same output still for running with J2ME/CDC and full-fledged jvms, but no luck so far.\r\n","updateAuthor":{"self":"https://issues.apache.org/jira/rest/api/2/user?username=myrna","name":"myrna","emailAddress":"m dot v dot lunteren at gmail dot com","avatarUrls":{"48x48":"https://issues.apache.org/jira/secure/useravatar?avatarId=10452","24x24":"https://issues.apache.org/jira/secure/useravatar?size=small&avatarId=10452","16x16":"https://issues.apache.org/jira/secure/useravatar?size=xsmall&avatarId=10452","32x32":"https://issues.apache.org/jira/secure/useravatar?size=medium&avatarId=10452"},"displayName":"Myrna van Lunteren","active":true},"created":"2011-08-08T19:12:52.048+0000","updated":"2011-08-08T19:12:52.048+0000"},{"self":"https://issues.apache.org/jira/rest/api/2/issue/12517943/comment/13081305","id":"13081305","author":{"self":"https://issues.apache.org/jira/rest/api/2/user?username=myrna","name":"myrna","emailAddress":"m dot v dot lunteren at gmail dot com","avatarUrls":{"48x48":"https://issues.apache.org/jira/secure/useravatar?avatarId=10452","24x24":"https://issues.apache.org/jira/secure/useravatar?size=small&avatarId=10452","16x16":"https://issues.apache.org/jira/secure/useravatar?size=xsmall&avatarId=10452","32x32":"https://issues.apache.org/jira/secure/useravatar?size=medium&avatarId=10452"},"displayName":"Myrna van Lunteren","active":true},"body":"With weme 6.2 (j2ME/Foundation), with the following in ijTest5:\r\n        if (JDBC.vmSupportsJSR169()) {\r\n            props.setProperty(\"ij.dataSource\",\r\n                              \"org.apache.derby.jdbc.EmbeddedSimpleDataSource\");\r\n            props.setProperty(\"ij.dataSource.databaseName\", \"wombat\");\r\n            props.setProperty(\"ij.dataSource.createDatabase\", \"create\");\r\n        }\r\nI get a diff with weme 6.2 if all three lines are there, because the database was already created. With showNoConnectionsAtStartup=true this gets masked...\r\nIf I comment out the createDatabase property line, I get a diff because of an extra connection (i.e. it shows Connection0 and Connection1. This is because of the CleanDatabase Setup).\r\nIf I comment out also the ij.dataSource.databaseName line, I get an extra line with error message 'XJ004: Database ' ' not found.\r\nAnd if I don't set ij.dataSource at all, we get the getURL(String) method not found error.\r\n\r\nIn all, I don't think this test can be made to work exactly the same with j2ME as with the more richer jvms. \r\nIn the old harness we handled this sort of difference by adding another master file, but although it would've made the test work, maintaining multiple masters is a nightmare, and as this test never ran with JSR169/j2ME/Foundation, and it's not testing major functionality, but only one test case, I think it's ok to not run this with JSR169/j2ME/Foundation.\r\n\r\nSo I'm attaching a patch that I will commit shortly, which skips this test from running with JSR169, both in the test itself and in the tools._Suite.\r\nIn addition, I noticed the .sql file still mentions ConnOne, which was removed, so I changed that to say Connection0.","updateAuthor":{"self":"https://issues.apache.org/jira/rest/api/2/user?username=myrna","name":"myrna","emailAddress":"m dot v dot lunteren at gmail dot com","avatarUrls":{"48x48":"https://issues.apache.org/jira/secure/useravatar?avatarId=10452","24x24":"https://issues.apache.org/jira/secure/useravatar?size=small&avatarId=10452","16x16":"https://issues.apache.org/jira/secure/useravatar?size=xsmall&avatarId=10452","32x32":"https://issues.apache.org/jira/secure/useravatar?size=medium&avatarId=10452"},"displayName":"Myrna van Lunteren","active":true},"created":"2011-08-08T23:52:14.009+0000","updated":"2011-08-08T23:52:14.009+0000"},{"self":"https://issues.apache.org/jira/rest/api/2/issue/12517943/comment/13081311","id":"13081311","author":{"self":"https://issues.apache.org/jira/rest/api/2/user?username=myrna","name":"myrna","emailAddress":"m dot v dot lunteren at gmail dot com","avatarUrls":{"48x48":"https://issues.apache.org/jira/secure/useravatar?avatarId=10452","24x24":"https://issues.apache.org/jira/secure/useravatar?size=small&avatarId=10452","16x16":"https://issues.apache.org/jira/secure/useravatar?size=xsmall&avatarId=10452","32x32":"https://issues.apache.org/jira/secure/useravatar?size=medium&avatarId=10452"},"displayName":"Myrna van Lunteren","active":true},"body":"somehow the connection0 change didn't make it in the first svn diff. ","updateAuthor":{"self":"https://issues.apache.org/jira/rest/api/2/user?username=myrna","name":"myrna","emailAddress":"m dot v dot lunteren at gmail dot com","avatarUrls":{"48x48":"https://issues.apache.org/jira/secure/useravatar?avatarId=10452","24x24":"https://issues.apache.org/jira/secure/useravatar?size=small&avatarId=10452","16x16":"https://issues.apache.org/jira/secure/useravatar?size=xsmall&avatarId=10452","32x32":"https://issues.apache.org/jira/secure/useravatar?size=medium&avatarId=10452"},"displayName":"Myrna van Lunteren","active":true},"created":"2011-08-09T00:01:22.841+0000","updated":"2011-08-09T00:01:22.841+0000"},{"self":"https://issues.apache.org/jira/rest/api/2/issue/12517943/comment/13081316","id":"13081316","author":{"self":"https://issues.apache.org/jira/rest/api/2/user?username=myrna","name":"myrna","emailAddress":"m dot v dot lunteren at gmail dot com","avatarUrls":{"48x48":"https://issues.apache.org/jira/secure/useravatar?avatarId=10452","24x24":"https://issues.apache.org/jira/secure/useravatar?size=small&avatarId=10452","16x16":"https://issues.apache.org/jira/secure/useravatar?size=xsmall&avatarId=10452","32x32":"https://issues.apache.org/jira/secure/useravatar?size=medium&avatarId=10452"},"displayName":"Myrna van Lunteren","active":true},"body":"resolving after commit of the patch with revision 1155163.\r\nWill close after a round of nightly tests.","updateAuthor":{"self":"https://issues.apache.org/jira/rest/api/2/user?username=myrna","name":"myrna","emailAddress":"m dot v dot lunteren at gmail dot com","avatarUrls":{"48x48":"https://issues.apache.org/jira/secure/useravatar?avatarId=10452","24x24":"https://issues.apache.org/jira/secure/useravatar?size=small&avatarId=10452","16x16":"https://issues.apache.org/jira/secure/useravatar?size=xsmall&avatarId=10452","32x32":"https://issues.apache.org/jira/secure/useravatar?size=medium&avatarId=10452"},"displayName":"Myrna van Lunteren","active":true},"created":"2011-08-09T00:08:00.241+0000","updated":"2011-08-09T00:08:00.241+0000"},{"self":"https://issues.apache.org/jira/rest/api/2/issue/12517943/comment/13081382","id":"13081382","author":{"self":"https://issues.apache.org/jira/rest/api/2/user?username=bryanpendleton","name":"bryanpendleton","emailAddress":"bpendleton dot derby at gmail dot com","avatarUrls":{"48x48":"https://issues.apache.org/jira/secure/useravatar?avatarId=10452","24x24":"https://issues.apache.org/jira/secure/useravatar?size=small&avatarId=10452","16x16":"https://issues.apache.org/jira/secure/useravatar?size=xsmall&avatarId=10452","32x32":"https://issues.apache.org/jira/secure/useravatar?size=medium&avatarId=10452"},"displayName":"Bryan Pendleton","active":true},"body":"Thanks Myrna!\r\n","updateAuthor":{"self":"https://issues.apache.org/jira/rest/api/2/user?username=bryanpendleton","name":"bryanpendleton","emailAddress":"bpendleton dot derby at gmail dot com","avatarUrls":{"48x48":"https://issues.apache.org/jira/secure/useravatar?avatarId=10452","24x24":"https://issues.apache.org/jira/secure/useravatar?size=small&avatarId=10452","16x16":"https://issues.apache.org/jira/secure/useravatar?size=xsmall&avatarId=10452","32x32":"https://issues.apache.org/jira/secure/useravatar?size=medium&avatarId=10452"},"displayName":"Bryan Pendleton","active":true},"created":"2011-08-09T02:43:31.331+0000","updated":"2011-08-09T02:43:31.331+0000"},{"self":"https://issues.apache.org/jira/rest/api/2/issue/12517943/comment/13081650","id":"13081650","author":{"self":"https://issues.apache.org/jira/rest/api/2/user?username=houxzhang","name":"houxzhang","emailAddress":"houxzhang at gmail dot com","avatarUrls":{"48x48":"https://issues.apache.org/jira/secure/useravatar?avatarId=10452","24x24":"https://issues.apache.org/jira/secure/useravatar?size=small&avatarId=10452","16x16":"https://issues.apache.org/jira/secure/useravatar?size=xsmall&avatarId=10452","32x32":"https://issues.apache.org/jira/secure/useravatar?size=medium&avatarId=10452"},"displayName":"Houx Zhang","active":true},"body":"Thanks for your patient and valuable work, Myrna!","updateAuthor":{"self":"https://issues.apache.org/jira/rest/api/2/user?username=houxzhang","name":"houxzhang","emailAddress":"houxzhang at gmail dot com","avatarUrls":{"48x48":"https://issues.apache.org/jira/secure/useravatar?avatarId=10452","24x24":"https://issues.apache.org/jira/secure/useravatar?size=small&avatarId=10452","16x16":"https://issues.apache.org/jira/secure/useravatar?size=xsmall&avatarId=10452","32x32":"https://issues.apache.org/jira/secure/useravatar?size=medium&avatarId=10452"},"displayName":"Houx Zhang","active":true},"created":"2011-08-09T14:22:56.762+0000","updated":"2011-08-09T14:22:56.762+0000"},{"self":"https://issues.apache.org/jira/rest/api/2/issue/12517943/comment/13685347","id":"13685347","author":{"self":"https://issues.apache.org/jira/rest/api/2/user?username=knutanders","name":"knutanders","emailAddress":"knut dot hatlen at oracle dot com","avatarUrls":{"48x48":"https://issues.apache.org/jira/secure/useravatar?avatarId=10452","24x24":"https://issues.apache.org/jira/secure/useravatar?size=small&avatarId=10452","16x16":"https://issues.apache.org/jira/secure/useravatar?size=xsmall&avatarId=10452","32x32":"https://issues.apache.org/jira/secure/useravatar?size=medium&avatarId=10452"},"displayName":"Knut Anders Hatlen","active":true},"body":"[bulk update] Close all resolved issues that haven't been updated for more than one year.","updateAuthor":{"self":"https://issues.apache.org/jira/rest/api/2/user?username=knutanders","name":"knutanders","emailAddress":"knut dot hatlen at oracle dot com","avatarUrls":{"48x48":"https://issues.apache.org/jira/secure/useravatar?avatarId=10452","24x24":"https://issues.apache.org/jira/secure/useravatar?size=small&avatarId=10452","16x16":"https://issues.apache.org/jira/secure/useravatar?size=xsmall&avatarId=10452","32x32":"https://issues.apache.org/jira/secure/useravatar?size=medium&avatarId=10452"},"displayName":"Knut Anders Hatlen","active":true},"created":"2013-06-17T09:19:45.375+0000","updated":"2013-06-17T09:19:45.375+0000"}]},"votes":{"self":"https://issues.apache.org/jira/rest/api/2/issue/DERBY-5374/votes","votes":0,"hasVoted":false},"worklog":{"startAt":0,"maxResults":20,"total":0,"worklogs":[]},"customfield_12311820":"0|i06l07:"}}