{"expand":"renderedFields,names,schema,transitions,operations,editmeta,changelog","id":"27488","self":"https://issues.apache.org/jira/rest/api/latest/issue/27488","key":"DERBY-8","fields":{"issuetype":{"self":"https://issues.apache.org/jira/rest/api/2/issuetype/1","id":"1","description":"A problem which impairs or prevents the functions of the product.","iconUrl":"https://issues.apache.org/jira/images/icons/issuetypes/bug.png","name":"Bug","subtask":false},"timespent":null,"project":{"self":"https://issues.apache.org/jira/rest/api/2/project/10594","id":"10594","key":"DERBY","name":"Derby","avatarUrls":{"48x48":"https://issues.apache.org/jira/secure/projectavatar?pid=10594&avatarId=10122","24x24":"https://issues.apache.org/jira/secure/projectavatar?size=small&pid=10594&avatarId=10122","16x16":"https://issues.apache.org/jira/secure/projectavatar?size=xsmall&pid=10594&avatarId=10122","32x32":"https://issues.apache.org/jira/secure/projectavatar?size=medium&pid=10594&avatarId=10122"},"projectCategory":{"self":"https://issues.apache.org/jira/rest/api/2/projectCategory/10090","id":"10090","description":"DB related projects","name":"DB"}},"fixVersions":[{"self":"https://issues.apache.org/jira/rest/api/2/version/10993","id":"10993","description":"","name":"10.1.1.0","archived":false,"released":true,"releaseDate":"2005-08-03"},{"self":"https://issues.apache.org/jira/rest/api/2/version/11187","id":"11187","description":"","name":"10.2.1.6","archived":false,"released":true,"releaseDate":"2006-10-02"}],"aggregatetimespent":null,"resolution":{"self":"https://issues.apache.org/jira/rest/api/2/resolution/1","id":"1","description":"A fix for this issue is checked into the tree and tested.","name":"Fixed"},"customfield_12310220":"2004-11-30 12:33:43.0","customfield_12312322":null,"customfield_12312323":null,"customfield_12310420":"21711","customfield_12310222":"1_*:*_1_*:*_23184796000_*|*_6_*:*_2_*:*_25290694000_*|*_5_*:*_1_*:*_9000_*|*_4_*:*_1_*:*_38000","customfield_12312320":null,"customfield_12312321":null,"customfield_12312120":null,"customfield_12312121":null,"resolutiondate":"2006-04-12T02:26:11.000+0000","workratio":-1,"customfield_12312328":null,"customfield_12312329":null,"customfield_12312326":null,"customfield_12310300":null,"customfield_12312327":null,"customfield_12312324":null,"customfield_12312325":null,"lastViewed":null,"watches":{"self":"https://issues.apache.org/jira/rest/api/2/issue/DERBY-8/watchers","watchCount":0,"isWatching":false},"created":"2004-09-28T01:00:34.000+0000","priority":{"self":"https://issues.apache.org/jira/rest/api/2/priority/4","iconUrl":"https://issues.apache.org/jira/images/icons/priorities/minor.png","name":"Minor","id":"4"},"labels":[],"customfield_12312333":null,"customfield_12312334":null,"customfield_12310310":"1.0","customfield_12312331":null,"customfield_12312332":null,"timeestimate":null,"aggregatetimeoriginalestimate":null,"versions":[{"self":"https://issues.apache.org/jira/rest/api/2/version/10920","id":"10920","description":"initial source drop","name":"10.0.2.0","archived":false,"released":true,"releaseDate":"2004-08-30"}],"customfield_12311120":null,"customfield_12312330":null,"issuelinks":[{"id":"12310266","self":"https://issues.apache.org/jira/rest/api/2/issueLink/12310266","type":{"id":"12310000","name":"Duplicate","inward":"is duplicated by","outward":"duplicates","self":"https://issues.apache.org/jira/rest/api/2/issueLinkType/12310000"},"inwardIssue":{"id":"12311251","key":"DERBY-346","self":"https://issues.apache.org/jira/rest/api/2/issue/12311251","fields":{"summary":"running jdbcapi/xaSimplePostive.sql under the DerbyNetClient framework gives   error \"Cannot set holdability ResultSet.HOLD_CURSORS_OVER_COMMIT for a global transaction.\"","status":{"self":"https://issues.apache.org/jira/rest/api/2/status/6","description":"The issue is considered finished, the resolution is correct. Issues which are closed can be reopened.","iconUrl":"https://issues.apache.org/jira/images/icons/statuses/closed.png","name":"Closed","id":"6","statusCategory":{"self":"https://issues.apache.org/jira/rest/api/2/statuscategory/3","id":3,"key":"done","colorName":"green","name":"Complete"}},"priority":{"self":"https://issues.apache.org/jira/rest/api/2/priority/3","iconUrl":"https://issues.apache.org/jira/images/icons/priorities/major.png","name":"Major","id":"3"},"issuetype":{"self":"https://issues.apache.org/jira/rest/api/2/issuetype/1","id":"1","description":"A problem which impairs or prevents the functions of the product.","iconUrl":"https://issues.apache.org/jira/images/icons/issuetypes/bug.png","name":"Bug","subtask":false}}}}],"customfield_12312339":null,"assignee":{"self":"https://issues.apache.org/jira/rest/api/2/user?username=mamtas","name":"mamtas","emailAddress":"msatoor at gmail dot com","avatarUrls":{"48x48":"https://issues.apache.org/jira/secure/useravatar?avatarId=10452","24x24":"https://issues.apache.org/jira/secure/useravatar?size=small&avatarId=10452","16x16":"https://issues.apache.org/jira/secure/useravatar?size=xsmall&avatarId=10452","32x32":"https://issues.apache.org/jira/secure/useravatar?size=medium&avatarId=10452"},"displayName":"Mamta A. Satoor","active":true},"customfield_12312337":null,"customfield_12312338":null,"updated":"2006-04-12T02:26:10.000+0000","customfield_12312335":null,"customfield_12311720":null,"customfield_12312336":null,"status":{"self":"https://issues.apache.org/jira/rest/api/2/status/6","description":"The issue is considered finished, the resolution is correct. Issues which are closed can be reopened.","iconUrl":"https://issues.apache.org/jira/images/icons/statuses/closed.png","name":"Closed","id":"6","statusCategory":{"self":"https://issues.apache.org/jira/rest/api/2/statuscategory/3","id":3,"key":"done","colorName":"green","name":"Complete"}},"components":[{"self":"https://issues.apache.org/jira/rest/api/2/component/11407","id":"11407","name":"JDBC"}],"timeoriginalestimate":null,"description":"Reporting for Mamta Satoor, filed on Derby-dev list.\n\nI think there is a bug in Derby when the user code tries to get the\nConnection object from XAConnection \"inside\" the global transaction.\nIn this case, the Connection object gets created with un-supported\nholdability. Look at the following piece of code and it's output to\nsee what exactly happens\n    EmbeddedXADataSource dscsx = new EmbeddedXADataSource();\n    dscsx.setDatabaseName(\"wombat\");\n    XAConnection xac = dscsx.getXAConnection(\"fred\", \"wilma\");\n    XAResource xr = xac.getXAResource();\n    xid = getXid(27, (byte) 21, (byte) 01);\n    xr.start(xid, XAResource.TMNOFLAGS);\n    conn1 = xac.getConnection();\n    System.out.println(\"This is a bug. Connection's holdability should\nhave been CLOSE_CURSORS_AT_COMMIT since it is in the global\ntransaction\");\n    System.out.println(\"CONNECTION(in xa transaction) HOLDABILITY \" +\n(conn1.getHoldability() == ResultSet.HOLD_CURSORS_OVER_COMMIT));\n    System.out.println(\"Autocommit on Connection inside global\ntransaction has been set correctly to \" + conn1.getAutoCommit());\n    xr.end(xid, XAResource.TMSUCCESS);\nThe output for the above piece of code is\n    This is a bug. Connection's holdability should have been\nCLOSE_CURSORS_AT_COMMIT since it is in the global transaction\n    CONNECTION(in xa transaction) HOLDABILITY true\n    Autocommit on Connection inside global transaction has been set\ncorrectly to false\n","customfield_10010":null,"timetracking":{},"customfield_12312026":null,"customfield_12310200":null,"customfield_12312023":null,"customfield_12312024":null,"customfield_12312340":null,"aggregatetimeestimate":null,"customfield_12312022":null,"customfield_12312341":null,"customfield_12312220":null,"customfield_12310921":null,"customfield_12310920":"40753","summary":"Connection object gets created with un-supported holdability on getting Connection object from XAConnection \"inside\" the global transaction","creator":{"self":"https://issues.apache.org/jira/rest/api/2/user?username=tulika","name":"tulika","emailAddress":"tulika dot agrawal at gmail dot com","avatarUrls":{"48x48":"https://issues.apache.org/jira/secure/useravatar?avatarId=10452","24x24":"https://issues.apache.org/jira/secure/useravatar?size=small&avatarId=10452","16x16":"https://issues.apache.org/jira/secure/useravatar?size=xsmall&avatarId=10452","32x32":"https://issues.apache.org/jira/secure/useravatar?size=medium&avatarId=10452"},"displayName":"Tulika Agrawal","active":true},"subtasks":[],"customfield_12310090":null,"reporter":{"self":"https://issues.apache.org/jira/rest/api/2/user?username=tulika","name":"tulika","emailAddress":"tulika dot agrawal at gmail dot com","avatarUrls":{"48x48":"https://issues.apache.org/jira/secure/useravatar?avatarId=10452","24x24":"https://issues.apache.org/jira/secure/useravatar?size=small&avatarId=10452","16x16":"https://issues.apache.org/jira/secure/useravatar?size=xsmall&avatarId=10452","32x32":"https://issues.apache.org/jira/secure/useravatar?size=medium&avatarId=10452"},"displayName":"Tulika Agrawal","active":true},"customfield_12310291":null,"customfield_12310290":null,"aggregateprogress":{"progress":0,"total":0},"environment":null,"customfield_12311020":null,"customfield_12310050":null,"duedate":null,"customfield_12310250":null,"progress":{"progress":0,"total":0},"comment":{"startAt":0,"maxResults":8,"total":8,"comments":[{"self":"https://issues.apache.org/jira/rest/api/2/issue/27488/comment/56026","id":"56026","author":{"self":"https://issues.apache.org/jira/rest/api/2/user?username=shreyas","name":"shreyas","emailAddress":"Shreyas at sun dot com","avatarUrls":{"48x48":"https://issues.apache.org/jira/secure/useravatar?avatarId=10452","24x24":"https://issues.apache.org/jira/secure/useravatar?size=small&avatarId=10452","16x16":"https://issues.apache.org/jira/secure/useravatar?size=xsmall&avatarId=10452","32x32":"https://issues.apache.org/jira/secure/useravatar?size=medium&avatarId=10452"},"displayName":"Shreyas Kaushik","active":true},"body":"My comments on this issue:\r\n\r\nBoth the XAResource and the Connection handle got by calling a getConnection() method on a XAConnection are child entities of the XAConnection. So the XAResource and the Connection are in parallel if a hierarchy is imagined with a XAConnection as the head. \r\n  So the Connection handle got by calling a getConnection method on the XAResource is not bound to have the same holdability for cursors as that of the Transaction. It should have its own holdability state.\r\n\r\nMoreover in a managed sscenario the XAConnection interface is not directly used, we just get a java.sql.Connection handle by calling the getConnection method on the DataSource. It is the DataSource configuration that determines what all happens behind the scene to return a Connection handle.\r\n\r\nSo in my opinion Derby is behaving properly.","updateAuthor":{"self":"https://issues.apache.org/jira/rest/api/2/user?username=shreyas","name":"shreyas","emailAddress":"Shreyas at sun dot com","avatarUrls":{"48x48":"https://issues.apache.org/jira/secure/useravatar?avatarId=10452","24x24":"https://issues.apache.org/jira/secure/useravatar?size=small&avatarId=10452","16x16":"https://issues.apache.org/jira/secure/useravatar?size=xsmall&avatarId=10452","32x32":"https://issues.apache.org/jira/secure/useravatar?size=medium&avatarId=10452"},"displayName":"Shreyas Kaushik","active":true},"created":"2004-11-30T12:33:43.000+0000","updated":"2004-11-30T12:33:43.000+0000"},{"self":"https://issues.apache.org/jira/rest/api/2/issue/27488/comment/56076","id":"56076","author":{"self":"https://issues.apache.org/jira/rest/api/2/user?username=mamtas","name":"mamtas","emailAddress":"msatoor at gmail dot com","avatarUrls":{"48x48":"https://issues.apache.org/jira/secure/useravatar?avatarId=10452","24x24":"https://issues.apache.org/jira/secure/useravatar?size=small&avatarId=10452","16x16":"https://issues.apache.org/jira/secure/useravatar?size=xsmall&avatarId=10452","32x32":"https://issues.apache.org/jira/secure/useravatar?size=medium&avatarId=10452"},"displayName":"Mamta A. Satoor","active":true},"body":"Should we then reconsider what happens to the holdability of the connection handle(got by calling a getConnection() method on a XAConnection OUTSIDE the global transaction) when it becomes part of a global transaction? \r\n\r\nFollowing example code shows that Derby currently (silently) switches the the holdability of the connection handle from HOLD_CURSORS_OVER_COMMIT to CLOSE_CURSORS_AT_COMMIT when it becomes part of the global transaction.\r\n\r\n    EmbeddedXADataSource dscsx = new EmbeddedXADataSource(); \r\n    dscsx.setDatabaseName(\"wombat\"); \r\n    XAConnection xac = dscsx.getXAConnection(\"fred\", \"wilma\"); \r\n    XAResource xr = xac.getXAResource(); \r\n    Xid xid = getXid(27, (byte) 21, (byte) 01); \r\n    Connection conn1 = xac.getConnection(); \r\n    System.out.println(\"By default, autocommit is \" + conn1.getAutoCommit() + \" for a connection\");\r\n    System.out.println(\"Default holdability for a connection is HOLD_CURSORS_OVER_COMMIT\");\r\n    System.out.println(\"CONNECTION(not in xa transaction yet) HOLDABILITY \" + (conn1.getHoldability() == ResultSet.HOLD_CURSORS_OVER_COMMIT));\r\n    xr.start(xid, XAResource.TMNOFLAGS);\r\n    System.out.println(\"Notice that autocommit now is \" + conn1.getAutoCommit() + \" for connection because it is part of the global transaction\");\r\n    System.out.println(\"Notice that connection's holdability at this point is CLOSE_CURSORS_AT_COMMIT because it is part of the global transaction\");\r\n    System.out.println(\"CONNECTION(in xa transaction) HOLDABILITY \" + (conn1.getHoldability() == ResultSet.HOLD_CURSORS_OVER_COMMIT));\r\n\r\nOutput of this code snippet when run under Derby is as follows.\r\nSTART XA HOLDABILITY TEST\r\nBy default, autocommit is true for a connection\r\nDefault holdability for a connection is HOLD_CURSORS_OVER_COMMIT\r\nCONNECTION(not in xa transaction yet) HOLDABILITY true\r\nNotice that autocommit now is false for connection because it is part of the global transaction\r\nNotice that connection's holdability at this point is CLOSE_CURSORS_AT_COMMIT because it is part of the global transaction\r\nCONNECTION(in xa transaction) HOLDABILITY false\r\n\r\nthanks,\r\nMamta","updateAuthor":{"self":"https://issues.apache.org/jira/rest/api/2/user?username=mamtas","name":"mamtas","emailAddress":"msatoor at gmail dot com","avatarUrls":{"48x48":"https://issues.apache.org/jira/secure/useravatar?avatarId=10452","24x24":"https://issues.apache.org/jira/secure/useravatar?size=small&avatarId=10452","16x16":"https://issues.apache.org/jira/secure/useravatar?size=xsmall&avatarId=10452","32x32":"https://issues.apache.org/jira/secure/useravatar?size=medium&avatarId=10452"},"displayName":"Mamta A. Satoor","active":true},"created":"2004-12-01T23:05:16.000+0000","updated":"2004-12-01T23:05:16.000+0000"},{"self":"https://issues.apache.org/jira/rest/api/2/issue/27488/comment/56080","id":"56080","author":{"self":"https://issues.apache.org/jira/rest/api/2/user?username=djd","name":"djd","emailAddress":"djd at apache dot org","avatarUrls":{"48x48":"https://issues.apache.org/jira/secure/useravatar?avatarId=10452","24x24":"https://issues.apache.org/jira/secure/useravatar?size=small&avatarId=10452","16x16":"https://issues.apache.org/jira/secure/useravatar?size=xsmall&avatarId=10452","32x32":"https://issues.apache.org/jira/secure/useravatar?size=medium&avatarId=10452"},"displayName":"Daniel John Debrunner","active":true},"body":"I think the point is being missed that Derby does not support holdability when in a global transaction, thus holdability should always be CLOSE_CURSORS_AT_COMMIT when in a global transaction, regardless of the state set by the connection in local mode. So I believe the bug summary is correct, and there is a bug.","updateAuthor":{"self":"https://issues.apache.org/jira/rest/api/2/user?username=djd","name":"djd","emailAddress":"djd at apache dot org","avatarUrls":{"48x48":"https://issues.apache.org/jira/secure/useravatar?avatarId=10452","24x24":"https://issues.apache.org/jira/secure/useravatar?size=small&avatarId=10452","16x16":"https://issues.apache.org/jira/secure/useravatar?size=xsmall&avatarId=10452","32x32":"https://issues.apache.org/jira/secure/useravatar?size=medium&avatarId=10452"},"displayName":"Daniel John Debrunner","active":true},"created":"2004-12-02T03:25:29.000+0000","updated":"2004-12-02T03:25:29.000+0000"},{"self":"https://issues.apache.org/jira/rest/api/2/issue/27488/comment/12313960","id":"12313960","author":{"self":"https://issues.apache.org/jira/rest/api/2/user?username=mamtas","name":"mamtas","emailAddress":"msatoor at gmail dot com","avatarUrls":{"48x48":"https://issues.apache.org/jira/secure/useravatar?avatarId=10452","24x24":"https://issues.apache.org/jira/secure/useravatar?size=small&avatarId=10452","16x16":"https://issues.apache.org/jira/secure/useravatar?size=xsmall&avatarId=10452","32x32":"https://issues.apache.org/jira/secure/useravatar?size=medium&avatarId=10452"},"displayName":"Mamta A. Satoor","active":true},"body":"I have a patch to fix Derby-8 (Connection object gets created with un-supported holdability on getting Connection object from XAConnection \"inside\" the global transaction) and Derby-366 (In jdk13, when a connection transitions from global transaction to local transaction, its default holdability of HOLD_CURSORS_OVER_COMMIT is not restored.) The patch is attached to both Derby-8 and Derby-366.\r\n\r\nThe fix for both these bugs was centered around fixing the holdability handling in BrokeredConnection.java This was because BrokeredConnection.java had no code for restoring the holdability of real connection object and no code for saving the current holdability state of real connection object. I put fix for both these issues in BrokeredConnection.java so that both jdk13 and jdk14+ environments will be handled correctly. Had to use reflection for this holdability work\r\nbecause Connection.setHoldability and Connection.getHoldability methods are not available through JDK13 apis.\r\n\r\nsvn stat \r\nM      java\\engine\\org\\apache\\derby\\iapi\\jdbc\\BrokeredConnection.java\r\nM      java\\engine\\org\\apache\\derby\\iapi\\jdbc\\BrokeredConnection30.java\r\nM      java\\testing\\org\\apache\\derbyTesting\\functionTests\\tests\\store\\xaOffline1.sql\r\nM      java\\testing\\org\\apache\\derbyTesting\\functionTests\\tests\\store\\xab2354.sql\r\nM      java\\testing\\org\\apache\\derbyTesting\\functionTests\\tests\\jdbcapi\\xaAnotherTest.sql\r\nM      java\\testing\\org\\apache\\derbyTesting\\functionTests\\tests\\jdbcapi\\xaSimplePositive.sql\r\nM      java\\testing\\org\\apache\\derbyTesting\\functionTests\\tests\\jdbcapi\\xaSimpleNegative.sql\r\nM      java\\testing\\org\\apache\\derbyTesting\\functionTests\\tests\\jdbcapi\\checkDataSource30.java\r\nM      java\\testing\\org\\apache\\derbyTesting\\functionTests\\master\\xaOffline1.out\r\nM      java\\testing\\org\\apache\\derbyTesting\\functionTests\\master\\xaSimplePositive.out\r\nM      java\\testing\\org\\apache\\derbyTesting\\functionTests\\master\\xab2354.out\r\nM      java\\testing\\org\\apache\\derbyTesting\\functionTests\\master\\xaSimpleNegative.out\r\nM      java\\testing\\org\\apache\\derbyTesting\\functionTests\\master\\xaAnotherTest.out\r\nM      java\\testing\\org\\apache\\derbyTesting\\functionTests\\master\\checkDataSource30.out\r\n\r\nKathey, may be you can try this fix with Network Server and see if it resolves any related issues you had there?\r\n\r\nI have run the test suite and this fix has not caused any failures. Have changed some of the existing XA tests so that they can rely on correct holdability status inside and outside global transaction.\r\n\r\nIf no comments from anyone, can a commiter please commit this patch?\r\n","updateAuthor":{"self":"https://issues.apache.org/jira/rest/api/2/user?username=mamtas","name":"mamtas","emailAddress":"msatoor at gmail dot com","avatarUrls":{"48x48":"https://issues.apache.org/jira/secure/useravatar?avatarId=10452","24x24":"https://issues.apache.org/jira/secure/useravatar?size=small&avatarId=10452","16x16":"https://issues.apache.org/jira/secure/useravatar?size=xsmall&avatarId=10452","32x32":"https://issues.apache.org/jira/secure/useravatar?size=medium&avatarId=10452"},"displayName":"Mamta A. Satoor","active":true},"created":"2005-06-18T16:54:35.000+0000","updated":"2005-06-18T16:54:35.000+0000"},{"self":"https://issues.apache.org/jira/rest/api/2/issue/27488/comment/12314196","id":"12314196","author":{"self":"https://issues.apache.org/jira/rest/api/2/user?username=kmarsden","name":"kmarsden","emailAddress":"kmarsdenderby at sbcglobal dot net","avatarUrls":{"48x48":"https://issues.apache.org/jira/secure/useravatar?avatarId=10452","24x24":"https://issues.apache.org/jira/secure/useravatar?size=small&avatarId=10452","16x16":"https://issues.apache.org/jira/secure/useravatar?size=xsmall&avatarId=10452","32x32":"https://issues.apache.org/jira/secure/useravatar?size=medium&avatarId=10452"},"displayName":"Kathey Marsden","active":true},"body":"Checked this in.\r\nTransmitting file data ...............\r\nCommitted revision 191755.\r\n","updateAuthor":{"self":"https://issues.apache.org/jira/rest/api/2/user?username=kmarsden","name":"kmarsden","emailAddress":"kmarsdenderby at sbcglobal dot net","avatarUrls":{"48x48":"https://issues.apache.org/jira/secure/useravatar?avatarId=10452","24x24":"https://issues.apache.org/jira/secure/useravatar?size=small&avatarId=10452","16x16":"https://issues.apache.org/jira/secure/useravatar?size=xsmall&avatarId=10452","32x32":"https://issues.apache.org/jira/secure/useravatar?size=medium&avatarId=10452"},"displayName":"Kathey Marsden","active":true},"created":"2005-06-22T13:09:51.000+0000","updated":"2005-06-22T13:09:51.000+0000"},{"self":"https://issues.apache.org/jira/rest/api/2/issue/27488/comment/12314249","id":"12314249","author":{"self":"https://issues.apache.org/jira/rest/api/2/user?username=kmarsden","name":"kmarsden","emailAddress":"kmarsdenderby at sbcglobal dot net","avatarUrls":{"48x48":"https://issues.apache.org/jira/secure/useravatar?avatarId=10452","24x24":"https://issues.apache.org/jira/secure/useravatar?size=small&avatarId=10452","16x16":"https://issues.apache.org/jira/secure/useravatar?size=xsmall&avatarId=10452","32x32":"https://issues.apache.org/jira/secure/useravatar?size=medium&avatarId=10452"},"displayName":"Kathey Marsden","active":true},"body":"This issue was fixed with Mamta's fix for DERBY-8 and DERBY366.  I think this one is actually a dup of DERBY-8","updateAuthor":{"self":"https://issues.apache.org/jira/rest/api/2/user?username=kmarsden","name":"kmarsden","emailAddress":"kmarsdenderby at sbcglobal dot net","avatarUrls":{"48x48":"https://issues.apache.org/jira/secure/useravatar?avatarId=10452","24x24":"https://issues.apache.org/jira/secure/useravatar?size=small&avatarId=10452","16x16":"https://issues.apache.org/jira/secure/useravatar?size=xsmall&avatarId=10452","32x32":"https://issues.apache.org/jira/secure/useravatar?size=medium&avatarId=10452"},"displayName":"Kathey Marsden","active":true},"created":"2005-06-23T03:15:15.000+0000","updated":"2005-06-23T03:15:15.000+0000"},{"self":"https://issues.apache.org/jira/rest/api/2/issue/27488/comment/12314276","id":"12314276","author":{"self":"https://issues.apache.org/jira/rest/api/2/user?username=mamtas","name":"mamtas","emailAddress":"msatoor at gmail dot com","avatarUrls":{"48x48":"https://issues.apache.org/jira/secure/useravatar?avatarId=10452","24x24":"https://issues.apache.org/jira/secure/useravatar?size=small&avatarId=10452","16x16":"https://issues.apache.org/jira/secure/useravatar?size=xsmall&avatarId=10452","32x32":"https://issues.apache.org/jira/secure/useravatar?size=medium&avatarId=10452"},"displayName":"Mamta A. Satoor","active":true},"body":"The fix has been committed by Kathey","updateAuthor":{"self":"https://issues.apache.org/jira/rest/api/2/user?username=mamtas","name":"mamtas","emailAddress":"msatoor at gmail dot com","avatarUrls":{"48x48":"https://issues.apache.org/jira/secure/useravatar?avatarId=10452","24x24":"https://issues.apache.org/jira/secure/useravatar?size=small&avatarId=10452","16x16":"https://issues.apache.org/jira/secure/useravatar?size=xsmall&avatarId=10452","32x32":"https://issues.apache.org/jira/secure/useravatar?size=medium&avatarId=10452"},"displayName":"Mamta A. Satoor","active":true},"created":"2005-06-23T09:13:50.000+0000","updated":"2005-06-23T09:13:50.000+0000"},{"self":"https://issues.apache.org/jira/rest/api/2/issue/27488/comment/12374088","id":"12374088","author":{"self":"https://issues.apache.org/jira/rest/api/2/user?username=mamtas","name":"mamtas","emailAddress":"msatoor at gmail dot com","avatarUrls":{"48x48":"https://issues.apache.org/jira/secure/useravatar?avatarId=10452","24x24":"https://issues.apache.org/jira/secure/useravatar?size=small&avatarId=10452","16x16":"https://issues.apache.org/jira/secure/useravatar?size=xsmall&avatarId=10452","32x32":"https://issues.apache.org/jira/secure/useravatar?size=medium&avatarId=10452"},"displayName":"Mamta A. Satoor","active":true},"body":"Need to put correct fix-in version","updateAuthor":{"self":"https://issues.apache.org/jira/rest/api/2/user?username=mamtas","name":"mamtas","emailAddress":"msatoor at gmail dot com","avatarUrls":{"48x48":"https://issues.apache.org/jira/secure/useravatar?avatarId=10452","24x24":"https://issues.apache.org/jira/secure/useravatar?size=small&avatarId=10452","16x16":"https://issues.apache.org/jira/secure/useravatar?size=xsmall&avatarId=10452","32x32":"https://issues.apache.org/jira/secure/useravatar?size=medium&avatarId=10452"},"displayName":"Mamta A. Satoor","active":true},"created":"2006-04-12T02:25:33.000+0000","updated":"2006-04-12T02:25:33.000+0000"}]},"votes":{"self":"https://issues.apache.org/jira/rest/api/2/issue/DERBY-8/votes","votes":0,"hasVoted":false},"worklog":{"startAt":0,"maxResults":20,"total":0,"worklogs":[]},"customfield_12311820":"0|i07c9j:"}}