{"expand":"renderedFields,names,schema,transitions,operations,editmeta,changelog","id":"12346651","self":"https://issues.apache.org/jira/rest/api/latest/issue/12346651","key":"DERBY-1589","fields":{"issuetype":{"self":"https://issues.apache.org/jira/rest/api/2/issuetype/1","id":"1","description":"A problem which impairs or prevents the functions of the product.","iconUrl":"https://issues.apache.org/jira/images/icons/issuetypes/bug.png","name":"Bug","subtask":false},"timespent":null,"project":{"self":"https://issues.apache.org/jira/rest/api/2/project/10594","id":"10594","key":"DERBY","name":"Derby","avatarUrls":{"48x48":"https://issues.apache.org/jira/secure/projectavatar?pid=10594&avatarId=10122","24x24":"https://issues.apache.org/jira/secure/projectavatar?size=small&pid=10594&avatarId=10122","16x16":"https://issues.apache.org/jira/secure/projectavatar?size=xsmall&pid=10594&avatarId=10122","32x32":"https://issues.apache.org/jira/secure/projectavatar?size=medium&pid=10594&avatarId=10122"},"projectCategory":{"self":"https://issues.apache.org/jira/rest/api/2/projectCategory/10090","id":"10090","description":"DB related projects","name":"DB"}},"fixVersions":[{"self":"https://issues.apache.org/jira/rest/api/2/version/12312590","id":"12312590","description":"","name":"10.3.1.4","archived":false,"released":true,"releaseDate":"2007-08-10"}],"aggregatetimespent":null,"resolution":{"self":"https://issues.apache.org/jira/rest/api/2/resolution/1","id":"1","description":"A fix for this issue is checked into the tree and tested.","name":"Fixed"},"customfield_12310220":"2006-08-24 14:12:49.0","customfield_12312322":null,"customfield_12312323":null,"customfield_12310420":"22584","customfield_12310222":"1_*:*_1_*:*_4764262000_*|*_6_*:*_1_*:*_0_*|*_5_*:*_1_*:*_38913216703","customfield_12312320":null,"customfield_12312321":null,"customfield_12312120":null,"customfield_12312121":null,"resolutiondate":"2006-09-18T23:51:30.000+0000","workratio":-1,"customfield_12312328":null,"customfield_12312329":null,"customfield_12312326":null,"customfield_12310300":null,"customfield_12312327":null,"customfield_12312324":null,"customfield_12312325":null,"lastViewed":null,"watches":{"self":"https://issues.apache.org/jira/rest/api/2/issue/DERBY-1589/watchers","watchCount":0,"isWatching":false},"created":"2006-07-25T20:27:08.000+0000","priority":{"self":"https://issues.apache.org/jira/rest/api/2/priority/3","iconUrl":"https://issues.apache.org/jira/images/icons/priorities/major.png","name":"Major","id":"3"},"labels":[],"customfield_12312333":null,"customfield_12312334":null,"customfield_12310310":"1.0","customfield_12312331":null,"customfield_12312332":null,"timeestimate":null,"aggregatetimeoriginalestimate":null,"versions":[{"self":"https://issues.apache.org/jira/rest/api/2/version/11187","id":"11187","description":"","name":"10.2.1.6","archived":false,"released":true,"releaseDate":"2006-10-02"}],"customfield_12311120":null,"customfield_12312330":null,"issuelinks":[{"id":"12312897","self":"https://issues.apache.org/jira/rest/api/2/issueLink/12312897","type":{"id":"10030","name":"Reference","inward":"is related to","outward":"relates to","self":"https://issues.apache.org/jira/rest/api/2/issueLinkType/10030"},"outwardIssue":{"id":"12346116","key":"DERBY-1523","self":"https://issues.apache.org/jira/rest/api/2/issue/12346116","fields":{"summary":"Statements in cache need to depend on privileges and the appropriate statements in cache should get invalidated if those privileges change.","status":{"self":"https://issues.apache.org/jira/rest/api/2/status/6","description":"The issue is considered finished, the resolution is correct. Issues which are closed can be reopened.","iconUrl":"https://issues.apache.org/jira/images/icons/statuses/closed.png","name":"Closed","id":"6","statusCategory":{"self":"https://issues.apache.org/jira/rest/api/2/statuscategory/3","id":3,"key":"done","colorName":"green","name":"Complete"}},"priority":{"self":"https://issues.apache.org/jira/rest/api/2/priority/3","iconUrl":"https://issues.apache.org/jira/images/icons/priorities/major.png","name":"Major","id":"3"},"issuetype":{"self":"https://issues.apache.org/jira/rest/api/2/issuetype/1","id":"1","description":"A problem which impairs or prevents the functions of the product.","iconUrl":"https://issues.apache.org/jira/images/icons/issuetypes/bug.png","name":"Bug","subtask":false}}}},{"id":"12312899","self":"https://issues.apache.org/jira/rest/api/2/issueLink/12312899","type":{"id":"10030","name":"Reference","inward":"is related to","outward":"relates to","self":"https://issues.apache.org/jira/rest/api/2/issueLinkType/10030"},"outwardIssue":{"id":"12312336","key":"DERBY-464","self":"https://issues.apache.org/jira/rest/api/2/issue/12312336","fields":{"summary":"Enhance Derby by adding grant/revoke support. Grant/Revoke provide finner level of privileges than currently provided by Derby that is especially useful in network configurations.","status":{"self":"https://issues.apache.org/jira/rest/api/2/status/6","description":"The issue is considered finished, the resolution is correct. Issues which are closed can be reopened.","iconUrl":"https://issues.apache.org/jira/images/icons/statuses/closed.png","name":"Closed","id":"6","statusCategory":{"self":"https://issues.apache.org/jira/rest/api/2/statuscategory/3","id":3,"key":"done","colorName":"green","name":"Complete"}},"priority":{"self":"https://issues.apache.org/jira/rest/api/2/priority/3","iconUrl":"https://issues.apache.org/jira/images/icons/priorities/major.png","name":"Major","id":"3"},"issuetype":{"self":"https://issues.apache.org/jira/rest/api/2/issuetype/4","id":"4","description":"An improvement or enhancement to an existing feature or task.","iconUrl":"https://issues.apache.org/jira/images/icons/issuetypes/improvement.png","name":"Improvement","subtask":false}}}}],"customfield_12312339":null,"assignee":{"self":"https://issues.apache.org/jira/rest/api/2/user?username=bryanpendleton","name":"bryanpendleton","emailAddress":"bpendleton dot derby at gmail dot com","avatarUrls":{"48x48":"https://issues.apache.org/jira/secure/useravatar?avatarId=10452","24x24":"https://issues.apache.org/jira/secure/useravatar?size=small&avatarId=10452","16x16":"https://issues.apache.org/jira/secure/useravatar?size=xsmall&avatarId=10452","32x32":"https://issues.apache.org/jira/secure/useravatar?size=medium&avatarId=10452"},"displayName":"Bryan Pendleton","active":true},"customfield_12312337":null,"customfield_12312338":null,"updated":"2007-12-13T09:05:06.701+0000","customfield_12312335":null,"customfield_12311720":null,"customfield_12312336":null,"status":{"self":"https://issues.apache.org/jira/rest/api/2/status/6","description":"The issue is considered finished, the resolution is correct. Issues which are closed can be reopened.","iconUrl":"https://issues.apache.org/jira/images/icons/statuses/closed.png","name":"Closed","id":"6","statusCategory":{"self":"https://issues.apache.org/jira/rest/api/2/statuscategory/3","id":3,"key":"done","colorName":"green","name":"Complete"}},"components":[{"self":"https://issues.apache.org/jira/rest/api/2/component/11408","id":"11408","name":"SQL"}],"timeoriginalestimate":null,"description":"Currently, the last sql statement in following set of sql statements will raise a null pointer exception\n\nconnect 'jdbc:derby:c:/dellater/dbmaintest2;create=true' user 'mamta1' as mamta1;\ncreate table t11ConstraintTest (c111 int not null, c112 int not null, primary key (c111, c112));\ngrant references on t11ConstraintTest to mamta3;\nconnect 'jdbc:derby:c:/dellater/dbmaintest2;create=true' user 'mamta3' as mamta3;\ndrop table t31ConstraintTest;\n-- the following statement should remember that it depends on REFERENCES privilege on mamta1.t11ConstraintTest\ncreate table t31ConstraintTest (c311 int, c312 int, foreign key(c311, c312) references mamta1.t11ConstraintTest);\ndrop table t31ConstraintTest;\nset connection mamta1;\n-- following should revoke all the privileges granted on it\ndrop table t11ConstraintTest;\ncreate table t11ConstraintTest (c111 int not null, c112 int not null, primary key (c111, c112));\ngrant references(c111) on t11ConstraintTest to mamta3;\ngrant references(c112) on t11ConstraintTest to PUBLIC;\n--connect 'jdbc:derby:c:/dellater/dbmaintest2;create=true' user 'mamta3' as mamta3;\nset connection mamta3;\ndrop table t31ConstraintTest;\n-- following sql should recompie itself because the earlier plan depended on a privilege which doesn't\n-- exist anymore. Instead, new privileges have been granted and the plan for following statement should depend\n-- on those new privileges\ncreate table t31ConstraintTest (c311 int, c312 int, foreign key(c311, c312) references mamta1.t11ConstraintTest); ","customfield_10010":null,"timetracking":{},"customfield_12312026":null,"customfield_12310200":null,"customfield_12312023":null,"customfield_12312024":null,"customfield_12312340":null,"aggregatetimeestimate":null,"customfield_12312022":null,"customfield_12312341":null,"customfield_12312220":null,"customfield_12310921":null,"customfield_12310920":"39669","summary":"CREATE TABLE throws NullPointerException in Derby SQL Standard Authorization after DROPs and REVOKES","creator":{"self":"https://issues.apache.org/jira/rest/api/2/user?username=djd","name":"djd","emailAddress":"djd at apache dot org","avatarUrls":{"48x48":"https://issues.apache.org/jira/secure/useravatar?avatarId=10452","24x24":"https://issues.apache.org/jira/secure/useravatar?size=small&avatarId=10452","16x16":"https://issues.apache.org/jira/secure/useravatar?size=xsmall&avatarId=10452","32x32":"https://issues.apache.org/jira/secure/useravatar?size=medium&avatarId=10452"},"displayName":"Daniel John Debrunner","active":true},"subtasks":[],"customfield_12310090":null,"reporter":{"self":"https://issues.apache.org/jira/rest/api/2/user?username=djd","name":"djd","emailAddress":"djd at apache dot org","avatarUrls":{"48x48":"https://issues.apache.org/jira/secure/useravatar?avatarId=10452","24x24":"https://issues.apache.org/jira/secure/useravatar?size=small&avatarId=10452","16x16":"https://issues.apache.org/jira/secure/useravatar?size=xsmall&avatarId=10452","32x32":"https://issues.apache.org/jira/secure/useravatar?size=medium&avatarId=10452"},"displayName":"Daniel John Debrunner","active":true},"customfield_12310291":null,"customfield_12310290":null,"aggregateprogress":{"progress":0,"total":0},"environment":null,"customfield_12311020":null,"customfield_12310050":{"self":"https://issues.apache.org/jira/rest/api/2/customFieldOption/10052","value":"Normal","id":"10052"},"duedate":null,"customfield_12310250":null,"progress":{"progress":0,"total":0},"comment":{"startAt":0,"maxResults":14,"total":14,"comments":[{"self":"https://issues.apache.org/jira/rest/api/2/issue/12346651/comment/12423442","id":"12423442","author":{"self":"https://issues.apache.org/jira/rest/api/2/user?username=djd","name":"djd","emailAddress":"djd at apache dot org","avatarUrls":{"48x48":"https://issues.apache.org/jira/secure/useravatar?avatarId=10452","24x24":"https://issues.apache.org/jira/secure/useravatar?size=small&avatarId=10452","16x16":"https://issues.apache.org/jira/secure/useravatar?size=xsmall&avatarId=10452","32x32":"https://issues.apache.org/jira/secure/useravatar?size=medium&avatarId=10452"},"displayName":"Daniel John Debrunner","active":true},"body":"Original entered as DERBY-1523","updateAuthor":{"self":"https://issues.apache.org/jira/rest/api/2/user?username=djd","name":"djd","emailAddress":"djd at apache dot org","avatarUrls":{"48x48":"https://issues.apache.org/jira/secure/useravatar?avatarId=10452","24x24":"https://issues.apache.org/jira/secure/useravatar?size=small&avatarId=10452","16x16":"https://issues.apache.org/jira/secure/useravatar?size=xsmall&avatarId=10452","32x32":"https://issues.apache.org/jira/secure/useravatar?size=medium&avatarId=10452"},"displayName":"Daniel John Debrunner","active":true},"created":"2006-07-25T20:28:03.000+0000","updated":"2006-07-25T20:28:03.000+0000"},{"self":"https://issues.apache.org/jira/rest/api/2/issue/12346651/comment/12430246","id":"12430246","author":{"self":"https://issues.apache.org/jira/rest/api/2/user?username=rhillegas","name":"rhillegas","emailAddress":"rhillegas at apache dot org","avatarUrls":{"48x48":"https://issues.apache.org/jira/secure/useravatar?avatarId=10452","24x24":"https://issues.apache.org/jira/secure/useravatar?size=small&avatarId=10452","16x16":"https://issues.apache.org/jira/secure/useravatar?size=xsmall&avatarId=10452","32x32":"https://issues.apache.org/jira/secure/useravatar?size=medium&avatarId=10452"},"displayName":"Rick Hillegas","active":true},"body":"Assign to 10.2 and bump urgency.","updateAuthor":{"self":"https://issues.apache.org/jira/rest/api/2/user?username=rhillegas","name":"rhillegas","emailAddress":"rhillegas at apache dot org","avatarUrls":{"48x48":"https://issues.apache.org/jira/secure/useravatar?avatarId=10452","24x24":"https://issues.apache.org/jira/secure/useravatar?size=small&avatarId=10452","16x16":"https://issues.apache.org/jira/secure/useravatar?size=xsmall&avatarId=10452","32x32":"https://issues.apache.org/jira/secure/useravatar?size=medium&avatarId=10452"},"displayName":"Rick Hillegas","active":true},"created":"2006-08-24T14:12:49.000+0000","updated":"2006-08-24T14:12:49.000+0000"},{"self":"https://issues.apache.org/jira/rest/api/2/issue/12346651/comment/12433215","id":"12433215","author":{"self":"https://issues.apache.org/jira/rest/api/2/user?username=mamtas","name":"mamtas","emailAddress":"msatoor at gmail dot com","avatarUrls":{"48x48":"https://issues.apache.org/jira/secure/useravatar?avatarId=10452","24x24":"https://issues.apache.org/jira/secure/useravatar?size=small&avatarId=10452","16x16":"https://issues.apache.org/jira/secure/useravatar?size=xsmall&avatarId=10452","32x32":"https://issues.apache.org/jira/secure/useravatar?size=medium&avatarId=10452"},"displayName":"Mamta A. Satoor","active":true},"body":"I noticed that the stack trace for null pointer exception was not included in this jira entry. So, I ran the following sql script using ij in the trunk\r\nconnect 'jdbc:derby:c:/dellater/dbmaintest2;create=true' user 'mamta1' as mamta1; \r\ncreate table t11ConstraintTest (c111 int not null, c112 int not null, primary key (c111, c112)); \r\ngrant references on t11ConstraintTest to mamta3; \r\nconnect 'jdbc:derby:c:/dellater/dbmaintest2;create=true' user 'mamta3' as mamta3; \r\ndrop table t31ConstraintTest; \r\ncreate table t31ConstraintTest (c311 int, c312 int, foreign key(c311, c312) references mamta1.t11ConstraintTest); \r\ndrop table t31ConstraintTest; \r\nset connection mamta1; \r\ndrop table t11ConstraintTest; \r\ncreate table t11ConstraintTest (c111 int not null, c112 int not null, primary key (c111, c112)); \r\ngrant references(c111) on t11ConstraintTest to mamta3; \r\ngrant references(c112) on t11ConstraintTest to PUBLIC; \r\nset connection mamta3; \r\ndrop table t31ConstraintTest; \r\ncreate table t31ConstraintTest (c311 int, c312 int, foreign key(c311, c312) references mamta1.t11ConstraintTest); \r\n \r\n\r\nAnd the last create table always gave null pointer exception. The stack trace looks as follows\r\n        at org.apache.derby.iapi.sql.dictionary.TablePermsDescriptor.<init>(TablePermsDescriptor.java:70)\r\n        at org.apache.derby.iapi.sql.dictionary.TablePermsDescriptor.<init>(TablePermsDescriptor.java:81)\r\n        at org.apache.derby.impl.sql.catalog.DataDictionaryImpl.getTablePermissions(DataDictionaryImpl.java:9962)\r\n        at org.apache.derby.iapi.sql.dictionary.StatementTablePermission.oneAuthHasPermissionOnTable(StatementTablePermission.java:148)\r\n        at org.apache.derby.iapi.sql.dictionary.StatementTablePermission.hasPermissionOnTable(StatementTablePermission.java:141)\r\n        at org.apache.derby.iapi.sql.dictionary.StatementColumnPermission.check(StatementColumnPermission.java:94)\r\n        at org.apache.derby.impl.sql.conn.GenericAuthorizer.authorize(GenericAuthorizer.java:158)\r\n        at org.apache.derby.impl.sql.execute.GenericResultSetFactory.getDDLResultSet(GenericResultSetFactory.java:1020)\r\n        at org.apache.derby.impl.sql.execute.ConstantActionActivation.execute(ConstantActionActivation.java:54)\r\n        at org.apache.derby.impl.sql.GenericActivationHolder.execute(GenericActivationHolder.java:327)\r\n        at org.apache.derby.impl.sql.GenericPreparedStatement.execute(GenericPreparedStatement.java:356)\r\n        at org.apache.derby.impl.jdbc.EmbedStatement.executeStatement(EmbedStatement.java:1182)\r\n        at org.apache.derby.impl.jdbc.EmbedStatement.execute(EmbedStatement.java:585)\r\n        at org.apache.derby.impl.jdbc.EmbedStatement.execute(EmbedStatement.java:517)\r\n        at org.apache.derby.impl.tools.ij.ij.executeImmediate(ij.java:321)\r\n        at org.apache.derby.impl.tools.ij.utilMain.doCatch(utilMain.java:517)\r\n        at org.apache.derby.impl.tools.ij.utilMain.runScriptGuts(utilMain.java:370)\r\n        at org.apache.derby.impl.tools.ij.utilMain.go(utilMain.java:268)\r\n        at org.apache.derby.impl.tools.ij.Main.go(Main.java:204)\r\n        at org.apache.derby.impl.tools.ij.Main.mainCore(Main.java:170)\r\n        at org.apache.derby.impl.tools.ij.Main14.main(Main14.java:56)\r\n        at org.apache.derby.tools.ij.main(ij.java:71)","updateAuthor":{"self":"https://issues.apache.org/jira/rest/api/2/user?username=mamtas","name":"mamtas","emailAddress":"msatoor at gmail dot com","avatarUrls":{"48x48":"https://issues.apache.org/jira/secure/useravatar?avatarId=10452","24x24":"https://issues.apache.org/jira/secure/useravatar?size=small&avatarId=10452","16x16":"https://issues.apache.org/jira/secure/useravatar?size=xsmall&avatarId=10452","32x32":"https://issues.apache.org/jira/secure/useravatar?size=medium&avatarId=10452"},"displayName":"Mamta A. Satoor","active":true},"created":"2006-09-07T20:01:15.000+0000","updated":"2006-09-07T20:01:15.000+0000"},{"self":"https://issues.apache.org/jira/rest/api/2/issue/12346651/comment/12434491","id":"12434491","author":{"self":"https://issues.apache.org/jira/rest/api/2/user?username=bryanpendleton","name":"bryanpendleton","emailAddress":"bpendleton dot derby at gmail dot com","avatarUrls":{"48x48":"https://issues.apache.org/jira/secure/useravatar?avatarId=10452","24x24":"https://issues.apache.org/jira/secure/useravatar?size=small&avatarId=10452","16x16":"https://issues.apache.org/jira/secure/useravatar?size=xsmall&avatarId=10452","32x32":"https://issues.apache.org/jira/secure/useravatar?size=medium&avatarId=10452"},"displayName":"Bryan Pendleton","active":true},"body":"I need to learn more about Grant/Revoke data dictionary\r\nhandling as part of the work I'm doing on DERBY-1489, so\r\nI'll have a look at this one and see what I can figure out.\r\n","updateAuthor":{"self":"https://issues.apache.org/jira/rest/api/2/user?username=bryanpendleton","name":"bryanpendleton","emailAddress":"bpendleton dot derby at gmail dot com","avatarUrls":{"48x48":"https://issues.apache.org/jira/secure/useravatar?avatarId=10452","24x24":"https://issues.apache.org/jira/secure/useravatar?size=small&avatarId=10452","16x16":"https://issues.apache.org/jira/secure/useravatar?size=xsmall&avatarId=10452","32x32":"https://issues.apache.org/jira/secure/useravatar?size=medium&avatarId=10452"},"displayName":"Bryan Pendleton","active":true},"created":"2006-09-13T16:40:45.000+0000","updated":"2006-09-13T16:40:45.000+0000"},{"self":"https://issues.apache.org/jira/rest/api/2/issue/12346651/comment/12434577","id":"12434577","author":{"self":"https://issues.apache.org/jira/rest/api/2/user?username=bryanpendleton","name":"bryanpendleton","emailAddress":"bpendleton dot derby at gmail dot com","avatarUrls":{"48x48":"https://issues.apache.org/jira/secure/useravatar?avatarId=10452","24x24":"https://issues.apache.org/jira/secure/useravatar?size=small&avatarId=10452","16x16":"https://issues.apache.org/jira/secure/useravatar?size=xsmall&avatarId=10452","32x32":"https://issues.apache.org/jira/secure/useravatar?size=medium&avatarId=10452"},"displayName":"Bryan Pendleton","active":true},"body":"I think that the problem involves the prepared statement cache and how statements\r\nget invalidated. Notice that the very last statement is a CREATE TABLE statement\r\nwhich is identical in text to a CREATE TABLE statement issued earlier in the script,\r\nthough it refers to table t11ConstraintTest which has been dropped and recreated\r\nin the meantime.\r\n\r\nTracing through the code, it seems that when we hit the last line of the script, the\r\ncompiler locates information about the first CREATE TABLE statement and\r\nre-uses it, but since that cached statement refers to a table that no longer exists,\r\nthe permission checking code gets an NPE trying to look up information about\r\nthe non-existent table.\r\n\r\nIf I change the last line of the script to:\r\ncreate table t31ConstraintTest (c311 int, c312 int, a int, foreign key(c311, c312) references mamta1.t11ConstraintTest); \r\nthen the problem does not occur. I believe this is because the old statement\r\ninformation does not get re-used because the statement text is different.\r\n\r\nI think this means I get to go learn about how prepared statements are cached\r\nand how that cache is invalidated.\r\n","updateAuthor":{"self":"https://issues.apache.org/jira/rest/api/2/user?username=bryanpendleton","name":"bryanpendleton","emailAddress":"bpendleton dot derby at gmail dot com","avatarUrls":{"48x48":"https://issues.apache.org/jira/secure/useravatar?avatarId=10452","24x24":"https://issues.apache.org/jira/secure/useravatar?size=small&avatarId=10452","16x16":"https://issues.apache.org/jira/secure/useravatar?size=xsmall&avatarId=10452","32x32":"https://issues.apache.org/jira/secure/useravatar?size=medium&avatarId=10452"},"displayName":"Bryan Pendleton","active":true},"created":"2006-09-14T02:32:39.000+0000","updated":"2006-09-14T02:32:39.000+0000"},{"self":"https://issues.apache.org/jira/rest/api/2/issue/12346651/comment/12434592","id":"12434592","author":{"self":"https://issues.apache.org/jira/rest/api/2/user?username=bryanpendleton","name":"bryanpendleton","emailAddress":"bpendleton dot derby at gmail dot com","avatarUrls":{"48x48":"https://issues.apache.org/jira/secure/useravatar?avatarId=10452","24x24":"https://issues.apache.org/jira/secure/useravatar?size=small&avatarId=10452","16x16":"https://issues.apache.org/jira/secure/useravatar?size=xsmall&avatarId=10452","32x32":"https://issues.apache.org/jira/secure/useravatar?size=medium&avatarId=10452"},"displayName":"Bryan Pendleton","active":true},"body":"I think that the problem here may be that FKConstraintDefinitionNode, which is the\r\ncompiler implementation code for the \"foreign key ... references ... \" constraint\r\nin the compiler, is not properly registering that the statement containing the\r\nforeign key constraint has a dependency on the table being referenced. Due\r\nto the lack of the dependency, when the referenced table (t11ConstraintTest)\r\nis dropped, the statement is not invalidated.\r\n\r\nThe following diff seems to make the test script pass. More study and testing\r\nis needed, plus the construction of a real patch proposal.\r\n\r\nIndex: FKConstraintDefinitionNode.java\r\n===================================================================\r\n--- FKConstraintDefinitionNode.java     (revision 441800)\r\n+++ FKConstraintDefinitionNode.java     (working copy)\r\n@@ -104,6 +104,8 @@\r\n\r\n                getConstraintMoniker(),\r\n\r\n                refTableName.getTableName());\r\n\r\n+               getCompilerContext().createDependency(td);\r\n+\r\n                // Verify if REFERENCES_PRIV is granted to columns referenced\r\n                getCompilerContext().pushCurrentPrivType(getPrivType());\r\n","updateAuthor":{"self":"https://issues.apache.org/jira/rest/api/2/user?username=bryanpendleton","name":"bryanpendleton","emailAddress":"bpendleton dot derby at gmail dot com","avatarUrls":{"48x48":"https://issues.apache.org/jira/secure/useravatar?avatarId=10452","24x24":"https://issues.apache.org/jira/secure/useravatar?size=small&avatarId=10452","16x16":"https://issues.apache.org/jira/secure/useravatar?size=xsmall&avatarId=10452","32x32":"https://issues.apache.org/jira/secure/useravatar?size=medium&avatarId=10452"},"displayName":"Bryan Pendleton","active":true},"created":"2006-09-14T05:31:27.000+0000","updated":"2006-09-14T05:31:27.000+0000"},{"self":"https://issues.apache.org/jira/rest/api/2/issue/12346651/comment/12434689","id":"12434689","author":{"self":"https://issues.apache.org/jira/rest/api/2/user?username=mamtas","name":"mamtas","emailAddress":"msatoor at gmail dot com","avatarUrls":{"48x48":"https://issues.apache.org/jira/secure/useravatar?avatarId=10452","24x24":"https://issues.apache.org/jira/secure/useravatar?size=small&avatarId=10452","16x16":"https://issues.apache.org/jira/secure/useravatar?size=xsmall&avatarId=10452","32x32":"https://issues.apache.org/jira/secure/useravatar?size=medium&avatarId=10452"},"displayName":"Mamta A. Satoor","active":true},"body":"Bryan, you definitely look like on the right track with the dependency manager. I was just wondering though if this null pointer exception also happens outside of SQL authorization mode since \"foreign key ... references...\" gets implemented the same with or without SQL authorization mode. But I have a feeling it might be SQL authorization mode specific otherwise we would have probably run into this npe by now.","updateAuthor":{"self":"https://issues.apache.org/jira/rest/api/2/user?username=mamtas","name":"mamtas","emailAddress":"msatoor at gmail dot com","avatarUrls":{"48x48":"https://issues.apache.org/jira/secure/useravatar?avatarId=10452","24x24":"https://issues.apache.org/jira/secure/useravatar?size=small&avatarId=10452","16x16":"https://issues.apache.org/jira/secure/useravatar?size=xsmall&avatarId=10452","32x32":"https://issues.apache.org/jira/secure/useravatar?size=medium&avatarId=10452"},"displayName":"Mamta A. Satoor","active":true},"created":"2006-09-14T14:08:02.000+0000","updated":"2006-09-14T14:08:02.000+0000"},{"self":"https://issues.apache.org/jira/rest/api/2/issue/12346651/comment/12434716","id":"12434716","author":{"self":"https://issues.apache.org/jira/rest/api/2/user?username=mamtas","name":"mamtas","emailAddress":"msatoor at gmail dot com","avatarUrls":{"48x48":"https://issues.apache.org/jira/secure/useravatar?avatarId=10452","24x24":"https://issues.apache.org/jira/secure/useravatar?size=small&avatarId=10452","16x16":"https://issues.apache.org/jira/secure/useravatar?size=xsmall&avatarId=10452","32x32":"https://issues.apache.org/jira/secure/useravatar?size=medium&avatarId=10452"},"displayName":"Mamta A. Satoor","active":true},"body":"Bryan, I tried the following ij session (which is similar to the problem script except that there are no grant revoke statements involved) with connection authorization (ie using the old scheme of authorization in Derby) and didn't get a null pointer exception. So, this null pointer exception is specifc to SQL authorization mode only.\r\n\r\n$ java org.apache.derby.tools.ij\r\nij version 10.3\r\nij> connect 'jdbc:derby:c:/dellater/dbmaintest2;create=true' user 'mamta1' as mamta1;\r\nij> create table t11ConstraintTest (c111 int not null, c112 int not null, primary key (c111, c112));\r\n0 rows inserted/updated/deleted\r\nij> connect 'jdbc:derby:c:/dellater/dbmaintest2;create=true' user 'mamta3' as mamta3;\r\nWARNING 01J01: Database 'c:/dellater/dbmaintest2' not created, connection made to existing database instead.\r\nij(MAMTA3)> drop table t31ConstraintTest;\r\nERROR 42Y07: Schema 'MAMTA3' does not exist\r\nij(MAMTA3)> create table t31ConstraintTest (c311 int, c312 int, foreign key(c311, c312) references mamta1.t11ConstraintTest);\r\n0 rows inserted/updated/deleted\r\nij(MAMTA3)> drop table t31ConstraintTest;\r\n0 rows inserted/updated/deleted\r\nij(MAMTA3)> set connection mamta1;\r\nij(MAMTA1)> drop table t11ConstraintTest;\r\n0 rows inserted/updated/deleted\r\nij(MAMTA1)> create table t11ConstraintTest (c111 int not null, c112 int not null, primary key (c111, c112));\r\n0 rows inserted/updated/deleted\r\nij(MAMTA1)> set connection mamta3;\r\nij(MAMTA3)> drop table t31ConstraintTest;\r\nERROR 42Y55: 'DROP TABLE' cannot be performed on 'T31CONSTRAINTTEST' because it does not exist.\r\nij(MAMTA3)> create table t31ConstraintTest (c311 int, c312 int, foreign key(c311, c312) references mamta1.t11ConstraintTest);\r\n0 rows inserted/updated/deleted\r\nij(MAMTA3)> exit;","updateAuthor":{"self":"https://issues.apache.org/jira/rest/api/2/user?username=mamtas","name":"mamtas","emailAddress":"msatoor at gmail dot com","avatarUrls":{"48x48":"https://issues.apache.org/jira/secure/useravatar?avatarId=10452","24x24":"https://issues.apache.org/jira/secure/useravatar?size=small&avatarId=10452","16x16":"https://issues.apache.org/jira/secure/useravatar?size=xsmall&avatarId=10452","32x32":"https://issues.apache.org/jira/secure/useravatar?size=medium&avatarId=10452"},"displayName":"Mamta A. Satoor","active":true},"created":"2006-09-14T15:46:00.000+0000","updated":"2006-09-14T15:46:00.000+0000"},{"self":"https://issues.apache.org/jira/rest/api/2/issue/12346651/comment/12434722","id":"12434722","author":{"self":"https://issues.apache.org/jira/rest/api/2/user?username=bryanpendleton","name":"bryanpendleton","emailAddress":"bpendleton dot derby at gmail dot com","avatarUrls":{"48x48":"https://issues.apache.org/jira/secure/useravatar?avatarId=10452","24x24":"https://issues.apache.org/jira/secure/useravatar?size=small&avatarId=10452","16x16":"https://issues.apache.org/jira/secure/useravatar?size=xsmall&avatarId=10452","32x32":"https://issues.apache.org/jira/secure/useravatar?size=medium&avatarId=10452"},"displayName":"Bryan Pendleton","active":true},"body":"Thanks Mamta! That is very helpful. My feeling is that the basic dependency\r\nmanager issue is generic, but the NPE symptom is specific to SQL Auth. I think\r\nthat without SQL Auth in place, the system is re-using the old prepared statement\r\nwithout re-preparing it, but in this case there are no errors that result.\r\n\r\nThat is, SQL Auth converts this scenario from \"harmless incorrect re-use of an invalid\r\nprepared statement\" to \"NPE in permission descriptor handling due to incorrect\r\nre-use of an invalid prepared statement\".\r\n\r\nI will work up a complete patch with regression tests, comments, etc.\r\n\r\nThanks again for the feedback and extra testing.","updateAuthor":{"self":"https://issues.apache.org/jira/rest/api/2/user?username=bryanpendleton","name":"bryanpendleton","emailAddress":"bpendleton dot derby at gmail dot com","avatarUrls":{"48x48":"https://issues.apache.org/jira/secure/useravatar?avatarId=10452","24x24":"https://issues.apache.org/jira/secure/useravatar?size=small&avatarId=10452","16x16":"https://issues.apache.org/jira/secure/useravatar?size=xsmall&avatarId=10452","32x32":"https://issues.apache.org/jira/secure/useravatar?size=medium&avatarId=10452"},"displayName":"Bryan Pendleton","active":true},"created":"2006-09-14T16:21:40.000+0000","updated":"2006-09-14T16:21:40.000+0000"},{"self":"https://issues.apache.org/jira/rest/api/2/issue/12346651/comment/12434729","id":"12434729","author":{"self":"https://issues.apache.org/jira/rest/api/2/user?username=rhillegas","name":"rhillegas","emailAddress":"rhillegas at apache dot org","avatarUrls":{"48x48":"https://issues.apache.org/jira/secure/useravatar?avatarId=10452","24x24":"https://issues.apache.org/jira/secure/useravatar?size=small&avatarId=10452","16x16":"https://issues.apache.org/jira/secure/useravatar?size=xsmall&avatarId=10452","32x32":"https://issues.apache.org/jira/secure/useravatar?size=medium&avatarId=10452"},"displayName":"Rick Hillegas","active":true},"body":"Downgrading the urgency of this issue. I do not think it should block the release of 10.2.","updateAuthor":{"self":"https://issues.apache.org/jira/rest/api/2/user?username=rhillegas","name":"rhillegas","emailAddress":"rhillegas at apache dot org","avatarUrls":{"48x48":"https://issues.apache.org/jira/secure/useravatar?avatarId=10452","24x24":"https://issues.apache.org/jira/secure/useravatar?size=small&avatarId=10452","16x16":"https://issues.apache.org/jira/secure/useravatar?size=xsmall&avatarId=10452","32x32":"https://issues.apache.org/jira/secure/useravatar?size=medium&avatarId=10452"},"displayName":"Rick Hillegas","active":true},"created":"2006-09-14T16:42:24.000+0000","updated":"2006-09-14T16:42:24.000+0000"},{"self":"https://issues.apache.org/jira/rest/api/2/issue/12346651/comment/12435177","id":"12435177","author":{"self":"https://issues.apache.org/jira/rest/api/2/user?username=bryanpendleton","name":"bryanpendleton","emailAddress":"bpendleton dot derby at gmail dot com","avatarUrls":{"48x48":"https://issues.apache.org/jira/secure/useravatar?avatarId=10452","24x24":"https://issues.apache.org/jira/secure/useravatar?size=small&avatarId=10452","16x16":"https://issues.apache.org/jira/secure/useravatar?size=xsmall&avatarId=10452","32x32":"https://issues.apache.org/jira/secure/useravatar?size=medium&avatarId=10452"},"displayName":"Bryan Pendleton","active":true},"body":"After some more testing, I think that this patch is a reasonable fix.\r\nAttached is createDependency.diff, which changes the compiler so\r\nthat it creates a dependency from a statement with a FOREIGN KEY\r\nclause in it to the table which is referenced by that clause. The patch\r\nalso contains a simple regression test, based on the original bug\r\nscript. derbyall passed without errors.\r\n\r\nPlease have  a look and tell me what you think of this patch proposal.\r\n","updateAuthor":{"self":"https://issues.apache.org/jira/rest/api/2/user?username=bryanpendleton","name":"bryanpendleton","emailAddress":"bpendleton dot derby at gmail dot com","avatarUrls":{"48x48":"https://issues.apache.org/jira/secure/useravatar?avatarId=10452","24x24":"https://issues.apache.org/jira/secure/useravatar?size=small&avatarId=10452","16x16":"https://issues.apache.org/jira/secure/useravatar?size=xsmall&avatarId=10452","32x32":"https://issues.apache.org/jira/secure/useravatar?size=medium&avatarId=10452"},"displayName":"Bryan Pendleton","active":true},"created":"2006-09-16T04:41:44.000+0000","updated":"2006-09-16T04:41:44.000+0000"},{"self":"https://issues.apache.org/jira/rest/api/2/issue/12346651/comment/12435540","id":"12435540","author":{"self":"https://issues.apache.org/jira/rest/api/2/user?username=yipng","name":"yipng","emailAddress":"yipng168 at gmail dot com","avatarUrls":{"48x48":"https://issues.apache.org/jira/secure/useravatar?avatarId=10452","24x24":"https://issues.apache.org/jira/secure/useravatar?size=small&avatarId=10452","16x16":"https://issues.apache.org/jira/secure/useravatar?size=xsmall&avatarId=10452","32x32":"https://issues.apache.org/jira/secure/useravatar?size=medium&avatarId=10452"},"displayName":"Yip Ng","active":true},"body":"I have reviewed the patch and the fix looks reasonable to me.  I confirm that with Bryan's patch, the NPE no longer occurs and without it, the NPE can be reproduced by the above test.  +1 for commit.","updateAuthor":{"self":"https://issues.apache.org/jira/rest/api/2/user?username=yipng","name":"yipng","emailAddress":"yipng168 at gmail dot com","avatarUrls":{"48x48":"https://issues.apache.org/jira/secure/useravatar?avatarId=10452","24x24":"https://issues.apache.org/jira/secure/useravatar?size=small&avatarId=10452","16x16":"https://issues.apache.org/jira/secure/useravatar?size=xsmall&avatarId=10452","32x32":"https://issues.apache.org/jira/secure/useravatar?size=medium&avatarId=10452"},"displayName":"Yip Ng","active":true},"created":"2006-09-18T17:34:10.000+0000","updated":"2006-09-18T17:34:10.000+0000"},{"self":"https://issues.apache.org/jira/rest/api/2/issue/12346651/comment/12435609","id":"12435609","author":{"self":"https://issues.apache.org/jira/rest/api/2/user?username=bryanpendleton","name":"bryanpendleton","emailAddress":"bpendleton dot derby at gmail dot com","avatarUrls":{"48x48":"https://issues.apache.org/jira/secure/useravatar?avatarId=10452","24x24":"https://issues.apache.org/jira/secure/useravatar?size=small&avatarId=10452","16x16":"https://issues.apache.org/jira/secure/useravatar?size=xsmall&avatarId=10452","32x32":"https://issues.apache.org/jira/secure/useravatar?size=medium&avatarId=10452"},"displayName":"Bryan Pendleton","active":true},"body":"Thanks very much Yip for the review!\r\n\r\nI've committed the patch to subversion as revision 447644.","updateAuthor":{"self":"https://issues.apache.org/jira/rest/api/2/user?username=bryanpendleton","name":"bryanpendleton","emailAddress":"bpendleton dot derby at gmail dot com","avatarUrls":{"48x48":"https://issues.apache.org/jira/secure/useravatar?avatarId=10452","24x24":"https://issues.apache.org/jira/secure/useravatar?size=small&avatarId=10452","16x16":"https://issues.apache.org/jira/secure/useravatar?size=xsmall&avatarId=10452","32x32":"https://issues.apache.org/jira/secure/useravatar?size=medium&avatarId=10452"},"displayName":"Bryan Pendleton","active":true},"created":"2006-09-18T23:51:30.000+0000","updated":"2006-09-18T23:51:30.000+0000"},{"self":"https://issues.apache.org/jira/rest/api/2/issue/12346651/comment/12551383","id":"12551383","author":{"self":"https://issues.apache.org/jira/rest/api/2/user?username=fuzzylogic","name":"fuzzylogic","emailAddress":"mcintyre dot a at gmail dot com","avatarUrls":{"48x48":"https://issues.apache.org/jira/secure/useravatar?avatarId=10452","24x24":"https://issues.apache.org/jira/secure/useravatar?size=small&avatarId=10452","16x16":"https://issues.apache.org/jira/secure/useravatar?size=xsmall&avatarId=10452","32x32":"https://issues.apache.org/jira/secure/useravatar?size=medium&avatarId=10452"},"displayName":"Andrew McIntyre","active":true},"body":"This issue has been resolved for over a year with no further movement. Closing.","updateAuthor":{"self":"https://issues.apache.org/jira/rest/api/2/user?username=fuzzylogic","name":"fuzzylogic","emailAddress":"mcintyre dot a at gmail dot com","avatarUrls":{"48x48":"https://issues.apache.org/jira/secure/useravatar?avatarId=10452","24x24":"https://issues.apache.org/jira/secure/useravatar?size=small&avatarId=10452","16x16":"https://issues.apache.org/jira/secure/useravatar?size=xsmall&avatarId=10452","32x32":"https://issues.apache.org/jira/secure/useravatar?size=medium&avatarId=10452"},"displayName":"Andrew McIntyre","active":true},"created":"2007-12-13T09:05:06.700+0000","updated":"2007-12-13T09:05:06.700+0000"}]},"votes":{"self":"https://issues.apache.org/jira/rest/api/2/issue/DERBY-1589/votes","votes":0,"hasVoted":false},"worklog":{"startAt":0,"maxResults":20,"total":0,"worklogs":[]},"customfield_12311820":"0|i075kn:"}}